### PR TITLE
Fixes for gopts and spec

### LINKED ISSUE #4043: gopts: Wrong type detected too late
Forked from #4029.

This is "Class 2: wrong type".

## Steps to Reproduce the Problem
see #4029

## Expected Result
see #4029

## Actual Result
see #4029

## System Information
see #4029

### LINKED ISSUE #4044: error/success return values ignored in elektraGetDoUpdateWithGlobalHooks()
## Problem
In several places of `kdb.c` return values from plugins' `kdbGet()` are ignored.

This leads to errors in these plugins from being ignored and not reported back to the initial caller of `kdbGet()`.

## Examples of ignored return values (list might be incomplete)
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L795-L805

https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L837

https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L845

https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L853

https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L894

## Concrete example
One concrete example for the impact of the first example 
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L795-L805
is that errors detected within `elektraGoptsGet()` are "swallowed".

E.g. `opts.c` detects a missing argument for a long option and returns false.
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/opts/opts.c#L1789-L1792

This leads to the call to `elektraGlobalGet (handle, ks, parentKey, PROCGETSTORAGE, MAXONCE);` at:
https://github.com/ElektraInitiative/libelektra/blob/6701d9ea627a7fb6df7276c4d6fe69fa9a6b8ae4/src/libs/elektra/kdb.c#L803
to fail.

However, the return value is ignored and thusly the error is ignored.

### PR DESCRIPTION
**Pull request by kodebach**
Fixes #4043
Fixes #4044

@qwepoizt Please verify that this PR fixes the problems you found.

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

### CODE REVIEW

**Comment by qwepoizt** [comment]
@kodebach Thanks for fixing that so quickly! I am currently testing and will report later today. Looks very promising so far!

**Comment by qwepoizt** [comment]
@kodebach: I can confirm that this fixes

* #4042 
* #4043 
* #4044 

!

It does not fix #4049, but makes the fix possible. I'll take care of #4049.

Once all of these issues are fixed, the parent issue #4029 will be fixed.

**Review by qwepoizt — COMMENTED** [review]
As I don't know the internals of `kdbGet()`, I fear I can't provide any helpful review apart from reporting that it fixes several issues (see https://github.com/ElektraInitiative/libelektra/pull/4045#issuecomment-920031437).

**Review by markus2330 — APPROVED** [review]

**Comment by markus2330** [comment]
At least one test should be added that demonstrates that proc key gets validated.

@mpranj a leftover was added for you in this PR, is the PR okay for you?

**Comment by kodebach** [comment]
> At least one test should be added that demonstrates that proc key gets validated.

The `commands` part of `testscr_check_gen` covers this. Specifically, I added this additional check

https://github.com/ElektraInitiative/libelektra/blob/e7f62f204cbe53b293404ed165ec78a32ea16b51/tests/shell/gen/highlevel/commands.check.sh#L168-L179

The `res=$((res == 0))` (*) at the bottom ensures that the `./dummy` command failed. Yes, using `== 0` to check for failure is a bit weird, but it's because we then check `"$res" = 0`.

> mpranj a leftover was added for you in this PR, is the PR okay for you?

If you are referring to the fact that I disabled the cache, if a `procgetstorage` plugin is mounted, then I wouldn't be too concerned about it. This part of the code will change completely with #3693, so there is not much point in looking for a better fix now.

**Comment by markus2330** [comment]
Thank you! Is this ready to merge?

**Comment by kodebach** [comment]
> Thank you! Is this ready to merge?

Yes, I would say so.

**Comment by markus2330** [comment]
Thank you :fireworks:

**Pull request merged**
