### PR TITLE
YAMBi: Execute Unit Tests Again

### PR DESCRIPTION
**Pull request by sanssecours**

### CODE REVIEW

**Comment by markus2330** [comment]
Why do you need the main method at all?

**Comment by sanssecours** [comment]
> Why do you need the main method at all?

As far as I can tell, `srcdir_file` does not work properly, if we do not call `init (argc, argv)` beforehand. One function that has access to the command line arguments `argc` and `argv` is `main`. That is the reason why I added a main method that calls `init`.

**Comment by markus2330** [comment]
I see. Maybe we can provide the main (which calls init and also does cleanup afterwards) in a way so that all our google tests automatically use it?

**Comment by markus2330** [comment]
Thank you! I created  #2261.

**Pull request merged**
