### PR TITLE
[FLOSS H3] Replace type=int in ini files

### LINKED ISSUE #4060: Replace `type=int` with appropriate alternative
There are some places, where the deprecated `type=int` is still used.

@markus2330 wrote in #4058 that

> this is probably some relic from before we started to use the CORBA type system.

and

> these places need to be fixed!

## List of usages (maybe not exhaustive)

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/doc/METADATA.ini#L356-L357

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/doc/METADATA.ini#L77-L80

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/doc/METADATA.ini#L1191-L1195

### PR DESCRIPTION
**Pull request by sedadas**
As mentioned in #4060, `type=int` is deprecated and should be replaced everywhere. Some files slipped and this aims to fix them as well

Closes #4060 

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by muskater** [comment]
Thank you for this fix! I think you did a great job in fixing the issue. The only point that you may want to improve are the commit messages. You might want to use the following syntax: `module: message`. Other than that, nice work!

**Review by muskater — APPROVED** [review]
Thank you for this fix! I think you did a great job in fixing the issue. The only point that you may want to improve are the commit messages. You might want to use the following syntax: module: message. Other than that, nice work!

**Comment by sedadas** [comment]
jenkins build libelektra please

**Comment by 4ydan** [comment]
[FLOSS H3] Review
You did the job on moving from int to long. I enjoy that you also linked the issue. Nice to see your prettier cleaning white spaces. Looks fine to me. Nice work.

**Review by markus2330 — APPROVED** [review]
Looks very good, please set "ready to merge" when ready.

**Comment by markus2330** [comment]
Thank you! :fireworks:

**Pull request merged**
