### PR TITLE
simpleini-relative

### PR DESCRIPTION
**Pull request by e1528532**
# Purpose
makes the simpleini shellrecorder files relative

# Checklist

- [X] commit messages are fine (with references to issues)
- [X] I ran all tests and everything went fine

@markus2330 should be fine

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build fast please

**Comment by markus2330** [comment]
Thank you, do you have any idea why the tests did not fail?

Is this ready to merge?

**Comment by e1528532** [comment]
jenkins build please

**Comment by e1528532** [comment]
theoretically it is, but i have no idea why the tests don't get build?

**Comment by markus2330** [comment]
Thank you!

Some of the tests were running but you cannot see from the output if these files were actually used.

**Pull request merged**
