### PR TITLE
Ini fix key is below

### PR DESCRIPTION
**Pull request by tom-wa**

### CODE REVIEW

**Comment by markus2330** [comment]
Test case fails:
```
Compare <
>, with <globalkey1 = globalval1
>
in file /home/jenkins/workspace/workspace/elektra-mergerequests/src/plugins/ini/ini/emptyLines, line 1.
/home/jenkins/workspace/workspace/elektra-mergerequests/tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
/home/jenkins/workspace/workspace/elektra-mergerequests/src/plugins/ini/testmod_ini.c:426: error in test_preserveEmptyLines: files do not match as expected
```

**Comment by tom-wa** [comment]
this problem is because it depends on #598 
anyway, please don't merge now, i found a problem which makes preserving order while a keyset is appended impossible, currently trying to find a best afford solution.

```
system/section   binary  order #0
system/section/zkey1 "1" order #1
system/section/zkey2 "2" order #2
system/section2/key "bla" order #3
```
- append keyset
```
system/section/subsection
system/section/subsection/key
system/section/zkey3
```
it's impossible to get the right order number for `zkey3` from the keyset.

**Comment by markus2330** [comment]
Why? There might be more than one "right" number: either you give it `#2#0`, i.e. always appending keys to their respective section (if available) OR give it `#4` and reopen `[section]` for the last key. The first solution might be better because it is "only" an ordering problem and not also a problem of how to restore multiple sections correctly.

So first you have:
```
[section]
zkey=1
zkey2=2
[section2]
key=blah
```

and then

```
[section]
zkey=1
zkey2=2
zkey3 =3
[section/subsection]
key=whatever
[section2]
key=blah
```

But its not really an issue how to do it at long it properly roundtrips and the users ordering will be honored. If no order was given, you can order them as you think it is at least surprising.

**Comment by tom-wa** [comment]
i want to prevent reopening the sections whenever it's possible because it can become quite a mess.

the issue is that `section/subsection`'s order number should be #2/#1 (inserted directly below zkey2 and above `section2`) and `section/subsection/key`'s #2/#2, but when trying to insert `zkey3` it's position within the keyset would also be directly below `zkey2` and it's order number #2/#1

i've already solved that issue by using "order" just for sections, and having an additional metakey for the key order relative to their sections. i'm currently just trying to figure out if it's possible to get rid of the additional metakeys at the end of kdbGet

**Comment by markus2330** [comment]
Ok, thank you!

**Comment by tom-wa** [comment]
```
 % kdb export /examples
[highlevel/gps]
status =
[highlevel/powersaving]
gps =
[]
highlevel =
highlevel/device =
highlevel/device = vehicle
```

the first `highlevel/device` key is the `spec` key, the second one the `user`
how should this case be treated ?

**Comment by tom-wa** [comment]
to clarify: `/examples` is the sectionKey here, `[]` kinda "nullifies" the previous section (all keys above don't have a namespace) and both `spec/examples/highlevel/device` and `user/examples/highlevel/device` are below `/examples`

**Comment by markus2330** [comment]
This should be fixed within `kdb export`: every namespace should be exported separately. There is nothing useful you can do within the storage plugin. See doc/decisions/relative.md and #51

**Pull request merged**
