### PR TITLE
notification: zeromq plugins

### PR DESCRIPTION
**Pull request by waht**
# Purpose

Implementation of ZeroMq transport plugins using pub/sub sockets.

# Checklist

- [x] commit messages are fine (with references to issues)
- [x] I added unit tests
- [x] I ran all tests and everything went fine
- [x] affected documentation is fixed
- [x] I added code comments, logging, and assertions (see doc/CODING.md)
- [x] release notes are updated (doc/news/_preparation_next_release.md)
- [x] implement architectural decision from PR #1825 
- [x] have `kdb` tool print a warning on set if the connection timed out
- [x] improve connection & subscription message detection for better user experience

~~The branch is currently based on the `notification_dbus` branch from #1825. Once this PR is merged I will rebase it on `master`.~~

### CODE REVIEW

**Comment by waht** [comment]
Hooray, I found a fix for the "settle" time in the zeromqsend plugin! :)

Using a `ZMQ_XPUB` socket (instead of `ZMQ_PUB`) it is possible to receive the subscription message (first byte is `0x1` as [documented in the API docs](http://api.zeromq.org/4-2:zmq-socket#toc12)). Afterwards the socket is ready to send. Now the connection is established when sending the first notification.

I also added a timeout of one second which takes effect sending without an endpoint (e.g. hub is not started).

**Comment by waht** [comment]
jenkins build all please

**Comment by waht** [comment]
jenkins build muliticonfig-gcc-stable please

**Comment by waht** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by waht** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by markus2330** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by markus2330** [comment]
jenkins build multiconfig-gcc47-cmake-options please

**Comment by waht** [comment]
jenkins build all please

**Comment by waht** [comment]
Please keep in mind that #1856 sould be merged in order to be able to configure the plugins. The default configuration should work fine though.

**Comment by markus2330** [comment]
Seems like this PR needs a rebase, too.

**Comment by waht** [comment]
jenkins build all please

**Comment by waht** [comment]
jenkins build libelektra please

**Comment by machinekoder** [comment]
Looks interesting. Do you have a minimal example somewhere?

**Comment by waht** [comment]
Thank you! Here are two [two examples from the tutorial](https://github.com/waht/libelektra/blob/9be34393df0f889eec92ee5394637f8cb9c031ff/doc/tutorials/notifications.md#register-a-variable) (different PR).

To use the ZeroMQ plugins for notification they need to be [mounted globally](https://github.com/waht/libelektra/blob/4b34180022337c6617893d5c7fd554c2e096b4f1/src/plugins/zeromqsend/README.md#usage) and the [hub is required](https://github.com/waht/libelektra/blob/4b34180022337c6617893d5c7fd554c2e096b4f1/src/tools/hub-zeromq/README.md) for exchanging messages (`@tool@` is replaced with "hub-zeromq"; so the command is actually `kdb run-hub-zeromq`).

**Comment by markus2330** [comment]
@machinekoder Do you need more information for the review?

**Comment by waht** [comment]
jenkins build libelektra please

**Comment by waht** [comment]
jenkins build elektra please

**Comment by waht** [comment]
jenkins build elektra please

**Comment by waht** [comment]
jenkins build libelektra please

**Comment by waht** [comment]
jenkins build libelektra please

**Comment by waht** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build all please

**Comment by waht** [comment]
jenkins build all please

**Comment by waht** [comment]
@markus2330 this one is ready as well. besides renaming headers to match changes in #1850, this is ready for review

**Comment by markus2330** [comment]
@machinekoder if you want to try it out, it is now merged in the master! We are looking forward to feedback.

**Pull request merged**
