### PR TITLE
Mpranj cache tools

### PR DESCRIPTION
**Pull request by markus2330**
## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [ ] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] meta data is updated (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))

## Review

Reviewers will usually check the following:

- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
- [ ] Documentation is concise and good to read
- [ ] Examples are well chosen and understandable

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
@mpranj your new testcase fails (https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2850/2/pipeline). It seems like storage tests are included although the mmapstorage plugin is excluded.

**Comment by mpranj** [comment]
I forgot to exclude the mmapstorage_crc plugin variant which triggered an error in the tests. I'll branch off this and fix it.

**Comment by markus2330** [comment]
@mpranj thank you! I already pushed something here which might fix the problem, though.

Another minor thing: currently the logic is implemented with an enabled and an disabled key. This is actually not needed, see doc/decisions/bool.md for how bools are defined. We could implement everything exclusively with `system/elektra/cache/enabled`:

- key is not present: default case, use cache if available
- key is present, value is 0: never use cache
- key is present, value is 1: always use cache

**Comment by mpranj** [comment]
@markus2330 I implemented the changes, do you want me to open a new PR or just push to this branch?

**Comment by markus2330** [comment]
Maybe better in a new branch:
The history here is a mess, rebase failed, so I merged master (twice) and later I accidentally pushed some commits which do not belong here. Sorry about that.

**Comment by markus2330** [comment]
(but you can also push it here, I will close this anyway)

**Pull request merged**
