### PR TITLE
Add/Enhance CMake Modules for Botan, Gcrypt and OpenSSL detection

### LINKED ISSUE #1242: Curlget Plugin: OpenSSL Check Does Not Work Properly on macOS
# Steps to Reproduce

1. Clone the repository
2. Configure the build system:

    ```sh
    mkdir -p build &&						\
    cd build &&							\
    cmake ..							\
          -GNinja							\
          -DENABLE_TESTING=ON					\
          -DENABLE_DEBUG=ON						\
          -DENABLE_LOGGER=OFF					\
          -DBUILD_PDF=ON						\
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON			\
          -DPDFLATEX_COMPILER=`which latexmk`			\
          -DPDFLATEX_COMPILER_OPTIONS='-pdf;-f;-quiet'		\
          -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5			\
          -DTOOLS=ALL						\
          -DBINDINGS="ALL;-swig_python;-swig_python2;-swig_ruby"	\
          -DPLUGINS="ALL;-fcrypt"					\
    ```

3. Build Elektra

    ```sh
    ninja -C build
    ```

# Expected Result

The build finishes without problems using one of these two options:
  - CMake includes the Curlget plugin, or
  - CMake excludes the Curlget plugin, since it only found an incompatible version of OpenSSL or did nor find OpenSSL at all.

# Describe what actually happened

CMake includes the Curlget plugin:

```
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.51.0")
-- Found OpenSSL: /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib (found version "0.9.8zh")
-- Include Plugin curlget
```

, but `ninja` is not able to build Elektra:

```
[8/742] Building C object src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o
FAILED: src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DELEKTRA_STATIC -DHAVE_KDBCONFIG_H -DPLUGIN_SHORT_NAME=curlget -DREADME=readme_curlget.c -Isrc/include -I../src/include -I../src/plugins/base64 -Isrc/plugins/curlget -std=gnu99  -Wno-deprecated-declarations  -Wno-long-long -pedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wsign-compare -Wfloat-equal -Wformat-security -O2 -g -DNDEBUG   -fPIC -MD -MT src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o -MF src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o.d -o src/plugins/curlget/CMakeFiles/elektra-curlget-objects.dir/curlget.c.o   -c "Elektra/src/plugins/curlget/curlget.c"
Elektra/src/plugins/curlget/curlget.c:18:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^
1 error generated.
```

. As far as I can tell the Crypto plugin [handles this situation](https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/crypto/CMakeLists.txt) correctly.  

# System Information

- Elektra Version: master

## Other Relevant Software

I also installed OpenSSL via Homebrew. The text below shows the output of `brew info openssl` on my machine.

```
openssl: stable 1.0.2j (bottled) [keg-only]
SSL/TLS cryptography library
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2j (1,695 files, 12M)
  Poured from bottle on 2016-09-27 at 09:14:34
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb
==> Dependencies
Build: makedepend ✔
==> Options
--universal
	Build a universal binary
--without-test
	Skip build-time tests (not recommended)
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
```

### PR DESCRIPTION
**Pull request by petermax2**
# Purpose

crypto's CMakeLists.txt included several `try_compile` statements and `pkg-conf` calls to detect whether or not the following libraries are available:

- Botan
- libgcrypt
- OpenSSL

For every library there is a CMake module for detection. The modules aim to reduce clutter in crypto's CMakeLists.txt.

Fixes #1242 .

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [ ] I added unit tests
- [x] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by petermax2** [comment]
@sanssecours could you please check if this fixes your OpenSSL detection issue #1242 ?

**Comment by markus2330** [comment]
Thank you!

I added @sanssecours as reviewer.

**Comment by petermax2** [comment]
@sanssecours oh yeah, I did not update the curlget CMakeLists.txt ... Coming up right now. :smile:

**Comment by petermax2** [comment]
@sanssecours could you please check again? Curlget should now use the new CMake module.

**Comment by sanssecours** [comment]
> @sanssecours could you please check again? Curlget should now use the new CMake module.

Looks like it works now. Thank you!

**Comment by petermax2** [comment]
Great! Let's wait for the build server to finish then. :smile:

**Comment by petermax2** [comment]
> Maybe you could also add something like “This closes #1242.“ to the last commit message, to automatically close issue #1242, when Markus merges your changes.

I changed the PR description. This closes the issue too if @markus2330 merges.

**Comment by markus2330** [comment]
Thank you, great job!

Btw. you did not have to refer to COPYING-CMAKE-SCRIPTS, it is only present, because the copyrights of other cmake scripts (we copied from other repos) were referring to a file of this name.

Thus it is the same license, it does not really matter, so there is no need to change anything.

**Pull request merged**
