### PR TITLE
first logger draft

### PR DESCRIPTION
**Pull request by markus2330**
draft for logger, without docu (only the decision) and some missing implementation

### CODE REVIEW

**Comment by petermax2** [comment]
I like the logging interface! Should be easy to adapt to. Also I agree on using assertions more often.

**Comment by markus2330** [comment]
Thanks for looking into it!

Two two more concrete questions (directed to everyone):

1. Do you want the feature that a module can be defined per file, so that `ELEKTRA_LOG` does not need the module argument? (The old-style version still exists if `ELEKTRA_LOG_MODULE` is not defined)
2. Do you want a printf like functionality for `ELEKTRA_ASSERT`, too? If the logger is enabled, assert would use the logger (with high severity), otherwise it would directly printf to stderr.

**Comment by petermax2** [comment]
> Do you want the feature that a module can be defined per file, so that ELEKTRA_LOG does not need the module argument? (The old-style version still exists if ELEKTRA_LOG_MODULE is not defined)

I think `__FILE__` and `__LINE__` are more helpful than an "abstract" module name.

> Do you want a printf like functionality for ELEKTRA_ASSERT, too? If the logger is enabled, assert would use the logger (with high severity), otherwise it would directly printf to stderr.

Would the logger on high severity do something else than printf to stderr? It may be useful then. Also it would be more consistent if we used the logger.

**Comment by markus2330** [comment]
> I think __FILE__ and __LINE__ are more helpful than an "abstract" module name.

Yes,  __FILE__ and __LINE__ are very useful for output (and supported). The module name is only for filtering (usually you only want to see your own stuff, not everything). Let me reformulate my question: Do you think a abbreviation (with the first parameter predefined) for `ELEKTRA_LOG` in the case that in a source file only log statements for a single module are present (which should be the common case?) outweighs the disadvantage (the ugly hack that `ELEKTRA_LOG_MODULE` needs to be defined before any header file is included). Or should modules define their own macros when they want to make log statements shorter? (there are 4 macros for the 4 severity levels)

Or if this is still unclear: look at CODING.md line 77, do you need such a feature? (or is what is on line 84 enough)

> Would the logger on high severity do something else than printf to stderr?

Yes, currently the logger can write to files and syslog.

**Comment by petermax2** [comment]
ELEKTRA_LOG (modulename, "text to be printed according log filters", ...)

I think this would be enough.

**Comment by markus2330** [comment]
Ok, I only thought that, with longer module names and deep indentation, it would not look nice, e.g.

```
void foo()
{
        if (x)
        {
                ELEKTRA_LOG_NOTICE (ELEKTRA_LOG_MODULE_INTERNALNOTIFICATION, "..."
```

If you think its no problem to have such multi-line log messages, I would also prefer not to have it. But what would be worse if every module defines macros in an inconsistent way.

**Comment by waht** [comment]
Agree on the logging macros issue. Modules could still `#define` their module name to shorten the lines. e.g.

```
#define MODULE ELEKTRA_LOG_MODULE_INTERNALNOTIFICATION
...
ELEKTRA_LOG_NOTICE (MODULE, "..."
```

This way there is no need for defining the module name before headers.

**Comment by markus2330** [comment]
Yes, the only issue there is that it is a bit dangerous to define macros without prefixes, especially with generic text that really could appear somewhere else. (I think you know the min/max macro problems.) And with all prefixes and so on appended, you end up with a long name.

Basically, we have the same situation with warnings/errors, without any problem so far. I only brought up the topic, because logging should be used much more frequent than adding warnings or setting errors.

**Comment by sanssecours** [comment]
Since we currently have to specify the module (number) anyway: How about an optional way to include the plugin name in (front of) the log message? For example: If we use the following code: 

```c
ELEKTRA_LOG_DEBUG (ELEKTRA_LOG_MODULE_KDB, "Hi");
ELEKTRA_LOG_DEBUG (ELEKTRA_LOG_MODULE_AUGEAS, "Hi");
```

, then Elektra would write out something like this:

```
KDB:    Hi
Augeas: Hi
```

instead of this:

```
Hi
Hi
```
.

**Comment by petermax2** [comment]
@sanssecours you would get a lot of unidentified "Hi" then, because every module will use the logger in some way. Making the identification optional would lead to chaotic log files, I'm afraid.

**Comment by markus2330** [comment]
Thanks for the feedback.

The default format would be `"%s:%d:%s: %s\n", file, line, function, msg`

Then file, line and function already tells quite specifically who says "Hi". Unfortunately, it would *not* be trivial to output the module name, because we would need to maintain a mapping from enum to a string.

But let us discuss it.

**Pull request closed without merging**
