### PR TITLE
Style: Reformat Code With cmake-format 0.6

### PR DESCRIPTION
**Pull request by sanssecours**

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you very much! I'll merge this shortly before the release.

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
The release is planned to happen on Monday. So it would be enough if you reformat once on Monday morning (if you have time there?)

**Comment by sanssecours** [comment]
> So it would be enough if you reformat once on Monday morning (if you have time there?)

Yep, I should have time. I will update the pull request on Monday if there are any merge conflicts.

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
