### PR TITLE
fix #745 'empty LUABIN_VERSION_STRING'

### LINKED ISSUE #745: Fix error on empty LUABIN_VERSION_STRING
As @sirblackheart reported in #744 cmake fails when lua is not installed with:

```
CMake Error at cmake/Modules/FindLua.cmake:117 (string):
  string sub-command SUBSTRING requires four arguments.
Call Stack (most recent call first):
  cmake/Modules/FindLua.cmake:196 (verify_lua_executable_version)
  src/plugins/lua/CMakeLists.txt:2 (find_package)
```

Affected are http://community.markus-raab.org:8080/job/elektra-gcc-configure-debian-wheezy/lastFailedBuild/console http://community.markus-raab.org:8080/job/elektra-gcc47-all/lastFailedBuild/console http://community.markus-raab.org:8080/job/elektra-git-buildpackage-wheezy/lastFailedBuild/console http://community.markus-raab.org:8080/job/elektra-icc/lastFailedBuild/console

So a fix is highly appreciated.

### PR DESCRIPTION
**Pull request by mpranj**
Fixes #745.

### CODE REVIEW

**Comment by mpranj** [comment]
jenkins build elektra-gcc-configure-debian-wheezy please

**Comment by mpranj** [comment]
jenkins build gcc-configure-debian-wheezy please

**Comment by mpranj** [comment]
jenkins build gcc47-all please

**Comment by mpranj** [comment]
jenkins build git-buildpackage-wheezy please

**Comment by mpranj** [comment]
jenkins build icc please

**Comment by mpranj** [comment]
jenkins build gcc47-all please

**Comment by mpranj** [comment]
@markus2330 this can be merged now.

`elektra-git-buildpackage-wheezy` is not using the PR revision, hence it is still failing. I am not sure if it makes sense to build PRs with the `buildpackage` jobs in that case.

**Comment by markus2330** [comment]
Thank you!

And yes, it makes sense: if you need packages of the change you have in the PR in order to test something.  You would need to change the build-scripts to use sha1 instead of hard-coded master. But it is not urgent.

But we need documentation of all available (and working) phrases in doc/GIT.md

**Comment by mpranj** [comment]
@markus2330 exactly what I thought. I'll open a ticket for it and fix it later. Is it ok to just skip the version tag and build either master or PR, or do we need some fancy handling which builds either the (current) tag or the PR.

**Pull request merged**
