### PR TITLE
added my contact to AUTHORS.md

### PR DESCRIPTION
**Pull request by tucek**
Just updated Authors.md

### CODE REVIEW

**Comment by tucek** [comment]
I've intentionally added no line to the upcoming release notes (of course ci still complaints)

**Review by markus2330 — COMMENTED** [review]
It would be worth mentioning if you use Windows WSL(2). Please add something to the release notes, otherwise the build server does not run the formatting checks.

**Comment by tucek** [comment]
done and rdy to merge

**Comment by tucek** [comment]
The failed checks are unrelated to my changes...

**Pull request merged**
