### PR TITLE
pluginprocess-mktemp-warning-fix

### PR DESCRIPTION
**Pull request by e1528532**
# Purpose

Uses mkdtemp and puts the pipe inside this directory to avoid the mktemp warning (possible race condition between file name generation and pipe creation, maybe something else picks the name in the meanwhile, highly unlikely but theoretically possible). Fixes the issue mentioned in #1782 .

# Checklist

- [X] I ran all tests and everything went fine

@markus2330 tested by using this in conjunction with the process PR, i doubt any separate testing makes sense.

### CODE REVIEW

**Comment by e1528532** [comment]
jenkins build all please

**Comment by e1528532** [comment]
jenkins build incremental please

**Comment by e1528532** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by e1528532** [comment]
looks good. the jenkins docker build is actually done if you click the link and check the status, git doesn't seem to update the status. and the incremental test failure is strange and i guess unrelated to this PR. so imo its ready to merge unless you have any further objections.

**Comment by markus2330** [comment]
Thank you for the fix!

How does cleaning up the directory work? (unlinking it and the pipe)

**Comment by e1528532** [comment]
`elektraPluginProcessClose` which gets called in a plugin's close method calls the `cleanup` function (both in `pluginprocess.c`), which unlinks the pipes and then removes the directory. Additionally, if there is an initialization failure, it also cleans up any created pipes/directories. Ultimately if something goes very wrong then it stays, but as it gets created in `/tmp` distributions will usually clean it up themselves.

**Comment by markus2330** [comment]
Thank you, great!

If you can easily fix some cases where the cleanup does not take place, please go ahead.

**Pull request merged**
