### PR TITLE
Augeas: Fix Internal Inconsistency

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

Currently we can not build Elektra on macOS if we install [Augeas](http://augeas.net) via Homebrew:

```
CMake Error at cmake/Modules/LibAddPlugin.cmake:185 (message):
  Internally inconsistency, plugin elektra-augeas got different values for
  variable ARG_LINK_LIBRARIES: '/usr/local/lib/libaugeas.dylib' !=
  '/usr/local/lib/libaugeas.dylib;/usr/lib/libxml2.dylib'
Call Stack (most recent call first):
  cmake/Modules/LibAddPlugin.cmake:241 (restore_variable)
  src/plugins/augeas/CMakeLists.txt:28 (add_plugin)
  src/plugins/CMakeLists.txt:14 (include)
```

. This pull request should fix this bug.

# Checklist

- [x] I checked all commit messages.
- [x] I updated the release notes.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for fixing this!

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by markus2330** [comment]
Can you please also update the last question of doc/help/elektra-faq.md? (Answering where the sources + binaries of the logos are).

**Comment by markus2330** [comment]
Thank you for the fix!

**Pull request merged**
