### PR TITLE
Opmphm changes + new OPMPHM benchmarks

### PR DESCRIPTION
**Pull request by KurtMi**
# Purpose

Describe the purpose of the pull request.
(Long descriptions should be in documentation, not here)

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I added unit tests
- [x] I ran all tests and everything went fine
- [x] affected documentation is fixed
- [x] I added code comments, logging, and assertions (see doc/CODING.md)

I will update the release notes in the integration PR.

### CODE REVIEW

**Comment by KurtMi** [comment]
jenkins build gcc-configure-debian-optimizations please

**Comment by KurtMi** [comment]
jenkins build gcc-configure-debian-optimizations please

**Comment by KurtMi** [comment]
@markus2330 is seems that commit 2559c2f62b2dae7b8eda03791fa5b8ee4b98906d or dfaac9bd272c9f57a755e8055192c9e4e18f3cd7 from your broke a testcase.

**Comment by markus2330** [comment]
jenkins build gcc-configure-debian-optimizations please

**Comment by markus2330** [comment]
jenkins build gcc-configure-debian-log please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build stable please

**Comment by markus2330** [comment]
jenkins build unstable please

**Comment by markus2330** [comment]
> @markus2330 is seems that commit 2559c2f or dfaac9b from your broke a testcase.

Sorry, should be fixed now for all but travis and ini (see #1713).

**Comment by KurtMi** [comment]
jenkins build gcc-configure-debian-optimizations please

**Comment by KurtMi** [comment]
jenkins build gcc-configure-debian-optimizations please

**Comment by KurtMi** [comment]
jenkins build gcc-configure-debian-optimizations please

**Comment by KurtMi** [comment]
@markus2330 please review my PR!
The failed job from travis seems not to be related to this PR.
```
The following tests FAILED:
	104 - testshell_selftest (Failed)
	118 - testshell_markdown_dini (Failed)
	157 - testkdb_allplugins (Failed)
```

**Comment by markus2330** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Build finished. No test results found.

**Comment by sanssecours** [comment]
> The failed job from travis seems not to be related to this PR.

That is correct. I fixed the problematic tests yesterday. If you want you can rebase your PR on `master`. Afterwards the failing tests should work too.

**Comment by markus2330** [comment]
@KurtMi Can you also add release notes for your current state of OPMPH? (In a separate PR)

**Comment by KurtMi** [comment]
@markus2330 #1731 include the release notes.

**Pull request merged**
