### PR TITLE
Formatting: specify exact versions

### PR DESCRIPTION
**Pull request by kodebach**
## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

### CODE REVIEW

**Comment by kodebach** [comment]
@mpranj Is the restyled config broken in this PR, or is it normal that it doesn't run when the configfile was changed?

**Comment by mpranj** [comment]
I don't think anything is wrong on master. Seems like there is a [problem](https://restyled.io/gh/ElektraInitiative/repos/libelektra/pulls/3493/jobs) with the changes introduced in this pr. 

```
 Unexpected key "exclude", did you mean "include"?
```

**Comment by kodebach** [comment]
> I don't think anything is wrong on master. Seems like there is a [problem](https://restyled.io/gh/ElektraInitiative/repos/libelektra/pulls/3493/jobs) with the changes introduced in this pr.
> 
> ```
>  Unexpected key "exclude", did you mean "include"?
> ```

Thanks, I didn't see the error, since it wasn't linked in the PR with the other build checks.

**Comment by mpranj** [comment]
Thank you so much! It's always safer to pin these versions. 👍

**Pull request merged**
