### PR TITLE
conditionals: fix #651 *BSD regex

### LINKED ISSUE #651: OpenBSD: testmod_conditionals fails
2/104 Test   #2: testmod_conditionals ...............***Failed    0.02 sec
	CONDITIONALS     TESTS
	==================

	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:28: error in test_ifthenelseint: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:76: error in test_ifthengtint: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:93: error in test_ifthenkey: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:111: error in test_emptyisempty: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:129: error in test_notempty: error
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:199: error in test_assignElse: error setting then value
	/root/Projekte/libelektra/src/plugins/conditionals/testmod_conditionals.c:235: error in test_assignKeyElse: error setting then value

	testmod_conditionals RESULTS: 90 test(s) done. 7 error(s).

### PR DESCRIPTION
**Pull request by tom-wa**
seems like the OpenBSD (and most likely FreeBSD) posix regex implementation is completely different from the linux implementation. 

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you, nice refactoring.

But it seems like this broke Mac OS X. And please do not tamper with existing unit tests, only add new ones against regressions.

**Comment by tom-wa** [comment]
interesting. works fine on linux and openbsd for me. but i have no idea what's wrong with the os x version

the changes to the unit test were just an additional test to see if theres an issue with the whitespaces, but you are right, i'll change that part back and just add an additional test

**Comment by tom-wa** [comment]
no idea what to do about the OS X version. it works fine on OpenBSD, NetBSD and Linux
any ideas ?

**Comment by sanssecours** [comment]
> no idea what to do about the OS X version. it works fine on OpenBSD, NetBSD and Linux
any ideas ?

Just replace

```c
#if defined(__APPLE__)
#define REGEX_FLAGS_CONDITION (REG_EXTENDED | REG_ENHANCED | REG_MINIMAL)
#else
#define REGEX_FLAGS_CONDITION (REG_EXTENDED)
#endif
```

in `conditionals.c` by

```c
#define REGEX_FLAGS_CONDITION (REG_EXTENDED)
```

. After this change `testmod_conditionals` works on macOS too.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
