### PR TITLE
Fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Initialization and deinitialization is not needed anymore.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you very much for the pull request!

Please add yourself to the release notes as instructed by the build server, so that your contribution will be mentioned properly for the next release.

**Comment by markus2330** [comment]
@petermax2 do you have time to look at this?

**Comment by petermax2** [comment]
Thank you very much for the PR! The changes are looking good.

**Comment by markus2330** [comment]
Thank you for looking at it!

@neheb Thanks for your contribution! Can you add a line in the release notes?

**Comment by neheb** [comment]
I think that should do it.

**Comment by markus2330** [comment]
Perfect! Thank you very much for your contribution!

**Pull request merged**
