### PR TITLE
CM Pull request

### PR DESCRIPTION
**Pull request by mirunix**
CM Pull request for the Configuration management course registration.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating the PR! I invited you to the CM2019s group for the private repo.

Could you please add a release note to make the build server happy? (E.g. "Fixed capitalization of the initial letter").

**Comment by mirunix** [comment]
I'm not sure where can i add release notes?

**Comment by markus2330** [comment]
The build server gives you infos what to do. The file is called doc/news/_preparation_next_release.md

**Comment by mirunix** [comment]
I'm not sure what the two failures suggest, but except for that, release notes are written and I think this could be merged.

**Comment by markus2330** [comment]
Thank you for the fixes!

**Pull request merged**
