### PR TITLE
tools: catch exception in loop

### LINKED ISSUE #3669: jni: libjvm.so or libjawt.so not found at runtime
## Steps to Reproduce the Problem

```sh
kdb mount `pwd`/STUDENTS.ini system:/lvas/cm/students ini

#The command kdb mount terminated unsuccessfully with the info:
#Was not able to load such a plugin!

#Maybe you misspelled it, there is no such plugin or the loader has problems.
#You might want to try to set LD_LIBRARY_PATH, use kdb-full or kdb-static.
#Errors/Warnings during loading were:
# Sorry, 11 warnings were issued ;(
#	Sorry, module kdb issued the warning C01200:
#	Installation: Dlopen failed. Could not load module libelektra-jni.so. Reason: libjvm.so: cannot open shared object file: No #such file or directory
#	Mountpoint: /
#	Configfile:
#	At: /home/jenkins/libelektra/src/libs/loader/dl.c:90
```

This error does occur if the jni plugin is built. This also affects our packages for Ubuntu, Debian and Fedora as jni gets installed as part of the `libelektra5-all` package.
When setting `LD_LIBRARY=$JAVA_HOME/lib/server`, then mounting with ini, xml and json is working.
As far as I can tell, the `jni` plugin shouldn't even be needed for these plugins?

## System Information

- Elektra Version: master
- Docker Container with Ubuntu Focal (also occurs on Fedora33)
- OpenJdk11

### PR DESCRIPTION
**Pull request by markus2330**
partly fixes #3669

## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-3673/6/pipeline got stuck (6 hours) but looks like https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-3673/8/pipeline/ is hanging, too?

@mpranj is this maybe related to the changes with the docker registry?

**Comment by mpranj** [comment]
https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-3673/6/pipeline/ is running for 1h40m in my browser and is not stuck.

**Comment by mpranj** [comment]
Build 6 has completed successfully: https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-3673/6/pipeline/

**Comment by markus2330** [comment]
Ohh, thank you for pointing this out. I merge it then.

**Pull request merged**
