### PR TITLE
fcrypt: clean up CMakeLists.txt

### PR DESCRIPTION
**Pull request by petermax2**
# Purpose

Remove unnecessary sources from fcrypt plugin.

Hopefully fixes all compiler and linker warnings (see #1043 ).

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [ ] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

Remove unnesseccary dependencies (See #1043 ).

### CODE REVIEW

**Comment by petermax2** [comment]
jenkins build clang please

**Comment by petermax2** [comment]
jenkins build gcc-configure-debian-wheezy please

**Comment by petermax2** [comment]
jenkins build git-buildpackage-wheezy please

**Comment by petermax2** [comment]
jenkins build git-buildpackage-jessie please

**Comment by markus2330** [comment]
jenkins build gcc-configure-debian-jessie please

**Comment by markus2330** [comment]
I removed all jobs except jessie/wheezy from the build job. Please retrigger them as needed.

**Comment by markus2330** [comment]
Seems to be the same error:

```
../../plugins/fcrypt/CMakeFiles/elektra-fcrypt-objects.dir/__/base64/base64_functions.c.o: In function `libelektra_ELEKTRA_PLUGIN_NAME_C_LTX_elektraPluginbase64Encode':
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/base64/base64_functions.c:22: multiple definition of `libelektra_ELEKTRA_PLUGIN_NAME_C_LTX_elektraPluginbase64Encode'
../../plugins/base64/CMakeFiles/elektra-base64-objects.dir/base64_functions.c.o:/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/base64/base64_functions.c:22: first defined here
../../plugins/fcrypt/CMakeFiles/elektra-fcrypt-objects.dir/__/base64/base64_functions.c.o: In function `libelektra_ELEKTRA_PLUGIN_NAME_C_LTX_elektraPluginbase64Decode':
/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/base64/base64_functions.c:103: multiple definition of `libelektra_ELEKTRA_PLUGIN_NAME_C_LTX_elektraPluginbase64Decode'
../../plugins/base64/CMakeFiles/elektra-base64-objects.dir/base64_functions.c.o:/home/jenkins/workspace/workspace/elektra-git-buildpackage-jessie/libelektra/src/plugins/base64/base64_functions.c:103: first defined here
```

**Comment by petermax2** [comment]
I removed the sources from `fcrypt/CMakeLists.txt` yet they are pulled in by cmake?

The quickest solution would be to undo my last PR. What do you think?

**Comment by markus2330** [comment]
> What do you think?

As you wish: either cleanup/fix now or revert (and do cleanup later).

**Comment by markus2330** [comment]
I merged it to check if the build server was building the right thing. Maybe these two jobs do not build correctly if triggered via PR.

The merge should not make the revert harder because there already was a later commit changing something from the merge commit .. (But maybe that is not necessary after all)

**Comment by petermax2** [comment]
> But maybe that is not necessary after all

The build jobs are looking good. 

Still I think moving some common crypto/encoding code to a library would be a good idea.

**Comment by markus2330** [comment]
> The build jobs are looking good. 

Thanks for fixing it!

It might be best that you make a proposal where to move what so that we can discuss it in detail.

**Pull request merged**
