### PR TITLE
Move conversion functions from highlevel to ease

### PR DESCRIPTION
**Pull request by kodebach**
## Basics

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [x] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] meta data is updated (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))

## Review

- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
- [ ] Documentation is concise and good to read
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by kodebach** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you for creating this PR! Great idea to move them.

**Comment by kodebach** [comment]
@markus IMO this is ready to merge, link-checker won't work (see https://github.com/ElektraInitiative/libelektra/pull/2915#issuecomment-526836525)

**Comment by markus2330** [comment]
Thank you! I'll merge soon (I wait for the master build to complete)

**Pull request merged**
