### PR TITLE
Randoop

### PR DESCRIPTION
**Pull request by e1528532**
# Purpose

Adds a script you can use to execute randoop, including instructions. Furthermore adds a note for randoop to docs/TESTING.md.
The other bigger thing is i refactored the jna bindings a bit as discussed in #1506 to only allow "safe" operations in the public binding api (so nothing that crashes the jvm). I also provided appropriate factory methods so you can really use the bindings in a style you'd expect from java without having to deal with details like the varchar separators used in C. It is still possible to use the raw operations directly if one really wishes to do so (e.g. by extending the Key class to expose the pointer), but I've made sure this is not encouraged by the default API.
Some other improvements: use primitives types for getShort and so on to prevent unnecessary boxing of values. Also added better null handling to some methods where passing null would have just caused a NPE and some minor polishing.

# Checklist

- [X] commit messages are fine (with references to issues)
- [X] I ran all tests and everything went fine
- [X] I added unit tests
- [X] affected documentation is fixed
- [X] I added code comments, logging, and assertions
- [X] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Looks great, many improvements in the API! So using randoop was successful after all.

@vanessaNWK can you do a review?

**Comment by markus2330** [comment]
Does this fix #1652?

@e1528532 If yes, can we finish this for the release? (this weekend?)

**Comment by markus2330** [comment]
> Possibly, i have to check. Not sure if i find time tomorrow but i think i find time on monday or tuesday if thats still ok

It is okay but we will likely release without this, then. If you can fix something today, it would be ideal ;)

**Comment by e1528532** [comment]
today i'm already occupied but i try to shift some time tomorrow to check it out earlier then

**Comment by e1528532** [comment]
In case you agree with the memleak issue as stated in #1652 i think we can merge this to have better jna bindings for the upcoming release. In any case, even if there is still this one leak left where i am not sure if it is related to the bindings this version works better as before there were way more leak issues.

**Comment by markus2330** [comment]
Do we really need a copy of all those CMake files? Especially FindPackageHandleStandardArgs.cmake?

**Comment by e1528532** [comment]
These all were dependencies of FindJava.cmake (find_package_handle_standard_args is actually used in there), so if we want to use that module as it is (got it from cmake https://github.com/Kitware/CMake/tree/master/Modules) i think we do need them.

**Comment by markus2330** [comment]
We use `find_package_handle_standard_args` at several places already.

What is wrong with the upstream `FindJava.cmake` which must be a part of every CMake installation? It worked quite well up to now.

**Comment by sanssecours** [comment]
The package `FindPackageHandleStandardArgs.cmake` is already part of a standard CMake install at least on my machine:

```sh
locate FindPackageHandleStandardArgs.cmake
#> /usr/local/Cellar/cmake/3.9.4_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake
```

. The same is true for `FindJava.cmake`, `CMakeFindJavaCommon.cmake` and `FindPackageMessage.cmake`. Please remove these files.

**Comment by markus2330** [comment]
And bit more docu of how to execute the script would be nice. The script is also missing meta data.

Btw. is it on purpose that:

- CLASSPATH from outside is not considered
- CLASSPATH is not exported

**Comment by e1528532** [comment]
Ok fixed the java detection i think. on ubuntu the name of the module in find_package is case sensitive, on osx its not, which falsely led me to assume that FindJava is not included on ubuntu. 
There is a little mixup between java version strings between the jdk versions (oracle/openjdk, java8/java9) which i think have caught with my workaround.

> And bit more docu of how to execute the script would be nice. 

Slightly improved docu and added metadata, but could you tell me what is unclear? To me it seems pretty understandable, but that can easily be because i am familiar with it. Also bumped the default libelektra jar to 0.8.20 for the relase. 

I usually just pass the absolute paths like `./randoop /Users/admin/Downloads/randoop-3.1.5/randoop-all-3.1.5.jar /usr/local/share/java/libelektra4j-0.8.19.jar`

> CLASSPATH from outside is not considered
> CLASSPATH is not exported

Well yes it is intended yes. This variable gets submitted to the jvm via the -classpath argument and only has to contain libelektra4j-0.8.19.jar and randoop-all-3.1.5.jar in order to make randoop work.  This gets set up by the script, so i think there is little use to consider the system-wide classpath additionally (it may even break things if it is configured in a non-usual way i fear). Therefore there is no need to export it either, as it gets submitted as a parameter. At least on my systems the $CLASSPATH environment variable is empty anyway, so its probably the case for most of the systems.

Ultimately, my initial intention for the script was to have some kind of blueprint how randoop can be used to check our bindings using a standard configuration, and if someone wants to do more special things it would act as a start to get it running.

**Comment by markus2330** [comment]
Thank you for the update!

It seems like we have to wait with the release because the homepage is not ready. So if you can fix the other things till tomorrow, it would be fabulous. In particular #1666 should be fixed.

I saw that you hard code version numbers from Elektra, please use KDB_VERSION and friends instead.

> Slightly improved docu and added metadata, but could you tell me what is unclear?

It is clear together with what you say here. It should be the other way round: a more detailed explanation in the README, shorter descriptions in the PR. In particular examples are always good, the text after "I usually just pass the absolute paths like" exactly is what is missing in the description. You already improved it a lot, though.

> Ultimately, my initial intention for the script was ... it would act as a start to get it running.

Nothing wrong with that in general! For tests, however, it must be really simple so that anybody executes them at all.

**Comment by e1528532** [comment]
added my example from before, and use cmake to configure the script now to get the version number dynamically. Wasn't aware that we do preprocess our scripts via cmake too :)

**Comment by markus2330** [comment]
It seems like there is a conflict in this PR, please rebase.

**Comment by e1528532** [comment]
rebased

**Comment by markus2330** [comment]
Travis reports an error:

```
-- Found Java: /usr/lib/jvm/java-8-oracle/bin/java (found version "1.8.0.144") 

CMake Error at src/bindings/jna/CMakeLists.txt:11 (if):

  if given arguments:

    "Java_VERSION" "VERSION_GREATER_EQUAL" "1.8.0"

  Unknown arguments specified
```

**Comment by markus2330** [comment]
Also here the build takes endless... (not a single macOS build so far). Will have to wait for tomorrow.

**Comment by e1528532** [comment]
Unfortunately the macOS builds are very slow currently. I've cancelled the previous randoop builds and the haskell dependency builds (already merged, had my own build) which were still in the queue to free up some instances. Also i've triggered my own build at https://travis-ci.org/e1528532/libelektra/builds/295085816 like i did for the haskell dependency builds to hopefully speed up the process.

**Comment by markus2330** [comment]
Thank you, your build went through!

**Pull request merged**
