### PR TITLE
Travis: Fix Timeout Problems 

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request hopefully fixes the timeout problems of the Travis build. 

# Checklist

- [x] I checked all commit messages twice.
- [x] I ran all tests and everything went fine.
- [x] This pull requests updates the meta data of the Curlget plugin.

### CODE REVIEW

**Comment by sanssecours** [comment]
Looks like there was a [transient error](https://travis-ci.org/ElektraInitiative/libelektra/jobs/244306508#L960-L972) in `testcpp_contextual_thread`. That might be something we should look into.

**Comment by sanssecours** [comment]
The command `ninja install` reports the following [error](https://travis-ci.org/ElektraInitiative/libelektra/jobs/244460466#L1564-L1567), even if we install Cheetah on the build server:

```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: option --install-layout not recognized
```

. Is this a known issue?

**Comment by markus2330** [comment]
Thank you for unveiling these problems. Let us create new issues for them and merge this as is?

**Comment by sanssecours** [comment]
> Let us create new issues for them and merge this as is?

Okay. I filed a new issue for the bug [here](https://github.com/ElektraInitiative/libelektra/issues/1517).

**Comment by markus2330** [comment]
Thank you for this travis fix!

Can you also create an issue for the transient error in testcpp_contextual_thread? On my computer it "never" happens (tried it several hundred times in a loop now). Could you also reproduce it on your computer? `valgrind --tool=helgrind bin/testcpp_contextual_thread` reports some data races. Seems like the tests rely on that in 100ms one thread will overtake the other (without mutexes actually protecting the data).

**Comment by sanssecours** [comment]
> Can you also create an issue for the transient error in testcpp_contextual_thread?

I do not think that makes much sense, since the command:

```fish
for _ in (seq 1000)
  ctest -R testcpp_contextual_thread > /dev/null
  or echo 😱
end
```

did not print any “😱” characters on my machine.

**Comment by markus2330** [comment]
> did not print any “😱” characters on my machine.

Yes, same here. Seems to happen quite rarely. I opened the issue #1519 nevertheless.

Thank you for trying!

**Pull request merged**
