### PR TITLE
Introduce ELEKTRA_BIG_ENDIAN

### PR DESCRIPTION
**Pull request by KurtMi**
Introduce a flag to determine endianness.

@markus2330 please review my pull request

### CODE REVIEW

**Comment by KurtMi** [comment]
jenkins build gcc-configure-debian-optimizations please

**Comment by KurtMi** [comment]
jenkins build gcc-configure-debian-optimizations please

**Comment by markus2330** [comment]
Any idea why travis is not running? How can we test the big endian code? (Seems to be quite different to the little endian hash function.) I would refactor it into two  functions (or even three for the 4 common lines of code).

**Comment by sanssecours** [comment]
> Any idea why travis is not running?

Yes, currently Travis experiences a [major outage](https://www.traviscistatus.com) concerning all macOS builds.

**Comment by markus2330** [comment]
Thanks for the information! I merged for now, refactoring can happen later...

**Pull request merged**
