### PR TITLE
ci: Remove python3 from macOS brew install

### LINKED ISSUE #4789: macOS jobs broken
Currently, all macOS jobs fail with the same error:

```
==> Pouring python@3.10--3.10.9.big_sur.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.10

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.10

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3
/usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3
/usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3
/usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
```

I am not aware what `2to3` exactly is but from this output I conclude, that multiple packages try to install this binary. As I cannot find any recent changes in the macOS build instruction, I assume that something changed within the brew repositories.

https://github.com/ElektraInitiative/libelektra/actions/runs/3753156602/jobs/6376133446 is a job where this happens.

### PR DESCRIPTION
**Pull request by Eiskasten**
The aim of this PR is to fix #4789 which reported a broken macOS build job.

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you for working on this! Did you read https://docs.brew.sh/Homebrew-and-Python as recommended in the output?

I think first we should find out what pulls in python and why it uses the outdated 3.10 version if setup-python already installed 3.11.1.

**Comment by mpranj** [comment]
Python version aside, this PR removes Python from cirrus CI, where macOS builds are not failing.

The failed builds are the Github workflows which use actions to install a specific Python version.
Looks like python@3.10 is preinstalled in the used macOS image, and just being updated.

@Eiskasten do you have time or should I take a look at this?

**Comment by Eiskasten** [comment]
> Thank you for working on this! Did you read https://docs.brew.sh/Homebrew-and-Python as recommended in the output?
> 
> I think first we should find out what command pulls in the problematic Python and why it uses the outdated 3.10 version if setup-python already installed 3.11.1.

I read it, however I am not very familiar with macOS and I am not quite sure what consequences it means.

**Comment by Eiskasten** [comment]
> Python version aside, this PR removes Python from cirrus CI, where macOS builds are not failing.
> 
> The failed builds are the Github workflows which use actions to install a specific Python version. Looks like python@3.10 is preinstalled in the used macOS image, and just being updated.
> 
> @Eiskasten do you have time or should I take a look at this?

I also think, that 3.10 is the preinstalled version. I would appreciate if you can have a look on this since I literally know nothing about macOS build chains.

**Comment by Eiskasten** [comment]
As #4789 is resolved, this can be closed.

**Pull request closed without merging**
