### PR TITLE
rest-frontend: improvements

### PR DESCRIPTION
**Pull request by Namoshek**
# Purpose

Solves some tasks of #1151 and #1182. See commit messages for more info.

@markus2330 please review my pull request

### CODE REVIEW

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
Great job, I like the new slogan rewriting. A minor thing: maybe you can turn off the blinking after it went through all possibilities? (during writing it does not blink, too) Or change blinking speed?

**Comment by Namoshek** [comment]
Hm yes, I think there is an option for that. Unfortunately there are no options for:
- delay betwen typing and erasing
- delay betwen erasing and typing
- loop/repeat everything

**Comment by markus2330** [comment]
> Hm yes, I think there is an option for that.

That would be great, thanks!

> loop/repeat everything

No reason to change this: I like that it stops after some time ;)

**Comment by Namoshek** [comment]
Btw. 'finally' is the last word on purpose, I changed the order again (not sorted by length anymore). If you feel that it needs a change, you can also change it in the [WebsiteHomeController.js](https://blob.libelektra.org/src/tools/rest-frontend/resources/assets/js/controllers/main/website/WebsiteHomeController.js).

**Comment by markus2330** [comment]
Yes, I already noticed and liked it!

**Pull request merged**
