### PR TITLE
Fix man

### PR DESCRIPTION
**Pull request by KurtMi**
Fix man build because of:

invalid byte sequence in US-ASCII (ArgumentError)

caused by strange double quotes and –

### CODE REVIEW

**Comment by KurtMi** [comment]
@sanssecours please watch your double quotes :)

**Comment by sanssecours** [comment]
> @sanssecours please watch your double quotes :)

Sorry. I just used normal [English quotation marks](https://en.wikipedia.org/wiki/Quotation_mark) and [en-dashes](https://en.wikipedia.org/wiki/Dash#Em_dash). Those characters are quite common in English prose. May I ask which tool is not able to handle UTF-8 characters properly?

**Comment by KurtMi** [comment]
ronn the manpage builder, so it only concerns the files in doc/help

**Comment by sanssecours** [comment]
> ronn the manpage builder, so it only concerns the files in doc/help

Thank you for the information.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
