### PR TITLE
Conditionals: added new syntax for value assignments

### PR DESCRIPTION
**Pull request by tom-wa**

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you! Looks really nice. I was thinking, however, that not the metadata `check/condition` (its name would be contradictory) should be used for this feature, but instead the new metadata `assign`.

And it would be good to have examples for the feature, too. (Or even better: shell test cases embedded in the README.md.)

**Comment by markus2330** [comment]
jenkins build please

**Comment by tom-wa** [comment]
@markus2330 would you prefer "assign/condition" or "condition/assign" as metakey ?

**Comment by markus2330** [comment]
Why not simply use `assign`? Do you plan to implement `assign` for math-plugin, too (somewhere in future)? Then use `assign/condition` and `assign/math`.

Btw. in the contract you now have to state all metadata a plugin can take care of.

Thank you!

**Comment by tom-wa** [comment]
yeah, that's the plan (+ probably some other plugins in future), so i'll go with assing/condition

**Comment by markus2330** [comment]
Thank you! Please ping me if you are ready!

**Comment by tom-wa** [comment]
@markus2330 done

**Comment by markus2330** [comment]
Thank you! The docu sometimes talks about `assign`, but I will fix it.

**Comment by tom-wa** [comment]
sorry, i initially used `assign` but thought it would be ambiguous if other plugins would provide an assign operation too. Forgot to change it in the README.

**Pull request merged**
