### PR TITLE
Fix cmake errror when BUILD_DOCUMENTATION is set to OFF

### PR DESCRIPTION
**Pull request by KurtMi**
# Purpose

Setting DOCUMENTATION to Off leads to a cmake error traget `man` not found.

# Checklist

- [X] commit messages are fine (with references to issues)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by sanssecours** [comment]
> Setting DOCUMENTATION to Off leads to a cmake error traget `man` not found.

Can you please provide steps to reproduce this problem?

The following worked without problems on my machine:

```
mkdir build
cd build
cmake -GNinja -DBUILD_DOCUMENTATION=OFF ..
ninja
```

.

**Comment by KurtMi** [comment]
> Can you please provide steps to reproduce this problem?

Oh, it seems that this error occurs when cmake will be executed without `DBUILD_DOCUMENTATION=OFF` and changing it later with `ccmake .`.
I am not sure now if that is a bug :)

**Comment by sanssecours** [comment]
> Oh, it seems that this error occurs when cmake will be executed without `DBUILD_DOCUMENTATION=OFF` and changing it later with `ccmake .`.

I tried:

```sh
mkdir build
cd build
cmake -GNinja ..
ninja
cmake -GNinja -DBUILD_DOCUMENTATION=OFF ..
ninja
```

, which also worked on my machine.

> I am not sure now if that is a bug :)

I am not sure either 😊. I can remember that I encountered a similar bug once. Maybe we already fixed this problem in the `master` branch?

**Comment by KurtMi** [comment]
> I tried:
You missed a `c` the tool is:
https://cmake.org/cmake/help/v3.0/manual/ccmake.1.html
try:
```
mkdir build
cd build
cmake -GNinja ..
ninja
ccmake . <- change in the gui the BUILD_DOC flag
press c and then g
```

**Comment by sanssecours** [comment]
> You missed a c the tool is:…

As far as I can tell, there should be no real difference between `cmake` and the “graphical“ frontend `ccmake`. At lease `ccmake .` and `ccmake ..` show that `BUILD_DOCUMENTATION` currently has the value `OFF` on my machine.

**Comment by KurtMi** [comment]
> As far as I can tell, there should be no real difference between cmake and the “graphical“ frontend ccmake. At lease ccmake . and ccmake .. show that BUILD_DOCUMENTATION currently has the value OFF on my machine.

Ok, I am not sure, It is possible that it comes from my cmake version:
```
cmake version 3.9.4
```
Feel free to just drop this PR!

**Comment by sanssecours** [comment]
> Ok, I am not sure, It is possible that it comes from my cmake version:
> ```
> cmake version 3.9.4
> ```

I don’t think so. At least my version of `cmake` (`cmake version 3.9.5`) should not be that different from the one on your machine.

> Feel free to just drop this PR!

I leave that up to you. I am not sure about discarding the work you put into the PR, just because I am unable to reproduce the issue. Maybe Markus or some of the other developers can take a look and check if they are able to reproduce the problem.

**Comment by KurtMi** [comment]
There was not even 5 minutes work in this PR :) This PR will be dropped, reason issue non reproducible.

**Comment by markus2330** [comment]
Yes, when I set "BUILD_DOCUMENTATION" to OFF (with ccmake) I get:

```
 CMake Error at cmake/Modules/LibAddMacros.cmake:534 (add_dependencies):
   Cannot add target-level dependencies to non-existent target "man".

   The add_dependencies works for top-level logical targets created by the
   add_executable, add_library, or add_custom_target commands.  If you want to
   add file-level dependencies see the DEPENDS option of the add_custom_target
   and add_custom_command commands.
 Call Stack (most recent call first):
   scripts/CMakeLists.txt:20 (generate_manpage)
```

Seems like reopening is not possible because the branch was removed. I cannot try if the fix works.

**Comment by sanssecours** [comment]
> Yes, when I set "BUILD_DOCUMENTATION" to OFF (with ccmake) I get:

I tried again. I can now also reproduce the problem using the steps below. I think the problem was that I uninstalled `ronn` and never reinstalled it until now.

1. 

   ```sh
   mkdir build
   cd build
   ccmake ..
   ```

2. Press <kbd>c</kbd>

3. 

   ```
    CMake Warning at src/plugins/lua/CMakeLists.txt:50 (message):
      swig_lua bindings are required for testing, test deactivated
    Call Stack (most recent call first):
      src/plugins/CMakeLists.txt:14 (include)
   
   
   
    CMake Warning at src/plugins/python2/CMakeLists.txt:70 (message):
      swig_python2 bindings are required for testing, test deactivated
    Call Stack (most recent call first):
      src/plugins/CMakeLists.txt:14 (include)
   ```
   
4. Press <kbd>e</kbd>
5. Set `BUILD_DOCUMENTATION` to `OFF` by pressing <kbd>↩</kbd>
6. Press <kbd>c</kbd>
7. 

   ```
    CMake Error at cmake/Modules/LibAddMacros.cmake:534 (add_dependencies):
      Cannot add target-level dependencies to non-existent target "man".
   
      The add_dependencies works for top-level logical targets created by the
      add_executable, add_library, or add_custom_target commands.  If you want to
      add file-level dependencies see the DEPENDS option of the add_custom_target
      and add_custom_command commands.
    Call Stack (most recent call first):
      scripts/CMakeLists.txt:20 (generate_manpage)
   ```

**Comment by sanssecours** [comment]
> Seems like reopening is not possible because the branch was removed. I cannot try if the fix works.

[Copy and paste](https://github.com/KurtMi/libelektra/blob/ab0037aee14a96631be18e40ddf8a78d497a64dc/cmake/Modules/LibAddMacros.cmake) is everyone’s friend 😊. I tried the fix, and it seems to work.

**Comment by markus2330** [comment]
Thank you, can you create the PR again or directly push it?

**Comment by sanssecours** [comment]
> Thank you, can you create the PR again or directly push it?

I just pushed the changes. I used Kurt’s credentials in the authors field of the commit, since the update is his work.

**Pull request closed without merging**
