### PR TITLE
Rename KDB commands

### LINKED ISSUE #265: Improve Naming Schemes for KDB Commands
You are completely right!
This was outlined in [issue #260](https://github.com/ElektraInitiative/libelektra/issues/260) by Markus but I wanted to separate this into it's own issue for clarity.

From Markus:

> I would suggest to use a hierarchical naming schema:  
> kdb-plugin (no real command, just general info about plugins)
> kdb-plugin-check
> kdb-plugin-info
> kdb-plugin-list (or kdb-plugin-ls?)
> 
> To be discussed if this also applies to meta and/or mounting:    
> 
> kdb-meta (info about meta data)
> kdb-meta-ls
> kdb-meta-set
> 
> and for future spec, global mounts:    
> 
> kdb-global-mount
> kdb-global-unmount
> 
> kdb-spec-mount
> kdb-spec-unmount
> 
> I agree we should have aliases to not break scripts.

### PR DESCRIPTION
**Pull request by PhilippGackstatter**
- Prefix kdb info, check and list with plugin-
- Rename meta commands to `meta-rm`, `meta-set`, etc.
- Remove kdb fstab

fixes #265 

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [x] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise and good to read
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating the PR!

**Comment by PhilippGackstatter** [comment]
The jenkins build fails with this

```
dh_install --list-missing
dh_install: Cannot find (any matches for) "usr/share/man/man1/kdb-check.1" (tried in "." and "debian/tmp")
dh_install: elektra-bin missing files: usr/share/man/man1/kdb-check.1
dh_install: Cannot find (any matches for) "usr/share/man/man1/kdb-fstab.1" (tried in "." and "debian/tmp")
dh_install: elektra-bin missing files: usr/share/man/man1/kdb-fstab.1
...
```

I renamed kdb-check to kdb-plugin-check, both the doc/help markdown file and the man page itself. I can't find any explicit reference to those files, so why is that file still searched for?

**Comment by sanssecours** [comment]
> I renamed kdb-check to kdb-plugin-check, both the doc/help markdown file and the man page itself. I can't find any explicit reference to those files, so why is that file still searched for?

The problem here is the dreaded [`debian` branch](https://github.com/ElektraInitiative/libelektra/tree/debian). You probably have to update some of the Debian package description files in the folder [`debian`](https://github.com/ElektraInitiative/libelektra/tree/debian/debian). Otherwise building the Debian packages will not work.

**Comment by PhilippGackstatter** [comment]
Thank you! Since this is a different branch, what's the best way to go about this? Do I submit a separate PR that includes all of the changes from this PR plus the debian specific changes?

**Comment by markus2330** [comment]
You are allowed to directly push commits to the debian branch to fix such problems (add/remove files). The problems with the man pages is hopefully already fixed with e78d6035cd7a7bffc21e6d95a4244b4c135ce696

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by PhilippGackstatter** [comment]
> The problems with the man pages is hopefully already fixed with [e78d603](https://github.com/ElektraInitiative/libelektra/commit/e78d6035cd7a7bffc21e6d95a4244b4c135ce696)

Thank you!

**Comment by markus2330** [comment]
Looks good, all tests passed. Is this ready to merge?

**Comment by PhilippGackstatter** [comment]
Yes, it's ready to merge then.

**Comment by markus2330** [comment]
Thank you, great work!

**Pull request merged**
