### PR TITLE
Theme: Preparations for custom website theme

### PR DESCRIPTION
**Pull request by waht**
# Purpose

Preparations in the build configuration of "rest-frontend" for upcoming custom website theme.

# Checklist

- [x] commit messages are fine (with references to issues)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you! Great to see progress here!

**Comment by markus2330** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
add to whitelist

**Comment by waht** [comment]
Seems fine to me - some testshell tests failed.

**Comment by markus2330** [comment]
Yes, the failing of the testcases is unrelated to this PR here. Is this ready to merge?

**Comment by waht** [comment]
Yes, ready to merge.

**Comment by markus2330** [comment]
Thank you! Hopefully the build-homepage build job gets fixed soon.

**Pull request merged**
