### PR TITLE
Packaging for fuse tool

### PR DESCRIPTION
**Pull request by dev2718**
# Packaging for fuse tool

This PR introduces packaging (``libelektra(5)-fuse``) (Debian and Fedora) for the fuse tool,
improves the install location of the tool and updates the readme on tool-creation.

Issues:
- The Cirrus/Fedora Dockerfile has not been updated yet due to #4009 (which only affects the CI and not package creation).
- `python3-elektra` is not getting built on debian-bullseye, therefore `libelektra5-fuse` isn't as well
- The check task fails due to broken links because `http://wiki.jenkins.io/` is down at the moment

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
At the moment the build server does not succeed, do you need help?

You will need to add the deps in the Dockerfiles, so that the package actually gets built. Did you do this for Debian bullseye?

**Comment by dev2718** [comment]
> At the moment the build server does not succeed, do you need help?
> You will need to add the deps in the Dockerfiles, so that the package actually gets built. Did you do this for Debian bullseye?

There were two failures:
 1) [First One:](https://github.com/ElektraInitiative/libelektra/pull/3996/checks?check_run_id=3364915345) `... You should download the Command Line Tools for Xcode 12.5.` This seems like a problem related with the buildserver itself.
2) [Second One:](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-3996/3/pipeline/) Here we get ``elektra-fuse requires Python '>=3.8' but the running Python is 3.7.3``. This intrigues me, since CMake seemingly returns python3.7 although >= 3.8 was requested. I added a manual check to ensure the python version in efea71c1520a187829d1def4839a386e054073cf.

Regarding the dependencies in the Dockerfiles:
I haven't made any changes here yet.
For building I require python >= 3.8 with modules pip and wheel. Should I add these requirements to all Dockerfiles? What about older distributions that don't support python 3.8?

**Review by robaerd — CHANGES_REQUESTED** [review]

**Comment by dev2718** [comment]
Thank your for the review @robaerd, I applied your suggestions in 4fabfc8a6b74386a740854094242d67dd30157f1.

**Review by markus2330 — COMMENTED** [review]
Did you push on purpose only a trivial commit with the "python3-wheel" in the Docker image? In general it is better to create new PRs for trying out things like this and leave the original PR intact.

**Comment by dev2718** [comment]
> Did you push on purpose only a trivial commit with the "python3-wheel" in the Docker image? In general it is better to create new PRs for trying out things like this and leave the original PR intact.

That is correct, I will use separate PRs in the future and will restore  back this PR.

On a different note, this particular experiment is concerning [log](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-3996/32/pipeline/775):

Taking current master (552b34e299bb2d4c7c0f724272bb6ecc93b6394f) and adding a single dependency (python3-wheel) to `scripts/docker/debian/bullseye/Dockerfile` should not result in
- testruby_tools_plugindatabase.rb giving a segmentation fault on `debian-bullseye-full-optimizations-off`, and
-  testio_uv failing on `fedora-33-full`.

**Comment by markus2330** [comment]
Amazing job, I am looking forward to installing the packages!

**Pull request merged**
