### PR TITLE
adds python2 plugin

### PR DESCRIPTION
**Pull request by manuelm**
+ adds python2 plugin
+ marks all python2 stuff as deprecated

### CODE REVIEW

**Comment by manuelm** [comment]
jenkins build bindings please

**Comment by manuelm** [comment]
A short heads up: Since the python3 plugin has been merged without my permission and I was required to waste my time with rebasing, I'll accept this PR as soon as the build server is green.

This PR adds a fatal message to cmake if `BUILD_TESTING` is enabled but python bindings are missing. Without the bindings testing is not possible. So this _will_ kill some jenkins build jobs. Feel free to replace the message with `remove_plugin` or adapt the jenkins jobs after I've pulled this in.

**Comment by manuelm** [comment]
Build error is related to running python2 and python3 in the same binary. Will merge it anyway.

**Comment by markus2330** [comment]
Last minute fixes are ok, but last minute additions of new plugins is not ideal. Nevertheless, I keep it, with the same disclaimer as for python plugin. I won't look into build variants for python for this release, enough ping pong commits for now ;)

Thanks for your effort and I am looking forward to feedback with the plugins. I already got a small storage plugin working.

**Pull request merged**
