### PR TITLE
#4100,  4092 fixed, updated release notes documentation

### PR DESCRIPTION
**Pull request by flackojr**
## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by flackojr** [comment]
This is my first ever github contribution any and all help/guidance would go a long way

**Comment by mpranj** [comment]
Thank you for the quick fix!

It looks like only source formatting issues are remaining now. If you take a look at the [output](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4101/3/pipeline/520) in our Jenkins CI pipeline, you will see instructions how to fix them. The quickest way is to copy the patch to a file and apply the changes, as described in the instructions.

**Comment by flackojr** [comment]
Let me know if there is any change to be made. Thank you!

**Comment by flackojr** [comment]
Alright I'll have a look and get back to you by the end of the day I'm a bit tied up with college work right now

**Comment by flackojr** [comment]
Sorry I will remove myself from this I cannot seem to figure it out

**Comment by mpranj** [comment]
@flackojr it looks like you tried to fix the formatting using your editor or IDE, which is not the recommended or easy way. The simplest way to reformat the sources is shown directly in the [output of the build server](https://build.libelektra.org/blue/rest/organizations/jenkins/pipelines/libelektra/branches/PR-4101/runs/7/nodes/520/log/?start=0):

```
If you do not want to install any of the tools listed above you can also use the `patch` command after this message
to fix the formatting problems. For that please

1. copy the lines between the long dashes (`—`),
2. store them in a file called `format.patch` **in the root of the repository**

. After that use the following command to apply the changes:

    sh -c '
    line_prefix="$(head -n1 format.patch | sed -nE '"'"'s/(^[0-9]+:).*/_/p'"'"' | wc -c | sed -E '"'"'s/[ ]*//g'"'"')"
    { test "$line_prefix" -gt 1 && cut -c"$line_prefix"- format.patch || cat format.patch ; } | patch -p1
    '

.


————————————————————————————————————————————————————————————

diff --git a/scripts/cmake/ElektraCache.cmake b/scripts/cmake/ElektraCache.cmake
index ec1c9e218..5bde98ae1 100644
--- a/scripts/cmake/ElektraCache.cmake
+++ b/scripts/cmake/ElektraCache.cmake
@@ -422,9 +422,8 @@ mark_as_advanced (
 	GIT_EXECUTABLE
 	LIBGCRYPT_INCLUDE_DIR
 	XercesC_DIR
-	OPENSSL_INCLUDE_DIR
-)
-mark_as_advanced(
+	OPENSSL_INCLUDE_DIR)
+mark_as_advanced (
 	LUA_EXECUTABLE # The following settings are internal (not to be changed by users):
 	FEDORA
 	CARGO_EXECUTABLE
@@ -481,5 +480,4 @@ mark_as_advanced(
 	GLib_LIBRARY
 	LibGit2_VERSION_HEADER
 	libuv_VERSION_HEADER
-	Qt5Svg_DIR
-)
+	Qt5Svg_DIR)

————————————————————————————————————————————————————————————
```

So basically you only copy this diff (between the long dashes) to a file called `format.patch` and then apply this patch using the shown command. I would recommend removing the formatting commits you have already done, before applying the patch.

The PR looks pretty good other than the formatting issues.

**Pull request closed without merging**
