### PR TITLE
tests: remove clearenv in tests

### PR DESCRIPTION
**Pull request by markus2330**
# Purpose

See #1906

# Checklist

Check relevant points but please do not remove entries.
For docu fixes, spell checking, and similar nothing
needs to be checked.

- [ ] commit messages are fine ("module: short statement" syntax and refer to issues)
- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

### CODE REVIEW

**Comment by ingwinlu** [comment]
wrong issue referenced, should be #1906

**Comment by ingwinlu** [comment]
jenkins build docker please

**Comment by ingwinlu** [comment]
jenkins build docker please

**Comment by ingwinlu** [comment]
I can confirm that this fixes my issues locally, all tests seem to pass as well (except for clang, which is unrelated to this PR)

**Comment by markus2330** [comment]
Thank you for testing!

**Pull request merged**
