### PR TITLE
Elektra Qt Editor: add optional svg component in cmake

### LINKED ISSUE #796: svg module not added to COMPONENTS
Did you try to compile Elektra if the svg component is not installed?
(I did not find a way to install it on Debian, but it might be possible at other systems and is certainly is possible if you compile Qt yourself because it is an add-on).

I think it might need to be listed in QCOMPONENTS, what do you think?

### PR DESCRIPTION
**Pull request by sirblackheart**
should fix #796

### CODE REVIEW

**Comment by markus2330** [comment]
Is it necessary at all? Did you test it?

**Comment by sirblackheart** [comment]
On my system it worked without the addition from the beginning. But my system also has a qt5-svg package.

**Comment by sirblackheart** [comment]
So i need you to test it if it helps on your system where you found the problems.

**Comment by sirblackheart** [comment]
No this does not work

**Comment by sirblackheart** [comment]
Well it kind of does, it gives a warning because FindQt5Svg was not found if qt5-svg is not installed. If it is installed it works as expected. So it probably is the best way to solve this.

**Comment by sirblackheart** [comment]
This should do it. And yes it works now as expected.

**Comment by markus2330** [comment]
Is the additional (manual) message then necessary?

**Comment by markus2330** [comment]
I think its okay when cmake outputs a warning that a OPTIONAL_COMPONENTS was not found for us. We should not circumvent what cmake wants to do for us.

**Comment by sirblackheart** [comment]
It is how you should handle such cases as it is optional. Not finding the find file is more confusing to a user.

**Comment by markus2330** [comment]
I am talking about the part where its made QUIET with a manual output later.

Why not avoid the manuel output and not use QUIET?

**Comment by sirblackheart** [comment]
Because of the output it produces that is more confusing to a user then the manual message.
CMake complains about not finding the Find* file if not QUIET, that is basically meaningless for the user. Module not found makes more sense to him.

**Comment by markus2330** [comment]
The users are maintainers who see such messages every day.

I would rather expect that they would overlook our tiny message, because they expect warnings of missing components to be presented in the standard way.

Lets simply output both messages, then every case should be covered.

**Comment by sirblackheart** [comment]
Then please do that for everything, print clear warning messages when a binding gets excluded etc... And do not just make an exception for one case

**Comment by sirblackheart** [comment]
> The users are maintainers who see such messages every day.

Very bad reasoning to produce a bad warning. Only because everyday cmake users are used to this kind of warning it can be a problem for a new user.

**Comment by sirblackheart** [comment]
> I would rather expect that they would overlook our tiny message, because they expect warnings of missing components to be presented in the standard way.

Then lets open an issue and rework our cmake messaging system.

**Comment by markus2330** [comment]
Ok, done in 351fa1f3a9b5048599794996772a54472d66d10f

**Pull request merged**
