### PR TITLE
Add PLUGIN_DEPENDENCIES.md 

### PR DESCRIPTION
**Pull request by iandonnelly**
Added document that list packages needed to build plugins with dependencies.

### CODE REVIEW

**Comment by markus2330** [comment]
Can one of the admins verify if this patch should be build?

**Comment by markus2330** [comment]
Can one of the admins verify if this patch should be build?

**Comment by iandonnelly** [comment]
I split the dependencies into each plugin's readme as Markus and I agreed it would be better this way.

**Comment by markus2330** [comment]
thank you!

**Pull request merged**
