### PR TITLE
rest-frontend: improvements

### PR DESCRIPTION
**Pull request by Namoshek**
# Purpose

Some improvements mentioned in #1151 and #1153. See commit messages for further details.

# Checklist

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine

@markus2330 please review my pull request

### CODE REVIEW

**Comment by Namoshek** [comment]
jenkins build gcc-asan please

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
Would be nice to have this one merged too @markus2330.

**Comment by markus2330** [comment]
Thanks for pinging! Luckily I did not complain about the rss feed ...

**Comment by Namoshek** [comment]
Yeah I was quite sure you overlooked it after it being ready to merge for almost a day. :smile:

**Pull request merged**
