### PR TITLE
Bindir fix

### PR DESCRIPTION
**Pull request by kodebach**
## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you so much!

**Comment by kodebach** [comment]
@markus2330 @mpranj can one of you check, if `test_elektra-specload-testapp` works on your machine. It works on mine (*) and I have no idea, why it would fail.

(*) On my machine, it works without ASAN enabled. If I enable ASAN, I get some errors, but `valgrind` doesn't detect any leaks so I disabled the test when ASAN is enabled.

**Comment by markus2330** [comment]
```
test 127
    Start 127: test_elektra-specload-testapp

127: Test command: /home/markus/Projekte/Elektra/build/bin/test_elektra-specload-testapp "/home/markus/Projekte/Elektra/current/src/plugins/specload"
127: Environment variables: 
127:  LD_LIBRARY_PATH=/home/markus/Projekte/Elektra/build/lib
127: Test timeout computed to be: 30
127: SPECLOAD_TESTAPP     TESTS
127: ==================
127: 
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 0 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 1 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 2 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 3 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 4 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 5 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 6 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 7 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 8 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 9 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 10 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 11 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 12 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 13 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 14 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 15 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 16 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 17 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 18 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 19 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 20 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 21 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 22 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 23 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 24 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 25 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 26 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 27 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:112: error in check_binary_file: actual size 47 differs from expected size 28
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:120: error in test_default: output differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 0 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 1 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 2 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 3 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 4 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 5 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 6 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 7 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 8 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 9 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 10 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 11 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 12 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 13 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 14 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 15 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 16 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 17 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 18 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 19 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 20 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 21 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 22 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 23 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 24 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 25 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 26 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:93: error in check_binary_file: byte 27 differs
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:112: error in check_binary_file: actual size 3850 differs from expected size 28
127: /home/markus/Projekte/Elektra/current/src/plugins/specload/test_testapp.c:129: error in test_noparent: output differs
127: 
127: test_testapp Results: 6 Tests done — 60 errors.
127: /home/markus/Projekte/Elektra/current/tests/cframework/tests.c:528: error in clean_temp_home: Could not delete TMPHOME via nftw
1/1 Test #127: test_elektra-specload-testapp ....***Failed    0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.02 sec

The following tests FAILED:
        127 - test_elektra-specload-testapp (Failed)
```

**Comment by kodebach** [comment]
Very interesting... You got different file sizes than the build server

**Comment by kodebach** [comment]
I think I found the problem, `KDB_TEST_BIN_DIR` wasn't set for the test.

**Comment by markus2330** [comment]
Great work, the test cases passes for me now.

**Comment by markus2330** [comment]
What is missing here to get it ready for merging? #3623 has an workaround for this here.

**Comment by kodebach** [comment]
I did a rebase, because there was some weird Ruby dependency issue with the Cirrus macOS builds. It seems something broke during the rebase.

**Comment by mpranj** [comment]
It's just a formatting problem, according to restyled.

**Comment by markus2330** [comment]
If I did not miss something, this would be the last functional PR to be merged. Would be good to get this formatting/rebasing problem fixed.

**Comment by kodebach** [comment]
Yes, the problem was technically incorrect formatting. But that's because either through the rebase or by some other mistake, the release notes from #3608 landed in this PR. I removed them, now everything should be fine.

PS. My PRs are normally set to allow edits from maintainers, so if I don't have time to fix something like formatting quickly, feel free to help out.

**Comment by mpranj** [comment]
> PS. My PRs are normally set to allow edits from maintainers, so if I don't have time to fix something like formatting quickly, feel free to help out.

Nice, thank you so much!

**Pull request merged**
