### PR TITLE
Update Format of Markdown Headings

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

As [proposed by Dominik](https://github.com/ElektraInitiative/libelektra/pull/1338#issuecomment-279223751) (@domhof) this pull request removes trailing `#` characters from Markdown headings.

# Checklist

- [x] I double-checked all commit messages.
- [x] I ran all tests and everything went fine.
- [x] I also updated `CODING.md` to reflect the style change.

### CODE REVIEW

**Comment by markus2330** [comment]
@sanssecours Thank you! Seems like your regex did not include the `.github` folder?

@Namoshek Comments? (Or last words)

**Comment by Namoshek** [comment]
I initially tried to do the exact opposite (add trailing hashes), but I'm fine with it. I think no markdown parser has an issue with this.

**Comment by sanssecours** [comment]
> @sanssecours Thank you! Seems like your regex did not went over the `.github` folder?

Yes, looks like TextMate does not search hidden directories by default. I also updated `.github/CONTRIBUTING.md` in my latest update to this pull request. Thank you for the hint.

**Comment by markus2330** [comment]
Thanks for bringing it in a consistent state! So hopefully we will keep that state for a while!

**Comment by Namoshek** [comment]
Maybe a [linter](https://github.com/wooorm/remark-lint) (or [another one](https://github.com/DavidAnson/markdownlint)) could help? :+1:

**Pull request merged**
