### PR TITLE
jna-maven-fix-tests

### PR DESCRIPTION
**Pull request by e1528532**
# Purpose

Fix the failing jna bindings test as the native library is not yet installed to the system, so use the one from the build environment for our tests

# Checklist

- [X] commit messages are fine (with references to issues)
- [ ] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build stable please

**Comment by markus2330** [comment]
jenkins build unstable please

**Comment by markus2330** [comment]
jenkins build log please

**Comment by markus2330** [comment]
Please always start the build server jobs when creating PRs. It seems like the build server does not start automatically anymore.

**Comment by e1528532** [comment]
Ok it finds the native library now. The remaining issue is that it looks like the kdb tests fail if Elektra is not actually installed (so those that write to kdb and expect the keys to be still present when reopening kdb). Is this supposed to work on travis (persisting stuff in kdb)?

**Comment by markus2330** [comment]
Why shouldn't it work to persist keys? Many other tests do so, too.

Is it maybe a concurrency issue? One of the 3 builds succeeded: https://travis-ci.org/ElektraInitiative/libelektra/jobs/203455791

Btw. the errors are really vague, can you add more infos in the exceptions? (Everything you get from KDB)

**Comment by e1528532** [comment]
Yes the errors are indeed really vague, the bindings needed something like the printWarnings from c so i ported it over. Now we have better information:

```
Caused by: java.lang.Throwable:
failure in I/O to KDB: 3 Warnings were issued:
 Warning number: 1
        Description: could not load module, dlopen failed
        Ingroup: modules
        Module: dl
        At: /Users/admin/git/libelektra/src/libs/loader/dl.c:88
        Reason: of module: libelektra-resolver.so, because: dlopen(libelektra-resolver.so, 2): image not found
        Mountpoint:
        Configfile:
 Warning number: 1
        Description: could not load module, dlopen failed
        Ingroup: modules
        Module: dl
        At: /Users/admin/git/libelektra/src/libs/loader/dl.c:88
        Reason: of module: libelektra-resolver.so, because: dlopen(libelektra-resolver.so, 2): image not found
        Mountpoint:
        Configfile:
 Warning number: 40
        Description: failed to open default backend (see warnings for more information)
        Ingroup: kdb
        Module:
        At: /Users/admin/git/libelektra/src/libs/elektra/kdb.c:287
        Reason: could not open default backend
        Mountpoint:
        Configfile:

        at org.libelektra.KDBTest.removeCreatedKeys(KDBTest.java:57)
```

So it looks like the issue happens outside of java? Java loads the libelektra.dylib from the build/lib folder now (thats what my previous commit fixed). I think this dynamic library tries to locate the resolver then, which seems to fail. Shouldn't it detect it given that the libelektra-resolver.so sits in the same folder?

**Comment by markus2330** [comment]
Doesn't a "failure in I/O" imply that there also have been an error (and not only warnings?)

> Shouldn't it detect it given that the libelektra-resolver.so sits in the same folder?

It might using RPATH but this seems to be a fragile thing if multiple languages are involved. Try to set `LD_LIBRARY_PATH`. Lua and python test cases do so already.

Btw. seems like someone wants to work with the java binding to improve the website.
Very good timing, thus the java binding just got completed :-)

Anyway, I would ask you to not do the website tasks. There would be too much effort involved for you to learn the technology stack of the website and your time is better invested in solving other issues.

**Comment by e1528532** [comment]
Well thats how the error was called before so i left it that way. As far as i've seen it just throws this error message if some kdb method goes wrong, regardless of the actual reason. So I've added the warnings in order to see the actual reasons.  To my understanding, printWarnings already includes the "errors" too right? Or is there another metadata for it? In c++ i've only seen printWarnings so far.

But i can rename it to something more general like Failure when communicating with KDB: Warnings: <...>.

To the RPATH issue: I've tried it on my arch today and there it works without any further hassle, every time i tried it. The one build that succeeded on travis seems to be on an older version of macOS, specifically 10.10 `instance: aadc8bfa-b7c8-4c0c-a664-d2f8059138be:travis-ci-osx10.10-xcode6.4-1479248236`. Since 10.11 its no longer possible to pass LD_LIBRARY_PATH (or DYLD_LIBRARY_PATH as its called in mac) to child processes. But more about that in #1353 .

I think this PR can be merged after we have decided about the error message. It already contains some improvements (warning port and correct jna library path, which makes it work at least on linux and older macs).

**Comment by markus2330** [comment]
> To my understanding, printWarnings already includes the "errors" too right?

No, there also should be a `printError`.

> I think this PR can be merged after we have decided about the error message.

Yes, please add the error message and disable the tests on broken MacOSX versions.

**Comment by e1528532** [comment]
look at that beautiful green checkmark travis will produce :)

**Comment by e1528532** [comment]
jenkins build please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
