### PR TITLE
rest-frontend: some fixes and improvements

### PR DESCRIPTION
**Pull request by Namoshek**
# Purpose

Some fixes and improvements as requested in #1151 and #1175. For details see commit messages.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you! Is there really nothing useful we can do when javascript is disabled? (E.g. at least show the content of the mainpage?)

**Comment by Namoshek** [comment]
The home page itself is pretty much ugly without the whole frame around it. But we can keep it as improvement for the future (with low priority and after I'm done with all other stuff): create a static copy of the website or only the home page.

**Comment by markus2330** [comment]
Yes, you are right. I started a list with low priority homepage issues in doc/todo/TOOLS

Let us focus on #1033!

**Comment by markus2330** [comment]
jenkins build-homepage please

**Comment by markus2330** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
Doesn't seem to build the homepage. But you can also merge it and we run it manually.

**Comment by markus2330** [comment]
> Doesn't seem to build the homepage. But you can also merge it and we run it manually.

It worked, my first command had a typo (is deleted now).

So we can leave it open, but I would recommend to merge it soon (maybe after fixing links?)

**Comment by Namoshek** [comment]
Should be fixed now

**Comment by markus2330** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
Great! Thank you!

A very minor thing: is it possible to jump to the anchor at storage plugins on the plugin's page?

**Comment by Namoshek** [comment]
Even though the markdown parser adds some IDs to the elements, it doesn't seem to be possible because the markdown is rendered after the page is loaded. So the browser will look for an anchor element when it is not available yet.

**Comment by Namoshek** [comment]
Btw. maybe it would look better if we'd use wide-screen images for the Qt-GUI and "other applications" as well, because the current ones look quite large in their hight (caused by the little text on the side).

**Comment by markus2330** [comment]
Can you give some hints which resolution you want in the appropriate ticket?

**Pull request merged**
