### PR TITLE
Rename keyIsDirectBelow to keyIsDirectlyBelow

### PR DESCRIPTION
**Pull request by PhilippGackstatter**
This renames `keyIsDirectBelow` to `keyIsDirectlyBelow` as proposed in #2730 and #2979.

So this takes care of the bindings as well. For at least CPP, Java, Haskell and Rust this is a breaking change.

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise and good to read
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating this PR!

**Comment by markus2330** [comment]
The build server is happy now. Unfortunately, there is now a merge conflict. Can you please rebase?

**Comment by markus2330** [comment]
Something went wrong here, the file "src/bindings/haskell/src/Elektra/Key.chs" was added (but it should stay removed).

**Comment by PhilippGackstatter** [comment]
jenkins build libelektra please

**Comment by PhilippGackstatter** [comment]
jenkins build libelektra please

**Comment by PhilippGackstatter** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you, you have really great progress!

**Pull request merged**
