### PR TITLE
cirrus: fix failing freebsd tests

### LINKED ISSUE #3652: cirrus: freebsd 12.1 tests fail because of bison
As @dominicjaeger reported in #3649, the FreeBSD 12.1 and FreeBSD ASAN (also 12.1) build jobs fail.

```
CMake Error at /usr/local/share/cmake/Modules/FindBISON.cmake:103 (message):
  Command "/usr/local/bin/bison --version" failed with output:
  ld-elf.so.1: /usr/local/bin/bison: Undefined symbol
  "fputs_unlocked@FBSD_1.6"
Call Stack (most recent call first):
  src/plugins/toml/CMakeLists.txt:17 (find_package)
  src/plugins/toml/CMakeLists.txt:105 (check_dependencies)
```

A quick google search revealed that this can happens after an incomplete base update of freebsd. Since this only happens on 12.1 and 12.1 has already ended its support. Maybe updating the 12.1 images to 12.2 (latest version) fixes this issue?

## System Information

- Elektra Version: master
- Cirrus FreeBSD 12.1

### LINKED ISSUE #3656: FreeBSD 12: Tests fail with ASAN turned on
Asan tests timouts on FreeBSD 12.2 and also 12.1 (stable). 
I could reproduce this in my VM with FreeBSD 12.2. This also occurs on Cirrus with 12.1-stable and 12.2-release. 

## Steps to Reproduce the Problem

Run tests with `cmake --build ./build/ --target run_nocheckshell`

## Expected Result

Tests should pass.

## Actual Result

Following tests failed:
- testmod_keytometa (Timeout)
- testmod_mmapstorage (Timeout)
- testshell_markdown_tutorial_install_config (Timeout)
- testshell_markdown_tutorial_storage_plugins (Failed)
- testshell_markdown_cmerge (Timeout)
- testshell_markdown_msr_syntax (Failed)
- test_cmerge (Timeout)
- test_meta (Timeout)

## System Information

- Elektra Version: master
- FreeBSD 12.2
- clang version 10.0.1

## Further Log Files and Output
```
114/186 Test  #67: testmod_keytometa .............................***Timeout 1500.38 sec

115/186 Test  #79: testmod_mmapstorage ...........................***Timeout 1500.33 sec

116/186 Test #153: test_cmerge ...................................***Timeout 1500.00 sec

117/186 Test #162: test_meta .....................................***Timeout 1500.00 sec
../src/libs/meta/meta.c:184:16: runtime error: implicit conversion from type 'ssize_t' (aka 'long') of value -1 (64-bit, signed) to type 'size_t' (aka 'unsigned long') changed the value to 18446744073709551615 (64-bit, unsigned)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/libs/meta/meta.c:184:16 in
```

```
172/186 Test #138: testshell_markdown_tutorial_install_config ....***Timeout 1500.34 sec
Input: /home/ec2-user/libelektra/doc/tutorials/install-config-files.md
kdb set user:/tests/tempfiles/firstFile $(mktemp)
echo -e "keyA=a\nkeyB=b\nkeyC=c" > `kdb get user:/tests/tempfiles/firstFile`
kdb install-config-file system:/tests/installing `kdb get user:/tests/tempfiles/firstFile` mini
kdb set system:/tests/installing/keyB X
kdb set user:/tests/tempfiles/secondFile $(echo $(mktemp -d)/$(basename $(kdb get user:/tests/tempfiles/firstFile)))
echo -e "keyA=a\nkeyB=b\nkeyC=Y" > `kdb get user:/tests/tempfiles/secondFile`
kdb install-config-file system:/tests/installing $(kdb get user:/tests/tempfiles/secondFile) mini

        Start 139: testshell_markdown_tutorial_storage_plugins
173/186 Test #139: testshell_markdown_tutorial_storage_plugins ...***Failed    4.32 sec
Input: /home/ec2-user/libelektra/doc/tutorials/storage-plugins.md
kdb mount config.yaml user:/tests/storage yamlcpp
kdb set user:/tests/storage/root 🐓
kdb set user:/tests/storage/root/level1/level2/level3 🐣
kdb ls user:/tests/storage/root
kdb rm -r user:/tests/storage
kdb umount user:/tests/storage
kdb mount config.yaml user:/tests/storage yamlcpp
kdb set user:/tests/storage/null
kdb get user:/tests/storage/null
kdb meta-ls user:/tests/storage/null
kdb set user:/tests/storage/empty ''
kdb get user:/tests/storage/empty
kdb meta-ls user:/tests/storage/empty
kdb rm -r user:/tests/storage
kdb umount user:/tests/storage
kdb mount config.yaml user:/tests/storage yamlcpp type
kdb set user:/tests/storage/bool/value true
kdb meta-set user:/tests/storage/bool/value type boolean
kdb get user:/tests/storage/bool/value
kdb set user:/tests/storage/bool/value 1
kdb get user:/tests/storage/bool/value
kdb set user:/tests/storage/bool/value false
kdb get user:/tests/storage/bool/value
kdb set user:/tests/storage/bool/value 'non boolean'
kdb get user:/tests/storage/bool/value
kdb rm -r user:/tests/storage
kdb umount user:/tests/storage
kdb mount config.yaml user:/tests/storage yamlcpp
kdb set user:/tests/storage/root 🐓
kdb set user:/tests/storage/root/level1/level2/level3 🐣
kdb get user:/tests/storage/root
kdb get user:/tests/storage/root/level1/level2/level3
kdb rm -r user:/tests/storage
kdb umount user:/tests/storage
kdb mount config.yaml user:/tests/storage yamlcpp
kdb meta-set user:/tests/storage/array array ''
kdb set user:/tests/storage/array/#0 one
kdb set user:/tests/storage/array/#1 two
kdb meta-get user:/tests/storage/array array
kdb set user:/tests/storage/map
kdb set user:/tests/storage/map/#0
kdb set user:/tests/storage/map/#1
kdb meta-get user:/tests/storage/map array
kdb rm -r user:/tests/storage
kdb umount user:/tests/storage
shell_recorder /tmp/tmp.YW7dw3bS RESULTS: 59 test(s) done 0 error(s).2,7d1
< $key string 25 17
< tests/tempfiles/firstFile
< /tmp/tmp.0VM6Uz3o
< $key string 26 30
< tests/tempfiles/secondFile
< /tmp/tmp.WaraPoAi/tmp.0VM6Uz3o
Test did not leave user config in the same state at is was before!
This means the test itself is flawed or the KDB was externally modified while the tests were running!
You can inspect the original user config in /tmp/tmp.uE68ACx9/user.export.dump
compared to situation now in /tmp/tmp.uE68ACx9/user.check.dump

Other important recovery files are also in the directory /tmp/tmp.uE68ACx9
Please remove the /tmp/tmp.uE68ACx9 directory yourself after you fixed the situation, I cannot do it for you

        Start 140: testshell_markdown_cmerge
174/186 Test #140: testshell_markdown_cmerge .....................***Timeout 1500.07 sec
Input: /home/ec2-user/libelektra/doc/tutorials/cmerge.md
kdb set user:/tests/base a
kdb set user:/tests/their a
kdb set user:/tests/our a
kdb cmerge user:/tests/our user:/tests/their user:/tests/base user:/tests/result

        Start 141: testshell_markdown_msr_syntax
175/186 Test #141: testshell_markdown_msr_syntax .................***Failed    1.93 sec
Input: /home/ec2-user/libelektra/tests/shell/shell_recorder/tutorial_wrapper/SyntaxCheck.md
kdb set /tests/msr/a a
kdb set /tests/msr/b b
kdb get /tests/msr/a
kdb get /tests/msr/c
kdb rm -r /tests/msr
kdb set /tests/msr/x x
kdb set /tests/msr/y y
kdb get /tests/msr/x
kdb get /tests/msr/y
kdb export /tests/msr mini
kdb ls /tests/msr
kdb rm -r /tests/msr
ls
echo test
printf 'test\nbla'
if [ -e `kdb file user:/` ]; then cat `kdb file user:/`; fi
echo `kdb file system:/`
ls
echo `    kdb file system:/`
shell_recorder /tmp/tmp.JaMSPpsc RESULTS: 27 test(s) done 0 error(s).2,10d1
< $key string 10 1
< tests/base
< a
< $key string 9 1
< tests/our
< a
< $key string 11 1
< tests/their
< a
Test did not leave user config in the same state at is was before!
This means the test itself is flawed or the KDB was externally modified while the tests were running!
You can inspect the original user config in /tmp/tmp.FxeMHzOz/user.export.dump
compared to situation now in /tmp/tmp.FxeMHzOz/user.check.dump

Other important recovery files are also in the directory /tmp/tmp.FxeMHzOz
Please remove the /tmp/tmp.FxeMHzOz directory yourself after you fixed the situation, I cannot do it for you
```

### PR DESCRIPTION
**Pull request by robaerd**
Closes #3652 
Closes #3656 

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by robaerd** [comment]
This fixes the failing tests on FreeBSD 12, but now some tests on FreeBSD 12 ASAN are timing out.
```
60/190 Test  #68: testmod_keytometa .............................***Timeout 1500.03 sec
        Start  82: testmod_mozprefs
 61/190 Test  #82: testmod_mozprefs ..............................   Passed    0.02 sec
        Start  86: testmod_network
 62/190 Test  #80: testmod_mmapstorage ...........................***Timeout 1500.01 sec
```

Has anyone an idea why this could be happening? This only happens on the ASAN build job.

**Comment by mpranj** [comment]
Thank you for working on this!

It seems to me too that the clang version was updated from version 8 to 10 and this triggered the problems. Did you manage  to find out what exactly the problem is?

**Comment by robaerd** [comment]
Unfortunately no. But one of the failing tests returns an UndefinedBehaviorSanitizer error. Maybe it has something to do with this?

```
123/209 Test #185: test_meta .....................................***Timeout 1500.00 sec
../src/libs/meta/meta.c:184:16: runtime error: implicit conversion from type 'ssize_t' (aka 'long') of value -1 (64-bit, signed) to type 'size_t' (aka 'unsigned long') changed the value to 18446744073709551615 (64-bit, unsigned)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/libs/meta/meta.c:184:16 in
```

**Comment by robaerd** [comment]
However these tests pass when using clang 11 with ASAN enabled.
I will just update the freebsd jobs to use clang11 instead of the default one (clang 10).

**Comment by markus2330** [comment]
Thank you so much for fixing this! :sparkling_heart:

**Pull request merged**
