### PR TITLE
Add temporary fix for finding jni plugin

### PR DESCRIPTION
**Pull request by dmoisej**
## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] meta data is updated (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))

## Review

Reviewers will usually check the following:

- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
- [ ] Documentation is concise and good to read
- [ ] Examples are well chosen and understandable

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

@markus2330 @sanssecours , please review my pull request

### CODE REVIEW

**Comment by dmoisej** [comment]
@markus2330 @sanssecours 
This issue is related to previous pull request: https://github.com/ElektraInitiative/libelektra/pull/2615 (finding jni plugin).

So I was asked to review the function "safe_check_symbol_exists". After some debugging I found out, that the removed lines created the problems by finding the jni.h library. I read, that it is used for testing and I believe, that my solution is not correct, because I believe, the testing should still be there. Can you recommend me something?

**Comment by markus2330** [comment]
Could you please describe (in an issue) what the problem you try to solve here is? In particular CMakeFiles/CMakeOutput.log should tell you why exactly the symbol is not found (what it tried to compile and what the error was).

**Comment by markus2330** [comment]
> Not sure, why my review was requested. I have no idea what the CMake file in question does, so cannot comment on the changes.

Because you suggested in #2615 that he should do what he tried to do in this PR.

**Comment by dmoisej** [comment]
@markus2330 by running 
`kdb info jni` 
I get normal output
image

**Comment by kodebach** [comment]
> Because you suggested in #2615 that he should do what he tried to do in this PR.

I still don't know anything about this CMake macro. I just noted that his change indicated that there is something wrong with this macro. Because, if we don't need the `safe_check_symbol_exists` macro, why would it exist?

**Comment by dmoisej** [comment]
@kodebach @markus2330 , so what we should do with this? 

As far as I understood 
`cmake_push_check_state (RESET)`

is used for testing purposes but why is it there, when it doesn't work when installing Elektra with jni plugin.

**Comment by kodebach** [comment]
The way I read [the documentation](https://cmake.org/cmake/help/v3.0/module/CMakePushCheckState.html), `cmake_push_check_state` and `cmake_push_check_state` are used here, because the macro modifies `CMAKE_REQUIRED_DEFINITIONS`. Without this push/pop, the change would leak outside of the macro, where it might not be wanted.

**Comment by markus2330** [comment]
@dmoisej As already said before **please** describe (in an issue) what the problem you try to solve here is? In particular CMakeFiles/CMakeOutput.log should tell you why exactly the symbol is not found (what it tried to compile and what the error was).

Thank you! Otherwise we can do here only guesswork.

**Comment by dmoisej** [comment]
@markus2330 @kodebach 

The problem is, that I am trying to follow this guide in order to enable jni plugin for creating Java Plugins and install everything without problems and additional modifications in the code:
https://www.libelektra.org/plugins/jni

Specifically, I am talking about
> Enabling the Plugin  
section.

My steps:
- `git clone https://github.com/ElektraInitiative/libelektra.git`
- `cd libelektra`
- `mkdir build && cd build`
- `cmake -DPLUGINS="ALL;-EXPERIMENTAL;jni" ..`

On the last command I get error: 

> Exclude Plugin jni because jni.h does not define JNI_VERSION_1_8

but I defined everything and specified all the paths.

**Comment by markus2330** [comment]
Thank you for creating the issue!

As already said two times, the information in CMakeFiles/CMakeOutput.log is essential.

**Comment by dmoisej** [comment]
@markus2330 , oh sorry, here is the output regarding jni.h from the 
/libelektra/build/CMakeFiles/CMakeOutput.log

> Determining if the JNI_VERSION_1_8 exist passed with the following output:
Change Dir: /home/dmoisej/Projects/dmoisej/libelektra/build/CMakeFiles/CMakeTmp
Run Build Command:"/usr/bin/make" "cmTC_3a2dd/fast"
/usr/bin/make -f CMakeFiles/cmTC_3a2dd.dir/build.make CMakeFiles/cmTC_3a2dd.dir/build
make[1]: Entering directory '/home/dmoisej/Projects/dmoisej/libelektra/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3a2dd.dir/CheckSymbolExists.c.o
/usr/bin/cc  -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/default-java/include/linux  -std=gnu99  -Wno-deprecated-declarations  -Wstrict-prototypes  -Wno-long-long -Wpedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wsign-compare -Wfloat-equal    -o CMakeFiles/cmTC_3a2dd.dir/CheckSymbolExists.c.o   -c /home/dmoisej/Projects/dmoisej/libelektra/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_3a2dd
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3a2dd.dir/link.txt --verbose=1
/usr/bin/cc  -std=gnu99  -Wno-deprecated-declarations  -Wstrict-prototypes  -Wno-long-long -Wpedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wsign-compare -Wfloat-equal     -rdynamic CMakeFiles/cmTC_3a2dd.dir/CheckSymbolExists.c.o  -o cmTC_3a2dd 
make[1]: Leaving directory '/home/dmoisej/Projects/dmoisej/libelektra/build/CMakeFiles/CMakeTmp'

> File /home/dmoisej/Projects/dmoisej/libelektra/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
> /* */
> #include <jni.h>
> 
> int main(int argc, char** argv)
> {
>   (void)argv;
> #ifndef JNI_VERSION_1_8
>   return ((int*)(&JNI_VERSION_1_8))[argc];
> #else
>   (void)argc;
>   return 0;
> #endif
> }

**Comment by markus2330** [comment]
Are you this is the output of the failed build? (without this PR) It seems to have succeed?

Please everything together as a new issue: http://issues.libelektra.org/new

This would be much easier for other people that search for this issue.

**Comment by dmoisej** [comment]
@markus2330 the thing is, that I am playing right now with the code and try to find the difference between working code and code, that fails, so maybe it is some old output. I need some time for debugging and at the end, when I will get another output, then I will let you know and will open the issue.

**Comment by markus2330** [comment]
Thank you!

You should easily get the output when you start from a fresh build directory without any changes in the source dir.

**Comment by dmoisej** [comment]
@markus2330 
So I removed all content from CMakeError.log and CMakeOutput.log.
After that I tried to execute the command:
`cmake -DPLUGINS="ALL;jni;" ..`
(it is without any changes to the master code)

As a result I have nothing in CMakeOutput.log, which concerns jni.
Here are my both files from build/CMakeFiles directory:

[CMakeError.log](https://github.com/ElektraInitiative/libelektra/files/3294169/CMakeError.log)
[CMakeOutput.log](https://github.com/ElektraInitiative/libelektra/files/3294170/CMakeOutput.log)

**Comment by markus2330** [comment]
Please follow instructions more carefully:

1. create a new issue
2. you need to remove the whole build directory, not only the log files (CMake does not recheck symbols it already checked)

**Comment by dmoisej** [comment]
@kodebach , removing RESET as argument did help. 
@kodebach @markus2330 please review my pull request as soon as possible

**Comment by kodebach** [comment]
It works on the build server, and it works locally for you, so this looks fine to me.

**Comment by markus2330** [comment]
Great that we found a fix after all!

**Pull request merged**
