### PR TITLE
[FLOSS H3] Integrate missing pages into website

### LINKED ISSUE #4098: integrate pages into website
We have a few documents which are not yet integrated in the website, e.g.:

- [x] doc/CODING.md
- [ ] doc/README.md could be added to Documentation -> Index
- [x] doc/GIT.md
- [x] doc/BUILDSERVER.md
- [x] tests/shell/shell_recorder/tutorial_wrapper/README.md
- [x] doc/todo/RELEASE.md

These files should be added in the structure src/tools/website/resources/structure.json.in

For triage the pages which are missing are to be found.

Ideally we would also have a tool that can check if there are files floating in doc not integrated there.

### PR DESCRIPTION
**Pull request by sedadas**
Add some pages that were in the documentation but were missing in the libelektra website.
Closes #4098

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Review by markus2330 — CHANGES_REQUESTED** [review]
There are more pages listed in #4098

**Comment by markus2330** [comment]
Thank you, great to see this! :heart:

**Review by JakobWonisch — APPROVED** [review]
[FLOSS H3] Review

The pages that you could figure out where to add them are inserted, so that looks good to me!
As you mentioned in the issue, the other files where difficult to place, so I'd assume that this part of the issue is enough to be merged and the other pages can then be inserted in another pr.

**Comment by sedadas** [comment]
The changes, requested [here](https://github.com/ElektraInitiative/libelektra/issues/4098#issuecomment-992167385) ("Testing of tutorials" and "Citations"), have been added as well

**Comment by markus2330** [comment]
Thank you, see #4098 (top post) for remaining tasks!

**Comment by markus2330** [comment]
Btw. I merged so that we can see the updated website.

**Pull request merged**
