### PR TITLE
Fix: mingw: undefined reference rand_r

### PR DESCRIPTION
**Pull request by KurtMi**
Now using srandom and random.

Fix: #1254

### CODE REVIEW

**Comment by KurtMi** [comment]
jenkins build mingw64 please

**Comment by KurtMi** [comment]
@markus2330 please review.
not sure if the `jenkins build mingw64 please` worked.

**Comment by markus2330** [comment]
jenkins build mingw64 please

**Comment by markus2330** [comment]
add to whitelist

**Comment by markus2330** [comment]
Seems it did not work, I hope the "add to whitelist" fixed the issue and it will work the next time.

**Comment by KurtMi** [comment]
mingw is now failing due #1478.

**Comment by markus2330** [comment]
Thank you! Good solution, performance is definitely not the main issue in mingw.

**Pull request merged**
