### PR TITLE
keyRel2: fix handling of meta namespace

### PR DESCRIPTION
**Pull request by tom-wa**
# Purpose

fixed checking relations between metakeys

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [x] I added unit tests
- [ ] affected documentation is fixed
- [x] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the PR!

Please document the behavior of the change and add at least one test case triggering this behavior.

**Comment by tom-wa** [comment]
keyRel2 (the helper function keyAsCascading) handled metakeys and keys without namespaces wrong, e.g. for `meta/key` it skipped `meta` and returned `/key` which is wrong

now keyRel2 also works correctly for metakeys

**Comment by tom-wa** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build fast please

**Comment by markus2330** [comment]
Thank you for the fix!

**Pull request merged**
