### PR TITLE
Travis: Always Consider Exit Status of `run_all`

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This commit should fix the problem reported in issue #1764.

# Checklist

- [x] I checked the commit message. The issue reference in commit dfcd490 should be correct.

### CODE REVIEW

**Comment by markus2330** [comment]
Happy new year!

Are you sure this will fix the problem? If the language used in travis is similar to sh, this will only avoid `kdb run_all` to be  executed but will not fix the overall exit status.

In my /bin/sh shell, the "fix" triggers the problem we want to solve:

```
#!/bin/sh

set -ex

true

if true
then
	false
	true
fi

true
```

executes as wanted:
```
+ true
+ true
+ false
Exit-status: Failure
```

but:

```
#!/bin/sh

set -ex

true

if true
then
	false && true
fi

true
```

executes like:

```
+ true
+ true
+ false
+ true
Exit-status: Success
```

which would lead to the problem as described in #1764. But travis seems to have different semantics than my shell.

**Comment by sanssecours** [comment]
> Happy new year!

🍾 Happy new year to you too 🥂.

> Are you sure this will fix the problem?

I would assume so. I pushed a debug commit, to check if everything works as expected.

**Comment by sanssecours** [comment]
Seems the updated code works as [expected](https://travis-ci.org/ElektraInitiative/libelektra/jobs/323746774#L2324).

**Comment by markus2330** [comment]
> 🥂

🥂

Thank you for checking!

Please add ready to merge when you reverted the debug commit.

**Comment by markus2330** [comment]
Thank you for the fix!

**Pull request merged**
