### PR TITLE
Multi array key increment tests

### PR DESCRIPTION
**Pull request by FelixResch**
* Add additional tests for array key handling

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise and good to read
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the pull request! Please ask if there are any questions (e.g. why the build server fails).

**Comment by FelixResch** [comment]
I think I might have relied too much on IDEA automatically reformatting the code I was writing. I have now reformatted the code and added my changes to the change list.

Jenkins fails after all tests have been run and some(/all?) artifacts have been built with the following error message:

```
4s
Archiving artifacts
Failed to extract /home/jenkins/workspace/libelektra_PR-3032-X2DMFZSEGNIA7ACQPBFYOULCZFY26YPP27FUCGRMR7LK5IQHA33Q@2/build/transfer of 1 files
```

**Comment by markus2330** [comment]
Sorry that nobody gave you an answer for so long.

> I think I might have relied too much on IDEA automatically reformatting the code I was writing. I have now reformatted the code and added my changes to the change list.

It is no problem that you let the IDE reformat everything, you only need to configure your IDE so that it uses the same formatting tools as we use (scripts/dev/reformat-* scripts). Maybe doc/tutorials/contributing-clion.md helps you. You are welcome to extend the tutorial.

> Jenkins fails after all tests have been run and some(/all?) artifacts have been built with the following error message:

This looks like a network connection problem. Please restart in such cases. We are trying to get the build server more stable.

**Comment by mpranj** [comment]
Is this PR finished or is there anything left to do? (excepte rebase now..)

**Pull request closed without merging**
