### PR TITLE
SWIG performance

### PR DESCRIPTION
**Pull request by manuelm**
Hi Markus,

as requested I've looked into this in more detail. The first commit fixes one of the extra copies. Fixing the other was only possible by providing a `char *`-alternative (making the first commit actually unnecessary). As all SWIG wrapped languages operate on char pointers wrapping a function with `std::string` always adds an extra copy.

Can you please assign (+ping if already assigned) issues you want me to fix. Thanks

### CODE REVIEW

**Comment by markus2330** [comment]
So good to see you active again :sparkling_heart: Thank you very much for this PR!

> Can you please assign (+ping if already assigned) issues you want me to fix. Thanks

Assignments are done. I definitely do not expect the low-priority issues to be done. Simply see if they are easy to do and worth the effort.

**Comment by markus2330** [comment]
Please add release notes as instructed by the build server. In future it is good if you leave the text in pull request intact, so that you see what you need to do.

**Comment by manuelm** [comment]
I deliberately didn't append a release note. Do you want the first commit included? + Are you happy with the 2nd approach? Or should I add the `kdb::Key::setString(char *)` in the bindings only (included coping the body of `original setString`).

**Comment by markus2330** [comment]
> I deliberately didn't append a release note.

Please always add, so that the build server will do its checks.

> Do you want the first commit included? + Are you happy with the 2nd approach?

348cae5f40ec7288622df55b0c56720e24e82e6a is not recommended anymore and should not be needed with C++11. Maybe simply adding the C++11 compiler-option is enough (or even brings other benefits).

Does any commit change the way the API is to be used? Can you give an example how it changes?

Otherwise, if it is only about performance, the faster method is preferred.

**Comment by manuelm** [comment]
> [348cae5](https://github.com/ElektraInitiative/libelektra/commit/348cae5f40ec7288622df55b0c56720e24e82e6a) is not recommended anymore and should not be needed with C++11. Maybe simply adding the C++11 compiler-option is enough (or even brings other benefits).

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-in

**Comment by markus2330** [comment]
I refer to http://cpp-next.com/archive/2009/08/want-speed-pass-by-value/ (or if it is down, did not load here when I tried it see https://stackoverflow.com/questions/21605579/how-true-is-want-speed-pass-by-value)

But in the end it does not matter: you simply do what your benchmark says is best.

**Comment by manuelm** [comment]
Good to go then. No API changes.

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you, great job! I am looking forward to see the benchmarks on this.

**Comment by manuelm** [comment]
Do I have to do is? 😓😭 It's removing one of the alloc spikes

**Comment by markus2330** [comment]
No, you can also simply say that this case was optimized later.

**Pull request merged**
