### PR TITLE
cmake: use dini as default

### PR DESCRIPTION
**Pull request by markus2330**
# Purpose

Change default storage plugin to dini

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [ ] I added unit tests
- [ ] I ran all tests and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

### CODE REVIEW

**Comment by markus2330** [comment]
@sanssecours Can we merge this before #1762?

Release notes and update of documentation are missing in this PR.

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Strange, why did all builds restart here? They just finished successfully some time ago.

**Comment by sanssecours** [comment]
> @sanssecours Can we merge this before #1762?

Yeah, sure. The code in pull request #1762 is [not ready yet](https://build.libelektra.org/jenkins/job/elektra-ini-mergerequests/969) anyway.

> Strange, why did all builds restart here? They just finished successfully some time ago.

That happened because I triggered all build jobs, since you wanted to merge this PR.

**Comment by markus2330** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
I think you also need to [add `dini` in `scripts/configure-xdg`](https://build.libelektra.org/jenkins/job/elektra-gcc-configure-xdg/923/console):

```
selected default storage (dini) is not selected in PLUGINS, please change
  KDB_DEFAULT_STORAGE or PLUGINS
```

. I will stop the other build jobs for now.

**Comment by sanssecours** [comment]
jenkins build gcc-configure-xdg please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc47-cmake-options please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc47-cmake-options please

**Comment by markus2330** [comment]
Did elektra-multiconfig-gcc47-cmake-options only fail because of the change in the master branch or is this PR not safe to merge?

**Comment by sanssecours** [comment]
> Did elektra-multiconfig-gcc47-cmake-options only fail because of the change in the master branch…

As far as I can tell, yes.

> …is this PR not safe to merge?

I think we can merge the PR.

**Comment by markus2330** [comment]
Thank you for your help. Finally we got a new default storage format!

**Pull request merged**
