### PR TITLE
Add slogans svg

### PR DESCRIPTION
**Pull request by KurtMi**
# Purpose

add slogans svgs

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [ ] commit messages are fine (with references to issues)
- [ ] I added unit tests
- [ ] I ran all tests and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by sanssecours** [comment]
Thank you for adding the slogans. Seems like the correct rendering of the text currently depends on the locally installed fonts. The screenshot below shows how the first slogan looks on my system:

slogan

. I think you need to either embed the font in the SVG file or [convert the text to shapes](https://graphicdesign.stackexchange.com/questions/27238/preserving-font-type-in-illustrator-svg-file), otherwise the text will look quite different on systems that do not include the Google Play font.

**Comment by KurtMi** [comment]
Well then the version I have of the slogans is useless.

**Comment by sanssecours** [comment]
> Well then the version I have of the slogans is useless.

I do not think that is true. You just need some application that is able to convert fonts to shapes. For example, I installed [Google Play](https://fonts.google.com/specimen/Play) and used [OmniGraffle Pro](https://www.omnigroup.com/omnigraffle) to convert the first slogan:

[slogan_black_01.zip](https://github.com/ElektraInitiative/libelektra/files/1632435/slogan_black_01.zip)

. The slogan linked above looks correct, even if I remove Google Play from my system.

**Comment by markus2330** [comment]
What is the purpose of having the slogans as SVG in the main repo? Isn't the blobs repo better suitable for this?

**Comment by KurtMi** [comment]
font to shape and blob repo it is!

**Pull request closed without merging**
