### PR TITLE
Test: Exclude Ruby Instead of Semlock Plugin

### PR DESCRIPTION
**Pull request by sanssecours**
# Without Problematic Plugins

- [First Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/1/pipeline): 😊
- [Second Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/2/pipeline): 😊
- [Third Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/2/pipeline): 😊

# With Ruby Plugin

- [First Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/4/pipeline): 😊
- [Second Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/5/pipeline): 😊
- [Third Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/6/pipeline): 😭

# Without Ruby Plugin

- [First Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/7/pipeline): 😊
- [Second Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/8/pipeline): 😊
- [Third Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/9/pipeline): 😊
- [Fourth Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/10/pipeline): 😊
- [Fifth Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/11/pipeline): 😊
- [Sixth Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/12/pipeline): 😊
- [Seventh Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/13/pipeline): 😊
- [Eight Try](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2221/15/pipeline): 😊

### CODE REVIEW

**Comment by ingwinlu** [comment]
Hey, I appreciate you testing this, maybe I can help with automating the rebuilds?

I have a jenkins job `pipeline-playground` where I usually test Jenkinsfile changes. We could use that to trigger 3 builds after each other for your PR.
The code in https://build.libelektra.org/jenkins/job/pipeline-playground should start a pr 3 times and log their results.

You can adapt it for the next rounds of tests (by pointing it to your PR) and starting it. Then you do not need to restart them manually.

**Comment by ingwinlu** [comment]
Sry had an error. Hopefully it works now.

**Comment by markus2330** [comment]
Thank you both for looking into this! :heart:

**Comment by markus2330** [comment]
Thank you! Hopefully we have now more stable builds!

**Pull request merged**
