### PR TITLE
New repo layout

### PR DESCRIPTION
**Pull request by kodebach**
This is going to be a very big PR implementing some or all of the decisions relating to file layout in the repo.

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add them to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - add a line in `doc/news/_preparation_next_release.md`
  - reformat the code with `scripts/dev/reformat-all`
  - make all unit tests pass
  - fix all memleaks
  - fix the CI itself (or rebase if already fixed)
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if everything is done** and no further pushes are planned by you.

### CODE REVIEW

**Comment by kodebach** [comment]
This PR also introduces a new GitHub Action which verifies the new rules for `#includes`: https://github.com/ElektraInitiative/libelektra/actions/runs/4457534558

**Comment by atmaxinger** [comment]
Are those changes mostly automated?

**Comment by kodebach** [comment]
These two commits where automated via my TreeSurgeon tool:

- cafcfaa5d764beb4b5e3161d5fdd6178fad8ee3b
- 9be1c706d43ce63bdaa48e71cea840869b6b8f97
 661665d3251b2a64c7f05401739c5987bb2e085e and f8e1de4f53d67121c456cb3d8ef678199d555fd0 are just the existing reformatting script.

The rest was manual changes.

A good chunk of 7a3ad1d2665be1dbf9585214ad25b7650e4606b9 could in theory be done with TreeSurgeon too, but there were some parsing issues in those files (probably because is parsed C++ with the C grammar out of laziness), so the updates couldn't be performed automatically. Since it was only a handful of files, I didn't bother investigate the cause further.

**Comment by kodebach** [comment]
I also plan on automating the changes necessary after splitting `kdb.h` and `kdbprivate.h` into multiple files. But I need to extend TreeSurgeon first, so that's gonna take a bit more time.

**Comment by atmaxinger** [comment]
Okay, we need to coordinate whether we merge #4843 before or after this. But if it's mostly automated it would probably a good idea to merge the changetracking implementation first.

**Comment by kodebach** [comment]
Yup, this PR is a draft for exactly this reason. It'll take me bit more time to get it ready anyway and then we need to find the right moment to merge it.

However, I could also apply the TreeSurgeon script to other PRs, if we merge this one first.

**Comment by kodebach** [comment]
`kdb.h` has now been split into multiple headers. These commits were automated with TreeSurgeon: 4da1029a84894e4cffb8086645b0194ccb93ea10 and 34399e2980ffc6e89aa077a6a14cbb86527e77d1. The "fix formatting" commits used the standard reformat scripts. e8fbffb9d7bc4ce8e2907d8066eb1e53be63451a was a simple regex replace (could technically be done with TreeSurgeon but the current version runs into infinite loops here). The rest was manual work. 

5525f7dc5db968482bdaa7978ef91f7349ebcd70 is a bit bigger than expected, because I had to add quite a few `#include`s where code relied on transitively included headers that have been removed.

**Pull request closed without merging**
