### PR TITLE
Kdb complete improvements

### PR DESCRIPTION
**Pull request by e1528532**
# Purpose

Unified the const & code style and fixed a small issue with depth and mountpoints and empty names, and fixed a possible warning output when not in debug or verbose mode. Also started working on shell recorder tests.

# Checklist

- [X] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [x] I added unit tests
- [X] affected documentation is fixed
- [X] I added code comments, logging, and assertions
- [X] meta data is updated (e.g. README.md of plugins)

@markus2330 WIP, still need to master how to use the shell recorder correctly, but the other fixes should be fine i think.

### CODE REVIEW

**Comment by e1528532** [comment]
no tests atm for some escaping cases as we discussed in the meeting escaping becomes a problem when use in markdown/shell recorder. Included various base cases, do you think we should also include bookmark & mounting tests?

**Comment by markus2330** [comment]
> do you think we should also include bookmark & mounting tests?

No, we should better improve coverage for the most important `kdb` commands before we add tests for such specific features.

**Comment by e1528532** [comment]
in that case, i guess we can merge this

**Comment by markus2330** [comment]
Thank you!

I merged it, but we should take a closer look if the shell recorder style is okay for man pages. I opened #1369 so that we do not forget.

**Pull request merged**
