### PR TITLE
Skip meleak plugins in testkdb_allplugins when running with valgrind

### PR DESCRIPTION
**Pull request by Eiskasten**
## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by Eiskasten** [comment]
The `testkdb_allplugins` now seems to be fine, now the problem is that it does not compile on all machines due to the missing valgrind includes. The [official valgrins docs](https://valgrind.org/docs/manual/manual-core-adv.html#manual-core-adv.clientreq) suggest to just copy them into the project. However, there are quite a lot includes and I am not sure if this is not an overkill.

**Comment by kodebach** [comment]
Actually the test still fails once and succeeds on the rerun: https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4814/2/pipeline/810#step-941-log-276

The error is different though...

For the header issue: This [SO post](https://stackoverflow.com/a/623646989) suggests checking the `LD_PRELOAD` env-var instead.

**Comment by kodebach** [comment]
I think I found a fix, I applied it in #4778. Let's see if it works.

**Comment by kodebach** [comment]
Looks like it still doesn't work in #4778, but the plugins are now excluded, so I'll close this PR.

**Pull request closed without merging**
