### PR TITLE
[CM P2] web-ui 2.0

### PR DESCRIPTION
**Pull request by wasseramseleo**
## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

implements #4356

### CODE REVIEW

**Comment by lukashartl** [comment]
@markus2330 unfortunately, we are not able to get this PR to be checked by Jenkins.

It always boils down to this log entry:

```
15:10:06 Connecting to https://api.github.com/ with no credentials, anonymous access
Examining [ElektraInitiative/libelektra](https://github.com/ElektraInitiative/libelektra)

  Checking pull-requests...

  Getting remote pull request [#4369](https://github.com/ElektraInitiative/libelektra/pull/4369)...

    Checking pull request #4369
ERROR: {"message":"Requires authentication","documentation_url":"https://docs.github.com/rest/reference/repos#get-repository-permissions-for-a-user"}
```

Do you have any idea?

**Comment by kodebach** [comment]
This seems to be a general issue, AFAICT none of the currently open PRs are checked by Jenkins.

@markus2330 @mpranj I think this may be related to [the recent npm leak on GitHub](https://www.bleepingcomputer.com/news/security/github-attackers-stole-login-details-of-100k-npm-user-accounts/). GitHub probably revoked a token and we need to reconfigure Jenkins.

**Comment by markus2330** [comment]
build allow

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by lukashartl** [comment]
Jenkins said:

```
#18 60.33 go: github.com/google/uuid@v1.3.0: Get https://proxy.golang.org/github.com/google/uuid/@v/v1.3.0.mod: net/http: TLS handshake timeout
#18 60.35 src/tools/elektrad/CMakeFiles/elektrad.dir/build.make:65: recipe for target 'src/tools/elektrad/elektrad/elektrad' failed
#18 60.35 make[2]: *** [src/tools/elektrad/elektrad/elektrad] Error 1
```

I switched from Ubuntu 16.04 to 20.04, from node 10 to node 12 and from some go-ppa to the default golang version in ubuntu:20.04.

If this doesn't work, we can try to set `GOPROXY=direct` to directly download go dependencies without the use of proxy.golang.org.

**Comment by kodebach** [comment]
I'm 99% sure the TLS handshake timeout was a temporary issue (in [the first build of this PR](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4369/1/pipeline). There is a [later build](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4369/3/pipeline) were a different error occurred in a later stage.

That issue won't be fixed by updating things, since it is an issue with the Dockerfile/the build command...

**Comment by lukashartl** [comment]
@kodebach Ahh, I see what you mean. Thanks for the hint.

Still... updating the dependencies isn't really a bad idea either ... I mean, ubuntu 16.04 probably isn't the best base image nowadays.

**Comment by lukashartl** [comment]
Ok. To fix the later problem, we have to set the build argument `BASE_IMG`.

Docker Stages are built here:

https://github.com/ElektraInitiative/jenkins-library/blob/7926eda8e5431d7ed1a4cde4baf2b9a2937514ba/vars/dockerUtils.groovy#L112-L128

We have to somehow make it possible to add further build arguments to this function... and we probably also shouldn't restrict it only to this specific case...

**Comment by kodebach** [comment]
You could just add an `extraArgs` parameter that is appended to the end of the arguments:

```groovy
def buildImage(image, extraArgs = "") {
  docker.withRegistry("https://${PipelineConfig.instance.registry}",
                  'docker-hub-elektra-jenkins') {
    def uid = getUid()
    def gid = getGid()
    def cpus = cpuCount()
    def i = docker.build(
      image.id,"""\
--pull \
--build-arg JENKINS_GROUPID=${gid} \
--build-arg JENKINS_USERID=${uid} \
--build-arg PARALLEL=${cpus} \
${extraArgs} \
-f ${image.file} ${image.context}"""
    )
    i.push()
  }
}
```

This would work for extra `--build-arg`s but also other options.

**Comment by markus2330** [comment]
@lukashartl  I also saw the TLS handshake problem many times. If there is anything we can do about it, it would be great. Can you open an issue for investigations?

**Comment by lukashartl** [comment]
@kodebach 

> You could just add an `extraArgs` parameter that is appended to the end of the arguments:
> 
> ```groovy
> def buildImage(image, extraArgs = "") {
>   docker.withRegistry("https://${PipelineConfig.instance.registry}",
>                   'docker-hub-elektra-jenkins') {
>     def uid = getUid()
>     def gid = getGid()
>     def cpus = cpuCount()
>     def i = docker.build(
>       image.id,"""\
> --pull \
> --build-arg JENKINS_GROUPID=${gid} \
> --build-arg JENKINS_USERID=${uid} \
> --build-arg PARALLEL=${cpus} \
> ${extraArgs} \
> -f ${image.file} ${image.context}"""
>     )
>     i.push()
>   }
> }
> ```
> 
> This would work for extra `--build-arg`s but also other options.

I think I have a better idea:

* I don't like string concatenation without proper shell escaping for commands
* What about extracting the tag building function to a separate groovy function:

```groovy
def tagArtifact() {
  def jobName = env.JOB_NAME
  def escapedJobName = jobName.replaceAll('/', '_') // docker version tag may not include a `/`

  return "${escapedJobName}_${env.BUILD_NUMBER}"
}
```

And then we could do something like:

```groovy
def buildImage(image) {
  docker.withRegistry("https://${PipelineConfig.instance.registry}",
                  'docker-hub-elektra-jenkins') {
    def uid = getUid()
    def gid = getGid()
    def cpus = cpuCount()
    def pipeline_tag = tagArtifact()

    def i = docker.build(
      image.id,"""\
--pull \
--build-arg JENKINS_GROUPID=${gid} \
--build-arg JENKINS_USERID=${uid} \
--build-arg PARALLEL=${cpus} \
--build-arg PIPELINE_TAG=${pipeline_tag} \
-f ${image.file} ${image.context}"""
    )
    i.push()
  }
}
```

This would add `PIPELINE_TAG` for all docker build processes, but most of them would just ignore it.

/cc @markus2330

**Comment by kodebach** [comment]
The idea with the `PIPELINE_TAG` sounds good and might in future be useful elsewhere too. But I would generate the tag slightly differently:

```groovy
def tagArtifact() {
  def jobName = env.JOB_NAME
  def escapedJobName = jobName.replaceAll('/', '.') // docker version tag may not include a `/`

  return "${escapedJobName}_${env.BUILD_NUMBER}"
}
```

**Comment by lukashartl** [comment]
I've created the appropriate PR in https://github.com/ElektraInitiative/jenkins-library/pull/2 .
I hope this is okay for you @kodebach and @markus2330.

**Comment by lukashartl** [comment]
jenkins build libelektra please

**Review by kodebach — APPROVED** [review]

**Pull request merged**
