### PR TITLE
CI: improve fedora image

### LINKED ISSUE #3227: Jenkins CI: add Fedora docker image
Add a current Fedora docker image to the Jenkins CI pipeline to test compatibility with newer packages than on Debian.

If I take on this issue I will probably replace one of the `mmap` builds with fedora, so that we don't **just** increase build times.

### PR DESCRIPTION
**Pull request by mpranj**
Jenkins: main build stage with debian and fedora stable. Move oldstable to second build stage.

Improve cirrus fedora image and add fedora docker image for jenkins to cover many tests.

Closes #3227.

### CODE REVIEW

**Comment by markus2330** [comment]
Amazing to finally see Fedora Images for Jenkins!

**Comment by mpranj** [comment]
What do you think about moving debian oldstable to the second build stage and keeping current debian and fedora stable as the main builds? Is there any specific reason to keep strech in the main builds?

**Comment by markus2330** [comment]
Both Stretch and Buster was some time together in the main builds because Stretch did not build/test anything. But I think this is already fixed since quite some time so there is actually no reason to keep Stretch in the main builds.

Having one Fedora and and one Debian build in the main builds sounds very reasonable to me.

**Comment by mpranj** [comment]
@sanssecours only if you want/have time to glance over it. Feel free to merge if you do look it over.

**Pull request merged**
