### PR TITLE
Markdown Shell Recorder: Print Path to Test File

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

After this PR the Markdown Shell Recorder prints the location of the current test file.

# Checklist

- [x] I checked all commit messages. The issue reference in commit e6c157e should be correct.
- [x] I ran all tests and everything went fine.
- [x] The PR also updates the release notes.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
jenkins build all please

**Comment by markus2330** [comment]
sorry, I needed to restart jenkins due to high load

**Comment by sanssecours** [comment]
jenkins build test-bindings please

**Comment by sanssecours** [comment]
jenkins build incremental please

**Comment by sanssecours** [comment]
jenkins build homepage please

**Comment by sanssecours** [comment]
jenkins build gcc-i386 please

**Comment by sanssecours** [comment]
jenkins build doc please

**Comment by sanssecours** [comment]
jenkins build bindings please

**Comment by sanssecours** [comment]
jenkins build doc please

**Comment by sanssecours** [comment]
jenkins build gcc-i386 please

**Comment by sanssecours** [comment]
jenkins build homepage please

**Comment by sanssecours** [comment]
jenkins build bindings please

**Comment by sanssecours** [comment]
jenkins build incremental please

**Comment by markus2330** [comment]
Thank you!

Why have there been so many build errors?

**Comment by sanssecours** [comment]
> Why have there been so many build errors?

The configuration values for the post-build action “Send build artifacts over SSH“ for some jobs were missing.

**Comment by markus2330** [comment]
Thank you for fixing this.

@ingwinlu was this maybe related to the Jenkins upgrade?

**Pull request merged**
