### PR TITLE
crypto: add payload version to the contract

### LINKED ISSUE #1582: crypto: put payload version information in the contract
I relocated @markus2330  's message from #1567 to here:

A minor implementation note: It would be great if a user can introspect which values a plugin uses by default by returning relevant information via the contract. (Similar to the resolver, e.g. `system/elektra/modules/crypto` ELEKTRA_PLUGIN_NAME `/constants/TMPDIR`)

You should also consider returning the payload version, so something like (`system/elektra/modules/crypto` ELEKTRA_PLUGIN_NAME `/constants/PAYLOAD_VERSION`). Then users can easily introspect which payload version their plugin is able to handle.

Obviously you can also return any other information relevant to the user, such as the used crypto algorithm, password length and so on...

### PR DESCRIPTION
**Pull request by petermax2**
Closes #1582 .

# Purpose

Describe the purpose of the pull request.
(Long descriptions should be in documentation, not here)

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [ ] commit messages are fine (with references to issues)
- [ ] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by petermax2** [comment]
@markus2330 I added the `crypto` paylaod version to the contract.

**Comment by markus2330** [comment]
Yes, this is exactly what I am talking about. Is there some reason the other macro constants are not added?

Seems like `scripts/reformat-source` was not applied, can you do it please?

**Comment by petermax2** [comment]
I fixed the remaining problems and added some more constants. I am not sure about what is important for the user tough.

**Comment by markus2330** [comment]
Thank you! Should now contain everything someone wants to know ;)

**Pull request merged**
