### PR TITLE
Fix rust test case

### PR DESCRIPTION
**Pull request by PhilippGackstatter**
#3045 showed that an error code wasn't properly mapped to a Rust error. 
I don't believe it was the original cause of the test failure though.
I'm testing if this occurs again with this pr.

## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by PhilippGackstatter** [comment]
jenkins build libelektra please

**Comment by PhilippGackstatter** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you for working on this! Any progress so far?

**Comment by PhilippGackstatter** [comment]
> Thank you for working on this! Any progress so far?

The last build succeeded, so the error at least did not occur again.

I also discovered, that I was missing the ResourceError in the mapping. I thought that only the "leafs" of the ["error code tree"](https://github.com/ElektraInitiative/libelektra/blob/master/doc/decisions/error_codes.md#decision) would be possible concrete errors, but the ResourceError is an exception to that assumption. So that's added now and if the builds succeed, I think this can be merged. 

Unfortunately the existing enum nesting implementation doesn't allow for the inheritance style that is required by the error specification. That means that `OutOfMemoryError` is not a subtype of `GeneralResourceError` as required. They are distinct variants. It's a small limitation, but I wanted to point it out.

It's still possible to catch all types of Resource Errors, so it should be fine.

```rust
    if let KDBError::Permanent(PermanentError::Resource(err)) = res {
        // Here both GeneralResourceError and
        // OutOfMemoryError need to be handeled separately
    }
```

I'm not sure what caused the error in the first place, but it may have to do with the missing ResourceError. Since the jenkins server often fails with some laggy filesystem error, maybe this error was thrown but not caught due to the missing map case.

I added more logging to the error mapping, so if the error occurs again, then we'll have more information on what exactly went wrong.

**Comment by markus2330** [comment]
Thank you very much for this!

> Unfortunately the existing enum nesting implementation doesn't allow for the inheritance style that is required by the error specification. That means that OutOfMemoryError is not a subtype of GeneralResourceError as required. They are distinct variants. It's a small limitation, but I wanted to point it out.

Can you please create an issue about this? OutOfMemoryError should be a subtype of the ResourceError.

**Pull request merged**
