### PR TITLE
build-homepage script: create and copy api description

### PR DESCRIPTION
**Pull request by Namoshek**
# Purpose

Handles the missing API description of #1181.

# Checklist

@markus2330 please review my pull request

### CODE REVIEW

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
@markus2330 you need to change the path to the build jobs in github, they do not work anymore.

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
Works properly, can be merged.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
