### PR TITLE
Fix JavaDoc generation on Debian Sid

### PR DESCRIPTION
**Pull request by atmaxinger**
## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [x] make all unit tests pass
  - [x] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [x] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [x] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [x] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by atmaxinger** [comment]
If we don't want to use jdk-17, we could alternatively ask CMake to only use jdk-11.

**Review by markus2330 — APPROVED** [review]
I think you also need to whitelist #4624

But I cross the fingers :crossed_fingers:, hopefully the build will pass!

**Comment by atmaxinger** [comment]
True, I've also added those two links right now. We should probably make an issue to remove them from the whitelist after master builds again.

**Comment by kodebach** [comment]
JDK 17 is the latest LTS version, so I think it makes sense to use it.

**Comment by atmaxinger** [comment]
jenkins build libelektra please

**Comment by atmaxinger** [comment]
@markus2330 the build now failed because of spelling errors. Should I fix them in this PR?

**Comment by atmaxinger** [comment]
Also, can we check those spelling mistakes earlier? Waiting 2 hours for a build just for it to fail because of spelling mistakes is a waste of time.

**Comment by markus2330** [comment]
> @markus2330 the build now failed because of spelling errors. Should I fix them in this PR?

Yes, please! Goal of this PR is to let master builds succeed again.

Btw. I don't see spelling errors in https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4635/6/pipeline
?

> Also, can we check those spelling mistakes earlier? Waiting 2 hours for a build just for it to fail because of spelling mistakes is a waste of time.

Actually I thought that spelling checks are done in basic checks. But if it is not, it should be there.

**Comment by kodebach** [comment]
AFAICT this is one of those weird instances, where the Jenkins CI actually succeeded, but is still marked as failed.

**Comment by atmaxinger** [comment]
@kodebach no it actually failed. You need to click on "Tests"

grafik

**Comment by atmaxinger** [comment]
https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4635/6/tests

**Comment by markus2330** [comment]
Is it possible that the `ctest --rerun-failed` causes this problem? (return status ok, but actually a test failed)

**Comment by kodebach** [comment]
> You need to click on "Tests"

Ah okay, but then, we didn't any of the pipeline stages fail?

> Actually I thought that spelling checks are done in basic checks. But if it is not, it should be there.

I don't think it's done in the "Basic checks" stage. But it should happen in the "Main builds".

The issue here is that it seems tests failed, but the pipeline did not fail.

> Is it possible that the `ctest --rerun-failed` causes this problem?

Might be. One more reason to get rid of this weird hack.

**Comment by atmaxinger** [comment]
@markus2330 success!

**Review by mpranj — APPROVED** [review]

**Comment by mpranj** [comment]
Thank you so much for the fix! 🥇

**Comment by flo91** [comment]
Thank you very much for making this PR! 🎆 

> True, I've also added those two links right now. We should probably make an issue to remove them from the whitelist after master builds again.

I think, we should remove the links after they are fixed, and wrote in https://github.com/ElektraInitiative/libelektra/issues/4624#issuecomment-1298834730:
"I suggest to leave this issue open until the links are fixed and removed from the whitelist."

**Pull request merged**
