### PR TITLE
[FLOSS H3] testmod_resolver fixes for new Backend

### PR DESCRIPTION
**Pull request by lawli3t**
## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by lawli3t** [comment]
@kodebach

It seems like there are some other issues related to the paths obtained from the handle.

```
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:60: error in test_resolve: string "" is not equal to "elektra.ecf"
153:    compared: h->system.path and "elektra.ecf"
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:70: error in test_resolve: string "/home/jenkins/workspace/elektra-build-docker/.config/kdb/system/" is not equal to "/home/jenkins/workspace/elektra-build-docker/.config/kdb/system/elektra.ecf"
153:    compared: h->system.filename and KDB_DB_SYSTEM "/elektra.ecf"
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:72: error in test_resolve: string "" is not equal to "elektra.ecf"
153:    compared: h->user.path and "elektra.ecf"
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:73: error in test_resolve: string "/tmp/elektra-test.VoY85K/.config/" is not equal to "/tmp/elektra-test.VoY85K/.config/elektra.ecf"
153:    compared: h->user.filename and path
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:84: error in test_resolve: string "/home/jenkins/workspace/elektra-build-docker/.config/kdb/system/" is not equal to "elektra.ecf"
153:    compared: h->system.path and "elektra.ecf"
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:94: error in test_resolve: string "/home/jenkins/workspace/elektra-build-docker/.config/kdb/system/" is not equal to "/home/jenkins/workspace/elektra-build-docker/.config/kdb/system/elektra.ecf"
153:    compared: h->system.filename and KDB_DB_SYSTEM "/elektra.ecf"
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:96: error in test_resolve: user was initialized, but is not needed
153: Resolve Name
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:149: error in test_name: string "/home/jenkins/workspace/elektra-build-docker/.config/kdb/system/" is not equal to "/home/jenkins/workspace/elektra-build-docker/.config/kdb/system/elektra.ecf"
153:    compared: keyString (parentKey) and KDB_DB_SYSTEM "/elektra.ecf"
153: Resolve Dirname
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:202: error in test_lockname: resulting filename not correct
153: Resolve Tempname
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:253: error in test_tempname: resulting filename not correct
```

Has the content / convention for storing the filenames changed as well or is this some new error in the resolver? If the convention hasn't changed then there seems to be a bug, as the expected values would make sense to me, while the values obtained from the struct seem strange. The `parentKey` passed in `kdbGet` might have something to do with it?

**Comment by kodebach** [comment]
First: It seems the `testmod_resolver` tests are pretty useless. They only test with one filename (which is even the default one), and only for the `system:/` namespace. There are other tests for the resolver (e.g. `tests/shell/check_resolver.sh`), but we should probably extend `testmod_resolver` as well.

Regarding your problem: Yes, there is an additional change. Previously, `resolver` took the `/path` key from its plugin config, resolved that and returned the result as the value of the `parentKey`. Now it takes the path to be resolved from the `parentKey` and simply updates the value.

So instead of this
```c
Key * parentKey = keyNew ("system:/", KEY_END);
Plugin * plugin = elektraPluginOpen ("resolver", modules, set_pluginconf (), 0);
```
the tests should now use
```c
Key * parentKey = keyNew ("system:/", KEY_VALUE, "elektra.ecf", KEY_END);
Plugin * plugin = elektraPluginOpen ("resolver", modules, ksNew (0, KS_END), 0);
```

**Comment by lawli3t** [comment]
> First: It seems the `testmod_resolver` tests are pretty useless. They only test with one filename (which is even the default one), and only for the `system:/` namespace. There are other tests for the resolver (e.g. `tests/shell/check_resolver.sh`), but we should probably extend `testmod_resolver` as well.

Yes I thought so as well when I read through it, I'll try to look into the shell recorder tests and get some inspiration for additional checks in `testmod_resolver`

> Regarding your problem: Yes, there is an additional change. Previously, resolver took the /path key from its plugin config, resolved that and returned the result as the value of the parentKey. Now it takes the path to be resolved from the parentKey and simply updates the value.

Thanks, I'll try this way.

**Review by JakobWonisch — COMMENTED** [review]
[FLOSS H3] Review

The changes are well documented and seem to make sense within the program. The suggested changes in this PR should fix any remaining problems.

**Comment by lawli3t** [comment]
I have added your suggestion, which in turn led to more errors most of which I should have also fixed (by removing unnecessary test code)

Still got 4 errors left tho

```
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:47: error in test_resolve: string "gV" is not equal to "elektra.ecf"
153:    compared: h->system.path and "elektra.ecf"
```
```
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:59: error in test_resolve: string "gV" is not equal to "elektra.ecf"
153:    compared: h->user.path and "elektra.ecf"
```

Those two look to me like the last paths of the path in `/tmp`, the first string seems random too. Is there any easy way of getting the location of the temp dir I'm not aware of. But even then, the test seems kind of pointless, especially if the new handle only contains the last part...

```
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:71: error in test_resolve: string "/home/jenkins/workspace/elektra-build-docker/.config/kdb/system/elektra.ecf" is not equal to "elektra.ecf"
```

This seems like the only assert worth fixing out of those, I just need to get the root path somehow.

```
153:    compared: h->system.path and "elektra.ecf"
153: /home/jenkins/workspace/src/plugins/resolver/testmod_resolver.c:83: error in test_resolve: user was initialized, but is not needed
```

This test seems unnecessary as well to me, because apparently user gets initialized whether its needed or not now. Or is this an oversight in the new backend plugin? (I doubt it)




What do you think @kodebach

**Comment by kodebach** [comment]
Almost everything that is tested in `testmod_resolver` is also covered by other test cases. So I think it would be fine, if you find a set of tests that seems sensible to you and get those working.

To address the failing tests in particular:

> Those two look to me like the last paths of the path in /tmp, the first string seems random too.

To me it looks, like you might be accessing uninitialized memory. That could produce random stuff. I haven't had time to look at the code, so maybe it is something else. If you find the error, good. Otherwise, remove or comment out (with a TODO) the checks.

> But even then, the test seems kind of pointless

Testing the full path is more difficult, because it depends on the CMake config. It's not impossible of course, because the actual resolver code uses the CMake variables too, but then you would basically check that the code your testing uses the same variable as the test.

However, what is a bit pointless is that we test with `elektra.ecf` which is one of the default files. It would be better to test with a more random filename like `apple.banana` so we at least verify that the resolver uses the name it received as an argument.

> This seems like the only assert worth fixing out of those, I just need to get the root path somehow.

Like I said, you can look at the code of the resolver itself (I think `filename.c` specifically) to see how you get the path from the CMake config.

> This test seems unnecessary as well to me, because apparently user gets initialized whether its needed or not now. Or is this an oversight in the new backend plugin?

Not sure, what happend here. There is an argument that loading the user paths when we don't need them is wasteful. User paths in particular are a bit expensive to compute (compared to the other namespaces), because the could involve syscalls and file-reads.

For now, just comment out this check and add a `TODO`. I will look into the problem myself.

**Comment by kodebach** [comment]
@markus2330 I merged this PR, because it improves the situation with `testmod_resolver`, even if the solution is not entirely perfect/complete.

**Comment by markus2330** [comment]
@kodebach Thank you for taking this code in!

**Pull request merged**
