### PR TITLE
Improve usecase template formatting

### PR DESCRIPTION
**Pull request by omnidan**

### CODE REVIEW

**Comment by markus2330** [comment]
Can you also fix the "doc/usecases/snippet_sharing"? Any idea why the one job within travis failed? (It is not related to this PR)

**Comment by markus2330** [comment]
Please also add here "ready to merge" if ready to merge.

**Comment by omnidan** [comment]
@markus2330 done! I hope travis passes this time (not sure why it failed).

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
