### PR TITLE
Tests: Enable Tests on ASAN Linux Builds

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

I opened this PR to check out why [`elektra-clang-asan`](https://build.libelektra.org/jenkins/blue/organizations/jenkins/elektra-clang-asan) fails. My current assumption would be that the failures are related to a [call of a function via a pointer of incorrect type](https://github.com/ElektraInitiative/libelektra/pull/1728).

# Checklist

- [x] I checked all commit messages.
- [x] I do not think the updates in this PR are important enough to be part of the release notes.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
Since all the ASAN builds work perfectly fine on [Travis](https://travis-ci.org/sanssecours/elektra/builds/367530790), my current solution to our problems with [`elektra-clang-asan`](https://build.libelektra.org/jenkins/blue/organizations/jenkins/elektra-clang-asan) and possibly [`elektra-clang`](https://build.libelektra.org/jenkins/job/elektra-clang/) would be to either:

- Use a version of Debian with less outdated software,
- use Clang 5 just as we do on Travis, or
- delete or disable the build jobs

.

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Thank you so much for looking into this!

Using Clang 5 for the ASAN builds is reasonable. It can easily be installed via backports.

Clang 3.8 can still be used for non-ASAN builds.

**Comment by sanssecours** [comment]
I marked this pull request as “ready to merge”. While the PR re-enables `testscr_check_kdb_internal_check`, another test that fails on [`elektra-clang-asan`](https://build.libelektra.org/jenkins/blue/organizations/jenkins/elektra-clang-asan/detail/elektra-clang-asan/435/pipeline#log-1783), I think everything should work again as soon as we switch the compiler in our ASAN/Clang environment to Clang 5.

**Comment by markus2330** [comment]
@ingwinlu Can you redirect the clang-asan build jobs to an agent with clang5? (e.g. debian-unstable-mm)

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
