### PR TITLE
crypto: handle return code of execv in the gpg module

### PR DESCRIPTION
**Pull request by petermax2**
See #1590 for details.

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy.
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the PR! Looks good!

**Comment by petermax2** [comment]
I just simplified the code. As you wrote in #1590 `execv` always sets `errno` in case of error.

**Comment by petermax2** [comment]
jenkins build please

**Comment by petermax2** [comment]
`testmod_gopts` runs into a timeout on jenkins but I think it wasn't me :stuck_out_tongue:

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by mpranj** [comment]
> testmod_gopts runs into a timeout on jenkins but I think it wasn't me stuck_out_tongue

I've had this today too.

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by petermax2** [comment]
> Do we have a guarantee that the buffer is allocated large enough? What about simply transferring the number and calling strerror at the receiver side?

Good idea!

**Comment by petermax2** [comment]
The job "Full builds / build/hub.libelektra.org/build-elektra-web-base:PR-3137_5" failed

    [ 42%] Linking C shared module ../../../lib/libelektra-line.so
    Cannot contact hetzner-jenkins1: java.lang.InterruptedException
    gtest/googlemock/gtest/CMakeFiles/gtest.dir/build.make:62: recipe for target 'gtest/googlemoc/gtes/CMakeFiles/gtest.dir/src/gtest-all.cc.o' failed
    CMakeFiles/Makefile2:18135: recipe for target 'gtest/googlemock/gtest/CMakeFiles/gtest.dir/all' failed
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report, with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    make[2]: *** [gtest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 4
    make[1]: *** [gtest/googlemock/gtest/CMakeFiles/gtest.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....


Everything else looks good now.

**Comment by markus2330** [comment]
@petermax2 thank you very much!

> Cannot contact hetzner-jenkins1: java.lang.InterruptedException

This is some network problem or overload on the hetzner server. @Mistreated do you know about it?

**Comment by Mistreated** [comment]
> This is some network problem or overload on the hetzner server.

At the moment the node is stuck, doing nothing..
Should I rerun it and see how it behaves?

**Comment by markus2330** [comment]
@Mistreated yes, please rerun and try to fix the problem why it gets stuck.

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Great job! Looking forward to see the next contribution :100:

**Pull request merged**
