### PR TITLE
Reduce fedora image size

### PR DESCRIPTION
**Pull request by 4ydan**
Adding the option install_weak_deps=False reduces the image size of these fedora docker images #4637

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add them to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - add a line in `doc/news/_preparation_next_release.md`
  - reformat the code with `scripts/dev/reformat-all`
  - make all unit tests pass
  - fix all memleaks
  - fix the CI itself (or rebase if already fixed)
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if everything is done** and no further pushes are planned by you.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating the PR! There are several CI jobs broken but I don't think it is because of your changes.

Can you estimate which ones are easy to fix and which pipelines we should rather disable?

**Comment by markus2330** [comment]
Thx, unfortunately the hard ones are the more needed ones (macOS we don't have in Jenkins).

Please do the Jenkins fixes first. (Temporary) removal of openwrt is okay.

**Comment by 4ydan** [comment]
So I spent a bit of time with this and found the following information.

- Libassuan has a new version 2.5.6 which is downloaded by the cirrus ci. Libelektra needs 2.5.5.
- The macos stuff is a bit more complicated, Idk if [this](https://github.com/Homebrew/homebrew-core/issues/135315) issue is related to it. Installing brew seems to fail two of the pipelines, one of them also fails because of libassuan.
- Installing sudo on the openwrt image isnt' as easy as I thought.

Maybe its faster to fix this moving libelektra to libassuan 2.5.6?

Overall none of them was easy fixable, for me at least.

**Comment by atmaxinger** [comment]
Can we merge this?

**Comment by 4ydan** [comment]
Fine from my side, nothing more to be done.

**Comment by atmaxinger** [comment]
Please rebase on top of the current master, so the Jenkins build can run through.

**Comment by 4ydan** [comment]
Ready to be merged.

**Pull request merged**
