### PR TITLE
YAML CPP & Test Fixes

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This PR fixes a problem, where YAML CPP would crash if you save a value directly below a mountpoint. 

The pull request also adds code to only run a test if all the required plugins for the test are available. This update makes sure that running the test suite also works if we use a minimal configuration. 

# Checklist

- [x] I checked all commit messages.
- [x] I ran all tests and everything went fine.
- [x] The PR includes updated release notes.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build docker please

**Comment by sanssecours** [comment]
jenkins build docker please

**Comment by sanssecours** [comment]
jenkins build haskell please

**Comment by sanssecours** [comment]
jenkins build docker please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
