### PR TITLE
Fix Various Minor Problems

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This PR fixes various minor problems.

# Checklist

- [x] I checked all commit messages.
- [x] This PR adds code comments and updates logging statements.
- [x] The pull request also updates the release notes.

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by markus2330** [comment]
https://build.libelektra.org/job/elektra-gcc-configure-xdg/980/ seems to have a memory leak?

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
> https://build.libelektra.org/job/elektra-gcc-configure-xdg/980/ seems to have a memory leak?

I know. The tests `testkdb_conflict`, `testkdb_error`, `testkdb_nested` and most of the Shell Recorder tests leak too.

Do you know why [`elektra-clang-asan`](https://build.libelektra.org/jenkins/job/elektra-clang-asan/410/console) does not seem to add symbol information to binaries? Without this information we are not able to use a suppression list for memory leaks, since Clangs’s leak sanitizer checks for problems at runtime.

**Comment by sanssecours** [comment]
jenkins build elektra-gcc-configure-xdg please

**Comment by sanssecours** [comment]
jenkins build gcc-configure-xdg please

**Comment by markus2330** [comment]
Sorry, I do not know. `-DCMAKE_BUILD_TYPE=Debug` should add all symbol information available. And it does, I successfully started gdb with the binary on the agent and all source code information was available. I would rather suspect the ASAN setup, maybe it is not configured to lookup the information.

I installed clang 5 and 7, maybe this fixes the problem.

**Comment by markus2330** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
> I would rather suspect the ASAN setup, maybe it is not configured to lookup the information.

That may be the case. Since the current setup works perfectly fine on Travis (Linux) and on my local machine (macOS), I would recommend we disable `elektra-clang-asan` for now.

**Comment by markus2330** [comment]
One last try with clang-5.0. Otherwise we can temporarily disable it.

**Comment by markus2330** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by markus2330** [comment]
jenkins build gcc-configure-debian-log please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build gcc-configure-debian-stretch please

**Comment by markus2330** [comment]
A bit thanks to your uncomplaining patience with the build server!

Can you split up the release notes to a different PR or directly push them to master? I have more and more local changes and the chances of conflicts increase :small_airplane:

**Comment by sanssecours** [comment]
> Can you split up the release notes to a different PR or directly push them to master? I have more and more local changes and the chances of conflicts increase :small_airplane:

Please just push your changes to `master`, I will rebase the PR afterwards.

**Comment by sanssecours** [comment]
jenkins build gcc-configure-debian-stretch please

**Comment by markus2330** [comment]
(Seems like we did something at the same time)

Thank you, great to have this merged!

So now nothing should stop the release :-)

**Pull request merged**
