### PR TITLE
merger sync key problem

### PR DESCRIPTION
**Pull request by fberlakovich**
The commit should fix the issue discussed in #295. However, I could not test the fix with the gui. The gui eats up all my system ressources until the system grinds to a halt. When it finally starts it is so slow that I can hardly click anything. Please let me know if the issue is resolved.

### CODE REVIEW

**Comment by markus2330** [comment]
Is the problem with the GUI also without any mountpoints?

**Comment by markus2330** [comment]
thanks for the fix! I opened #347 which might be caused due to merging.

**Comment by fberlakovich** [comment]
I will try the GUI without any mountpoints. I only had two very small files mounted at the time and a `kdb ls` was very fast. I already had it running successfully previously, however, it never was very responsive on my development machine.

**Comment by markus2330** [comment]
Problem is discussed in #348, fix will be done soon

**Comment by markus2330** [comment]
Is fixed. It shouldn't matter if you have mountpoints.

**Pull request merged**
