### PR TITLE
plugin: remove name parameter from ELEKTRA_PLUGIN_FUNCTION

### PR DESCRIPTION
**Pull request by petermax2**
it is provided by the build system automatically.
See #1042 for further details.

## Basics

Do not describe the purpose here but:

- [ ] Short descriptions should be in the release notes (added as entry in
      doc/news/_preparation_next_release.md which contains `*(my name)*`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [x] I added unit tests
- [x] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

### CODE REVIEW

**Comment by petermax2** [comment]
**TODO**

- [ ] move release doc to _Misc_ section

**Comment by petermax2** [comment]
@markus2330 `fcrypt` is fine now but the Python bindings fail. How do I generate them?

**Comment by markus2330** [comment]
Thank you for working on this!

**Comment by petermax2** [comment]
@mpranj you used `ELEKTRA_PLUGIN_FUNCTION` quite a lot, so there are many changes in `nmap`. Please have a quick look if those changes work for you. =)

@markus2330 please have a look at the changes. The build server does not complain so it should not be too bad. =)

**Comment by markus2330** [comment]
Thank you, great job!

**Pull request merged**
