### PR TITLE
Elektra-web 1.1

### PR DESCRIPTION
**Pull request by omnidan**
## Updates

- got rid of cluster configuration, focussed on instance configuration
- revamped design (including completely reworked tree view!)
- implement adding and removing keys within the tree view
- implement dynamic fields (via elektra metadata), e.g. checkbox/boolean, radio/enum, number, text/string
- search/filter functionality
- drag & drop to move keys (including subkeys)
- editing metadata
- keys are refreshed/synchronized in a much better way now, e.g. before editing key is refreshed so that you always edit the latest value
- improved routing, e.g. you can directly go to `/instances/:id` now and it will load properly
- updated READMEs and packaging, client is now the main entry point (makes more sense than dealing with clusterd directly) -> see [new getting started guide](https://github.com/omnidan/libelektra/tree/elektra-web1.1/src/tools/web#getting-started).

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Does this PR also includes the performance improvements?

Are you still working on the "Still missing" or is this PR ready to review? If it is ready to review, please mark as "ready to merge" and move the "Still missing" to a separate issue.

**Comment by omnidan** [comment]
@markus2330 

> Does this PR also includes the performance improvements?

Yes

> Are you still working on the "Still missing" or is this PR ready to review? If it is ready to review, please mark as "ready to merge" and move the "Still missing" to a separate issue.

I am still working on it and will make a separate issue/PR for those features.

**Comment by markus2330** [comment]
@Namoshek Could you please review the source code?

**Comment by markus2330** [comment]
When trying to start the client I get following error:

```
src/tools/web/client> npm start                                                                                                                                                                                                               Montag 12:15:09

> @elektra-web/client@1.1.0 start /home/markus/Projekte/Elektra/libelektra/src/tools/web/client
> npm run server


> @elektra-web/client@1.1.0 server /home/markus/Projekte/Elektra/libelektra/src/tools/web/client
> cd ../clusterd && npm start


> @elektra-web/clusterd@1.1.0 start /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd
> npm run build && npm run start:prod


> @elektra-web/clusterd@1.1.0 build /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd
> cross-env NODE_ENV=production babel -d build/ src/ && npm run build --prefix ../client

sh: 1: cross-env: not found

npm ERR! Linux 4.9.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @elektra-web/clusterd@1.1.0 build: `cross-env NODE_ENV=production babel -d build/ src/ && npm run build --prefix ../client`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @elektra-web/clusterd@1.1.0 build script 'cross-env NODE_ENV=production babel -d build/ src/ && npm run build --prefix ../client'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @elektra-web/clusterd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production babel -d build/ src/ && npm run build --prefix ../client
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @elektra-web/clusterd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @elektra-web/clusterd
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/npm-debug.log

npm ERR! Linux 4.9.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @elektra-web/clusterd@1.1.0 start: `npm run build && npm run start:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @elektra-web/clusterd@1.1.0 start script 'npm run build && npm run start:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @elektra-web/clusterd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run start:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @elektra-web/clusterd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @elektra-web/clusterd
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/markus/Projekte/Elektra/libelektra/src/tools/web/clusterd/npm-debug.log

npm ERR! Linux 4.9.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "server"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @elektra-web/client@1.1.0 server: `cd ../clusterd && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @elektra-web/client@1.1.0 server script 'cd ../clusterd && npm start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @elektra-web/client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ../clusterd && npm start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @elektra-web/client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @elektra-web/client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/markus/Projekte/Elektra/libelektra/src/tools/web/client/npm-debug.log

npm ERR! Linux 4.9.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @elektra-web/client@1.1.0 start: `npm run server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @elektra-web/client@1.1.0 start script 'npm run server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @elektra-web/client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @elektra-web/client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @elektra-web/client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/markus/Projekte/Elektra/libelektra/src/tools/web/client/npm-debug.log
```

[npm-debug.log]()

**Comment by markus2330** [comment]
Seems like some text still refers to clusterd.

**Comment by omnidan** [comment]
@markus2330 I fixed the issue (dependencies of clusterd were not installed automatically). I did a fresh clone and it works for me now.

I think it's alright that some parts still refer to clusterd, it still exists and is used to manage instances and serve the client. However, the main "entry point" of elektra-web is the client now, which probably makes more sense to users.

**Comment by markus2330** [comment]
Thank you a lot!

**Pull request merged**
