### PR TITLE
small fix of documentation links for initial pull request in CM

### PR DESCRIPTION
**Pull request by goJoWe16**
Small fix of documentation links for initial pull request in **CM**

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating the PR! I'll add you to the private repo soon.

**Comment by markus2330** [comment]
I added you to the private repo.

Please add a line to the release notes, so that the build server is happy.

**Comment by goJoWe16** [comment]
There are now conflicts in the release notes which I am not to resolve because I have vo write access

**Comment by markus2330** [comment]
You would need to rebase (in your own repo). Also the release notes does not have the syntax as required (your name needs to be there, see build server output).

But maybe the fix is not necessary:
Why did you find that the links are broken?
I could not find a place where they are broken:

- https://www.libelektra.org/manpages/elektra-introduction
- https://master.libelektra.org/doc/help/elektra-introduction.md

**Comment by goJoWe16** [comment]
I have tried it with my IDE and there, these links have not been working, but maybe it's just a Problem in the IDE-View. In this case, this pull request can be declined as it's not chaning anything important.

**Pull request closed without merging**
