### PR TITLE
Code Check: Fix Some Warnings Reported by LGTM

### PR DESCRIPTION
**Pull request by sanssecours**
@markus2330 👋 Markus, can you please [activate the LGTM integration for the repository](https://lgtm.com/projects/g/ElektraInitiative/libelektra/ci/)? I think that would be really helpful in checking, if the PR really fixes some of the warnings reported by [LGTM](https://lgtm.com).

### CODE REVIEW

**Comment by markus2330** [comment]
I gave the permissions.

**Comment by markus2330** [comment]
This pull request **fixes 1 alert** when merging 22a85e3ba63a3aa97edc2728f288c615f8753d19 into 9010360ba57231dfd05a378fd2b67c324671dde1 - [view on LGTM.com](https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-df2dbfe79b76b9ce73b190d577ab5145d67e741c)

**fixed alerts:**

* 1 for Unnecessary pass

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by markus2330** [comment]
This pull request **fixes 1 alert** when merging 7d455abdcda2ecdef7729a6612b646bedda6471d into 9010360ba57231dfd05a378fd2b67c324671dde1 - [view on LGTM.com](https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-a7396c07228c3113311cf1b1530c807e6337cf1c)

**fixed alerts:**

* 1 for Unnecessary pass

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by markus2330** [comment]
This pull request **fixes 3 alerts** when merging 2d0daae0caa529cc991bfc26946dfbb91195d32a into 9010360ba57231dfd05a378fd2b67c324671dde1 - [view on LGTM.com](https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-fa17267d922325fa6309a83c026f93f9cf375c1b)

**fixed alerts:**

* 2 for Duplicate include guard
* 1 for Unnecessary pass

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by markus2330** [comment]
This pull request **fixes 3 alerts** when merging eed057aa7be3d609849eea2a35b84c69fa9bcb4e into 9010360ba57231dfd05a378fd2b67c324671dde1 - [view on LGTM.com](https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-61894238332a341b6ba68e149992dfdd2151488e)

**fixed alerts:**

* 2 for Duplicate include guard
* 1 for Unnecessary pass

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by markus2330** [comment]
This pull request **fixes 5 alerts** when merging dba02a83a5d5ec2a37352982a083336081c1aabd into e510189737a79714b0f65190e9355ecace937be2 - [view on LGTM.com](https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-1acda285661d6ef0dfa5d9324d9ada85bfb0d868)

**fixed alerts:**

* 2 for Duplicate include guard
* 2 for Short global name
* 1 for Unnecessary pass

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by markus2330** [comment]
This pull request **fixes 6 alerts** when merging 0e3c40e91bf2655224ca7fcf74237b8115d9aeba into 0f9f89493d150093a5d57319aadfe47e62619557 - [view on LGTM.com](https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-e0d9d91d03a353e5451ff2d1b6b993a5bee34ecd)

**fixed alerts:**

* 2 for Duplicate include guard
* 2 for Short global name
* 1 for Unnecessary pass
* 1 for Missing header guard

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by markus2330** [comment]
This pull request **fixes 7 alerts** when merging 26d8d33ef27060686d9606114741d3163f254c22 into 0f9f89493d150093a5d57319aadfe47e62619557 - [view on LGTM.com](https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-d5ce19e16eccf75fac3f8b23d916a9709353756b)

**fixed alerts:**

* 2 for Missing header guard
* 2 for Duplicate include guard
* 2 for Short global name
* 1 for Unnecessary pass

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by markus2330** [comment]
This pull request **fixes 19 alerts** when merging 35ac099a162b72f6a1c10d33371a06a6d536d992 into 0f9f89493d150093a5d57319aadfe47e62619557 - [view on LGTM.com](https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-3a37d91ed60b9d06cf5731ffb87f5822aa7bef8d)

**fixed alerts:**

* 10 for Missing header guard
* 2 for Duplicate include guard
* 2 for Short global name
* 1 for Unnecessary pass
* 1 for Unused import
* 1 for Comparison result is always the same
* 1 for Empty branch of conditional
* 1 for Variable used in its own initializer

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by markus2330** [comment]
This pull request **fixes 19 alerts** when merging 070235cd7995fd732e2028cca662dc3984c64023 into 0f9f89493d150093a5d57319aadfe47e62619557 - [view on LGTM.com](https://lgtm.com/projects/g/ElektraInitiative/libelektra/rev/pr-a644f612d4b245216fe4d3aed062a7605db26e25)

**fixed alerts:**

* 10 for Missing header guard
* 2 for Duplicate include guard
* 2 for Short global name
* 1 for Unnecessary pass
* 1 for Unused import
* 1 for Comparison result is always the same
* 1 for Empty branch of conditional
* 1 for Variable used in its own initializer

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by markus2330** [comment]
Thank you so much for fixing these problems!

Did you see some problems where you think a fix is needed? If yes, could you open an issue for which ones? If they are easy to fix, feel free to tag it with "good first issue" for the CM people.

**Comment by sanssecours** [comment]
> Did you see some problems where you think a fix is needed?

I think we should address [all of the problems recognized by LGTM](https://lgtm.com/projects/g/ElektraInitiative/libelektra/) 

- either by fixing them, or
- ignoring them explicitly (using something like `// lgtm [language/error]`

.

> If yes, could you open an issue for which ones?

I do not think opening an issues for every warning reported by LGTM makes much sense.

**Comment by markus2330** [comment]
>  I do not think opening an issues for every warning reported by LGTM makes much sense.

No, only one issue that says that warnings of LGTM should be fixed.

We already have similar issues for other warnings (openbsd iirc)

**Pull request merged**
