### PR TITLE
Address Sanitizer: Fix Warnings

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request fixes some warnings reported by the address sanitizer. 

# Checklist

- [x] I checked all commit messages twice.
- [x] I ran all tests and everything went fine.

### CODE REVIEW

**Comment by sanssecours** [comment]
This update should be ready. If I should change anything else, then please just comment below. Thank you.

**Comment by markus2330** [comment]
Thank you for taking care of such issues!

@tom-wa @e1528532 Can you take a look?

**Comment by markus2330** [comment]
@tom-wa Can you take a look?

**Comment by tom-wa** [comment]
thanks for finding/fixing that bug.
would that also work if kdbGet gets called twice ?

**Comment by markus2330** [comment]
@tom-wa Thanks for looking at it!

Which problem do you think could occur if `kdbGet` is called twice?

**Comment by tom-wa** [comment]
i'm currently trying to wrap my head around it. the loop runs until the next placement is found. if the last placement is reached it would go straight back the the first placement (% getEnd) but with the placement < getEnd condition that might never happen. 

maybe `while (!placements->getPlacements[currentPlacement % getEnd])` would be a better solution ? an incorrectly configured list plugin would result in an endless-loop though. 

what do you think ?

**Comment by markus2330** [comment]
Actually it is enough if you confirm that it does not break anything that worked before.

Does `while (!placements->getPlacements[currentPlacement % getEnd])` also yield no sanitizer problems? What would be the difference in behavior?

> an incorrectly configured list plugin would result in an endless-loop though.

Better to avoid that (if otherwise there is no difference).

**Comment by tom-wa** [comment]
>Actually it is enough if you confirm that it does not break anything that worked before. 

thats what i'm currently trying to confirm. in my original implementation (which i have to admit had some bugs) it would loop % lastplacement, so after the last placement is reached, it would begin with the first one again. and i'm not sure if behaviour is still the same

**Comment by markus2330** [comment]
Take your time. Can you add some unit tests so that we can be more confident for the next changes?

**Comment by tom-wa** [comment]
the problem with the endless loops with a misconfigured list plugin is present anyway, i only noticed it now
i think something like 
```
	placements->errCurrent = ((++currentPlacement) % errEnd);
        ErrPlacements counter = 0;
	while (!placements->errPlacements[currentPlacement % errEnd] && counter++ < errEnd)
	{
		placements->errCurrent = ((++currentPlacement) % errEnd);
	}
```
would fix both issues for now until someone (me ? ) adds a check if the plugin actually has any placements for kdb{Get,Set,Error} when List{Get,Set,Error} are called.

**Comment by markus2330** [comment]
@tom-wa Thanks for looking into it! Do you have time to prepare a PR, ideally with test cases?

**Pull request closed without merging**
