### PR TITLE
cache: enable ini

### LINKED ISSUE #2787: do not remove cache with INI
As discussed, please remove the restrictions with INI (let it also be cached) but instead only disable the cache for the failing test case.

### PR DESCRIPTION
**Pull request by mpranj**
Closes #2787.

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [ ] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

### CODE REVIEW

**Comment by markus2330** [comment]
Did you find a solution for the INI plugin?

**Comment by mpranj** [comment]
No, the error was temporarily gone on my machine. This one here definitely won't be finished today.

**Comment by markus2330** [comment]
Any progress here?

**Comment by mpranj** [comment]
Nothing new. I just re-tested it after all the other fixes (cache/multifile etc.) but it's the same error. I didn't have time yet to implement the _workaround_ (= simply document and ignore it) yet. Maybe I can do it within the next week, but I'll ping you when it's ready.

**Comment by mpranj** [comment]
Now that #2831 is merged, I'll update this as discussed. (enable cache+ini and disable the cache only for the one failing test.

**Comment by mpranj** [comment]
@markus2330 seems like disabling the cache inside the single test does not work (because markdown shellrecorder does the backup/tests before/after the actual markdown file). I would have to implement the workaround inside the shellrecorder itself, or disable the cache completely for "debian-stretch-full-ini" (or basically any testsuite where ini is the default storage".

**Comment by markus2330** [comment]
If it is only about debian-stretch-full-ini, then simply disable the cache there (then you actually do not need a separate nocache test).

**Comment by mpranj** [comment]
Thank you! I disabled it there. I can remove the nocache test, but I assumed that we might deprecate the ini test sometime so I left the separate nocache test.

**Comment by mpranj** [comment]
@markus2330 done!

**Comment by markus2330** [comment]
Thank you very much! I'll do some more testing but I am confident it is suitable for the release.

**Pull request merged**
