### PR TITLE
rest-backend: ensure backend starts daemonized

### PR DESCRIPTION
**Pull request by Namoshek**
# Purpose

The PR should fix the issue that the backend dies at the end of the build.

### CODE REVIEW

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
Looks good, but formatting is broken!

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
Jenkins still kills the backend, so now I'm trying what is described in the [jenkins wiki](https://wiki.jenkins-ci.org/display/JENKINS/Spawning+processes+from+build) and daemonize the rest-backend (without the run-script, which does the same).

**Comment by Namoshek** [comment]
It works :sob: :+1:.

**Comment by Namoshek** [comment]
Daemonize breaks some other functions. Another option would be the one described in [this post](http://stackoverflow.com/questions/17024441/process-leaked-file-descriptors-error-on-jenkins/21567647#21567647), but it is for all jenkins projects.

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
Can't believe it actually works now :sob: :smile:.

**Comment by markus2330** [comment]
Great! So the BUILD_ID did the trick?

**Comment by Namoshek** [comment]
Actually this was enough, yes. In the wiki they describe it like you need to use daemonize additionally, but with daemonize + the cppcms daemon it was a mess, so this is the best solution anyway.

**Pull request merged**
