### PR TITLE
Fix version release pipeline

### PR DESCRIPTION
**Pull request by tmakar**
## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add them to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - add a line in `doc/news/_preparation_next_release.md`
  - reformat the code with `scripts/dev/reformat-all`
  - make all unit tests pass
  - fix all memleaks
  - fix the CI itself (or rebase if already fixed)
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if everything is done** and no further pushes are planned by you.

### CODE REVIEW

**Comment by tmakar** [comment]
Due to this error I checked where the `v` prefix might be used:

```sh
DCMAKE_INSTALL_PREFIX=/home/jenkins/workspace/libelektra-release@2/system ../elektra-0.10.0
CMake Error: The source directory "/home/jenkins/workspace/libelektra-release@2/libelektra/build/elektra-0.10.0" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
script returned exit code 1
```

> NOTE: The goal is to have a tag prefixed with `v` but the version in Elektra should still be used without the `v` prefix.

**Comment by tmakar** [comment]
Here is the function where it failed:

```sh
create_source_package() {
	echo "Preparing package..."

	export KDB_VERSION=$(kdb get system:/elektra/version/constants/KDB_VERSION)
	export CMAKE_BINARY_DIR=$BUILD_DIR

	cd "$BUILD_DIR"
	make source-package

	# Check if tar is reproduceable + sign it:
	gpg --sign elektra-"$VERSION".tar.gz

	# Unpack + compile (with all available plugins) + test those sources:
	tar xvzf elektra-"$VERSION".tar.gz
	mkdir "$BUILD_DIR"/builder
	cd "$BUILD_DIR"/builder
	cmake -DPLUGINS="ALL" \
		-DTOOLS="ALL" \
		-DENABLE_DEBUG="OFF" \
		-DENABLE_LOGGER="OFF" \
		-DBUILD_SHARED=ON \
		-DBUILD_FULL=ON \
		-DBUILD_STATIC=ON \
		-DKDB_DB_SYSTEM="${WORKSPACE}/config/kdb/system" \
		-DKDB_DB_SPEC="${WORKSPACE}/config/kdb/spec" \
		-DKDB_DB_HOME="${WORKSPACE}/config/kdb/home" \
		-DCMAKE_INSTALL_PREFIX="${WORKSPACE}/system" \
		../elektra-"$VERSION"
	make
	make run_all
	memcheck

	cp "$BUILD_DIR"/elektra-"$VERSION".tar.gz* "$BASE_DIR"/"$VERSION"/
}
```

**Comment by tmakar** [comment]
@markus2330 Do I need to adapt all the files again and set `0.10.0` as release version?

**Comment by markus2330** [comment]
> @markus2330 Do I need to adapt all the files again and set 0.10.0 as release version?

Why do you think it would be needed?

**Pull request merged**
