### PR TITLE
Fix readme typos

### PR DESCRIPTION
**Pull request by raphi011**
Hi guys - this is my first pull request for Elektra, it contains a small typo fix in the root README.md file.

You will probably see more of me because as part of my bachelors thesis I will write go bindings and rewrite the nodejs web api with GO :)

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] meta data is updated (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))

## Review

Reviewers will usually check the following:

- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
- [ ] Documentation is concise and good to read
- [ ] Examples are well chosen and understandable

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the PR!

Please add release notes so that the contribution will be mentioned in the next release, even if the PR is trivial (on multiple similar contributions I will summarize). Please also do not remove the text from the PR template.

**Comment by raphi011** [comment]
sorry :) could you add a link to a pastebin or something so I can re-add the PR template text?

**Comment by markus2330** [comment]
So the PR is getting bigger :+1: 

As commit message, we prefer "module: <text>", where module would be "doc" in this case. (see the text you copied) You do not need to change it for commits you already did.

**Comment by raphi011** [comment]
I'm reading parts of the documentation atm - if I stumble over typos I will add it to the MR!

> As commit message, we prefer "module: ", where module would be "doc" in this case. (see the text you copied) You do not need to change it for commits you already did.

noted!

**Comment by markus2330** [comment]
> I'm reading parts of the documentation atm - if I stumble over typos I will add it to the MR!

This is very much appreciated!

But maybe also give the build server a chance to finish, it needs about 2-3h. If you push every hour you will never see a result :smile: 

Btw. we also have scripts/sed where you can collect automatic replacements to be done in future (like build-in -> built-in)

**Comment by markus2330** [comment]
(scripts/fix-spelling will use scripts/sed)

**Comment by markus2330** [comment]
Looks good, the build server is happy!

Do you really need the file  src/bindings/go/elektra.go already?

See above: Can you add build-in -> built-in in  scripts/sed?

When you are ready, please set the label "ready to merge" (I invited you now).

**Comment by raphi011** [comment]
> Looks good, the build server is happy!
> 
> Do you really need the file src/bindings/go/elektra.go already?

Ups .. that was not on purpose .. will remove it.

> 
> See above: Can you add build-in -> built-in in scripts/sed?

Gonna add it with the next commit.

> 
> When you are ready, please set the label "ready to merge" (I invited you now).

Will do

**Comment by markus2330** [comment]
Good job! Some builds sporadically fail, in this case please simply restart them (to be sure it does not hide any other problems) before putting "ready to merge". Of course, even better would be to fix these sporadic failures: #2310

**Pull request merged**
