### PR TITLE
Fix problems with mingw64 builds

### PR DESCRIPTION
**Pull request by qwepoizt**
@markus2330: This PR fixes several problems I discovered while compiling windows builds of Elektra for redshift.

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [x] make all unit tests pass
  - [x] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by qwepoizt** [comment]
@markus2330 I need to add release notes and execute the formatting scripts. Other than that, this is ready to merge IMO.

**Comment by qwepoizt** [comment]
@robaerd Can you please take a look at the build server related changes? Please feel free to change related files!

Basically, we want 32- and 64-bit mingw builds in the "master" and "release" pipeline:

1. "release" pipeline: I tried to include that in the "Jenkinsfile.release", but am not sure if it will work.
2. "master" pipeline: I think this is fine, see e.g. the [last Jenkins run for this PR](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-4070/13/artifacts) which successfully produced artifacts/debian-bullseye-mingw-w64-i686/elektra.zip and artifacts/debian-bullseye-mingw-w64-x86_64/elektra.zip

**Review by robaerd — APPROVED** [review]
LGTM!
I only moved the mingw builds from the publishing stage to the release build stage.

**Comment by qwepoizt** [comment]
> LGTM!
> I only moved the mingw builds from the publishing stage to the release build stage.

Great, thanks for your help!

**Comment by mpranj** [comment]
Thank you! Great work!

**Comment by markus2330** [comment]
Thank you :sparkling_heart: 

Please also add in the release notes that we now have mingw builds for our releases, I created an issue for the upcoming release: #4077

**Pull request merged**
