### PR TITLE
Style: Format Java Code With Clang-Format

### PR DESCRIPTION
**Pull request by sanssecours**

### CODE REVIEW

**Comment by Piankero** [comment]
I am not sure what to review here. I am no particular fan of reformatting java code with a C/C++ focused tool as because it will require to reconfigure your IDE to autoformat that correctly (which is a little bit abnoxious).

Other than that the PR is absolutely fine!

**Comment by markus2330** [comment]
> I am not sure what to review here.

To tell us if you can live with this format. Were you able to configure your IDE to format according to this?

**Comment by Piankero** [comment]
> To tell us if you can live with this format

This is just a matter of personal taste. Personally I am fine with this formatting.

> Were you able to configure your IDE to format according to this?

There are multiple IDEs I use but I think that the [clangformatij](https://plugins.jetbrains.com/plugin/8396-clangformatij) could be used for that. I made the experience though that for elektra I am better off by using the scripts/dev reformatters. Therefore I do not configure my IDE for this project.

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
This is the last open PR for the upcoming release. @sanssecours can you please rebase?

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you very much!

**Pull request merged**
