### PR TITLE
Removed public release API for Key and KeySet, updated docs and enabled strict javadoc checking

### LINKED ISSUE #4038: Remove manual release API [JNA bindings]
As soon as the garbage collector based clean-up of native resources is working (see #3875), the API for manual releasing native resources `Key::remove` and `KeySet::remove` should be removed (=made private).

Additionally all java-doc declaring related `IllegalArgumentException`s have to be updated.

### PR DESCRIPTION
**Pull request by tucek**
close #4038 and #3754

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [x] make all unit tests pass
  - [x] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [x] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by tucek** [comment]
This PR is included in #4440. Either directly review and merge #4440 and close this PR or review and merge them in sequence.

**Comment by markus2330** [comment]
This one is "ready to merge", #4440 is not?

**Comment by tucek** [comment]
> This one is "ready to merge", #4440 is not?

Sorry for the delay! Yes this one is, but I wanted to ensure the unit test we talked about is included in #4440.

**Comment by tucek** [comment]
jenkins build libelektra please

**Comment by tucek** [comment]
jenkins build all please

**Comment by tucek** [comment]
@kodebach 
I don't think the build error has anything todo with my changes... Are there currently known issues?

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
> I don't think the build error has anything todo with my changes... Are there currently known issues?

As written in #160 there was a power outage at the TU Wien.

**Comment by markus2330** [comment]
I think this can be closed? There is a merge conflict and it probably makes more sense to directly merge  #4440?

**Comment by tucek** [comment]
jenkins build libelektra please

**Comment by tucek** [comment]
will be merged together with #4440

**Pull request closed without merging**
