### PR TITLE
kdb: Don't fail if target-key has same value as source-key

### LINKED ISSUE #2560: kdb cp should not fail if keys are identical
## Steps to Reproduce the Problem

```sh
kdb set user/tests/hello world
kdb set user/tests/copy world

kdb cp user/tests/hello user/tests/copy
```

## Expected Result

That nothing happens (and no error message).

## Actual Result

```
The command kdb cp terminated unsuccessfully with the info:
Copy will not be done, because user/tests/copy already exists, use -f to force copy
```

## System Information

- Elektra Version: master

## Implementation Hint

also must work for -r (in this case it is even more important)

### PR DESCRIPTION
**Pull request by e01306821**
src/tools/kdb/cp.cpp
Added ckeck of key-values of target- and source-key. If the values are identical, 'kdb cp' now succeeds.
Close #2560 

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [X] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [X] I added unit tests
- [X] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

### CODE REVIEW

**Comment by e01306821** [comment]
I have a question regarding the manual of kdb cp:

```
To copy keys below an existing key:
kdb cp -r user/example user/example/key1
Note that in this example, all keys in the example directory will be copied below key1 except key1.
```
Suppose I have the following keys:
user/example/one
user/example/two

If I now execute 'kdb cp -r user/example user/example/one', I would have expected that now the following keys exist (based on the description of this case above):

- user/example/one
- user/example/one/two
- user/example/two

But now these keys exist:

- user/example/one
- **user/example/one/one**
- user/example/one/two
- user/example/two

Is this a bug, or am I misunderstanding the manual?

**Comment by e01306821** [comment]
I'm not sure, if "testmod_dbusrecv" is allowed to fail. Besides that and "testmod_dbus", everything seems to be fine, so please review my pull request @markus2330

**Comment by sanssecours** [comment]
> I'm not sure, if "testmod_dbusrecv" is allowed to fail.

That this test sometimes fails is a [known issue](https://issues.libelektra.org/2439). I restarted the failed build job.

**Comment by markus2330** [comment]
Thank you for this fix!

> Is this a bug, or am I misunderstanding the manual?

Thank you, the manual was wrong there. I removed the sentence.

**Comment by markus2330** [comment]
I had to revert this commit as it most likely was the reason of #2600.

Could you please redo this PR without this issue and a test case that shows it works properly with `-r`?

**Pull request merged**
