### PR TITLE
crypto-plugin: fix compile error for wheezy #453

### PR DESCRIPTION
**Pull request by petermax2**
fix for issue #453.

- [X] fix other compiler warnings
- [X] fix unused parameter warnings

### CODE REVIEW

**Comment by petermax2** [comment]
I can't get rid of the "unused parameter" warnings because of the compile variants.


	/elektra/src/plugins/crypto/crypto.c: In function 'elektraCryptoInit':
	/elektra/src/plugins/crypto/crypto.c:33:35: warning: unused parameter 'errorKey' [-Wunused-parameter]
	/elektra/src/plugins/crypto/crypto.c: In function 'elektraCryptoEncrypt':
	/elektra/src/plugins/crypto/crypto.c:61:41: warning: unused parameter 'handle' [-Wunused-parameter]
	/elektra/src/plugins/crypto/crypto.c:61:57: warning: unused parameter 'data' [-Wunused-parameter]
	/elektra/src/plugins/crypto/crypto.c:61:68: warning: unused parameter 'errorKey' [-Wunused-parameter]
	/elektra/src/plugins/crypto/crypto.c: In function 'elektraCryptoDecrypt':
	/elektra/src/plugins/crypto/crypto.c:123:41: warning: unused parameter 'handle' [-Wunused-parameter]
	/elektra/src/plugins/crypto/crypto.c:123:57: warning: unused parameter 'data' [-Wunused-parameter]
	/elektra/src/plugins/crypto/crypto.c:123:68: warning: unused parameter 'errorKey' [-Wunused-parameter]

**Comment by markus2330** [comment]
Thank you for the PR!

ELEKTRA_UNUSED should help, iirc it does not yield a warning if parameter used nevertheless.

**Comment by petermax2** [comment]
@markus2330 you are right! There are no warnings even if the parameter is used.

**Comment by petermax2** [comment]
I think I'm done =)

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
