### PR TITLE
intercept: generate configuration

### PR DESCRIPTION
**Pull request by tom-wa**
```
/preload/open/~\/.vimrc =~/.vimrc-other
/preload/open/~\/.vimrc/readonly = 1
/preload/open/~\/.vimrc/generate = /other/key
/preload/open/~\/.vimrc/generate/plugin = ini
```

@markus2330 should the generated configuration be written to ~/.vimrc-other or a temporary file ?

### CODE REVIEW

**Comment by markus2330** [comment]
You can also disallow such setups. Do you see a reason someone needs such a combination? If allowed, you should rather write to the specified file.

Btw. you can use O_TMPFILE to completely avoid any file in the filesystem. (if no file given, which will be the common case when someone uses `generate`)

**Comment by tom-wa** [comment]
O_TMPFILE doesn't seem like a good idea,
open(2)
```
              O_TMPFILE requires support by the underlying filesystem; only
              a subset of Linux filesystems provide that support. 
```

**Comment by markus2330** [comment]
Do you have any filesystem in use which does not support it? But you are right, it is not the most portable solution, but somewhat nice if you actually never need a file visible in the filesystem.

Btw. On the buildserver the kernel might be too old, its a 3.2.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
