### PR TITLE
Remove kdb vset

### PR DESCRIPTION
**Pull request by Piankero**
## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by Piankero** [comment]
I hope i caught all `vset` occurrences in the code correctly.

I am not sure concerning the asciinema-demo (https://github.com/ElektraInitiative/libelektra/pull/3255/commits/1df45a19ae8ea3bbb17f95e8cc158a5ba8351def). Did I fix that correctly @markus2330 ?

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
> I am not sure concerning the asciinema-demo (1df45a1). Did I fix that correctly @markus2330 ?

I do not know, can you try to play it? Can you also do #3207 (which should be a simple search and replace).

**Comment by Piankero** [comment]
> I do not know, can you try to play it?

Actually I am  not even sure what this asciicinema is about and how to start it.

> Can you also do #3207 (which should be a simple search and replace).

Sure

**Comment by markus2330** [comment]
https://asciinema.org/

actually, best would be if you could re-record it with the latest version of Elektra because then we would also get the new error messages.

In general it would also be good if you slow down in typing the commands so that it is easier to follow.

**Comment by markus2330** [comment]
Thank you very much!

**Pull request merged**
