### PR TITLE
tools: fix key description in gen-gpg-testkey

### LINKED ISSUE #2957: testshell_markdown_tutorial_crypto fails
On my laptop, which uses buster and has several gpg keys, testshell_markdown_tutorial_crypto fails. If the test is executed with `ctest -V -R testshell_markdown_tutorial_crypto` it opens a pinentry for my key, which obviously should not be like this as the test case should have its own key.

```
Test project /home/markus/Projekte/Elektra/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 220
    Start 220: testshell_markdown_tutorial_crypto

220: Test command: /home/markus/Projekte/Elektra/build/tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh "/home/markus/Projekte/Elektra/current/doc/tutorials/crypto.md"
220: Environment variables: 
220:  LD_LIBRARY_PATH=/home/markus/Projekte/Elektra/build/lib
220: Test timeout computed to be: 1500
220: Input: /home/markus/Projekte/Elektra/current/doc/tutorials/crypto.md
220: kdb mount test.ini user/tests ini
220: kdb set user/tests/password 1234
220: kdb file user/tests/password | xargs cat
220: kdb rm user/tests/password
220: kdb umount user/tests
220: kdb mount test.ini user/tests fcrypt "encrypt/key=$(kdb gen-gpg-testkey)" ini
220: kdb set user/tests/password 1234
220: 
220: ERROR - RET:
220: Return value “5” does not match “0”
220: 
220: kdb file user/tests/password | xargs cat
220: 
220: ERROR - RET:
220: Return value “123” does not match “0”
220: 
220: kdb rm user/tests/password
220: 
220: ERROR - RET:
220: Return value “11” does not match “0”
220: 
220: kdb umount user/tests
220: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey)" ini
220: kdb set user/tests/password 1234
220: 
220: ERROR - RET:
220: Return value “5” does not match “0”
220: 
220: kdb file user/tests/password | xargs cat
220: 
220: ERROR - RET:
220: Return value “123” does not match “0”
220: 
220: kdb rm user/tests/password
220: 
220: ERROR - RET:
220: Return value “11” does not match “0”
220: 
220: kdb umount user/tests
220: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey),encrypt/key=$(kdb gen-gpg-testkey)" ini
220: kdb set user/tests/password 1234
220: 
220: ERROR - RET:
220: Return value “5” does not match “0”
220: 
220: kdb file user/tests/password | xargs cat
220: 
220: ERROR - RET:
220: Return value “123” does not match “0”
220: 
220: kdb rm user/tests/password
220: 
220: ERROR - RET:
220: Return value “11” does not match “0”
220: 
220: kdb umount user/tests
220: kdb mount test.ini user/tests crypto_gcrypt "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
220: kdb setmeta user/tests/password crypto/encrypt 1
220: kdb set user/tests/password 1234
220: kdb set user/tests/unencrypted "I am not encrypted"
220: kdb file user/tests/password | xargs cat
220: kdb setmeta user/tests/password crypto/encrypt 0
220: kdb file user/tests/password | xargs cat
220: kdb rm user/tests/unencrypted
220: kdb rm user/tests/password
220: kdb umount user/tests
220: shell_recorder /tmp/tmp.SFkbumzoDP RESULTS: 31 test(s) done 9 error(s).
220: 
220: —— Protocol ————————————————————————————————————————————————————
220: CMD: kdb mount test.ini user/tests ini
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 0
220: STDOUT: Create a new key user/tests/password with string "1234"
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 0
220: STDOUT: password=1234
220: 
220: CMD: kdb rm user/tests/password
220: RET: 0
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: 
220: CMD: kdb mount test.ini user/tests fcrypt "encrypt/key=$(kdb gen-gpg-testkey)" ini
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 5
220: === FAILED return value does not match expected pattern 0
220: STDERR: Sorry, module fcrypt issued the error C01100:
220: Resource: Renaming file /tmp/test.ini.28619:1568523969.513222.tmpiKxwWb to /home/markus/.config/test.ini.28619:1568523969.513222.tmp failed. Reason: Invalid cross-device link
220: ERROR: C01100
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 123
220: === FAILED return value does not match expected pattern 0
220: STDERR: cat: /home/markus/.config/test.ini: Datei oder Verzeichnis nicht gefunden
220: 
220: CMD: kdb rm user/tests/password
220: RET: 11
220: === FAILED return value does not match expected pattern 0
220: STDERR: Did not find the key
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: 
220: CMD: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey)" ini
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 5
220: === FAILED return value does not match expected pattern 0
220: STDERR: Sorry, module fcrypt issued the error C01100:
220: Resource: Renaming file /tmp/test.ini.28833:1568523969.829088.tmpYQyRfB to /home/markus/.config/test.ini.28833:1568523969.829088.tmp failed. Reason: Invalid cross-device link
220: ERROR: C01100
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 123
220: === FAILED return value does not match expected pattern 0
220: STDERR: cat: /home/markus/.config/test.ini: Datei oder Verzeichnis nicht gefunden
220: 
220: CMD: kdb rm user/tests/password
220: RET: 11
220: === FAILED return value does not match expected pattern 0
220: STDERR: Did not find the key
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: 
220: CMD: kdb mount test.ini user/tests fcrypt "sign/key=$(kdb gen-gpg-testkey),encrypt/key=$(kdb gen-gpg-testkey)" ini
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 5
220: === FAILED return value does not match expected pattern 0
220: STDERR: Sorry, module fcrypt issued the error C01100:
220: Resource: Renaming file /tmp/test.ini.29064:1568523970.266048.tmp7T6B0X to /home/markus/.config/test.ini.29064:1568523970.266048.tmp failed. Reason: Invalid cross-device link
220: ERROR: C01100
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 123
220: === FAILED return value does not match expected pattern 0
220: STDERR: cat: /home/markus/.config/test.ini: Datei oder Verzeichnis nicht gefunden
220: 
220: CMD: kdb rm user/tests/password
220: RET: 11
220: === FAILED return value does not match expected pattern 0
220: STDERR: Did not find the key
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: 
220: CMD: kdb mount test.ini user/tests crypto_gcrypt "crypto/key=$(kdb gen-gpg-testkey)" base64 ini
220: RET: 0
220: 
220: CMD: kdb setmeta user/tests/password crypto/encrypt 1
220: RET: 0
220: 
220: CMD: kdb set user/tests/password 1234
220: RET: 0
220: STDOUT: Set string to "1234"
220: 
220: CMD: kdb set user/tests/unencrypted "I am not encrypted"
220: RET: 0
220: STDOUT: Create a new key user/tests/unencrypted with string "I am not encrypted"
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 0
220: STDOUT: unencrypted=I am not encrypted
220: #@META crypto/encrypt = 1
220: password=@BASE64IyFjcnlwdG8wMBEAAAAtetcvCr4QmzanFLTfM1CsHkl03scQOwm8ywpbowM7lqGFB3W3G37UCSmPr3ugIpq6
220: 
220: CMD: kdb setmeta user/tests/password crypto/encrypt 0
220: RET: 0
220: 
220: CMD: kdb file user/tests/password | xargs cat
220: RET: 0
220: STDOUT: unencrypted=I am not encrypted
220: #@META crypto/encrypt = 0
220: password=1234
220: 
220: CMD: kdb rm user/tests/unencrypted
220: RET: 0
220: 
220: CMD: kdb rm user/tests/password
220: RET: 0
220: 
220: CMD: kdb umount user/tests
220: RET: 0
220: ————————————————————————————————————————————————————————————————
1/1 Test #220: testshell_markdown_tutorial_crypto ...***Failed    4.10 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
kdbtests    =   4.10 sec*proc (1 test)
memleak     =   4.10 sec*proc (1 test)

Total Test time (real) =   4.11 sec

The following tests FAILED:
        220 - testshell_markdown_tutorial_crypto (Failed)
Errors while running CTest
```

### PR DESCRIPTION
**Pull request by petermax2**
The string 'gen-gpg-testkey' is being put into the key description to prevent mismatches with libelektra.org e-mail addresses. See #2957 for full discussion.

Fixes #2957 .

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by petermax2** [comment]
The build was successful but one `docker push` failed on the build server (something with build-eletra-web-base):

    error creating overlay mount to /home/_docker/overlay2/f410387d40a6c4ee68461c2f4c81d506cee69545b1514a935dc4d4e715c387ae/merged: device or resource busy

**Comment by petermax2** [comment]
The Cirrus CI / 🍎 Clang says: "agent not responding".

**Comment by petermax2** [comment]
@markus2330 do you want to repeat the failed / non-responding build steps?

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
yes, if you see some failure please always restart. It is easier than checking if there are some follow-up stages that might fail.

**Comment by petermax2** [comment]
Cirrus CI / Clang completed successfully after restart.

The Jenkins problem with "build-elektra-web-base" still remains. But I don't think that my chagnes cause the `docker push` to fail?!

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
I also do not think so. But I wonder if this is a PR specific problem that sometimes these `docker pull` fail. Let us try one more time :wink:

**Comment by markus2330** [comment]
Thank you, great job!

**Pull request merged**
