### PR TITLE
rest-frontend / rest-backend: improvements

### PR DESCRIPTION
**Pull request by Namoshek**
# Purpose

Fixes some issues described in #1151 and #1214.

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine

@markus2330 please review my pull request

### CODE REVIEW

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
jenkins build unstable please

**Comment by markus2330** [comment]
jenkins build fast please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
