### PR TITLE
fix OS X RPATH issues

### PR DESCRIPTION
**Pull request by omnidan**
this should fix `kdb` as well #270

### CODE REVIEW

**Comment by manuelm** [comment]
Will this retain RPATH information after `make install`?

**Comment by omnidan** [comment]
I tried running `make install` and it worked fine, even running `kdb` works now. Anything else I should try out?

**Comment by manuelm** [comment]
Run `otool -l <installed_kdb_bin>` and look for the LC_RPATH value

**Comment by omnidan** [comment]
Global installation does not have the `LC_RPATH` variable:

```
dan@galaxy ~> otool -l /usr/local/bin/kdb | grep LC_RPATH
dan@galaxy ~ [1]>
```

The local build has `libelektra/build/lib` as `LC_RPATH`

**Comment by manuelm** [comment]
:+1:

**Comment by omnidan** [comment]
@manuelm so it should be safe to merge? /cc @markus2330

**Comment by manuelm** [comment]
Yeah, looks fine for me. I wonder why this flag isn't enabled per default.

**Comment by markus2330** [comment]
Thanks for finding out and reviewing it.

**Pull request merged**
