### PR TITLE
news: irrelevant news

### PR DESCRIPTION
**Pull request by mpranj**
Ignore. Testing sporadic failures of `testkdb_allplugins `.

### CODE REVIEW

**Comment by mpranj** [comment]
Fail log, build 1:

- [Jenkins](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2216/1/pipeline): debian-stable-multiconf[buildType=Debug] failed - 163 - `testmod_zeromqsend` (Failed)
- [Travis](https://travis-ci.org/ElektraInitiative/libelektra/jobs/423048405): one build timed out

**Comment by mpranj** [comment]
Should be resolved, as mentioned by @ingwinlu in #160.

**Comment by ingwinlu** [comment]
sadly not. See #2220 for further discussion.

**Comment by mpranj** [comment]
Resolved via cdbccaa6cdfc16ae850872bef63496e36846397a. (Hopefully this time for real.)

**Pull request closed without merging**
