### PR TITLE
[FLOSS H3] mini: fix silent failure on meta-key insertion

### LINKED ISSUE #4582: [FLOSS] mini plugin fails silently on meta-set
As discussed in #4555
## Steps to Reproduce the Problem
```sh
$ sudo kdb mount mini.ini user:/tests/mini mini
# RET: 0
$ kdb meta-set user:/tests/mini/key value value
# RET: 0  
$ kdb meta-get user:/tests/mini/key value
Metakey not found
# RET: 2
```
## Expected Result

Should print an error on `kdb meta-set user:/tests/mini/key value value` and return a non 0 exit code

## Actual Result
`$ kdb meta-set user:/tests/mini/key value value` fails silently and `kdb meta-get user:/tests/mini/key value`  returns Metakey not found

## System Information
Operating System:
Arch Linux, Kernel 5.19.13-arch1-1

kdb and plugins version
```sh
# kdb --version
KDB_VERSION: 0.9.11
SO_VERSION: 5
```

## Relevant Source Code
While mini explicitly states in its documentation that it does not support metadata, it still doesn't have any warning if a user tries to set a meta key

https://github.com/ElektraInitiative/libelektra/blob/cf4b6f303432dbfdcb9cc222c84f41045962b211/src/plugins/mini/mini.c#L280

### PR DESCRIPTION
**Pull request by Bujuhu**
fixes #4582

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by flo91** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by Bujuhu** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Great work! :+1:

**Pull request merged**
