### PR TITLE
crypto: add shut-down logic in testmod_crypto

### LINKED ISSUE #2341: fcrypt / gpgme / crypto: test case fails
Fcrypt test cases failed on master:

```
122/131 MemCheck  #93: testmod_fcrypt ...................***Failed   29.99 sec

OK closing connection

Terminating gpg-agent returned with status “256”FCRYPT       TESTS

==================


/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/src/plugins/fcrypt/testmod_fcrypt.c:161: error in test_gpg: failed to install the GPG test key

/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/src/plugins/fcrypt/testmod_fcrypt.c:189: error in test_file_crypto_operations: kdb set failed

/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/src/plugins/fcrypt/testmod_fcrypt.c:190: error in test_file_crypto_operations: file content did not change during encryption

/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/src/plugins/fcrypt/testmod_fcrypt.c:193: error in test_file_crypto_operations: kdb get (pregetstorage) failed

/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/src/plugins/fcrypt/testmod_fcrypt.c:197: error in test_file_crypto_operations: kdb get (postgetstorage) failed

/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/src/plugins/fcrypt/testmod_fcrypt.c:198: error in test_file_crypto_operations: postgetstorage did not encrypt the file again

/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/src/plugins/fcrypt/testmod_fcrypt.c:233: error in test_file_signature_operations: kdb set failed

/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/src/plugins/fcrypt/testmod_fcrypt.c:234: error in test_file_signature_operations: file content did not change during encryption

/home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA/src/plugins/fcrypt/testmod_fcrypt.c:237: error in test_file_signature_operations: kdb get failed


fcrypt Results: 39 Tests done — 9 errors.
```

https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/master/361/pipeline

@petermax2 any idea?

### PR DESCRIPTION
**Pull request by petermax2**
Try to kill the gpg-agent if the shutdown of the agent should fail.
This is an attempt to resolve #2341 .

## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by petermax2** [comment]
Is there maybe a way of running the Debian builds under high server load?

**Comment by markus2330** [comment]
Simply produce load within your testcase setup (e.g. spawn up threads that do the kind of load you would like to have; or maybe a simple `system("command-producing load)`). This way there are no complications about starting the right things at the right time on the right nodes.

**Comment by mpranj** [comment]
If you use system() you could also add something like `stress-ng` to produce the desired load.

**Comment by petermax2** [comment]
Do you have any ideas which kind of "stress" might cause the `gpg-connect-agent` to not close properly?

**Comment by petermax2** [comment]
The fork test seemed to trigger it :tada: 

    INFO: killed gpg-agent because shutdown failed with status 256.

**Comment by petermax2** [comment]
@mpranj  could you please restart the debian-unstable-* builds on Jenkins? Maybe we can reproduce the error again.

**Comment by mpranj** [comment]
@petermax2 done. You can always push a trivial change to trigger the builds or ping me via mail for jenkins access.

**Comment by petermax2** [comment]
Valgrind reports a memory leak in `/bin/kill`. Do you think it's safe to suppress this error?

See [DynamicAnalysis.xml](https://build.libelektra.org/job/libelektra/job/PR-3404/6/artifact/artifacts/debian-unstable-full/DynamicAnalysis.xml).

**Comment by petermax2** [comment]
The broken link is not my fault.

    if test -s broken_links.txt; then
      printf >&2 'Broken Links:\n'
      printf >&2 '—————————————\n'
      cat >&2 broken_links.txt
      printf >&2 '—————————————\n'
      false
    fi
    Broken Links:
    —————————————
    doc/tutorials/notifications.md:411:0 http://www.hpl.hp.com/techreports/2006/HPL-2006-2.html
    —————————————

**Comment by petermax2** [comment]
@mpranj and @markus2330 please review my changes.

I think this PR is ready to merge.

**Pull request merged**
