### PR TITLE
Draw Plugins: Support Space Characters in Repository Path

### PR DESCRIPTION
**Pull request by sanssecours**
I think this should be ready to merge. I do have one question though. Is it expected behavior that the generated image look differently, even if I use Docker and execute the current version of the script from the `master` branch?

### CODE REVIEW

**Comment by markus2330** [comment]
I never tried to create the images with something else then with my computer. If your image looks better, we can use it.

**Comment by sanssecours** [comment]
>  If your image looks better, we can use it.

I do not think it looks better. On my system Graphviz just seems to place the nodes slightly different. The result is an image that is taller, but less wide:

comparison

. I do not think that is a problem, though. On the other hand, the PDF is [cropped on my machine](https://github.com/ElektraInitiative/libelektra/files/3529925/cropped.pdf). Using the command:

```sh
fdp -Tpdf "${OUTPUT}.flatten" -o "$SOURCE/doc/images/plugins.pdf"
```

instead of Ghostscript would [fix the problem](https://github.com/ElektraInitiative/libelektra/files/3529922/fixed.pdf). However, the comment:

```sh
# bad fonts
```

seems to suggest that there are problems with the generated PDF. For me the font does looks okay. Does the PDF output of `fdp` still look bad on your machine?

**Comment by markus2330** [comment]
Different fonts could explain the different result.

I like taller results more, as they better fit to https://www.libelektra.org/plugins/readme

**Comment by sanssecours** [comment]
> Different fonts could explain the different result.

I just checked. The font seems to be the same. 

Comparison

The only difference is probably that your machine (right image) uses [sub-pixel antialiasing](https://en.wikipedia.org/wiki/Subpixel_rendering), while mine does not (left image).

**Pull request merged**
