### PR TITLE
Gitattributes: renormalize

### PR DESCRIPTION
**Pull request by mpranj**

### CODE REVIEW

**Comment by kodebach** [comment]
jenkins build libelektra please

**Comment by kodebach** [comment]
@mpranj Is there a particular reason, why this is still a draft PR?

**Comment by mpranj** [comment]
> Is there a particular reason, why this is still a draft PR?

The only reason is that I could not get the builds to succeed.

**Comment by kodebach** [comment]
The last one that failed was broken link. That should be fixed now. All the other builds eventually succeeded by re-running them.

**Comment by mpranj** [comment]
Thank you so much for taking care of it! 🚀

**Pull request merged**
