### PR TITLE
Toml updates

### PR DESCRIPTION
**Pull request by bauhaus93**
## Contains small updates/fixes for the toml plugin:
- Additional test case for comments in front of table arrays
- Replacement of custom metakey finding function with one provided by Elektra
- Fixed README typo
- Disabled `null` plugin in `toml` plugin, `NULL` values are now written as `'@NULL'` to the toml file.
- The `type` metakey is now also set for numbers (float and integer) on reading.
- Added doc for types and numbers

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy.
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [x] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [x] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
Any reason why this is draft? It seems like a great improvement nice to have in master.

**Comment by markus2330** [comment]
Ahh, I see why draft, null keys do not work yet:

```
kdb set user/tests/storage/a
kdb get -d user/tests/storage/a
#> Sorry, module type issued the error C03200:
#> Validation Semantic: The type 'string' failed to match for 'user/tests/storage/a' with string ''
#> At: src/plugins/type/type.c:97
```

Could it be that the null key turns into a string but it should be a binary? In any case the type checker does not like how it is and fails.

@kodebach The error message for the type plugin is not ideal, it is unclear if it is an empty string or a null key. A special case for length == 0 in the error message would be helpful. (If I did not overlook something, it must be length == 0 as there is no other check for strings. I would say, however, a check for binary should also be present?)

@bauhaus93 Do you know about the `kdb test` utility? It tries to save various things to some given backend and reads it out again. The toml plugin currently does not pass these tests.

I also do not really understand how the types in the toml plugin are handled, e.g.:

```
kdb set user/tests/storage/a 123
kdb set user/tests/storage/b 123

kdb meta-set 'user/tests/storage/b' 'type' 'string'

kdb meta-set user/tests/storage/a type long 
kdb meta-get user/tests/storage/a type
#> Metakey not found
```

I would have expected long here. The file itself, however, is okay:

```toml
a = 123
b = "123"
```

Some part explaining this in the README.md would be helpful.

**Comment by kodebach** [comment]
> The error message for the type plugin is not ideal, [...]

Yes, the error message for strings is a bit confusing. Also, a separate message for binary keys with a type other than `any` might be a good idea.

**Comment by bauhaus93** [comment]
> Ahh, I see why draft, null keys do not work yet:
> 
> ```
> kdb set user/tests/storage/a
> kdb get -d user/tests/storage/a
> #> Sorry, module type issued the error C03200:
> #> Validation Semantic: The type 'string' failed to match for 'user/tests/storage/a' with string ''
> #> At: src/plugins/type/type.c:97
> ```
> 

Hmm, I think this issue should be solved already. Whats the content of the file after setting the key? Is the `base64` plugin enabled?
(Currently, on writing, it is assumed that any binary values (NULL or non-NULL) are already translated by the `base64` plugin into a string encoding.)

When I would execute this, I get the expected results:
```
#!/bin/sh

sudo kdb mount test.toml user/test/storage toml type

kdb set 'user/test/storage/a'
# > Create a new key user/test/a with null value
kdb get -d 'user/test/storage/a'
# > 

kdb rm -r user/test/storage
sudo kdb umount user/test/storage
```

> Could it be that the null key turns into a string but it should be a binary? In any case the type checker does not like how it is and fails.

Yeah, that may be correct - I already added checks on handling these special string sequences (NULL and base64 strings).
NULL string values get directly get translated by me into an empty binary value with `keySetBinary(key, NULL, 0)`, not setting any `type`.
Base64 encoded strings only don't get the `type` metakey set to `string`.

> @bauhaus93 Do you know about the kdb test utility? It tries to save various things to some given backend and reads it out again. The toml plugin currently does not pass these tests.

No not yet, I will check it out, thanks.

> I also do not really understand how the types in the toml plugin are handled, e.g.:

For your case with the `long` type: The plugin currently does only set the `type` metakeys for strings and booleans on reading, so I think that's why the metakey is missing. I can fix the plugin to also add types like `long` and `float`/`double` on reading.

In general, on writing, if a value has the `type` metakey, it will check if the metakey is a string or boolean. 
If it's a string, it writes the content in quotes.
If it's a boolean it will translate the supplied value into TOML's boolean.
If it's any other `type`, the value will be written as-is (I may need to add further checks for this case however, currently it is assumed that there only could be numbers at this point)

If the `type` metakey is missing, I added custom checks if the value matches a valid TOML number (float, binary/octal/decimal/hexadecimal integer) or a datetime.
If it does, the value is written as-is.
If not, the value is written in quotes.

I will edit the README to explain the type handling of the plugin.

**Comment by markus2330** [comment]
> Hmm, I think this issue should be solved already.

I'll try again once it is merged. Maybe I forgot to build the toml plugin and used the (old) installed toml plugin... (It was mounted correctly with base64+type).

> Currently, on writing, it is assumed that any binary values (NULL or non-NULL) are already translated by the base64 plugin into a string encoding.

Isn't it very easy to get rid of this assumption? Because at the moment the assumption unfortunately may not hold for default backend and import/export. Not relevant for this PR, though.

> No not yet, I will check it out, thanks.

Thank you. I think, however, that this PR can be merged without any further fixes as this PR is needed before I can start removing the null plugin. @mpranj what do you think about the status of this PR?

> For your case with the long type

:sparkling_heart: I was simply missing such a text in the readme.

**Review by mpranj — APPROVED** [review]
Thank you so much for the improvements. Great that you also updated the README with examples.

**Comment by markus2330** [comment]
Thank you for merging, will test again once the build server made the Debian packages.

**Pull request merged**
