### PR TITLE
Shell Recorder: Fix Test Issues of PR #1915

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request should fix the test issues of PR #1915 and therefore closes #1915.

# Checklist

- [x] I checked all commit messages.
- [x] I ran all tests locally and everything went fine.
- [x] The PR contains exactly the same release notes as PR #1915.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build gcc please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Thank you so much!

**Pull request merged**
