### PR TITLE
[FLOSS H2] scripts: fix overwriting PATH variable in Dockerfiles

### LINKED ISSUE #4035: reformat-all in docker image is missing shfmt
## Steps to Reproduce the Problem

Building image:
```sh
$ docker build -t buildelektra-debian-sid --build-arg JENKINS_USERID=$(id -u) --build-arg JENKINS_GROUPID=$(id -g) -f scripts/docker/debian/sid/Dockerfile scripts/docker/debian/sid/
```
```sh
[+] Building 2.0s (18/18) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                           0.0s
 => => transferring dockerfile: 38B                                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/debian:sid                                                                                                                                                  1.9s
 => [ 1/14] FROM docker.io/library/debian:sid@sha256:6de4ad8f3d3c5646d35ea796bd29cd270b4dcd9bd803b32de0a4781616aec7d8                                                                                          0.0s
 => CACHED [ 2/14] RUN apt-get update && apt-get -y install         antlr4         automake         autotools-dev         bison         build-essential         checkinstall         clang-12         clang-f  0.0s
 => CACHED [ 3/14] RUN ldconfig                                                                                                                                                                                0.0s
 => CACHED [ 4/14] RUN pip3 install wheel                                                                                                                                                                      0.0s
 => CACHED [ 5/14] RUN pip3 install cmake-format[yaml]==0.6.13                                                                                                                                                 0.0s
 => CACHED [ 6/14] RUN mkdir -p /opt/gtest     && cd /tmp     && curl -o gtest.tar.gz       -L https://github.com/google/googletest/archive/release-1.11.0.tar.gz     && tar -zxvf gtest.tar.gz --strip-compo  0.0s
 => CACHED [ 7/14] RUN npm install --global prettier@2.3.2                                                                                                                                                     0.0s
 => CACHED [ 8/14] RUN cd /tmp     && curl -o hyperfine.deb        -L https://github.com/sharkdp/hyperfine/releases/download/v1.5.0/hyperfine_1.5.0_amd64.deb     && dpkg -i hyperfine.deb     && rm hyperfin  0.0s
 => CACHED [ 9/14] RUN groupadd     -g 1000     -f     jenkins                                                                                                                                                 0.0s
 => CACHED [10/14] RUN useradd     --create-home     --uid 1000     --gid 1000     --shell "/bin/bash"     jenkins                                                                                             0.0s
 => CACHED [11/14] RUN cd /tmp && wget https://services.gradle.org/distributions/gradle-7.2-bin.zip && unzip gradle-7.2-bin.zip && rm gradle-7.2-bin.zip && mv gradle-7.2 /opt/gradle                          0.0s
 => CACHED [12/14] RUN echo "export PATH=/usr/lib/llvm-12/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/gradle/bin:/opt/gradle/bin" >> /home/jenkins/.bashrc                           0.0s
 => CACHED [13/14] RUN mkdir -p "/home/jenkins/bin"     && cd "/home/jenkins/bin"     && curl -L "https://github.com/mvdan/sh/releases/download/v3.3.1/shfmt_v3.3.1_linux_amd64" -o shfmt     && chmod a+x sh  0.0s
 => CACHED [14/14] RUN gem install --user-install ronn-ng -v 0.10.1.pre1 && ronn --version                                                                                                                     0.0s
 => exporting to image                                                                                                                                                                                         0.0s
 => => exporting layers                                                                                                                                                                                        0.0s
 => => writing image sha256:a712b830dd8d80c09c7aa805f53aabd6d0bc87bcd809f78102e7f0911d66cedc                                                                                                                   0.0s
 => => naming to docker.io/library/buildelektra-debian-sid                                                                                                                                                     0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```

Running container and issuing reformat-all in repo root directory:
```sh
$ docker run -it --rm -v "$PWD:/home/jenkins/workspace" -w /home/jenkins/workspace buildelektra-debian-sid
jenkins@6bdf913b594e:~/workspace$ scripts/dev/reformat-all
starting scripts/dev/reformat-c ...
starting scripts/dev/reformat-cmake ...
starting scripts/dev/reformat-java ...
starting scripts/dev/reformat-javascript ...
starting scripts/dev/reformat-markdown ...
starting scripts/dev/reformat-shell ...
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
shfmt:
Version:
Please install `shfmt` version 3
finished scripts/dev/reformat-shell
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
npm WARN exec The following package was not found and will be installed: prettier@2.3.2
npm WARN exec The following package was not found and will be installed: prettier@2.3.2
finished scripts/dev/reformat-java
finished scripts/dev/reformat-javascript
finished scripts/dev/reformat-c
finished scripts/dev/reformat-markdown
finished scripts/dev/reformat-cmake
jenkins@6bdf913b594e:~/workspace$
```

## Expected Result

`reformat-shell` should be run successfully

## Actual Result

`reformat-shell` is missing `shfmt`

## System Information

- Elektra Version: master
- Operating System: Ubuntu 20.04 LTS auf WSL2

### PR DESCRIPTION
**Pull request by sedadas**
As described in #4035, adding explicit lines to `.bashrc` may break the PATH of the container
and is rendered useless because of the `ENV` instruction, which preserves environment variables for all subsequent instructions:

https://docs.docker.com/engine/reference/builder/#env

Not only do we fix #4035, we also reduce the sizes of the images by removing a useless instruction

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by sedadas** [comment]
@markus2330 to avoid such issues in the future, a potential component in the CI could be something like [Terratest](https://terratest.gruntwork.io/), which allows us to test docker images after building them and potentially terminate the pipeline if something went wrong.

**Review by markus2330 — APPROVED** [review]
Very well spotted and excellent work :fireworks:

**Comment by markus2330** [comment]
> @markus2330 to avoid such issues in the future, a potential component in the CI could be something like Terratest, which allows us to test docker images after building them and potentially terminate the pipeline if something went wrong.

Yes, good idea if this test is not too time consuming. If it is, we could pack it in a nightly job, as it is not release critical if a broken docker file actually ends up in the repo.

**Review by flo91 — APPROVED** [review]
**[FLOSS H2]**
Thank you for the PR!
That looks like a great finding and improvement! :+1:
Currently two buildserver tests are still failing, but it looks like that's a general problem of the build system, because the same two checks also recently failed on many other PRs.

Otherwise, I couldn't find any issues with this PR. :100:

**Comment by markus2330** [comment]
Thank you for fixing this problem! :1st_place_medal:

**Pull request merged**
