### PR TITLE
Travis: Install Old Version of Qt on macOS

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

Since Qt 5.10.1 building the Qt-GUI with GCC on macOS fails, reporting the following error:

> 'init_priority' attribute is not supported on this platform

. This PR fixes this problem by excluding the Qt-GUI from the build process on the macOS/GCC Travis build job. 

# Checklist

- [x] I checked all commit messages.
- [x] I ran all tests and everything went fine.
- [x] This PR also adds a comment about the problem described above to `.travis.yml`.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build fast please

**Comment by sanssecours** [comment]
jenkins build fast please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build incremental please

**Comment by markus2330** [comment]
@0003088 Do you have an alternative to removing qtgui for Mac?

**Comment by 0003088** [comment]
Hrm, I have absolutely no experience with Apple. According to the message it seems to be some issue with macOSX itself (?) but I do not have hard- or software at hand to experiment in this matter. Sorry.

**Comment by sanssecours** [comment]
jenkins build gcc47-all please

**Comment by sanssecours** [comment]
jenkins build homepage please

**Comment by sanssecours** [comment]
jekins build gcc-configure-debian-wheezy please

**Comment by sanssecours** [comment]
jenkins build gcc-configure-debian-wheezy please

**Comment by markus2330** [comment]
Is it possible to pin to a version of Qt which did not have this problem? And hopefully they will soon upload a version with a fix.

**Comment by sanssecours** [comment]
> Is it possible to pin to a version of Qt which did not have this problem?

I guess so. I published a separate branch where Travis installs Qt 5.5 instead of Qt 5.10.1. If the [result of the update](https://travis-ci.org/sanssecours/elektra/builds/342274325) looks promising, I will integrate the changes into this PR.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
