### PR TITLE
Memleak Crypto Plugin

### LINKED ISSUE #932: Memleak Crypto Plugin
Seems like that the build jobs during PR did not check memleak at least for one debian version:
http://community.markus-raab.org:8080/job/elektra-incremental/lastFailedBuild/console

### PR DESCRIPTION
**Pull request by petermax2**
# Purpose

Fixes some mistakes detected by valgrind.
Updates the suppressions file.

Fixes #932 .

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by petermax2** [comment]
@markus2330 can the build server check the variant that failed in #932 ?

**Comment by petermax2** [comment]
Travis seems to have a problem:

    Error: cmake-3.0.2 already installed

occuring in the build job " Xcode: beta-xcode6.1".

**Comment by petermax2** [comment]
travis build please

**Comment by markus2330** [comment]
Thank you! Lets see if everything works now!

Yes, you should be able to trigger every build job, see doc/GIT.

**Pull request merged**
