### PR TITLE
[FLOSS H3] Shell recorder: Fix test creation and add check if file exists

### LINKED ISSUE #4702: Shell recorder tests never fail / not executing properly
While extending some tests i discoverey that the tests `tests/shell_recorder/*.esr` never seem to fail.

In selftest.esr the mountpoint is `user:/tests`, then a command is issued `kdb set $Mountpoint/key value` and the check is `STDOUT: Create a new key user:/test/key with string "value"`.  (Notice test**s** vs test) - But during `make run_all` the tests don't seem to fail, while when executing the shell_recorder test manually they fail as expected.

As my new tests don't increase the coverage, but executing the tests manually does increase the coverage, i suspect the tests don't even get executed properly.

## Steps to Reproduce the Problem
- `tests/shell/shell_recorder/shell_recorder.sh ../tests/shell/shell_recorder/selftest.esr`

```=== FAILED stdout does not match expected pattern Create a new key user:/test/key with string "value"```

but
- `make run_all`
```...
Start 153: testshell_selftest
204/212 Test #153: testshell_selftest ...........................   Passed    0.25 sec
```

No matter how hard i try to make the tests fail during `make run_all` they always pass. But changing for example `plugins/hexnumber/README.md` to something that should fail makes them fail (as expected).

So this seems to be a problem with the files in ` tests/shell_recorder/` only.

## Expected Result
Tests should fail as they do on manual execution.

## Actual Result
Tests never fail - even if they do on manual execution

## System Information

- Elektra: master (4283744cc4689792a8143d55f5f49e6dc1eac81c)
- Operating System: Ubuntu 22.04

Sadly this is actually blocking me for [FLOSS T1].

### PR DESCRIPTION
**Pull request by 0x6178656c**
This is the cause for the behavior observed in #4702.

Before shellrecorder did not check if the file exists and exited with `0` when the file did not exist. Now a check is implemented and the exit code is `1` if no file is found.

**Update**: I fixed the creation of tests in the CMake file.

Closes #4702

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Review by joni1993 — APPROVED** [review]
**Documentation is introductory, concise, good to read and describes everything what the PR does**
Docs are good!
**Examples are well chosen and understandable**
N/A
**Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)**
Yes.
**APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)**
N/A
Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
N/A

**Comment by markus2330** [comment]
Great job! :heart: 

Please fix or disable the failing test (testshell_mathcheck) so that we can merge this!

**Comment by 0x6178656c** [comment]
> Please fix or disable the failing test (testshell_mathcheck) so that we can merge this!

Hmm, the test only seems to be failing on "debian-bullseye-full-xdg". Can you think of a reason why this might be the case? For instance in "debian-bullseye-full" the test is passing.

Is it possible to disable the test only for a specific build?

The log says

```
CMD: kdb mount mathcheck.esr user:/tests/mathcheck mathcheck ni

RET: 7

STDERR: The command /home/jenkins/workspace/libelektra_PR-4709/build directory/bin/kdb mount terminated unsuccessfully with the info:

No plugin that provides ni could be found
```

So the actual problem seems to be the missing ni plugin?

**Comment by flo91** [comment]
jenkins build libelektra please

**Comment by flo91** [comment]
jenkins build libelektra please

**Comment by 0x6178656c** [comment]
> Hmm, the test only seems to be failing on "debian-bullseye-full-xdg". Can you think of a reason why this might be the case? For instance in "debian-bullseye-full" the test is passing.

I noticed that the XDG build has only a subset of plugins:

https://github.com/ElektraInitiative/libelektra/blob/90f70811c51a76e758f671f373cace2b98b412ed/scripts/jenkins/Jenkinsfile#L695

I added `ni` as plugin dependency for the math test. Let's see if this resolves the issue.

**Comment by flo91** [comment]
Great work, thank you! 🎉

**Pull request merged**
