### PR TITLE
Documentation: Update Restrictions of Yan LR

### PR DESCRIPTION
**Pull request by sanssecours**

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for improving the docu! Is now Yan LR or yamlcpp the recommended yaml parser?

**Comment by sanssecours** [comment]
> Is now Yan LR or yamlcpp the recommended yaml parser?

For now it is certainly YAML CPP. I do have to improve both plugins for them to be ready for general use though.

**Comment by markus2330** [comment]
Thanks for the info! Do you plan to add the support for comments?

**Comment by sanssecours** [comment]
> Do you plan to add the support for comments?

I might. However, since I am doing this work for free, there is obviously no guarantee that I will do it.

**Comment by markus2330** [comment]
Thank you for working on it! There is also no absolute guarantee if you pay someone for it.

**Comment by markus2330** [comment]
Thank you!

**Comment by markus2330** [comment]
Btw. it looks like your previous change worked, now several master builds appear to be running.

**Pull request merged**
