### PR TITLE
[FLOSS H3] jna: whitelist plugin: add validation check on get

### LINKED ISSUE #4001: [FLOSS] Enable validation on read [Java example whitelist plugin]
The Java example plugin `whitelist` should also validate values on `get` instead on `set` only. Validation errors should result in warnings.

See also: https://github.com/ElektraInitiative/libelektra/pull/3889#discussion_r689116331

### PR DESCRIPTION
**Pull request by Bujuhu**
Fixes #4001

Add new validation warnings on get. This is useful, as keys could be changed on disk, causing them to be stored in an invalid state.

I haven't added tests for this functionality, as I don't know how I could bypass the validation during set, such that I could even test this automatically.

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by deoknats861** [comment]
### Review

**CI status**
The CI is currently failing due to a valgrind memcheck test.  As this failure is related to `testcpp_contextual_thread`, it's unlikely that this problem is related to the changes made in this PR.

**Documentation** 
Documentation was added to the notes of the next release. It describes everything that was done in this PR clearly.

**Examples are well chosen and understandable**
There are currently no tests added for this PR. 

**Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)**
The code is consistent with the guidelines. 

**APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)**
No APIs changes were made.

**Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)**
The code is consistent with the guidelines.

**Comment by flo91** [comment]
jenkins build libelektra please

**Comment by flo91** [comment]
jenkins build libelektra please

**Comment by Bujuhu** [comment]
jenkins build libelektra please

**Comment by flo91** [comment]
jenkins build libelektra please

**Pull request merged**
