### PR TITLE
crypto: fix OpenSSL compile errors for Debian Stretch

### PR DESCRIPTION
**Pull request by petermax2**
# Purpose

crypto: fix OpenSSL compile errors for Debian Stretch

See #1437 for full discussion.

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build gcc-configure-debian-stretch please

**Comment by markus2330** [comment]
Thanks for the fix!

Are all the casts really like the API is designed to be?

What is missing in the PR? (Why is it work in progress)?

Unstable built already, so it looks okay.

**Comment by petermax2** [comment]
jenkins build gcc-configure-debian-stretch please

**Comment by petermax2** [comment]
> Are all the casts really like the API is designed to be?

I followed the examples from the OpenSSL wiki [1]https://wiki.openssl.org/index.php/EVP_Symmetric_Encryption_and_Decryption#Encrypting_the_message).

> What is missing in the PR? (Why is it work in progress)?

I was just waiting for the build server results.

Everything looks good now.

**Comment by markus2330** [comment]
Thank you for the quick fix! Great job!

**Pull request merged**
