### PR TITLE
Add Vagrantfile for ubuntu artful 32-bit

### PR DESCRIPTION
**Pull request by mpranj**
Vagrantfile for debugging #1973.

Build image inside `cripts/vagrant/ubuntu/artful32/`:
```
vagrant up
vagrant ssh
```

Steps to reproduce errors:
```
mkdir /vagrant/build
cd /vagrant/build

export INSTALL_DIR="$PWD/install"
export SYSTEM_DIR="$PWD/kdbsystem"
export PATH=$PATH:"$PWD/bin"
export LD_LIBRARY_PATH="$PWD/lib"
export GTEST_ROOT="/opt/gtest"

cmake -DENABLE_COVERAGE=OFF -DENABLE_OPTIMIZATIONS=OFF -DENABLE_DEBUG=ON -DENABLE_LOGGER=ON -DBUILD_STATIC=OFF -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DKDB_DB_SYSTEM="$SYSTEM_DIR" -DINSTALL_SYSTEM_FILES=OFF -DPLUGINS="ALL" -DTOOLS="ALL" ..

make -j4
make run_all
```

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the PR! It is always good to have more reproducibility.

Can you please place everything below scripts/vagrant? e.g. scripts/vagrant/artful32 is okay.

**Comment by mpranj** [comment]
@markus2330 sure. It was never intended to be merged. If you want to merge it, I will place it nicely. I just did not want to move the other Vagrantfile around.

**Comment by markus2330** [comment]
Yes, if the file is used by someone I think it would be useful to have it in the repo. It is not that big and its easier if files are in master and not somewhere hidden in PRs.

In docker we also named the subdirectories with distribution/codename. Maybe we create the same structure for Vagrant?

**Comment by mpranj** [comment]
I was a bit too hasty there. It should be ready now.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
