### PR TITLE
Fix Path to Qt on Travis/Use Namespace `ckdb` in `kdberrors.h`

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This PR improves

  - the detection of Qt on macOS, and
  - the usability of `kdberrors.h` inside C++ code

.

# Checklist

- [x] I checked all commit messages.
- [x] The PR also contains updates for the release notes.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Build started sha1 is merged.

**Comment by sanssecours** [comment]
jenkins build homepage please

**Comment by sanssecours** [comment]
jenkins build incremental please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build gcc47-all please

**Comment by sanssecours** [comment]
jenkins build source-package-test please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc47-cmake-options please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build source-package-test please

**Comment by sanssecours** [comment]
jenkins build incremental please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Build finished. No test results found.

**Comment by sanssecours** [comment]
jenkins build ini please

**Comment by sanssecours** [comment]
jenkins build homepage please

**Pull request closed without merging**
