### PR TITLE
[FLOSS T1] csvstorage: missing parent keys

### LINKED ISSUE #2304: kdb export csvstorage no output if parentKeys are missing
## Steps to Reproduce the Problem

```sh
kdb set /tests/csv/a1/a a1
kdb set /tests/csv/a2/a a2
kdb set /tests/csv/a3/a a3

kdb export /tests/csv csvstorage -c export=,export/a= 
```

## Expected Result

```sh
kdb export /tests/csv csvstorage -c export=,export/a= 
#> a1
#> a2
#> a3
```

## Actual Result

No output

## Workaround

Create parentKeys:
```sh
kdb set /tests/csv/a1 a1
kdb set /tests/csv/a2 a2
kdb set /tests/csv/a3 a3
```

## Implementation Hint

Create a plugin that automatically adds all parentKeys for convenience. This then can be added for kdb export and to make it easier for applications to iterate over keys.

## System Information

- Elektra Version: master

### PR DESCRIPTION
**Pull request by muskater**
## Basics

This will fix #2304 . At the moment we only have the markdown shell recorder test case working and are open for  suggestion on how to fix the problem.

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

## ToDo 

- fix release notes

## FLOSS
- We used the libelektra issue tracker and found this stale issue (#2304). We thought this would be a good fit since we already had planed to fix a bug in the csvstorgae plugin. 
- The tests run on Jenkins as well as the Mac OS X / FreeBSD Cirrus CI
- We all worked together on integrating the test case into the README file. We also discussed the issue and possible causes in length.

### CODE REVIEW

**Comment by muskater** [comment]
We have now converted the test cases into the Markdown variant

**Comment by lawli3t** [comment]
We discussed how to fix this issue and are unsure. Is there any heuristic of determining whether a Key that gets set needs a parent Key?
Should we check for each set call whether the current Key name minus the base name exists and if it doesn't set it with an array meta Key?

**Comment by markus2330** [comment]
> Is there any heuristic of determining whether a Key that gets set needs a parent Key?

If any keys of an array is returned, the parent key (with the metadata array) must be returned, too.

**Comment by markus2330** [comment]
Is there still a question open? Please readd "help wanted" if the question is not resolved yet.

**Comment by markus2330** [comment]
There are still failing tests and there are conflicting files (please rebase).

**Comment by markus2330** [comment]
What is the state of this PR?

**Comment by muskater** [comment]
Unfortunately, we were not able to finish this PR.

**Pull request closed without merging**
