### PR TITLE
Metadata linecont

### PR DESCRIPTION
**Pull request by tom-wa**
# Purpose

consistent line continuation / multiline values in `METADATA.ini` and `CONTRACT.ini`
use "  " as line continuation string in `mount-info`

### CODE REVIEW

**Comment by markus2330** [comment]
Thanks!

Is this ready to merge? What is the default linecontinuation? Would be nice if we internally use formats that work with default options.

**Comment by tom-wa** [comment]
ini defaults to `\t` because it's the hardest to add as a command line option. want me to change both CONTRACT.ini and METADATA.ini to tabs ?

**Comment by markus2330** [comment]
Yes, please use tabs.

**Comment by markus2330** [comment]
Please remove space after `kdb mount` and set ready to merge if ready to merge.

**Comment by markus2330** [comment]
Merci!

**Pull request merged**
