### PR TITLE
build: use Debian Bullseye to build the documentation (closes #4455)

### LINKED ISSUE #4455: latest latex version fails to produce pdf
@lukashartl is it possible that we lack some Doxygen/LaTeX dependency?

Build for master and all PRs where I tried, e.g. #4440 #4448, fail but I cannot reproduce it locally: the pdf (2378 pages) builds successfully.

I tried to disable l1 and restarted a job but it doesn't seem to be specific to l1.

### PR DESCRIPTION
**Pull request by atmaxinger**
Build the documentation with Debian Bullseye instead of Sid. This fixes #4455.

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [x] make all unit tests pass
  - [x] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [x] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [x] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [x] Documentation is introductory, concise, good to read and describes everything what the PR does
- [x] Examples are well chosen and understandable
- [x] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [x] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [x] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [x] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [x] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by atmaxinger** [comment]
jenkins build libelektra please

**Review by markus2330 — APPROVED** [review]
Great job! Build server does not pass yet?

**Comment by atmaxinger** [comment]
@markus2330 yes, because Debian unstable seems to have a new version of GCC that outputs an additional warning as error in the csvmerge plugin.

```
`/home/jenkins/workspace/libelektra_PR-4456@2/src/plugins/csvstorage/csvstorage.c: In function ‘createHeaders’:

/home/jenkins/workspace/libelektra_PR-4456@2/src/plugins/csvstorage/csvstorage.c:283:30: error: the comparison will always evaluate as ‘true’ for the pointer operand in ‘colNames + (sizetype)((long unsigned int)colCounter * 8)’ must not be NULL [-Werror=address]

  283 |                 if (colNames && (colNames + colCounter))

      |                              ^~

/home/jenkins/workspace/libelektra_PR-4456@2/src/plugins/csvstorage/csvstorage.c: In function ‘readHeaders’:

/home/jenkins/workspace/libelektra_PR-4456@2/src/plugins/csvstorage/csvstorage.c:315:30: error: the comparison will always evaluate as ‘true’ for the pointer operand in ‘colNames + (sizetype)((long unsigned int)colCounter * 8)’ must not be NULL [-Werror=address]

  315 |                 if (colNames && (colNames + colCounter))

      |                              ^~
```

**Comment by markus2330** [comment]
I think @lawli3t fixed this problem in #4341? @lawli3t can you create a PR only containing the csvstorage plugin please?

**Pull request merged**
