### PR TITLE
Use new MountBackendBuilder Interface when mounting backends

### PR DESCRIPTION
**Pull request by 0003088**
* Add feature to remove already added plugins
* Add feature to auto-add recommended plugins
* Plugins can be removed from the list or from a button next to the plugin-dropdown.

How about the new icons? Should I change them myself? I suggest you merge #753 before this one?

### CODE REVIEW

**Comment by 0003088** [comment]
btw, do you have an astyle template or something for correct formatting?

**Comment by mpranj** [comment]
Yes, clang-format. The configuration is in the project root. Watch out for qml I'm not sure how it's handled.

**Comment by markus2330** [comment]
@sirblackheart Can you review and try it please?

**Comment by sirblackheart** [comment]
This looks good to me and this definitely a useful addition to the backend mount dialog.

@0003088  A short tough regarding backend mounting in the gui. What do you think about to either hide it when the `Elektra Qt Editor` is started in user mode or request elevated rights for the mounting?

**Comment by markus2330** [comment]
Thank you for testing it!

The disable-mounting-when-not-available discussion is exactly the same as the "isWritable" discussion, we should do it in a different issue.

**Pull request merged**
