### PR TITLE
Elektra: Core: KeySet: fix warning when ENABLE_OPTIMIZATIONS=OFF

### LINKED ISSUE #1812: Add -Werror to all Build Jobs
```
/home/markus/Projekte/Elektra/current/src/libs/elektra/keyset.c: In function ‘elektraOpmphmInvalidate’:
/home/markus/Projekte/Elektra/current/src/libs/elektra/keyset.c:48:47: warning: unused parameter ‘ks’ [-Wunused-parameter]
 static void elektraOpmphmInvalidate (KeySet * ks)
                                               ^~
/home/markus/Projekte/Elektra/current/src/libs/elektra/keyset.c: In function ‘elektraOpmphmCopy’:
/home/markus/Projekte/Elektra/current/src/libs/elektra/keyset.c:65:41: warning: unused parameter ‘dest’ [-Wunused-parameter]
 static void elektraOpmphmCopy (KeySet * dest, const KeySet * source)
                                         ^~~~
/home/markus/Projekte/Elektra/current/src/libs/elektra/keyset.c:65:62: warning: unused parameter ‘source’ [-Wunused-parameter]
 static void elektraOpmphmCopy (KeySet * dest, const KeySet * source)
                                                              ^~~~~~
```

### PR DESCRIPTION
**Pull request by KurtMi**
fix #1812 

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [ ] I added unit tests
- [ ] I ran all tests and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by KurtMi** [comment]
mergerequest-fast fail due to `typechecker`

**Comment by markus2330** [comment]
jenkins build fast please

**Comment by markus2330** [comment]
@e1528532 any idea why fast failed?

**Comment by e1528532** [comment]
@markus2330 That error seems to exist since i first tested the PR. I think its because it "cached" the typechecker plugin entry and expects it to be there as the fast build is incremental as far as i know. However, since the plugin doesn't exist in this PR it then fails. The strange thing is that in theory every new plugin should have caused this behavior in theory.
A quick solution seems to be clearing the workspace, or waiting for the other PR to be merged (which hopefully happens soon since the debian branch got merged finally)

**Comment by markus2330** [comment]
I have cleaned up the workspace, let us see if this helps.

@e1528532 Good idea, let us merge this PR soon. Fast is rebuild after every change in your PR...

**Comment by markus2330** [comment]
jenkins build fast please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
