### PR TITLE
[FLOSS H2] CMake fix developer warning for package DISCOUNT

### PR DESCRIPTION
**Pull request by deoknats861**
## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by Bujuhu** [comment]
## Review


### Documentation is introductory, concise, good to read and describes everything what the PR does
    Documentation is concise and adheres to the syntax except for the last commit message, which does not describe the changes done to the release not well. You could fix this by just squashing the commits, using the CLI by 
```sh
git reset --soft HEAD~3
git commit -m "CMAKE: Fix developer warning for package DISCOUNT

close #4589"
git push --force
```
or using [GitHub Desktop](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits).

Or just leave it as it is. I don't think much value is lost, if a commit that does essentially nothing doesn't have an expressive commit message.

### Examples are well-chosen and understandable
N/A

### Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
N/A

### APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
N/A

### Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)
N/A

The PR just changes a CMake dependency from lowercase to uppercase. So no semantics is involved, and design guideline checks are not really applicable. As no new code was introduced, but rather a fix was applied no new tests or examples were provided, so nothing to check here either.

**Review by joni1993 — APPROVED** [review]

**Comment by deoknats861** [comment]
jenkins build libelektra please

**Comment by deoknats861** [comment]
Hi!
I am not able to retrace the jenkins error which is displayed here in the PR checks section. When I look at the details of the check, every stage seems to be green. Nevertheless, the outcome fails.
Am I missing here something?

**Comment by markus2330** [comment]
You need to press "Tests" in the top bar to see the problem. It is probably a spurious problem in concurrent runs of kdb. I reported it in https://github.com/ElektraInitiative/libelektra/issues/4642. Simply restart Jenkin's CI to fix it (by saying "jenking build libelektra please" here in a comment).

**Comment by Bujuhu** [comment]
jenkins build libelektra please

**Comment by deoknats861** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Great job! :revolving_hearts: 

The change afterwards sometimes looks more simple than it actually was...

**Pull request merged**
