### PR TITLE
[FLOSS H2] documentation: Unify spelling of documentation

### PR DESCRIPTION
**Pull request by joni1993**
## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the PR! There are also other occurrences of docu. Ideally you could even add common misspelling to scripts/sed. (docu is also used in CSS but the replacement shouldn't harm if you also replace it in the html).

**Review by 0x6178656c — CHANGES_REQUESTED** [review]
[FLOSS H2 REVIEW]

Great idea making this consistent.

I also found:

https://github.com/joni1993/libelektra/blob/e718d4a1da247d2ed04b10a5f542edcda23a943f/src/tools/kdb/shell.hpp#L48

**Comment by 0x6178656c** [comment]
> Thank you for the PR! There are also other occurrences of docu. Ideally you could even add common misspelling to scripts/sed. (docu is also used in CSS but the replacement shouldn't harm if you also replace it in the html).

Is there a policy on making changes to news / changelogs? (In this case the changes are somewhat trivial, but still they might be considered historical artifacts.)

**Comment by markus2330** [comment]
> Is there a policy on making changes to news / changelogs?

Yes, there is a policy to always add them. Duplicates are removed later, so do not worry about that. If something is unclear, please do not hesitate to open an issue.

**Comment by 0x6178656c** [comment]
HEAD is at e718d4a1da247d2ed04b10a5f542edcda23a943f

```sh
$ git ls-tree --name-only -r -z HEAD | xargs -0 grep -li "\bdocu\b"
```

returns the list

```txt
.github/PULL_REQUEST_TEMPLATE.md
doc/API.md
doc/api_review/core/keyCopy.md
doc/news/2015-07-13_0.8.12.md
doc/news/2015-11-19_0.8.14.md
doc/news/2016-11-22_0.8.19.md
doc/news/2018-05-13_0.8.23.md
doc/todo/API
doc/todo/PLUGINS
doc/todo/TOOLS
scripts/packaging/debian/changelog
src/libs/tools/src/specreader.cpp
src/tools/kdb/shell.hpp
src/tools/website/public/pages/main/website/listfiles.html
src/tools/website/public/pages/main/website/news.html
src/tools/website/resources/assets/skin/base/theme.less
src/tools/website/resources/structure.json.in
tests/shell/check_doc.sh
```

The following replacements would cover all cases

```
docu -> documentation
Docu -> Documentation
DOCU -> DOCUMENTATION
```

Not sure if all of them are harmless.

**Comment by flo91** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Great job!

**Pull request merged**
