### PR TITLE
Ruby Libtool bindings

### PR DESCRIPTION
**Pull request by BernhardDenner**
# Purpose

Ruby bindings for libtools, extends existing bindings (same src tree, same build but different Ruby module)

# Checklist

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [x] I added unit tests
- [x] affected documentation is fixed
- [x] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 final version

### CODE REVIEW

**Comment by markus2330** [comment]
Thanks for sharing!

I am looking forward to suggestions how we can improve the libtools API. Please do not create workarounds in the ruby bindings if we can fix them better in the API.

**Comment by markus2330** [comment]
Looks great! Seems like a lot of functionality works now!

**Comment by BernhardDenner** [comment]
Travis build is failing, due to failing JNA bindings tests. I've no idea why this is happening. But Ruby bindings build and tests are fine.

**Comment by markus2330** [comment]
Maybe maven is missing? @e1528532 can you take a look?

**Comment by e1528532** [comment]
I've already opened an issue about it #1353 i'll look at it tomorrow.

**Comment by BernhardDenner** [comment]
Ohhh, I've missed to add SpecReader ;)

**Comment by BernhardDenner** [comment]
I've finished these bindings already. Works pretty good here.
I've done a rebase now, if the build on travis is ok, we can merge the PR

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build stable please

**Comment by markus2330** [comment]
jenkins build unstable please

**Comment by markus2330** [comment]
add to whitelist

**Comment by markus2330** [comment]
jenkins build bindings please

**Comment by markus2330** [comment]
@BernhardDenner Thank you! Looks good!

Let us see what the build server says.

**Comment by markus2330** [comment]
Please add ready to merge if they all build and test successfully.

**Comment by BernhardDenner** [comment]
all builds succeeded, except the "elektra-gcc-configure-mingw-w64" build. However, I don't think this is due to my bindings, since this build also fails for others too. Seems to be an linker error for opmphm.c not finding the sym 'rand_r'.
So from my point of view this PR is ready to merge ;)

**Comment by markus2330** [comment]
I was thinking about another review with focus on how to improve the libtools API.

Was there a special reason you needed a quick merge? Please state that in future.

**Pull request merged**
