### PR TITLE
Merge: Fix libgit markers

### PR DESCRIPTION
**Pull request by Chemin1**
This PR is based on commit f09f302 from #3106 and (ignoring some stuff that came in from rebasing) adds a fix for LibGit2 and a cleanup (=> only the last two commits are relevant). I plan to rebase and merge it after #3106 is merged. Alternatively, I could also merge it into #3106 now as its checks are not successful anyway atm.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating this PR!

**Comment by Chemin1** [comment]
jenkins build libelektra please

**Comment by Chemin1** [comment]
jenkins build libelektra please

**Comment by Chemin1** [comment]
Merged into #3209

**Pull request closed without merging**
