### PR TITLE
Stricter cleanup of docker images on docker nodes

### PR DESCRIPTION
**Pull request by ingwinlu**
## Basics

Do not describe the purpose here but:

- [ ] Short descriptions should be in the release notes (added as entry in
      doc/news/_preparation_next_release.md which contains `*(my name)*`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

@markus2330 please review my pull request

### CODE REVIEW

**Comment by ingwinlu** [comment]
jenkins build libelektra please

**Comment by ingwinlu** [comment]
any idea why the ini crash test failed?

**Comment by e1528532** [comment]
have you tried building it again? in my experience there are some very rare race conditions in our tests.

**Comment by ingwinlu** [comment]
Multiple times now. Still the same result.

**Comment by sanssecours** [comment]
> Multiple times now. Still the same result.

Seems you have found a new kind of “transient permanent” error 🙃. Anyway, as pull request #2206 shows, the failure of `testshell_markdown_ini_crash_test` should have nothing to do with the content of this pull request.

**Pull request closed without merging**
