### PR TITLE
YAML CPP: Do Not Add Intermediate Keys 

### PR DESCRIPTION
**Pull request by sanssecours**
# Checklist

- [x] I ran all tests locally and everything went fine
- [x] The PR contains updated documentation

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build elektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
> Ideally we should have guidelines for how parsers should interpret configuration files.

I **might** add documentation about this in a separate PR.

**Comment by markus2330** [comment]
You can also document it in your thesis and we transfer it afterwards. But we need guidelines, the inconsistencies between storage plugins is bothering everyone.

**Comment by markus2330** [comment]
Thank you, great job! It would also be interesting how intermediate keys are represented (if they are stored on purpose, e.g. with empty values).

**Comment by sanssecours** [comment]
> It would also be interesting how intermediate keys are represented (if they are stored on purpose, e.g. with empty values).

This does not work in the moment. Currently I try to fix this problem in the [Directory Value](https://www.libelektra.org/plugins/directoryvalue) plugin, which does not support empty or null keys properly yet.

**Pull request merged**
