### PR TITLE
build: Rewrite Jenkinsfile.daily

### LINKED ISSUE #1916: Jenkinsfile.daily - properties
The current implementation has several problems:
* properties: a initial run is needed for picking them up
* not testable in PR's: you can not specificly run it as part of an pr

So I will create a pr and remove the properties settings from Jenkinsfiles and let them stay in the build server configuration.

### PR DESCRIPTION
**Pull request by ingwinlu**
* Remove pipelineTriggers
* Keep stages better seperated
* Split up into more functions
* Add 'Stage2' of #1908

Resolves #1916 

### post merge checklist
- [ ] Setup triggers in job

### CODE REVIEW

**Comment by ingwinlu** [comment]
[Full Testrun](https://build.libelektra.org/jenkins/blue/organizations/jenkins/pipeline-playground/detail/pipeline-playground/83/pipeline/237)

**Comment by markus2330** [comment]
Thank you for the improvements!

Is Jenkinsfile.daily still the correct name? It seems like it does not execute daily anymore?

**Comment by ingwinlu** [comment]
@markus2330 what makes you think that?
I just moved the trigger configuration out of the file into the jenkins build job due to #1916. It is a chicken - egg problem unfortunately.

**Comment by markus2330** [comment]
> what makes you think that? 

I thought so because of the removal of the cron line. For example, you could always update the reference repos (on every build).

> I just moved the trigger configuration out of the file into the jenkins build job due to #1916.

Thanks for the clarification!

**Pull request merged**
