### PR TITLE
rest-backend: add conversion tests + fix issues

### PR DESCRIPTION
**Pull request by Namoshek**
# Purpose

This PR adds some tests for the conversion (they only run if the required plugins are available). It does also fix the import / conversion issue mentioned in #1151.

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [x] I added unit tests
- [x] I added code comments, logging, and assertions
- [ ] affected documentation is fixed
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Thanks for adding the tests, they are great!

But I do not think that overloading `addSubkeys` with quite different behaviour is a good idea! Better you pick different names if you really need both of these behaviors. Are you sure the initial implementation of `addSubkeys` is correct (in the case of having subkeys in different namespaces)?

**Comment by Namoshek** [comment]
> if you really need both of these behaviors

I don't really *need* the behavior of the other (old) implementation, but it makes a huge difference when it comes to bootstrapping the cache. The very initial implementation was like
```
for (auto elem : ks)
{
    if (elem.isEntryRoot()) // actually done by regex, but for sake of simplicity...
    {
        model::Entry entry (elem);
        entry.addSubkeys (ks);
        // and add to list of entries here
    }
}
```
Obviously it is completely unnecesary to try adding every single key of the keyset as subkey because it is ordered; so the moment you leave the area where a key **can** be a subkey, you can quit. That's what the other implementation does.

But I agree, somehow this should be improved by taking the logic from the model to the service implementing the cache. This will also make it easier to swap it for the cachefilter implementation. I'll do so later, so keep the PR open pls.

**Comment by Namoshek** [comment]
I removed the obsolete iterator-based `addSubkeys` method and added an optional flag to the `addSubkey` function, because the subkey comparison might be too expensive to do it twice for every key (inavoidable in some places otherwise).

**Comment by markus2330** [comment]
Thank you, nice job!

Maybe you can come up with a better name than "secure" for this optimization flag and I am also interested in the benchmarks that show that this optimization actually is measureable.

**Comment by Namoshek** [comment]
It is only measurable implicitely by using the cache (pre-load vs. live-load). Not sure how much of a difference it actually makes, but I guess true/false comparison is much cheaper than `key.isBelow(otherkey)`, so it should give an advantage here and there.

**Comment by markus2330** [comment]
Of course there is a difference, the question is if it matters (is it measurable at all, is it 0.001%?). It definitely makes the API more difficult to use and obscures the responsibilities.

**Pull request merged**
