### PR TITLE
Kdb mount error message fix

### PR DESCRIPTION
**Pull request by Piankero**
## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by Piankero** [comment]
The bug was introduced with https://github.com/ElektraInitiative/libelektra/commit/ca63b86f53cefb5e0941ec0b7a1d116f504bcb12 where you reverted a commit with the text "breaks the behavior".

Since I do not know which "behavior is broken" I tried to solve the problem differently.

The problem was that `KDBMountException` emits errors differently than a typical KDBException.
While all errors emit it via the error key, the `KDBMountException` sets it like this:
https://github.com/ElektraInitiative/libelektra/blob/d07e90881541e703a166f8334260a971394061da/src/tools/kdb/mountbase.cpp#L136-L145

I am not very proficient in c++ so please tell me if there is a better method to fix this problem

**Comment by markus2330** [comment]
> Since I do not know which "behavior is broken" I tried to solve the problem differently.

The commit message clearly said: "fix external commands with arguments" so obviously the wanted behavior is that arguments are correctly passed to external commands.

Back then, I asked you to write a test case for this.

> The problem was that KDBMountException emits errors differently than a typical KDBException.

Maybe this special case is not needed anymore (if the error message itself is already clear).

Furthermore, the text does not apply to the new error system anymore: IIRC "Configfile:" will not shown unless `-v` is used. I think this is also quite a usability problem, as people might not think of using `-v` and `kdb mount` with `-v` is extremely verbose. Hopefully you can come up with a better idea.

**Comment by Piankero** [comment]
> The commit message clearly said: "fix external commands with arguments" so obviously the wanted behavior is that arguments are correctly passed to external commands.

"behavior is broken" indicates for me that something else does not work as expected anymore and not that "command line arguments are not passed".

> Back then, I asked you to write a test case for this.

It is still in the backlog: https://github.com/ElektraInitiative/libelektra/issues/2859
There are higher priorities though such as https://github.com/ElektraInitiative/libelektra/issues/3120

> Hopefully you can come up with a better idea

I do not see a way other than letting user either pass `-v` and receive super verbose text or reword the error message so that `Configfile:` does not appear anymore.

**Comment by markus2330** [comment]
> I do not see a way other than letting users either pass -v and receive super verbose text or reword the error message so that Configfile: does not appear anymore.

You could give the tip that `kdb file system/elektra/mountpoints` will show the file name in question. It also gives a lot of insight how Elektra works (that mounting also only write to KDB).

**Comment by Piankero** [comment]
> You could give the tip that kdb file system/elektra/mountpoints will show the file name in question.

I changed the error message to give this tip as otherwise I really did not see an opportunity. I also tried to set a resource error but the namespace clash does with kdb::Key and ckdb::Key does not allow for that.

**Comment by markus2330** [comment]
Thank you for the improvement!

> I also tried to set a resource error but the namespace clash does with kdb::Key and ckdb::Key does not allow for that.

What do you mean? You can always use kdb::Key and ckdb::Key, regardless of what `using` namespaces might have been before?

**Comment by Piankero** [comment]
> What do you mean? You can always use kdb::Key and ckdb::Key, regardless of what `using` namespaces might have been before?

The parentKey is a kdb::Key whereas I would need a ckdb::Key in order to use the error macros.

**Comment by markus2330** [comment]
So you need getKey? https://doc.libelektra.org/api/current/html/classkdb_1_1Key.html#a6be9b3bb17434fd4362d137183d51100

**Comment by Piankero** [comment]
> So you need getKey?

Ah ok, I did not know about that.

> Maybe this special case is not needed anymore (if the error message itself is already clear).

After some more tinkering I found that this might apply. If I do not catch the Mount exception it would emit the following warning + error message: 
``` Sorry, 2 warnings were issued ;(
	Sorry, module dump issued the warning C01100:
	Resource: Insufficient permissions to open configuration file /etc/kdb/elektra.ecf.21913:1573985716.67629.tmp for writing. You might want to retry as root. Reason: Permission denied
	Sorry, module resolver_fm_hpu_b issued the warning C01100:
	Resource: Could not unlink the file '/etc/kdb/elektra.ecf.21913:1573985716.67629.tmp'. Reason: No such file or directory
Sorry, module resolver_fm_hpu_b issued the error C01100:
Resource: Could not reopen configuration file '/etc/kdb/elektra.ecf' for writing. Reason: Permission denied```

I could add the "retry as sudo" message here:
https://github.com/ElektraInitiative/libelektra/blob/e69ef90488e8ddbb649f269c13d1f20ea924051b/src/plugins/resolver/resolver.c#L659-L664

The message is kind of verbose with the warnings but the `-vd` options correctly work and the config file can also be given.

What do you think?

**Comment by markus2330** [comment]
Yes, this warning and error is not really understandable for beginners. Then we better leave this special case with a custom message for now. (To finish the release soon.)

In long term, however, it would be great if such remapping could happen directly in the core. Then not every tool needs to implement this.

E.g. `kdb set system/elektra something` would also benefit from this improved error message.

**Comment by Piankero** [comment]
> Then we better leave this special case with a custom message for now. (To finish the release soon.)

Alright, please take a look at the error message again since I changed it. If you are fine with that we can merge it once the build servers are fine

**Comment by markus2330** [comment]
> Alright, please take a look at the error message again since I changed it. If you are fine with that we can merge it once the build servers are fine.

Can you please test if it fixes the original error and paste the output here?

**Comment by Piankero** [comment]
> Can you please test if it fixes the original error and paste the output here?

Screenshot from 2019-11-17 17-01-13

It is still quite verbose but the main message is written in yellow which fixes the actual problem

**Comment by markus2330** [comment]
Yes, looks good! :heart:  Hopefully it builds successfully!

**Comment by Piankero** [comment]
jenkins build libelektra please

**Comment by Piankero** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by Piankero** [comment]
jenkins build libelektra please

**Comment by Piankero** [comment]
jenkins build libelektra please

**Comment by Piankero** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you! @darddan can you check if your issue is resolved now?

**Pull request merged**
