### PR TITLE
AUTHORS: add Hannes Laimer

### PR DESCRIPTION
**Pull request by hannes99**
## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add them to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - add a line in `doc/news/_preparation_next_release.md`
  - reformat the code with `scripts/dev/reformat-all`
  - make all unit tests pass
  - fix all memleaks
  - fix the CI itself (or rebase if already fixed)
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if everything is done** and no further pushes are planned by you.

### CODE REVIEW

**Review by markus2330 — CHANGES_REQUESTED** [review]
Please also add yourself to modules you want to maintain. Please clarify with @atmaxinger who will do 3-way merge integration.

**Comment by atmaxinger** [comment]
I'm not quite sure what you mean by "3-way merge integration". AFAICS, `cmerge` is already ported to the new C command line tooling.

**Comment by hannes99** [comment]
Yup, there is now only one merge command which uses the 3-way merge (implemented by Dominic J. if I remember correctly).
 https://github.com/ElektraInitiative/libelektra/blob/c13f6709c466e880bdad6d1386765aba5a329980/src/tools/kdb/cmerge.c#L77

**Comment by atmaxinger** [comment]
@hannes99 please also add yourself as a maintainer to the README files of the modules you touch as part of your thesis. See how flo91 does it in #4871.

**Review by tmakar — APPROVED** [review]

**Comment by atmaxinger** [comment]
Please rebase to resolve merge conflicts

**Review by markus2330 — APPROVED** [review]
:+1:

**Pull request merged**
