### PR TITLE
Haskell debian strech

### PR DESCRIPTION
**Pull request by e1528532**
# Purpose

Fixes Haskell builds on debian strech with ghc 8.0.1 and cabal 1.24.0 as reported in #1782 .

# Checklist

- [X] commit messages are fine (with references to issues)
- [ ] I added unit tests
- [X] I ran all tests and everything went fine
- [x] affected documentation is fixed
- [X] I added code comments, logging, and assertions (see doc/CODING.md)
- [x] meta data is updated (e.g. README.md of plugins)
- [x] release notes are updated (doc/news/_preparation_next_release.md)

@markus2330 imo its not worth mentioning this in the release, it should work anyway. Can i have access to the build server to configure a haskell debian build additionally? I'd avoid adding it to all build configurations for now, we can consider that later on if the first step works fine.

### CODE REVIEW

**Comment by e1528532** [comment]
jenkins build all please

**Comment by e1528532** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by e1528532** [comment]
jenkins build all please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build gcc-configure-debian-log please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
Apparently, it does not work with ASAN enabled. Somehow cabal fails to find the elektra libraries then although they exist. As i can't reproduce this on my mac where i use newer cabal versions, i guess they fixed that at some point, so in order to finally move forward i've simply disabled the asan builds.

Now there is only the memleak issue left we already know from the process plugin. @markus2330 Once i ensured that the memleaks only arise from the fork issue, can i just ignore them to move forward with the typechecker? Those low-level issues always cost tons of time.

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
As a "proof", here is the output when running valgrind with --

```
==21640== 512 bytes in 1 blocks are still reachable in loss record 10 of 19
==21640==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==21640==    by 0x52712A1: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x526C012: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x526C2DF: getStablePtr (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x5279AC5: foreignExportStablePtr (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x400F8A9: call_init.part.0 (dl-init.c:72)
==21640==    by 0x400F9BA: call_init (dl-init.c:30)
==21640==    by 0x400F9BA: _dl_init (dl-init.c:120)
==21640==    by 0x4000C59: ??? (in /lib/x86_64-linux-gnu/ld-2.24.so)
==21640==    by 0x1: ???
==21640==    by 0xFFF0006CE: ???
==21640==    by 0xFFF0006FF: ???
==21640== 
==21640== 1,536 bytes in 1 blocks are still reachable in loss record 13 of 19
==21640==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==21640==    by 0x52712A1: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x526BF8E: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x526C2DF: getStablePtr (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x5279AC5: foreignExportStablePtr (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x400F8A9: call_init.part.0 (dl-init.c:72)
==21640==    by 0x400F9BA: call_init (dl-init.c:30)
==21640==    by 0x400F9BA: _dl_init (dl-init.c:120)
==21640==    by 0x4000C59: ??? (in /lib/x86_64-linux-gnu/ld-2.24.so)
==21640==    by 0x1: ???
==21640==    by 0xFFF0006CE: ???
==21640==    by 0xFFF0006FF: ???
==21640== 
==21640== 8,192 bytes in 1 blocks are still reachable in loss record 17 of 19
==21640==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==21640==    by 0x52712A1: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x527576E: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x526BFDA: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x526C2DF: getStablePtr (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x5279AC5: foreignExportStablePtr (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x400F8A9: call_init.part.0 (dl-init.c:72)
==21640==    by 0x400F9BA: call_init (dl-init.c:30)
==21640==    by 0x400F9BA: _dl_init (dl-init.c:120)
==21640==    by 0x4000C59: ??? (in /lib/x86_64-linux-gnu/ld-2.24.so)
==21640==    by 0x1: ???
==21640==    by 0xFFF0006CE: ???
==21640==    by 0xFFF0006FF: ???
==21640== 
==21640== 8,248 bytes in 1 blocks are still reachable in loss record 18 of 19
==21640==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==21640==    by 0x52712A1: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x527575A: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x526BFDA: ??? (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x526C2DF: getStablePtr (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x5279AC5: foreignExportStablePtr (in /usr/lib/ghc/rts/libHSrts-ghc8.0.1.so)
==21640==    by 0x400F8A9: call_init.part.0 (dl-init.c:72)
==21640==    by 0x400F9BA: call_init (dl-init.c:30)
==21640==    by 0x400F9BA: _dl_init (dl-init.c:120)
==21640==    by 0x4000C59: ??? (in /lib/x86_64-linux-gnu/ld-2.24.so)
==21640==    by 0x1: ???
==21640==    by 0xFFF0006CE: ???
==21640==    by 0xFFF0006FF: ???
==21640== 
```

So afterwards there are only some ghc things coming through. Though its interesting as i muted the child process, the stuff that god malloced in the dl_init (happening upon the constructor call, so probably already in the main process as this is already linked against the haskell libraries?).

Therefore maybe the memleak tag isn't even wrong.

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
looks very good now. I had to exclude the haskell tests from the memleak check, as similar to the other runtimes (i saw its the same for lua and python) the runtime itself doesn't clean up properly after itself.

**Comment by e1528532** [comment]
jenkins build haskell please

**Comment by e1528532** [comment]
jenkins build all please

**Comment by e1528532** [comment]
@markus2330 any more objections? I have a few other haskell-related things in mind but that belongs in an own PR as it has nothing to do with debian.

**Comment by markus2330** [comment]
No, the only objection some hours ago was that "ready to merge" was missing :-)

**Pull request merged**
