### PR TITLE
error: Enabled v and d as command line options for all commands #2743

### PR DESCRIPTION
**Pull request by Piankero**
## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see [Coding Guidelines](/doc/CODING.md))
- [ ] meta data is updated (e.g. README.md of plugins and [METADATA.ini](/doc/METADATA.md))

## Review

Reviewers will usually check the following:

- [ ] Code is conforming to [our Coding Guidelines](/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](/doc/DESGIN.md)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Documentation is concise and good to read
- [ ] Examples are well chosen and understandable

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by Piankero** [comment]
I tested it with `kdb export -vd ...` as written in #2743 and it works again just fine.
I removed all short options like you suggested.

Unfortunately the error triggering you proposed in https://github.com/ElektraInitiative/libelektra/pull/2704#discussion_r285479677 does not work.

**Comment by markus2330** [comment]
Looks good. Please add some tests and update the docu (for all the files in doc/help which now got new arguments).

**Comment by Piankero** [comment]
> Looks good. Please add some tests and update the docu (for all the files in doc/help which now got new arguments).

Docu is updated. I tried to patch the error plugin but without success to trigger an error for the export.

I added an extra `if` as discussed in the meeting:
```c
		meta = keyGetMeta (cur, "trigger/error/delayed");
		if (meta)
		{
			keySetMeta(cur, "trigger/error", keyString (meta));
		}
```

I fear that the only secure way to trigger errors is to manipulate on the file basis as done in my test

**Comment by markus2330** [comment]
> Docu is updated.

Thank you very much!

> I added an extra if as discussed in the meeting:

Please create a separate PR for this. (Error plugin and tests improvements)

> But no triggers for get or any other command.

Because currently elektraErrorGet does not check for a trigger.

> I fear that the only secure way to trigger errors is to manipulate on the file basis as done in my test

Your test is not bad per-se (we can keep it) but it relies on internals of the dump plugin (which has nothing to do with your test). This should be avoided if possible, or at least also have alternative tests so that we can drop the test once it stopped working.

**Pull request merged**
