### PR TITLE
[#3648] Fix mv

### LINKED ISSUE #3648: kdb mv (move single key, non-recursive) silently deletes child-keys
## Steps to Reproduce the Problem

```sh
kdb set user:/key "Some value"
kdb set user:/key/child "Some child value"
kdb ls user:/
#> user:/key
#> user:/key/child

kdb mv user:/key user:/otherkey

kdb ls user:/
#> user:/otherkey
```

## Expected Result

Either
```sh
kdb ls user:/
#> user:/key/child
#> user:/otherkey
```

or an error.

## Actual Result

The key `user:/key/child` gets deleted.
```sh
kdb ls user:/
#> user:/otherkey
```

## System Information

- Elektra Version: KDB_VERSION: 0.9.4, SO_VERSION: 5
- Operating System or Docker Container? Docker container, Ubuntu Focal

### PR DESCRIPTION
**Pull request by hannes99**
Add tests and fix the problem where subkeys were deleted when using `mv` without `-r`. Fixes #3648
## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add them to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - add a line in `doc/news/_preparation_next_release.md`
  - reformat the code with `scripts/dev/reformat-all`
  - make all unit tests pass
  - fix all memleaks
  - fix the CI itself (or rebase if already fixed)
- [x] The PR is rebased with current master.

## Checklist

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if everything is done** and no further pushes are planned by you.

### CODE REVIEW

**Comment by atmaxinger** [comment]
jenkins build libelektra please

**Review by atmaxinger — APPROVED** [review]
LGTM

**Comment by hannes99** [comment]
jenkins build libelektra please

**Comment by atmaxinger** [comment]
jenkins build libelektra please

**Review by tmakar — APPROVED** [review]
LGTM.

Just a quick note. For me it was not clear what the release note was describing. Maybe reformulating it a little bit e.g. `unwanted removed` :thinking: .

**Comment by tmakar** [comment]
There is an error in jenkins with multiple `free` function call.

```sh
free(): double free detected in tcache 2


FAILURE: Build failed with an exception.


* What went wrong:

Execution failed for task ':libelektra:test'.

> Process 'Gradle Test Executor 1' finished with non-zero exit value 134

  This problem might be caused by incorrect test process configuration.

  Please refer to the test execution section in the User Manual
```

It is something in the `jna` test (testjna_gradle). Maybe @tucek can assist you here.

**Comment by tmakar** [comment]
jenkins build libelektra please

**Comment by hannes99** [comment]
jenkins build libelektra please

**Comment by atmaxinger** [comment]
please rebase to resolve merge conflicts

**Pull request merged**
