### PR TITLE
improve CODING.md / DESIGN.md formatting

### PR DESCRIPTION
**Pull request by omnidan**

### CODE REVIEW

**Comment by markus2330** [comment]
thanks!

**Comment by omnidan** [comment]
@markus2330 I'm still not part of the organisation/team, btw ;)

**Comment by markus2330** [comment]
Now you are, please add yourself to doc/AUTHORS

**Comment by omnidan** [comment]
@markus2330 done :+1: https://github.com/ElektraInitiative/libelektra/pull/288

**Pull request merged**
