### PR TITLE
core: kdbSet read-only parentKey

### LINKED ISSUE #3587: kdbSet completely breaks with KEY_FLAG_RO_NAME
TL;DR: `kdbSet` completely breaks and potentially destroys the KDB, if the `parentKey` is read-only (`KEY_FLAG_RO_NAME`).

---

If you call `kdbSet` with a read-only `parentKey`, calls to `keySetName` will not be able to modify the name of `parentKey`. There are many places, where this is a problem, but this is the most obvious one:

https://github.com/ElektraInitiative/libelektra/blob/d9a8478478b0009971a070d2990af0b310abfd7e/src%2Flibs%2Felektra%2Fkdb.c#L1320

Instead of setting the name to the correct mountpoint for the backend, `keySetName` will do nothing to `parentKey` and return `-1`.

https://github.com/ElektraInitiative/libelektra/blob/4d43a084bccae3897a11a2e018f4984baefce0a9/src%2Flibs%2Felektra%2Fkeyname.c#L457-L460

This of course means, that **all storage plugins will be called with the same `parentKey`** no matter which mountpoint. The effects can range from immensely bad to catastrophically destructive.

---

@markus2330 @mpranj

I would have made a PR immediately, but I didn't know which of the following solutions would be best:
1. Swap `initialParent` and `parentKey` in `kdbSet`: Instead of using the `keyDup`ed key as a backup that is restored at the end, we use the `keyDup`ed key as the working key and `keyDel` it at the end.
2. Create the "working" `parentKey` completely from scratch with `keyNew (keyName (parentKey), KEY_END)`
3. Just fail, if `parentKey` is read-only

### PR DESCRIPTION
**Pull request by kodebach**
Fixes #3587

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [x] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [x] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

### CODE REVIEW

**Review by mpranj — APPROVED** [review]
Thank you for the fix! Looks good to me!

I restarted some temp-failed builds to see if everything is green.

**Review by markus2330 — APPROVED** [review]
Thank you for the fix!

**Comment by mpranj** [comment]
I would like to fix Travis-CI builds before we merge anything.

I marked this as ready to merge so it does not get forgotten after our CI works again.

**Comment by kodebach** [comment]
> I would like to fix Travis-CI builds before we merge anything.

Maybe manually migrating from travis-ci.org to travis-ci.com improves the macOS builds. [see docs](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository)

**Comment by kodebach** [comment]
Okay migrating to travis-ci.com manually is not a good idea... See #3603

**Comment by mpranj** [comment]
Thank you for finding and fixing this!

**Pull request merged**
