### PR TITLE
elektrad: attempt to fix for keyname overhaul

### PR DESCRIPTION
**Pull request by kodebach**
## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

### CODE REVIEW

**Comment by kodebach** [comment]
Honestly, I have no idea, if I fix or broke things... `go test ./...` (in `src/tools/elektrad`) seems to mostly work now. Sometimes there is a random segfault in `kdbGet` (AFAICT always somewhere inside `mmapstorage` during the `elektraCacheSet` call). I think it is some race condition. When debugging with `gdb` I see multiple goroutines that are in an active call to `kdbGet`/`kdbSet` when the segfault occurs.

**Comment by kodebach** [comment]
@mpranj As far as I am concerned, this PR is done. I won't mark it as "ready to merge", since the review from @raphi011 is still pending.

**Comment by markus2330** [comment]
Did you fix the crashes?

**Comment by kodebach** [comment]
The random segfaults still appear, but I have no idea how to fix them or why exactly they occur.

**Comment by markus2330** [comment]
Ok, hopefully @raphi011 has time to look at it, would be not ideal if we introduce segfaults...

How can I test this PR? I assume https://github.com/ElektraInitiative/go-elektra/pull/10 must be applied?

**Comment by kodebach** [comment]
> would be not ideal if we introduce segfaults...

The thing is, I'm not sure I introduced them.. They occur in a part of the code I did not touch

> How can I test this PR? I assume ElektraInitiative/go-elektra#10 must be applied?

If the PR in go-elektra is merged, it should just work. I think you can somehow run the tests through CMake, but I just ran `go test ./...` in `src/tools/elektrad`. You also need to have a current Elektra installed. Depending on how you installed Elektra, might need to set `PKG_CONFIG_PATH` and `LD_LIBRARY_PATH`.

If you want to test before merging the PR in go-elektra, you need to checkout the source code of the PR. Then you need to add an override line like then one I used (and forgot to remove at first):

https://github.com/ElektraInitiative/libelektra/blob/9ecf9ff1d6ceb8bcf939059be74c22fbb1720c63/src/tools/elektrad/go.mod#L5

This tells Go to not look for a git repo, but instead use the local path.

**Comment by markus2330** [comment]
I can reproduce, there are plenty of segfaults when I run `GOROOT=/usr/lib/go-1.14 /usr/lib/go-1.14/bin/go test ./..`.

This test definitely should have been in the CI. Now we will need to investigate what broke it.

Mmmh, not so easy how to move forward with this. It looks like @raphi011 does not respond anymore. Probably we need a maintainer for the go bindings anyway...

> The thing is, I'm not sure I introduced them.

But you also cannot exclude the possibility?

**Comment by raphi011** [comment]
Hi, i've managed to reproduce the bug but couldn't find the cause yet, I will try to find some time next week to dig some more.

**Comment by markus2330** [comment]
@raphi011 can you give us an update?

**Comment by mpranj** [comment]
I made some further changes on top of this and can not reproduce the segfault.

@kodebach take a look at #3789 if you can. My intention is to just move forward with these things, as the state on master is broken anyway. You invsted quite some work into this, I don't want it lying around unmerged.

**Comment by kodebach** [comment]
Continued in #3789

**Pull request closed without merging**
