### PR TITLE
Fix memleak

### PR DESCRIPTION
**Pull request by markus2330**
## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
@mpranj thank you for the fix!

**Comment by raphi011** [comment]
tried it out .. the memory is still not freed

**Comment by markus2330** [comment]
> tried it out .. the memory is still not freed

Please more details:

- which plugins are in your KDB
- how much memory, at which points and how did you find out?

**Comment by raphi011** [comment]
> > tried it out .. the memory is still not freed
> 
> Please more details:
> 
>     * which plugins are in your KDB
> 
>     * how much memory, at which points and how did you find out?

Same as before, built it with `cmake .. -DTOOLS="kdb" -DPLUGINS="ALL;-cache" -GNinja -DENABLE_DEBUG=ON && ninja`, ran the memleak benchmark, `sleep()`ed after calling `ksDel` on every keyset.

Htop shows that the memory is not freed but remains with its peak memory usage (after the last `kdbGet()` call

**Comment by markus2330** [comment]
> Htop shows that the memory is not freed but remains with its peak memory usage

But how much is this peak? Maybe it simply is not high enough that reclaiming makes sense. Please make this as experiment with more care, you can also add it to the thesis.

Did you try what @manuelm suggested? (malloc_trim)

**Comment by raphi011** [comment]
> > Htop shows that the memory is not freed but remains with its peak memory usage
> 
> But how much is this peak? Maybe it simply is not high enough that reclaiming makes sense. Please make this as experiment with more care, you can also add it to the thesis.
> 
> Did you try what @manuelm suggested? (malloc_trim)

Sorry I didn't elaborate in depth because I thought you would try it out yourself if the same symptoms occur on your system because you already ran the benchmarks before.

I've added `malloc_trim` to the benchmark [here](https://gist.github.com/raphi011/047e5d95dde0fb154ac652f70a09c2c3) like manuel mentioned [here](https://github.com/ElektraInitiative/libelektra/issues/3158#issuecomment-552049118) and with this call it successfully release the memory. 

So we should probably add this to elektra? IMO it should not be the responsibility of plugins or bindings.

**Comment by markus2330** [comment]
> Sorry I didn't elaborate in depth because I thought you would try it out yourself if the same symptoms occur on your system because you already ran the benchmarks before.

When the method is not clear, I cannot reproduce it. For example, I had the symptom that warnings were collected, you did not answer if this was also the case for you.

> So we should probably add this to elektra? IMO it should not be the responsibility of plugins or bindings.

If really needed, we would add it to elektrad. But maybe the initial problem is gone already: free sometimes calls malloc_trim.

**Comment by raphi011** [comment]
> I had the symptom that warnings were collected, you did not answer if this was also the case for you.

WIth my benchmarks my `ksClose did NOT free xxx keys` debug print message revealed that 200k keys  were not freed after each benchmark iteration (size of testdata keyset), which makes me pretty confident that it couldn't have (only) been the parentKey warnings.

> If really needed, we would add it to elektrad. But maybe the initial problem is gone already: free sometimes calls malloc_trim.

Since the first memory leak problems came up I also realized that my initial approach of freeing memory in the go bindings was not satisfactory I've changed he implementation to force the user to close the keysets / keys themselves.

While this is the the better solution I've forgot to clear some keys in Elektrad - adding to the now fixed memory leak in Elektra itself.

Looks like it all works now.

**Comment by markus2330** [comment]
> WIth my benchmarks my ksClose did NOT free xxx keys debug print message revealed that 200k keys were not freed after each benchmark iteration (size of testdata keyset), which makes me pretty confident that it couldn't have (only) been the parentKey warnings.

You did not post the output of the run nor you tracked how many keys actually WERE closed. Maybe a later ksClose deleted them.

> Looks like it all works now.

Good! I'll merge this PR.

**Pull request merged**
