### PR TITLE
[FLOSS H3] doc: add sources where elektra is mentioned #705

### PR DESCRIPTION
**Pull request by JakobWonisch**
## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Review by flo91 — COMMENTED** [review]
**[FLOSS H3]**

Thanks for the PR!
The CI currently fails because of an updated manpage, but if you rebase your PR-branch to the current master, it should probably be resolved.
If there are still remaining problems, you can also try to add a newline character at the end of [doc/todo/DOCUMENTATION](https://github.com/JakobWonisch/libelektra/blob/update-links/doc/todo/DOCUMENTATION)

You added links to four Wikipedia-pages in English, Dutch, French and German, but apparently only made changes to the English and German versions.

The changes you made look good and reasonable:
- You added a link to the Elektra-website on the [English page about freedesktop.org](https://en.wikipedia.org/wiki/Freedesktop.org)
- You removed the table listing Elektra plugins and replaced it with a link to the [corresponding Elektra documentation](https://www.libelektra.org/plugins/readme) on the [German page about Elektra](https://de.wikipedia.org/wiki/Elektra_%28Software%29). This can help to avoid incomplete or outdated information.

It would've been helpful if you mentioned the changes you made in the description of your PR.

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by JakobWonisch** [comment]
I have translated the Elektra wikipedia article to english: [link](https://en.wikipedia.org/wiki/Draft:Elektra_(Software)). It is published as a community draft, since I cannot yet publish articles on wikipedia because of my new account.

**Comment by markus2330** [comment]
Very good job! Please add the link, rebase this PR and set ready to merge.

Please also write in doc/todo/RELEASE.md that the versions should be updated on every release on the wiki pages (en+de).

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
I rebased and merged.

**Pull request closed without merging**
