### PR TITLE
pluginprocess: use pipes instead of named pipes

### LINKED ISSUE #2170: pluginprocess: defunct processes
## Steps to Reproduce the Problem

Mounting a global python plugin and run unit tests or run an application using the python binding.

## Expected Result

That it works as before.

## Actual Result

The child process hangs 
```
markus    9853  0.7  0.1 219624 25592 pts/14   S+   16:41   0:01 python ./application.py
markus    9854  0.0  0.0      0     0 pts/14   Z+   16:41   0:00 [python] <defunct>
```

Relevant Backtrace:

```
#8  elektraDumpGet (returned=0x55c2db1e13c0, parentKey=0x55c2db1e1930) at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/plugins/dump/dump.cpp:225
#9  0x00007f04364dc3e8 in elektraPluginProcessSend (pp=pp@entry=0x55c2db1e0e20, command=command@entry=ELEKTRA_PLUGINPROCESS_OPEN, originalKeySet=originalKeySet@entry=0x0, key=key@entry=0x55c2dacf5750)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/libs/pluginprocess/pluginprocess.c:278
#10 0x00007f04364dd2c3 in elektraPluginProcessOpen (pp=pp@entry=0x55c2db1e0e20, errorKey=errorKey@entry=0x55c2dacf5750)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/libs/pluginprocess/pluginprocess.c:509
#11 0x00007f04366e320b in libelektra_Python_LTX_elektraPluginOpen (handle=0x55c2db1e0da0, errorKey=0x55c2dacf5750)
    at /home/jenkins/workspace/libelektra_master-Q2SIBK3KE2NBEMJ4WVGJXAXCSCB77DUBUULVLZDKHQEV3WNDXBMA@2/libelektra/src/plugins/python/python.cpp:225
```

So it seems to hang in elektraPluginProcessOpen. Maybe there is no child or parent is receiving what is sent? I think it must be a bug in pluginprocess, elektraPluginProcessOpen should never hang.

Might be related to  #2162

Any idea what it could be or do I need to find a reproducible test case?

## System Information

- Elektra Version: master

### PR DESCRIPTION
**Pull request by e1528532**
## Basics

attempt to fix #2170 

## Checklist

- [X] I added unit tests
- [X] I ran all tests locally and everything went fine
- [X] affected documentation is fixed
- [X] I added code comments, logging, and assertions (see doc/CODING.md)
- [X] meta data is updated (e.g. README.md of plugins)

## Review

@markus2330 please review my pull request

### CODE REVIEW

**Comment by e1528532** [comment]
This seems to solve the global python issue you reported and reveals those errors instead:

```
18: ======================================================================
18: ERROR: test_set (__main__.KDB)
18: ----------------------------------------------------------------------
18: Traceback (most recent call last):
18:   File "/media/sf_git/libelektra/src/bindings/swig/python/tests/test_kdb.py", line 41, in test_set
18:     db.get(ks, TEST_NS)
18: kdb.KDBException: Sorry, the error (#49) occurred!
18: Description: unknown command detected in dumpfile
18: Ingroup: plugin
18: Module: dump
18: At: /media/sf_git/libelektra/src/plugins/dump/dump.cpp:194
18: Reason: [sw/elektra/examples/kdb-complete]
18: Mountpoint: user
18: Configfile: /home/armin/.config/default.ecf
18: 
18: 
18: ======================================================================
18: ERROR: tearDownClass (__main__.KDB)
18: ----------------------------------------------------------------------
18: Traceback (most recent call last):
18:   File "/media/sf_git/libelektra/src/bindings/swig/python/tests/test_kdb.py", line 62, in tearDownClass
18:     db.get(ks, TEST_NS)
18: kdb.KDBException: Sorry, the error (#49) occurred!
18: Description: unknown command detected in dumpfile
18: Ingroup: plugin
18: Module: dump
18: At: /media/sf_git/libelektra/src/plugins/dump/dump.cpp:194
18: Reason: [sw/elektra/examples/kdb-complete]
18: Mountpoint: user
18: Configfile: /home/armin/.config/default.ecf
18: 
18: 
18: ----------------------------------------------------------------------
```
Adding that the command terminates now at least.

However it broke macOS. For some reason childs never receive what the parent write... i tried using flush in the dump plugin already but it doesn't help either.

**Comment by e1528532** [comment]
If i use read manually on the pipe i get
`src/libs/pluginprocess/pluginprocess.c:138:elektraPluginProcessStart: we have read something1!!! kdbOpen 1@ksNew 5@keyNew 23 2@/pluginprocess/command`

But after that it just blocks? Is that supposed to mean that the keyset is not completely serialized? but then why does it work on debian?

**Comment by e1528532** [comment]
Apparently somehow the ifstream doesn't read correctly on macOS from the pipe that the dump plugin uses.
I made a hack that read the contents manually into a stringstream before instead of opening an ifstream upon deserialization on the pipe file and that does indeed work... However reading from the stream manually is very cumbersome and the dump plugin would need to be adjusted. Any advice how to deal with this situation? @markus2330

**Comment by e1528532** [comment]
more oddities: using mini instead of dump reads more stuff than dump on macOS and completely fails on debian.. do i have something wrong with the pipes?

**Comment by e1528532** [comment]
i think the issue with ini and mini is that they try to read more and more stuff because pipes are kept open during a child process' lifespan. dump doesn't have this issue as it reads until kdbEnd is encountered, but thats broken on macOS and writing a custom "dump" plugin using c functions to work around this seems like quite a lot of work.

**Comment by e1528532** [comment]
boost also offers a stream to read from file descriptors directly, but i guess you are not happy with dump depending on boost ;)

**Comment by e1528532** [comment]
last idea: write custom input stream for dump plugin for file descriptors (aka checking if the keyString == /dev/fd/<number>) as outlined in https://stackoverflow.com/questions/14086417/how-to-write-custom-input-stream-in-c#14086442, still quite some effort i guess...

**Comment by e1528532** [comment]
fixed it with a custom stream for dump to read from file descriptors directly

**Comment by e1528532** [comment]
starts to look good so far, travis seems a bit moody today, but i guess its already mature enough for a review @markus2330

**Comment by markus2330** [comment]
Thank you so much! I'll test with the python plugins asap (the build server needs the PR to be merged because it builds Debian Packages).

**Comment by markus2330** [comment]
It seems like this actually solved all problems that I had! No hanging anymore. Again a big thanks :100: 

Some tests, however, fail when the global plugin is mounted, I opened a separate issue #2177 for that (and a PR #2176 to reproduce the errors on the build server).

**Pull request merged**
