### PR TITLE
TCL Plugin: Fix Bug in Serialization Function

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request fixes a bug in the TCL plugin.

# Checklist

- [x] Commit messages are fine (References to issues are correct).
- [x] I ran all tests and everything went fine.

@markus2330 Please review my pull request.

### CODE REVIEW

**Comment by markus2330** [comment]
Hi, thanks for the PR!

I am afraid the solution is unsatisfactory because:

1. it would make tcl-files binary without any escaping
2. in the current implementation it gets cut off at the first null byte?

The proper solution is to require a encoding plugin that encodes the binary values to string values.

Currently we only have the "null" plugin, which only handles null keys but not other binary keys. base64 would be a solution, but I am afraid it is not yet tested for this scenario.

Btw.  most storage plugins have this problem.

**Comment by sanssecours** [comment]
> I am afraid the solution is unsatisfactory…

Thank you for the information, I will take another look at it.

**Comment by markus2330** [comment]
Btw. you can simply push the typo you found. Thanks for that!

**Comment by sanssecours** [comment]
> The proper solution is to require a encoding plugin that encodes the binary values to string values.

As far as I can tell I need to add `null` and `base64` to the list `infos/needs` in the ReadMe of the TCL plugin:

```md
- infos/needs = code null base64
```

. I did that and mounted the TCL plugin at `user/tests` with the following command:

```sh
kdb mount test.tcl user/tests tcl
```

. After that I imported `dump.xml` and looked at the resulting file using the commands below.

```sh
kdb import user/tests/dump xmltool < src/plugins/xmltool/xmltool/dump.xml
kdb file user/tests | xargs "$EDITOR"
```

The content of `test.tcl` looks more or less correct:

```tcl
{
	{
		user/tests/dump/.HiddenBinaryKey = @BASE64QmluYXJ5VmFsdWUA
		{
			comment = Binary key with hidden name
		}
	}
	{
		user/tests/dump/.HiddenDirectoryKey = DirectoryValue
		{
			comment = Directory key with hidden name
		}
		{
			mode = 700
		}
	}
	{
		user/tests/dump/.HiddenStringKey = StringValue
		{
			comment = String key with hidden name
		}
	}
	{
		user/tests/dump/PerfectBinaryKey = @BASE64QmluYXJ5VmFsdWUA
		{
			comment = Binary key with standard name
		}
	}
	{
		user/tests/dump/PerfectDirectoryKey = DirectoryValue
		{
			comment = Directory key with standard name
		}
		{
			mode = 700
		}
	}
	{
		user/tests/dump/PerfectStringKey = StringValue
		{
			comment = String key with standard name
		}
	}
	{
		user/tests/dump/Ug.ly:Bin@a€ry Key = @@NULL
		{
			comment = Binary key with ugly name
		}
	}
	{
		user/tests/dump/Ug.ly:Dir@ect€ory Key = @@EMPTY
		{
			comment = Directory with ugly name
		}
		{
			mode = 700
		}
	}
	{
		user/tests/dump/Ug.ly:St@ri€n.g Key = With a string value
		{
			comment = string key with ugly name
		}
	}
}
```

. If I export these values via

```sh
kdb export user/tests/dump tcl
```

, then all base64 encoded values will be converted back to their original binary form before they arrive at the `set` function of the TCL plugin. This is of course not ideal since this way the TCL plugin tries to write binary values using `key.getString()` again, and fails with the error described in issue #1019. It also seems kind of weird, that the plugin tries to convert the values again, although the version on disk is already correct?

Another problem is, that if I **do not mount** the TCL plugin to `user/tests`, import `dump.xml` and export `user/tests/dump` then the `base64` plugin is not invoked at all.

As you can see in pull request #1246 I re-read large parts of the documentation. However, I was not able to find a definite answer to my problem. It looks like the  [list plugin](/src/plugins/list/README.md) could help here, but I am not really sure how I can add the `null` and `base64` plugin at the appropriate places. 

Any help would be appreciated.

**Comment by markus2330** [comment]
> As far as I can tell I need to add null and base64 to the list infos/needs in the ReadMe of the TCL plugin:

For long term it would be better if we have some provider for binary escaping, and base64 is one way to do the escaping. So we would have:

     - infos/needs = code null binary

and base64 would have

      - infos/provides = binary

@petermax2 I assume the filefilter in provides is a copy&paste error from fcrypt?

`kdb import user/tests/dump xmltool` for me this crashes already... When running again I get error `#61`.

**Comment by markus2330** [comment]
> `kdb export` then all base64 encoded values will be converted back to their original binary form before they arrive at the set function of the TCL plugin

This is a different issue: kdb export currently only allows a single plugin, but would need base64. See  #1229 for the proposal to add an improved import/export (which considers `infos/needs`).

>  do not mount [...] export user/tests/dump

I assume you mean exporting with tcl? Then it is also #1229.

> I re-read large parts of the documentation

If you are working on issues not solved up to now there is unfortunately not much documentation around. And it is also not a good idea to write documentation of what actually does not work (except of `doc/decisions`). So it is better if you ask here.

The greater goal is to have storage plugins exclusively concerned with parsing and writing out configuration. Limitations of the parser should be handled by dedicated plugins that handle exactly that. So in this case here, we want to help parsers (that cannot handle binary data) by always giving them strings where the problematic bytes are already encoded. The idea is old, but it was never fully implemented. There are some plugins flying around that do some things in this direction (like ccode, hexcode, and base64) but they actually nowhere near actually fulfilling the greater goal.

If it helps you, we can split the issues into smaller steps, so instead of only talking about the "greater goal", we could write many small steps towards the goal. `base64` was not written for exactly this use case, so it might fail in some cases.

It might also help you to get started by writing your own parser, then you better know the limitations of your parser and know what other plugins need to recode first.

I would also recommend to you to write a tutorial that explains what is going on behind the scenes how plugins work together. If you write such a tutorial (like you nearly did in your post above) I can give you better feedback if we are talking about the same goals.

It might also help you to look at the test cases for plugin functionality (there are some already in `kdb test`, see `src/tools/kdb/test.cpp`; or also tests/shell/check_import.sh) that test if every possible key/value can be written and read out again. Roundtripping properties are something quite essential for configuration file parsers, so you should acquaint yourself with it.

**Comment by sanssecours** [comment]
Thank you for your detailed response.

> `kdb import user/tests/dump xmltool` for me this crashes already... When running again I get error `#61`.

I remember having a similar issue too. However, currently I am unable to reproduce this problem.

> I assume you mean exporting with tcl?

Yes.

**Comment by petermax2** [comment]
> I assume the filefilter in provides is a copy&paste error from fcrypt?

Very likely!

**Comment by sanssecours** [comment]
Looks like fixing this issue will take more time than I assumed. I think I will look into this later, when I have more experience with the Elektra code base.

**Comment by markus2330** [comment]
Yes, as said it is better to start with your own storage plugin. This should give you faster progress and more confidence to throughly fix the underlying issues surfacing in tcl (and nearly all others). In the next meeting we will look a bit more into plugin dependencies.

**Pull request closed without merging**
