### PR TITLE
Docu improvement and new Node debug

### PR DESCRIPTION
**Pull request by Mistreated**
## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

Checking the hetzner-jenkins1 node.

### CODE REVIEW

**Comment by Mistreated** [comment]
jenkins build libelektra please

**Comment by Mistreated** [comment]
I get this error on hetzner-jenkins1 node:
`Permission denied (os error 13)`

**Comment by markus2330** [comment]
> @markus2330 Have any idea?

See  #3139

> Where can I see which commands are executed?

I do not understand the question. And please open new issues for questions as they cannot easily be found afterwards within PRs.

**Comment by Mistreated** [comment]
#3138 
In the last commit i changed the docu.

**Comment by markus2330** [comment]
Please nevertheless make sure that everything builds. And please write more concrete release notes (build server docu).

**Comment by markus2330** [comment]
Unfortunately there is still a conflict in the release notes. After rebasing to master this should not happen again as we now use union merge for the release notes.

**Comment by Mistreated** [comment]
Its not clear to me here.. Should I just merge this with master?

**Comment by markus2330** [comment]
No, you should rebase this with master, i.e. go to your branch, run `git rebase master`, and force push your branch.

**Pull request closed without merging**
