### PR TITLE
INI: subkey draft

### PR DESCRIPTION
**Pull request by tom-wa**
just a draft, ignore syntax/formating problems and memleaks

### CODE REVIEW

**Comment by markus2330** [comment]
@strahlex can you check if this PR fixes your problem?

**Comment by markus2330** [comment]
@fberlakovich Do you have some time to take a look at this PR?

**Comment by markus2330** [comment]
@tom-wa It seems like this PR contains also a lot of other things (filecheck plugin), can you update the PR?

**Comment by fberlakovich** [comment]
I haven't tried it out yet, but it looks like a nice idea

**Comment by fberlakovich** [comment]
As already mentioned, the concrete example given by @strahlex in #375 should already be achievable via autosections.

**Comment by markus2330** [comment]
@tom-wa Is this PR still draft?

In the README it says "section keys to be manually created with a binary NULL value." What is the reason to use `ini/section` now` Can you document that?

**Comment by tom-wa** [comment]
@markus2330 done

the ini/section was a leftover from something i tried, already removed it

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
