### PR TITLE
Markdown Shell Recorder: Add Partial Support for Indented Code Blocks

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request should fix the problems of the Markdown Shell Recorder test of the Hexnumber plugin (see PR #1903).

# Checklist

- [x] I checked all commit messages.
- [x] I ran all tests locally and everything went fine.
- [x] This PR contains an updated version of the release notes.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build ini please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build gcc-configure-debian-optimizations please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build pr-merge please

**Comment by sanssecours** [comment]
@ingwinlu 👋 Can you please tell me how I can restart `pr-merge`? It also seems the configuration for “Blue Ocean” is broken:

jenkins

. At least the page for https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2002/9 stays blank in my browser.

**Comment by ingwinlu** [comment]
I noticed problems yesterday due to your branchname but thought it resolved itself as soon as you opened the PR. For me the url is loading.

anyway you can trigger a rebuild via 'jenkins build libelektra please'.

**Comment by sanssecours** [comment]
Thank you for the quick response.

> For me the url is loading.

Seems this is a Safari specific problem, as the page works in Opera.

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by ingwinlu** [comment]
> Thank you for the quick response.

No worries.

Please do not delete the source branch I might have to use it in a bug report against jenkins as it breaks the ui.

**Comment by ingwinlu** [comment]
Having the branch alone is enough. And no I have not gotten around to it yet.

**Comment by sanssecours** [comment]
> What does "partial support" mean?

It’s not really supported, but some things – e.g. the MSR test from #1903 – might nevertheless work.

> Can you document that please?

Before I do that, I might even add full support for that stuff. It seems like everybody assumes that indented code blocks work anyway.

**Comment by markus2330** [comment]
Thank you for the great work!

@sanssecours Would be great to see full support :wink: Do not forget to not remove the branch.

**Pull request merged**
