### PR TITLE
Markdownlink Converter

### PR DESCRIPTION
**Pull request by KurtMi**
* stat files
* cleanup external-links.txt
* link checker: fix fales positive

### CODE REVIEW

**Comment by KurtMi** [comment]
Should do: #1095 and  #923.
The cpp file comes from reformat src.

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build mingw64 please

**Comment by KurtMi** [comment]
the mem leak is not from me :)

**Comment by markus2330** [comment]
Yeah, its already reported  #1105.

I was mainly interested in what windows will do with the stat (mingw build).

**Comment by markus2330** [comment]
Thank you! Nice to have it before the release!

**Pull request merged**
