### PR TITLE
mmapcache: fix dependencies and segfault

### LINKED ISSUE #2605: Dependency issues/segfaults related to cache plugin
After updating the master branch I had major problems with `kdb`. Both of them are related to the `cache` plugin and both are missing dependencies in CMake.

1. The `cache` plugin is 100% required for kdb to work. Even a simple call to `kdb` without arguments results in a segfault, if the `cache` plugin is not found. Therefore the `cache` plugin should be a dependency of `kdb` in CMake. [Here is the valgrind output for the segfault.](https://github.com/ElektraInitiative/libelektra/files/3056051/valgrind.txt) Also, the segfault shouldn't happen, even if cache isn't found, ideally `kdb` would just run without a cache, but a meaningful error message is the least that I expect.
2. Once the `cache` plugin is found. The `mmapstorage` plugin caused errors. I assume it is a dependency of `cache` (not mentioned in the README). Therefore it should be a CMake dependency of `cache`. I had an old version of `mmapstorage` so I got some weird error message. If `mmapstorage` isn't present, I get a segfault very similar to the one above (stacktrace is the same).

Maybe we should add a CI job that only executes `make kdb` instead of `make all` to ensure `kdb` can be built and run without having to build all of Elektra...

### PR DESCRIPTION
**Pull request by mpranj**
Closes #2605.

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [x] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

### CODE REVIEW

**Comment by mpranj** [comment]
@markus2330 and @kodebach please review my pull request.

**Comment by mpranj** [comment]
I have found one quick addition, sorry, will be done in a minute!

**Comment by markus2330** [comment]
Thank you for the quick fix!

**Comment by mpranj** [comment]
I was already rebasing, but thank you!

**Comment by markus2330** [comment]
The fix was too important to wait for it. It was my fault to merge it in the wrong order.

**Pull request merged**
