### PR TITLE
jenkins: disable parallel tests

### PR DESCRIPTION
**Pull request by atmaxinger**
## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by atmaxinger** [comment]
jenkins build libelektra please

**Comment by atmaxinger** [comment]
jenkins build libelektra please

**Comment by atmaxinger** [comment]
jenkins build libelektra please

**Comment by atmaxinger** [comment]
jenkins build libelektra please

**Comment by kodebach** [comment]
AFAIK tests that cannot run in parallel should already be marked with [`RUN_SERIAL` in CMake](https://cmake.org/cmake/help/latest/prop_test/RUN_SERIAL.html) (possible via a helper function). I don't think this PR is a good fix for the situation. It ideally, we would just find the test(s) that cause the issues and mark them with `RUN_SERIAL`. However, I'm not sure _how_ to find those issues, so maybe this is the best solution after all (at least for now).

**Comment by atmaxinger** [comment]
Well for certain any test that touches the filesystem should not be run in serial. That probably means most tests that involve `KDB`, as well as all shell tests.

**Comment by kodebach** [comment]
Okay, so it seems we already mark the following tests with `RUN_SERIAL`:
- All tests from the SWIG bindings created via `do_python_test`, `do_ruby_test`, `do_lua_test`
- Tests for the glib binding created via `do_glib_test`
- `testshell_*` tests created via `add_shell_recorder_test`
- `testscr_*` tests created via `add_scripttest`
- All tests that use the GTest Framework (added via `add_gtest`)

That should already cover most tests that touch the file system AFAIK. Maybe there are some tests that aren't created via the helper functions?

**Review by mpranj — APPROVED** [review]
Thanks for working on this!
It's definitely safe that we test this, and it seems it doesn't affect pipeline runtime significantly (for now).

> Well for certain any test that touches the filesystem should not be run in parallel.

Depends on how the test touches the filesystem.

@atmaxinger could you open an issue or track this problem somewhere? (since disabling parallelism is a temporary workaround)

**Comment by kodebach** [comment]
> Depends on how the test touches the filesystem.

The main issues AFAICT is `system:/elektra/mountpoints`. It's stored in a single file and many tests want to modify it to isolate their changes. #4852 would solve all this. Most tests could use in-process mountpoints, which could then run in parallel.

**Comment by mpranj** [comment]
I merged so we can test the thesis that parallelism is the actual problem.

**Comment by atmaxinger** [comment]
> @atmaxinger could you open an issue or track this problem somewhere? (since disabling parallelism is a temporary workaround)

Well the main issue is #4837

**Pull request merged**
