### PR TITLE
New repo layout

### PR DESCRIPTION
**Pull request by kodebach**
Preview PR for changes to repo layout, API naming and API in general.

Will be a combination #4920, #4940, #4941 (and future PRs)

### CODE REVIEW

**Review by markus2330 — CHANGES_REQUESTED** [review]
Please avoid such a huge PR and instead please try to keep smaller PRs against master as much as possible. The name is also misleading, repo layout does not need to be changed, please concentrate on API refactorings useful for Elektra's goals.

**Comment by kodebach** [comment]
> Please avoid such a huge PR and instead please try to keep smaller PRs against master as much as possible.

I tried that with  #4920, #4940, #4941 (*) and you ignored all of them, because they were not reviewed twice and then you ignored #4920 for a few more days after it was reviewed twice. I understand that you may not have had the time to review the PR fully, but then at least respond with comment saying something (e.g. "no time right now, will look at it in a few days") after I explicitly @-tagged you. But no, you once again completely ignored my comments and at that point I just changed the base branch so I can move on and people an actually review #4940 and #4941 (which would not have been feasible without merging #4920 and #4940 respectively).

(*) These were already split up parts of the initial #4887 (closed before it was finished, but continued in my fork https://github.com/kodebach/libelektra/pull/41).

> The name is also misleading, repo layout does not need to be changed,

These PRs implement the decisions listed in #4920. None of them touch the API, but all of them change the repo layout. That's the reason for the PR name. **Yes**, the repo layout **does need to** change, because that is what we already decided in the decisions.

---

I know your time is limited, but my time is also limited and I cannot keep waiting for you, when you are the one imposing a time limit on me. I no longer care, whether this actually gets merged or not. I will simply do what I want/need for my thesis and put it into a PR. What you do with that PR is up to you. If you ask nicely, and don't come in, completely ignore everything that has been said/done and post a comment dismissing everything, I _may_ be willing to split this up into smaller PRs _after_ I'm done. But at this point that is very unlikely, because I've already tried that unsuccessfully...

Also just to be clear: In yesterdays meeting **you asked me** to create a PR for this branch so you can review it. You can confirm that by looking at the timestamp, when I asked for your review:

image

During the meeting I found this PR and asked for your review... So **please** at least for 24h be consistent in what you want from me

**Comment by markus2330** [comment]
I want and always wanted PRs targeting master which are as small as possible. This is like in basically every other FLOSS initiative, so I thought you might know. If you think something else was said, it is your imagination. On the rest I will not comment, I am sorry if you have such expectations.

**Comment by markus2330** [comment]
> However, the fact that you do not remember this, is exactly the problem.

The problem is that you assume things that were not commented to be confirmed.

**Comment by markus2330** [comment]
Anyway, it is very simple: please do best efforts to:

1. have PRs target master 
2. keep PRs small
3. have two reviews on the PRs
4. have only the content we discussed (is in the individual tasks of the email today)
 
I'll try to merge as much as possible.

**Comment by kodebach** [comment]
> have PRs target master

Tried that was ignored for days and weeks. Again, I don't expect immediate reviews. But writing a short comment to confirm that you know the PR is ready for your review, takes seconds.

> keep PRs small

#4920, #4940 and #4941 were as small as feasible

> have two reviews on the PRs

#4920, #4940 and #4941 are all reviewed twice. In #4920 I waited for 3 days for a response to https://github.com/ElektraInitiative/libelektra/pull/4920#issuecomment-1566114425. Since I got no response, I switched to a non-master branch.

> have only the content we discussed (is in the individual tasks of the email today)

This PR is literally the first item on that list. And all of #4920, #4940 and #4941 (which is all this PR contains) are reviewed twice.

> The problem is that you assume things that were not commented to be confirmed.

So I cannot assume anything you said in a meeting _in person_, but did not write down anywhere to be want you actually think and I should consider everything you said, but did not write, to be meaningless fluff. Got it. Basically your word means nothing I shouldn't trust you. I think I'm done here. Maybe I will finish my thesis, maybe I won't, but my time is to valuable to deal even one more second with this bullshit.

**Comment by markus2330** [comment]
I did not comment on this PR in person at all, as I didn't even look at it before the meeting.

Everything I said **and** what I wrote fully stands.

**Pull request closed without merging**
