### PR TITLE
Gsettings backend build test

### PR DESCRIPTION
**Pull request by sirblackheart**
This is PR is just for testing build status of gsettings on jenkins

### CODE REVIEW

**Comment by markus2330** [comment]
(you can use `jenkins build <jobname> please` to retrigger builds, you do not have to create new PRs for it)

@mpranj Can you please update the doc/GIT docu so that we easily can lookup all trigger commands?

**Comment by sirblackheart** [comment]
@markus2330 i want a different pr so i can push possible fixes without creating a long history of mini commits for the main pr. As this is going to be a long game of trial and error as i can not reproduce the error in debian stable locally.

**Comment by markus2330** [comment]
ahh ok, makes sense. rebase is not always ones friend.

**Comment by sirblackheart** [comment]
We really should ask for donations to upgrade our Jenkins build system ;)

**Comment by markus2330** [comment]
Its planned, but do not expect it anytime soon. Bernhard said he will set up with proper CM as case-study.

**Pull request closed without merging**
