### PR TITLE
Fix Warning and Various Runtime Errors

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request fixes various run-time errors reported by `kdb ls` after we enable address sanitization.

# Checklist

- [x] I checked all commit messages twice.
- [x] I ran all tests and everything went fine.

@markus2330 @tom-wa 👋 Please review my pull request.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you! I like the changes except the cast for elektraFree. Does your compiler emit a warning there? Is there some way to suppress this warning for different pointers passed to elektraFree?

**Comment by sanssecours** [comment]
>  I like the changes except the cast for elektraFree. Does your compiler emit a warning there? 

Yes. The build server reports the same [warning](https://build.libelektra.org/job/elektra-clang/lastBuild/warnings9Result/package.1645469987):

```
testmod_range.c:182: passing 'const char *' to parameter of type 'void *' discards qualifiers
```

. 

> Is there some way to suppress this warning for different pointers passed to elektraFree?

I do not know of any. I have to admit though, that I did not look too much into this problem. 

We could also fix the warning by removing the `const` qualifier from the variable `old_locale`, if you prefer that. Another option would be a more specific cast to `char *` instead of `void *`.

**Comment by markus2330** [comment]
Ahh okay, then removing const is the correct fix.

**Comment by sanssecours** [comment]
> Ahh okay, then removing const is the correct fix.

Thank you for the information. I updated the last commit accordingly.

**Comment by markus2330** [comment]
I think this is ready to merge. Do you want to wait for @tom-wa to review?

**Comment by sanssecours** [comment]
> I think this is ready to merge. Do you want to wait for @tom-wa to review?

If the changes in commit c2e4a39b are correct from your point of view, then I think it is alright if we merge this without waiting for Tom’s review.

**Comment by markus2330** [comment]
Ok, then lets have @tom-wa a look.

**Comment by sanssecours** [comment]
> Ok, then lets have @tom-wa a look.

Since this probably will take some time, I fixed another runtime error in the latest commit. I am not sure if the code changes address the problem properly though. Do we assume that `elektraPluginGetData` in [line 76 of `resolver.c`](https://github.com/ElektraInitiative/libelektra/blob/master/src/plugins/resolver/resolver.c#L76):

```c
resolverHandles * pks = elektraPluginGetData (handle);
```

never returns a null pointer?

**Comment by markus2330** [comment]
> never returns a null pointer?

Yes, we assume it (because open always sets the handle on success, thus it must be available in get). But this would be a perfect place for `ELEKTRA_ASSERT`.

**Comment by sanssecours** [comment]
> Yes, we assume it (because open always sets the handle on success, thus it must be available in get). But this would be a perfect place for `ELEKTRA_ASSERT`.

I replaced the `if` with an assertion in the latest commit. The text below shows the backtrace of the crash after I run `lldb -- kdb ls /` starting with a clean configuration:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff9da47d42 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff9db355bf libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff9d9ad420 libsystem_c.dylib`abort + 129
    frame #3: 0x0000000100fc90c7 libelektra-core.4.dylib`elektraAbort(expression=<unavailable>, function=<unavailable>, file=<unavailable>, line=<unavailable>, msg=<unavailable>) at nolog.c:33 [opt]
    frame #4: 0x000000010454301f libelektra-resolver.so`elektraGetResolverHandle(handle=<unavailable>, parentKey=0x0000606000000d40) at resolver.c:78 [opt]
    frame #5: 0x0000000104541fc2 libelektra-resolver.so`libelektra_resolver_fm_hpu_b_LTX_elektraPluginget(handle=0x000060700000cc00, returned=0x0000604000009410, parentKey=0x0000606000000d40) at resolver.c:441 [opt]
    frame #6: 0x0000000100f26414 libelektra-kdb.4.dylib`kdbGet at kdb.c:468 [opt]
    frame #7: 0x0000000100f26066 libelektra-kdb.4.dylib`kdbGet(handle=0x000061600000f680, ks=0x000060400000d010, parentKey=<unavailable>) at kdb.c:804 [opt]
    frame #8: 0x0000000100026d61 kdb`kdb::KDB::get(this=<unavailable>, returned=<unavailable>, parentKey=0x000060400000f198) at kdb.hpp:183 [opt]
    frame #9: 0x0000000100188a41 kdb`LsCommand::execute(this=<unavailable>, cl=<unavailable>) at ls.cpp:35 [opt]
    frame #10: 0x0000000100198f79 kdb`main(argc=<unavailable>, argv=0x00007fff5fbff830) at main.cpp:198 [opt]
    frame #11: 0x00007fff9d919235 libdyld.dylib`start + 1
```

. It looks like the problematic code might somehow be related to the `system` namespace, since the following commands do not crash:

- `kdb ls user`
- `kdb ls spec`
- `kdb ls dir`

. The command `kdb ls system` on the other hand fails reporting the following error:

```
Elektra/src/plugins/resolver/resolver.c:78:elektraGetResolverHandle: Assertion `pks != ((void*)0)' failed: Unable to retrieve plugin data

Sorry, I crashed by the signal SIGABRT
This should not have happened!

Please report the issue at https://issues.libelektra.org/
fish: 'kdb ls system' terminated by signal SIGABRT (Abort)
```

. By the way: Do you know why the build job `elektra-mergerequests` always fails?

**Comment by sanssecours** [comment]
Looks like after adding the assertion, additional tests fail on my machine:

```
	  4 - testtool_backendbuilder (OTHER_FAULT)
	 32 - test_kdb.lua (OTHER_FAULT)
	 85 - testscr_check_distribution (Failed)
	 86 - testscr_check_error (Failed)
	 92 - testscr_check_kdb_internal_check (Failed)
	 96 - testscr_check_mount (Failed)
	 99 - testscr_check_real_world (Failed)
	100 - testscr_check_resolver (Failed)
	101 - testscr_check_spec (Failed)
	151 - testkdb_allplugins (OTHER_FAULT)
```

. The files below contain detailed debug output for some of these tests. If someone wants to reproduce these failures: I used the following CMake command to generate the build system:

```sh
cmake ..                                                  \
  -GNinja                                                 \
  -DENABLE_ASAN=OFF                                       \
  -DENABLE_LOGGER=OFF                                     \
  -DENABLE_DEBUG=ON                                       \ 
  -DENABLE_TESTING=ON                                     \
  -DBUILD_PDF=OFF                                         \
  -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5                  \
  -DTOOLS=ALL                                             \
  -DBINDINGS="ALL;-swig_ruby;-swig_python;-swig_python2"  \
  -DPLUGINS="ALL"
```

.

## Logs 
- [testscr_check_distribution.txt](https://github.com/ElektraInitiative/libelektra/files/892943/testscr_check_distribution.txt)
- [testscr_check_error.txt](https://github.com/ElektraInitiative/libelektra/files/892945/testscr_check_error.txt)
- [testtool_backendbuilder.txt](https://github.com/ElektraInitiative/libelektra/files/892944/testtool_backendbuilder.txt)

**Comment by markus2330** [comment]
Thank you, great job! You found a bug! The initializer of the pk handle was done too early, which made no sense in the situation if the resolver is below `system/elektra/modules/resolver_*`. By printing the key name in the assertion it was trivial to find.

**Pull request closed without merging**
