### PR TITLE
tests: check getenv

### PR DESCRIPTION
**Pull request by markus2330**
## Basics

Do not describe the purpose here but:

- [ ] Short descriptions should be in the release notes (added as entry in
      doc/news/_preparation_next_release.md which contains `*(my name)*`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

@markus2330 please review my pull request

### CODE REVIEW

**Comment by mpranj** [comment]
@markus2330 seems like an older build job of this PR on Travis CI is stuck. See https://travis-ci.org/ElektraInitiative/libelektra/builds/484739299

I didn't want to restart/cancel your job without asking, maybe I am mistaken.

**Comment by markus2330** [comment]
Yes, it was an older build! Thank you for the hint. I restarted the Travis build job.

**Comment by sanssecours** [comment]
I rebased this PR and added a possible fix for the failing build jobs in commit 61ef552. I do think that it would make sense to directly set the KDB via `configure_file`, just like we do for the (Markdown) Shell Recorder:

https://github.com/ElektraInitiative/libelektra/blob/061ff14bea36aa17d2c20687854569b55b49cf0e/tests/shell/shell_recorder/CMakeLists.txt#L31-L45

. However, using that solution would require more work.

**Comment by markus2330** [comment]
Thank you for the fix!

Yes, I agree that Markdown Shell Recorder and include_common.sh should be identical in behavior. Wouldn't it make sense to implement it only for include_common.sh and include that file in the Markdown Shell Recorder?

**Comment by sanssecours** [comment]
> Wouldn't it make sense to implement it only for include_common.sh and include that file in the Markdown Shell Recorder?

That would make sense, but – like I said above – it would also require more work.

**Pull request merged**
