### PR TITLE
Whitelist antlr4 website

### PR DESCRIPTION
**Pull request by Chemin1**
The website responds with 404 on this link (at least there is some 404 in my network traffic when clicking it).

### CODE REVIEW

**Comment by mpranj** [comment]
I'm not sure but it seems that something was restructured and maybe the project just moved to some other link. The purpose of the link checker is exactly to find and fix such problems, I don't think whitelisting is the best approach here.

@sanssecours can you check where this should point now? There exists a https://repology.org/project/antlr/versions project with all versions, but no explicit antlr4 site.

**Comment by markus2330** [comment]
Yes, I agree. It looks like the project changed is repo, so we should update the link and not whitelist it.

**Comment by Chemin1** [comment]
Makes sense.

I thought that the 404 made the link checker fail, but apparently this was just coincidence and re-running the link checker some times gives a successful check.

**Comment by sanssecours** [comment]
I opened a [new pull request](https://github.com/ElektraInitiative/libelektra/pull/3166) that removes the link and adds install instructions for Arch Linux, Debian Linux and macOS instead.

**Pull request closed without merging**
