### PR TITLE
bindings/rust: upgrade bindgen version

### PR DESCRIPTION
**Pull request by atmaxinger**
## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add them to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - add a line in `doc/news/_preparation_next_release.md`
  - reformat the code with `scripts/dev/reformat-all`
  - make all unit tests pass
  - fix all memleaks
  - fix the CI itself (or rebase if already fixed)
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if everything is done** and no further pushes are planned by you.

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
@atmaxinger Except of the Changelog this should afaik be everything. I'll try to publish it.

**Comment by atmaxinger** [comment]
@markus2330 I've updated the normal Elektra changelog. Is there also another changelog for Rust somewhere?

**Comment by markus2330** [comment]
No, only in the main Changelog. Thx for the fix!

**Comment by markus2330** [comment]
I published Elektra 0.10.0 elektra and elektra-sys. After the release I'll publish 0.11.0. (@fel115)

@atmaxinger published_Cargo.toml are not updated, they should be updated, too. (with version pump to 0.11.0)

**Comment by markus2330** [comment]
@fel115 `Cargo.toml.in` is used for CMake (the build system), `published_Cargo.toml` is only documentation for what was used for publishing.

I published with changes as shown in #4985. Is there anything else I should change for the 0.11.0 release?

**Comment by fel115** [comment]
@markus2330 for some reason I still get [this](https://github.com/ElektraInitiative/opensesame/issues/45) conflict. I changed the elektra version to `elektra = { version = "0.10.0", features = ["pkg-config"] }`, but the error message still says: ```... which satisfies dependency `bindgen = "^0.50.0"``` of package `elektra-sys v0.9.1`. I don't know why `elektra-sys v0.9.1` is still in use?

**Pull request merged**
