### PR TITLE
Build: Reformat Code With cmake format 0.4

### PR DESCRIPTION
**Pull request by sanssecours**
# Checklist

- [x] I did not remove any entries in the list below 😊.
- [x] I ran all tests locally and everything went fine.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the PR!

Let us discuss at the meeting of how frequently we will update cmake-format.

**Comment by sanssecours** [comment]
> Let us discuss at the meeting of how frequently we will update cmake-format.

Can we still merge this beforehand? I think cmake format 0.4.1 improves the formatting quite considerably. Updating the installed `cmake-format` version should also be quite simple:

```sh
pip install --upgrade cmake-format
```

.

**Comment by markus2330** [comment]
Why the hurry? We should add a version check so that not the wrong cmake-format gets executed.

> pip install --upgrade cmake-format

Thank you, worked nicely.

**Comment by sanssecours** [comment]
> Why the hurry?

I just want to rebase PR #2122. I do not think that these formatting changes warrant a big discussion. Anyway, if you want I can wait too. The more important question is probably: Should I change anything in this pull request?

**Comment by markus2330** [comment]
I also do not want a big discussion but updating cmake-format might be a trouble for some people. It is important that people are included in decisions that directly affects them.

The PR seems fine, we can merge it during the meeting if it is okay for everyone.

**Pull request merged**
