### PR TITLE
Directory Value Plugin & Minor Fixes

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request adds a new plugin that adds a leaf (key without children) for every directory (key with children) that stores data. For more information, please take a look at issue #106.

The PR also fixes problems with the `ERROR` directive in the Markdown Shell Recorder, and other minor issues.

# Remark

The Directory Value plugin **currently does not work*** in conjunction with the INI plugin. I did not look closer into this issue since the Directory Value plugin seems to deliver the correct key set to the INI plugin. The code below shows a failing example:

```sh
kdb mount config.ini /examples/ini ini directoryvalue

kdb set /examples/ini/aimee/man 'Deathly'
kdb set /examples/ini/aimee 'Save Me'

kdb get /examples/ini/aimee/man
#> Deathly
kdb get user/examples/ini/aimee # 😭
#>
```

# Checklist

- [x] I checked all commit messages twice.
- [x] I added unit tests.
- [x] I ran all tests and everything went fine.
- [x] The source of the Directory Value plugin contains a ReadMe describing the features of the plugin.
- [x] I added code comments, logging, and assertions.
- [x] The metadata of the Directory Value plugin stored in `src/plugins/directoryvalue/README.md` should be correct.
- [x] I added a description about the Directory Value plugin to the release notes.

### CODE REVIEW

**Comment by markus2330** [comment]
Build triggered. sha1 is merged.

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Build finished. No test results found.

**Comment by markus2330** [comment]
Build finished. No test results found.

**Comment by markus2330** [comment]
Thank you for the many improvements and the many new shell recorder snippets! You used very creative names.

I have following questions (maybe they are separate issues):

- [ ] One of the goals of directoryvalue plugin was to avoid special handling within the testcases. For example tests/shell/check_import.sh line 58. Are there still errors if these tests run unconditionally?
- [ ] Has there been a bug in elektraArrayValidateName? If so, please add regression tests for the bug.
- [ ] What happens with nested directory values? (I did not see it in the docu.)
- [ ] How can we escape ___dirdata? (Allow keys and values already named this way?)

**Comment by sanssecours** [comment]
> One of the goals of directoryvalue plugin was to avoid special handling within the testcases. For example tests/shell/check_import.sh line 58. Are there still errors if these tests run unconditionally?

As far as I can tell the test now also works, if we remove the special case for the YAJL plugin.

> Has there been a bug in elektraArrayValidateName?

Not as far as I can tell.

> What happens with nested directory values? (I did not see it in the docu.)

Is: 

```
user/grandparent                = Grandparent
user/grandparent/leaf           = Leaf
user/grandparent/parent         = Parent
user/grandparent/parent/child   = Child
```

([line 24-27 of the ReadMe](https://github.com/ElektraInitiative/libelektra/tree/master/src/plugins/directoryvalue#directory-value)) not already an example for nested directory values? After the conversion the key set looks like this:

```
user/grandparent                    =
user/grandparent/___dirdata         = Grandparent
user/grandparent/leaf               = Leaf
user/grandparent/parent             =
user/grandparent/parent/___dirdata  = Parent
user/grandparent/parent/child       = Child
```

.

**Comment by markus2330** [comment]
> As far as I can tell the test now also works, if we remove the special case for the YAJL plugin.

Thank you. You do not need to answer such questions but only point to PR/issue where it is fixed or tracked.

>    Not as far as I can tell.

Okay, I wondered about the change.

> (line 24-27 of the ReadMe)

Sorry, I overlooked this.

> Are there really people who want to use a normal key that ends with ___dirdata?

I do not know. But we should make it a habit to properly escape everything and never assume anything about the content people want to store. (Think of storing wifi SSIDs. Then you could lock out users using Elektra when you call your access point ___dirdata.)

For now it is enough if you document it as limitation.

**Comment by markus2330** [comment]
Build finished. No test results found.

**Pull request merged**
