### PR TITLE
toml: fix problem with root level parentKey

### LINKED ISSUE #3896: toml plugin in 0.9.6 eats the first character of each key
In updating the openwrt package to 0.9.6 I noticed that the ini-plugin has been removed and toml is recommended instead. However it seems each time the toml plugin writes to the file it eats the first character of each key:

## Steps to Reproduce the Problem

```sh
root@OpenWrt:~/.config# kdb ls user:/
root@OpenWrt:~/.config# ls
root@OpenWrt:~/.config# kdb set user:/test/abcdef 1
Create a new key user:/test/abcdef with string "1"
root@OpenWrt:~/.config# ls
default.ecf
root@OpenWrt:~/.config# cat default.ecf 
est.abcdef = 1
root@OpenWrt:~/.config# kdb ls user:/
user:/est/abcdef
root@OpenWrt:~/.config# kdb set user:/test/xyz 2
Create a new key user:/test/xyz with string "2"
root@OpenWrt:~/.config# kdb ls user:/
user:/est/xyz
user:/st/abcdef
root@OpenWrt:~/.config# cat default.ecf 
st.abcdef = 1
est.xyz = 2
```

If your key database (KDB) might influence the outcome, please use `kdb stash`
to temporarily have an empty KDB. (Restore instructions are printed.)

## Expected Result

The keys should remain stable across any calls to `kdb set`

## Actual Result

Every time I use `kdb set` all keys got shorter by one character.

## System Information

- Elektra Version: 0.9.6
- OpenWRT 21.02.0-rc3

### PR DESCRIPTION
**Pull request by kodebach**
Fixes #3896

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [x] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [x] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by kodebach** [comment]
@markus2330 please confirm this fixes the issue. @mpranj please merge ASAP (assuming the build servers will be satisfied)

**Review by mpranj — APPROVED** [review]
Great work!

**Comment by markus2330** [comment]
@kodebach thank you for the quick fix!

> please confirm this fixes the issue

The goal is still to have a fully supported TOML as default storage, #3896 might be only one of several problems.

Can you rebase #3478 and #3500 to see if less (or even none) problems occur on the build server now with TOML as default?

**Comment by kodebach** [comment]
The PRs are now rebased

**Pull request merged**
