### PR TITLE
Update Clang-Format Style

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request slightly modifies the current code style. After the PR both

- the outdated<a href="#footnote1" id="foot1"><sup>1</sup></a> Clang-Format 5.0
- and current versions of Clang-Format (6.0, 7.0) 

produce the same formatted output for the whole codebase.

<a id="footnote1" href="foot1"><sup>1</sup></a> This comment might contain an opinion of the author of this PR

# Checklist

- [x] I checked all commit messages.
- [x] I ran all tests and everything went fine
- [x] The PR contains an updated version of the release notes.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build docker please

**Comment by markus2330** [comment]
I like the space before casts and "// end namespace" but the new formatting for enum breaks the otherwise consistent style.

Is amazing that you found a combination where clang-format is consistent is across versions. The big question is if someone will come up with new code where clang-format 5, 6, and 7 is not consistent?

**Comment by sanssecours** [comment]
> I like the space before casts and "// end namespace" but the new formatting for enum breaks the otherwise consistent style.

The style for enums is not consistent anyway, since Clang-Format 5.0 [does not add a newline after `typedef enum`](https://reviews.llvm.org/D37143?id=113035). We could upgrade to Clang-Format 6.0 though. I just pushed changes doing just that.

> The big question is if someone will come up with new code where clang-format 5, 6, and 7 is not consistent?

While it is certainly possible, it is highly unlikely.

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
As discussed at the meeting today, I just restored the old version of the PR.

**Comment by sanssecours** [comment]
> Can you also leave the commit with the enum improvement in the history (and revert it), so that we can revert it again somewhere in the future when llvm5 gets obsolete? Or write both variants in the config file and comment the one that triggers the bug in llvm5 out.

I prefixed the buggy option with a comment character and added a [ToDo](https://github.com/ElektraInitiative/libelektra/pull/1836/files#diff-69a68f7ce1ea3687a38d8e4705e6fa48R19) to `.clang-format`. Hope that works for you.

> Do we now check llvm5+6+7 with travis?

Before the latest update we checked the code with Clang-Format 5 and Clang-Format 7. I now also added Clang-Format 6 to one of the Linux build jobs.

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Build finished. No test results found.

**Comment by markus2330** [comment]
Sorry, I had to stop Jenkins. The machine got completely unresponsive (far beyond Jenkins) because backup and raid sync were running. I'll post updates to #160. (Hopefully we can also upgrade to latest Jenkins without disrupting everything again.)

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Thank you for this! Seems like github does not recognize it as merged because of a rebase.

**Pull request merged**
