### PR TITLE
Fixsync

### PR DESCRIPTION
**Pull request by markus2330**
## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [ ] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

@markus2330 please review my pull request

## Merging

Please add the "ready to merge" label when the build server and you say
that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
@petermax2 can you check if this fixes the fcrypt problem?

**Comment by petermax2** [comment]
> @petermax2 can you check if this fixes the fcrypt problem?

Your changes fix the problem! :tada:

**Comment by markus2330** [comment]
Thank you for the quick reply. I forgot to ask if it also still mounts sync in the other cases?

**Comment by petermax2** [comment]
> Thank you for the quick reply. I forgot to ask if it also still mounts sync in the other cases?

Yes, sir! :smile: 

```sh
root@5fd7ea8f213b:/libelektra/build# kdb mount test.ini user/test crypto_gcrypt "crypto/key=$(elektra-gpg-testkey)" base64 ini
root@5fd7ea8f213b:/libelektra/build# cat /etc/kdb/elektra.ini 
[mountpoints]
user\/test = This is a configuration for a backend, see subkeys for more information
user\/test/config = 
user\/test/config/path = test.ini
user\/test/errorplugins = 
user\/test/errorplugins/#5#resolver_fm_hpu_b#resolver# = 
user\/test/getplugins = 
user\/test/getplugins/#0#resolver = 
user\/test/getplugins/#5#ini#ini# = 
user\/test/getplugins/#8#base64#base64# = 
user\/test/getplugins/#9#crypto_gcrypt#crypto_gcrypt# = 
user\/test/getplugins/#9#crypto_gcrypt#crypto_gcrypt#/config = 
user\/test/mountpoint = user/test
user\/test/setplugins = 
user\/test/setplugins/#0#resolver = 
user\/test/setplugins/#1#crypto_gcrypt = 
user\/test/setplugins/#2#base64 = 
user\/test/setplugins/#5#ini = 
user\/test/setplugins/#6#sync#sync# = 
user\/test/setplugins/#7#resolver = 
[mountpoints/user\/test/getplugins/#9#crypto_gcrypt#crypto_gcrypt#/config/crypto]
key = 6C2CE3467EBF1BF8F5968792575C5FE620FA0712
masterpassword = "hQGMA1dcX+Yg+gcSAQv8DXuni9IkwOT9JZcCLG8GJDB8US2e4SvqKVS9LlDnqzgPhnlAvP0y/beB+v+s45I/lRtG2JnNp8R3dtl90YWKsBdFWA=="
root@5fd7ea8f213b:/libelektra/build# 
```

**Comment by markus2330** [comment]
Basically the output of:

```
kdb mount a.ecf /tests/something
kdb mountpoint-info /tests/something
kdb ls "system/elektra/mountpoints/\/tests\/something"
```

**Comment by markus2330** [comment]
Perfect, thank you! You typed faster than me :smile:

**Comment by markus2330** [comment]
See also  #2636 (follow up issue)

**Pull request merged**
