### PR TITLE
Fix for #1890

### PR DESCRIPTION
**Pull request by waht**
# Purpose

Fixed use of LibAddBinding CMake API and added quick introduction for it.

# Checklist

- [x] commit messages are fine ("module: short statement" syntax and refer to issues)
- [x] I ran all tests locally and everything went fine
- [x] release notes are updated (doc/news/_preparation_next_release.md)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for this fix even though the issue was already closed. It is great to see such kind of maintenance!

**Comment by ingwinlu** [comment]
jenkins build all please

**Comment by ingwinlu** [comment]
@waht can you rebase on the current master and run all tests again?

-lang, -log and -optimizations should not be affected by the changes in this pr.

**Comment by ingwinlu** [comment]
jenkins build all please

**Comment by waht** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Can we merge this for the upcoming release?

Seems like the first workaround for this problem was already needed in #1866.

**Comment by waht** [comment]
I tried to resolve the conflict with the web editor which lead to a "Merge"-Commit. If this is a problem, I can fix the issue tomorrow evening on my pc.

**Comment by sanssecours** [comment]
> I tried to resolve the conflict with the web editor which lead to a "Merge"-Commit. If this is a problem, I can fix the issue tomorrow evening on my pc.

I just rebased the branch on `master`. Hopefully I did not destroy anything in the process…

**Comment by markus2330** [comment]
Thank you for the update!

@ingwinlu should I first merge this or first merge #1866?

**Comment by ingwinlu** [comment]
this then I will verify the issue is fixed in #1866

**Comment by ingwinlu** [comment]
```
CMake Warning (dev) at src/plugins/haskell/CMakeLists.txt:3 (add_haskell_plugin):
  A logical block opening on the line
    /home/jenkins/workspace/elektra-jenkinsfile/cmake/Modules/LibAddHaskellPlugin.cmake:45 (if)
  closes on the line
    /home/jenkins/workspace/elektra-jenkinsfile/cmake/Modules/LibAddHaskellPlugin.cmake:244 (endif  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by markus2330** [comment]
I cannot reproduce. How do you get this warning?

Line 45 and 244 both have exactly the same arguments (`FINDEX GREATER -1`).

Please open separate issues for bugs.

**Comment by ingwinlu** [comment]
done in #1961

**Comment by sanssecours** [comment]
> Line 45 and 244 both have exactly the same arguments (`FINDEX GREATER -1`).

That is not the case in the `master` branch as far as I can tell. I (hopefully) fixed the problem in commit 61981101.

**Comment by ingwinlu** [comment]
jup everything is peachy again

**Pull request merged**
