### PR TITLE
travis: build qt-gui, use new travis macOS images, remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by mpranj**
add qt5 for qt-gui

### CODE REVIEW

**Comment by markus2330** [comment]
Does it impact the build time a lot? Is there some way to download Elektra from travis for Mac OS X users?

**Comment by markus2330** [comment]
Thank you, looks great. Seems like Travis also works for PRs now.

**Comment by mpranj** [comment]
Seems like it adds about two or minutes to builds. I think that is mostly due to package download+install time.

Other than that the OS X containers are all single core, so no option to speed it up there. Travis suggests to split the build in parts and test different things in parallel using the build matrix and env variables.

**Comment by mpranj** [comment]
We could save *a lot* of time by not installing java as #763 currently doesn't work anyway. I'll at least check the time difference now.

**Comment by markus2330** [comment]
Any progress here? Why is libffi needed?

**Comment by mpranj** [comment]
This thing was done at the time of the PR. Now I need to re-check it.

**Comment by markus2330** [comment]
Ok, please say when I can merge it.

**Comment by markus2330** [comment]
Seems like travis is broken now?

**Comment by mpranj** [comment]
@markus2330 done.

**Comment by markus2330** [comment]
Thank you, well done!

**Pull request merged**
