### PR TITLE
Use `type` metakey as fallback in range plugin

### LINKED ISSUE #3984: check/range uses check/type and not type
I'd like to fix this as part of my thesis.

Is this a sensible improvement or is there a reason for the current behavior?

check/range does not respect the `type` of a key. It uses the value of `check/type` and if none is set it defaults to `long long` (see https://www.libelektra.org/plugins/range).

If one does not carefully read the documentation, the current behavior is irritating.

## Steps to Reproduce the Problem

1. Create file `test.ini` with content: 
```
[]
mountpoint = test.ecf

[myfloat1a]
type = float
check/range = 0-1

[myfloat1b]
type = float
check/range = 0.0-1.0

[myfloat1c]
type = float
check/type = float
check/range = 0.0-1.0
```

2. ``sudo kdb mount -v `pwd`/test.ini spec:/tests/test ni``
3. `sudo kdb spec-mount /tests/`
4. `kdb set /tests/test/myfloat1a 1.1`
5. `kdb set /tests/test/myfloat1b 1.1`
6. `kdb set /tests/test/myfloat1c 1.1`

## Expected Result

kdb output for step 4 should be:
```
Using name user:/tests/test/myfloat1a
Sorry, module range issued the error C03200:
Validation Semantic: Value '1.1' of key 'user:/tests/test/myfloat1a' not within range 0.0-1.0
```

kdb output for step 5 should be:
```
Using name user:/tests/test/myfloat1b
Sorry, module range issued the error C03200:
Validation Semantic: Value '1.1' of key 'user:/tests/test/myfloat1b' not within range 0.0-1.0
```

kdb output for step 6 is:
```
Using name user:/tests/test/myfloat1c
Sorry, module range issued the error C03200:
Validation Semantic: Value '1.1' of key 'user:/tests/test/myfloat1c' not within range 0.0-1.0
```

### kdb output for step 4 is:
```
Using name user:/tests/test/myfloat1a
Set string to "1.1"
```

**Problem**: check/range accepted `1.1` because the truncated long long `1` is <= 1.

### kdb output for step 5 is:
```
Using name user:/tests/test/myfloat1b
Sorry, module range issued the error C03100:
Validation Syntactic: Invalid syntax: 0.0-1.0
```

**Problem**: check/range reports that the range `0.0-1.0` is invalid, because `check/type` is not set, defaults to `long long` and neither `0.0` nor `1.0` is a valid `long long`.

### kdb output for step 6 is:
 correct. check/range successfully detected that `1.1 > 1.0`
```
Using name user:/tests/test/myfloat1c
Sorry, module range issued the error C03200:
Validation Semantic: Value '1.1' of key 'user:/tests/test/myfloat1c' not within range 0.0-1.0
```

## System Information

- Elektra Version: 0.9.7
- Operating System: Ubuntu 20.04
- Versions of other relevant software: n/a

### PR DESCRIPTION
**Pull request by qwepoizt**
Fixes #3984.

Changes the range plugin to use `type` metakey as fallback if `check/type` is not given.

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [x] make all unit tests pass
  - [x] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [x] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by qwepoizt** [comment]
@markus2330 The builds currently fail because:

1. Building C object `src/bindings/io/glib/CMakeFiles/testio_glib.dir/testio_glib.c.o` fails because it uses a function which requires C11 standard.
2. (coveralls.io currently responds with status 503, but that's a transient problem).

Do you have an idea how to fix 1.? I haven't found evidence of this having occurred with any previous PRs but I also don't see how my changes correlate to this problem.

## Excerpt from build (Clang, clang, clang++, ON, NODEP, ALL, ALL;-rust)

```
[329/751] Building C object src/bindings/io/glib/CMakeFiles/testio_glib.dir/testio_glib.c.o
FAILED: src/bindings/io/glib/CMakeFiles/testio_glib.dir/testio_glib.c.o 
/usr/local/opt/llvm/bin/clang  -Isrc/include -I../src/include -I../tests/cframework -I../src/bindings/io/glib/SYSTEM -I/usr/local/Cellar/glib/2.70.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.70.0/lib/glib-2.0/include -std=gnu99  -Wno-deprecated-declarations  -Wstrict-prototypes -Werror -Wno-long-long -Wpedantic -Wno-variadic-macros -Wall -Wextra -Wno-overlength-strings -Wsign-compare -Wfloat-equal -Wformat -Wformat-security -Wshadow -Wcomments -Wtrigraphs -Wundef -Wuninitialized -Winit-self -Wsign-compare -Wfloat-equal -O2 -g -DNDEBUG -isysroot /Applications/Xcode-12.5.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11.2 -MD -MT src/bindings/io/glib/CMakeFiles/testio_glib.dir/testio_glib.c.o -MF src/bindings/io/glib/CMakeFiles/testio_glib.dir/testio_glib.c.o.d -o src/bindings/io/glib/CMakeFiles/testio_glib.dir/testio_glib.c.o -c ../src/bindings/io/glib/testio_glib.c
In file included from ../src/bindings/io/glib/testio_glib.c:17:
In file included from /usr/local/Cellar/glib/2.70.0/include/glib-2.0/glib.h:30:
In file included from /usr/local/Cellar/glib/2.70.0/include/glib-2.0/glib/galloca.h:32:
/usr/local/Cellar/glib/2.70.0/include/glib-2.0/glib/gtypes.h:463:3: error: '_Static_assert' is a C11 extension [-Werror,-Wc11-extensions]
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^
/usr/local/Cellar/glib/2.70.0/include/glib-2.0/glib/gmacros.h:819:31: note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
                              ^
1 error generated.
```

**Comment by markus2330** [comment]
@mpranj do you maybe have an idea about the glib compilation error?

**Comment by mpranj** [comment]
> do you maybe have an idea about the glib compilation error?

Yes, the problem was introduced upstream and the glib homebrew package was recently updated from 2.68.4 to 2.70.0.

I think it can be ignored in this PR as nothing related was changed.

**Comment by markus2330** [comment]
A special thanks for the docu updates!

**Pull request merged**
