### PR TITLE
YAJL: Save Value Directly Below Mountpoint

### PR DESCRIPTION
**Pull request by PhilippGackstatter**
## Basics

Do not describe the purpose here but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [x] I added unit tests
- [x] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed.

## Example
It is now possible to write a value directly to the mountpoint and have it saved to the file.
```shell
$ kdb mount config.json system/lvas/cm/yajl yajl
$ echo "{}" > config.json 
$ kdb set system/lvas/cm/yajl "string_value"
Set string to "string_value"
$ kdb get system/lvas/cm/yajl 
string_value
$ cat $(kdb file system/lvas/cm/yajl)
"string_value"
```

## Questions

I should probably add a comment to explain the additional code in `elektraYajlSet`, since it is not obvious what the 3 conditions test for? Or maybe a debug log statement would do the same implicitly?

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you very much for this PR! It goes to the right direction but the build server is not happy yet.

**Comment by PhilippGackstatter** [comment]
There are still tests failing, but I can't figure out what's wrong just from the logs on the CI. How can I run `testshell_markdown_yajl` on my machine, so I can figure out what it's actually doing? And where is it defined? I'm using cmake and make for building, but `make run_all` only runs 105 tests on my machine whereas the CI machines run 230 tests. And `kdb run_all` also just runs 90 tests. And none of these runs the mentioned test.

And the `testscr_check_real_world` test fails on my machine also when I use the latest master branch, so I'm not sure where to start there either.

**Comment by kodebach** [comment]
There are a few different problems here:
- You didn't add a line to the release notes, so the [Jenkins build server](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2548/2/pipeline) aborts very early.
- [Travis](https://travis-ci.org/ElektraInitiative/libelektra/jobs/513196959#L1762) shows that your code wasn't formatted correctly (thats the next reason Jenkins would abort, if you added release notes). Just follow the instructions directly in Travis' log of `testscr_check_formatting` to fix the problem.
- [This Travis build](https://travis-ci.org/ElektraInitiative/libelektra/jobs/513196956#L3899) fails because of `testshell_markdown_yajl`. The `testshell_markdown_*` tests are generated from any shell code inside the README of plugins. The test log also shows which shell commands where executed and then prints the full log. The syntax used is a special [shell recorder syntax](https://github.com/ElektraInitiative/libelektra/tree/master/tests/shell/shell_recorder) (see also [here](https://github.com/ElektraInitiative/libelektra/tree/master/tests/shell/shell_recorder/tutorial_wrapper)).
- The output of CMake should also show you why the `yajl` plugin isn't built on your machine. Something like [this](https://travis-ci.org/ElektraInitiative/libelektra/jobs/513196955#L1452). The library you need is called `libyajl-dev` on Debian, your distro may call it something different (Fedora calls it `yajl-devel` for example).

If you ever have more difficult to reproduce problems, you can also use one of the [docker images](https://github.com/ElektraInitiative/libelektra/tree/master/scripts/docker) the Jenkins server uses.

**Comment by sanssecours** [comment]
Looks like some of the more recent changes to the `master` branch created a merge conflict. Can you please rebase your PR branch on `master` and then force push your changes afterwards?

**Comment by PhilippGackstatter** [comment]
Thank you @kodebach, that was very helpful!
I rebased my changes to master.

**Comment by markus2330** [comment]
Thank you very much!

**Comment by markus2330** [comment]
@PhilippGackstatter to answer your questions:

> How can I run testshell_markdown_yajl on my machine, so I can figure out what it's actually doing?

You need to install libyajl-dev. CMake should output this information.

> And where is it defined?

In the CMake variable PLUGINS, but it will automatically pick everything where the dependencies are installed.

> I'm using cmake and make for building, but make run_all only runs 105 tests on my machine whereas the CI machines run 230 tests. And kdb run_all also just runs 90 tests. And none of these runs the mentioned test.

This is due to differences on how many dependencies you have installed locally.

> And the testscr_check_real_world test fails on my machine also when I use the latest master branch, so I'm not sure where to start there either.

Can you please report this problem in a separate issue? (Including output)

**Pull request merged**
