### PR TITLE
Rust: Rewrite KDBError

### LINKED ISSUE #3059: Rust: OutOfMemory is not a subtype of a general resource error
The error specification is defined as

- Permanent errors C01000
    - Resource C01100
        - Memory Allocation C01110

In Rust, due to lack of inheritance, the errors are implemented as nesting enums to allow for i.e. catching all types of permanent errors, as it would be with catching a PermanentErrorException in Java.

This works great as long as only the leafs of this tree are concrete errors. However, resource errors are the exception to this case, since they can also be a concrete error.

This is currently implemented like this

```rust
pub enum ResourceError {
    GeneralResourceError(KDBErrorWrapper),
    OutOfMemory(KDBErrorWrapper),
}
```

`OutOfMemory` errors have their own enum variant, but any other Resource error is wrapped in `GeneralResourceError`, which means that they are distinct variants and `OutOfMemory` is not a subtype of `GeneralResourceError` as it should be according to the spec.

I don't think this is a big problem, since you can still catch all types of resource errors with
 
```rust
if let KDBError::Permanent(PermanentError::Resource(err)) = kdb_open_result {
    // Now match which exact resource error we got
    match err {
        ResourceError::GeneralResourceError(resource_err) => { /* handle */ },
        ResourceError::OutOfMemory(oom_err) => { /* handle */ }
    }
}
 ```

@markus2330 wrote in #3047 

> OutOfMemoryError should be a subtype of the ResourceError.

From the user perspective it seems to work. Why do you think this is an issue?

### PR DESCRIPTION
**Pull request by PhilippGackstatter**
fixes #3059 

This implements `KDBError` using string matching in particular to allow using `kdb_error.is_resource()` to also catch an out of memory error, as the specification demands.

I additionally smoothed out some points in the documentation and the Readme.

I also added a `keyset!` macro that I think will be useful to easily create a larger keyset in a single invocation, similar to `ksNew`. Up until now all keys had to be added with a new `ks.append_key(...)` statement.

With the macro you can do

```rust
let ks = keyset![
    StringKey::new("user/test1").unwrap(),
    StringKey::new("user/test2").unwrap(),
    StringKey::new("user/test3").unwrap(),
];
```

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating this PR!

> With the macro you can do

Please add this to the docu.

**Comment by PhilippGackstatter** [comment]
> Please add this to the docu.

It's mentioned in the Readme and also in the libraries documentation. Is that what you mean?

**Comment by markus2330** [comment]
I did not see the example

```
let ks = keyset![
    StringKey::new("user/test1").unwrap(),
    StringKey::new("user/test2").unwrap(),
    StringKey::new("user/test3").unwrap(),
];
```

in the docu, only in the PR description and in the tests.

> It's mentioned in the Readme and also in the libraries documentation. Is that what you mean?

If it is mentioned there, then everything is perfect.

**Comment by PhilippGackstatter** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
