### PR TITLE
fix bash shebang in scripts for better portability

### PR DESCRIPTION
**Pull request by jirutka**
# Purpose

Bash is not always installed in `/bin`! For example BSDs install Bash into `/usr/local/bin`. Practically every *nix system has `/usr/bin/env`.

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [ ] commit messages are fine (with references to issues)
- [ ] I added unit tests
- [ ] I ran all tests and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you, nice catch!

Afaik Elektra is used on BSD but seems like these scripts were never executed there.

Looking forward to see further contributions from you! How should I call you in the next release notes (doc/news/_preparation_next_release.md)? Is the full name "Jakub Jirutka" okay?

**Comment by markus2330** [comment]
jenkins build all please

**Comment by jirutka** [comment]
> Is the full name "Jakub Jirutka" okay?

Yes, of course! 😺

**Comment by markus2330** [comment]
Looks good, the first tests passed successfully. Thus the jobs will now run anyway I'll wait until tomorrow for merging.

**Comment by markus2330** [comment]
Thank you, great job!

**Pull request merged**
