### PR TITLE
Add sanity-checks for keys to "kdb spec-mount" command

### LINKED ISSUE #3983: No validation warning when check/enum is used with type=string
I'd like to fix this as part of my thesis.

I am not sure if this is a user error. 

Would it make sense to improve usability by either:
1. throwing an error on mount (or spec-mount?) if a key uses `type=string` and `check/enum` (instead of `type=enum`)
2. or adding support for keys using `type=string` and `check/enum` (instead of `type=enum`)

?

## Steps to Reproduce the Problem

1. Create file `test.ini` with content: 
```
[]
mountpoint = test.ecf

[myenum]
type = string
check/enum = #1
check/enum/#0 = legalvalue1
check/enum/#1 = legalvalue2
```

2. ``sudo kdb mount -v `pwd`/test.ini spec:/tests/test ni``
3. `sudo kdb spec-mount /tests/test/`
4. `kdb set /tests/test/myenum neitherlegalvalue1nor2`

## Expected Result

kdb output for step 4 should be:
```
Using name user:/tests/test/myenum
Sorry, module type issued the error C03200:
Validation Semantic: The type 'string' failed to match for 'user:/tests/test/myenum' with string: 'neitherlegalvalue1nor2'
Allowed values: 'legalvalue1', 'legalvalue2'
```

## Actual Result
kdb output for step 4 is:
```
Using name user:/tests/redshift/provider/location
Create a new key user:/tests/redshift/provider/location with string "asdf"
```

## System Information

- Elektra Version: 0.9.7
- Operating System: Ubuntu 20.04
- Versions of other relevant software: n/a

### PR DESCRIPTION
**Pull request by qwepoizt**
Improves problems described in #3983 and #3987.

(This PR should not close these issues).

I've implemented several sanity checks in the spec-mounter.

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [x] make all unit tests pass
  - [x] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by qwepoizt** [comment]
@markus2330: I've implemented several sanity checks in the spec-mounter.

I think this is a good solution for #3987 and #3983: When someone creates a specification file and then executes kdb spec-mount ... to test/use it, they will receive errors if one of the sanity checks fails!

I think I can say from experience that these checks will help a lot, especially if someone is just getting started with Elektra/specification files. They cover the mistakes I made while writing the specification for redshift.

**Review by markus2330 — APPROVED** [review]
Thank you very much for this improvement! Fixes for problems you actually ran into are very valuable. Nevertheless we should leave the issues open (or create new ones) as it would be better if such inconsistencies cannot happen at all (better design of the specification).

**Comment by qwepoizt** [comment]
> Nevertheless we should leave the issues open.

Okay, I've edited the description of this PR so it won't auto close them!

**Comment by qwepoizt** [comment]
@markus2330: Currently, a test is failing in this PR, because I have not included "int" as an allowed value for the "type" metakey, but the following test uses a specification file with "type=int".

https://github.com/ElektraInitiative/libelektra/blob/5702ce0496823fdd12c4e1e6ff9d6d1ca1b71a40/tests/shell/gen/highlevel/nodefault.data.ini#L1-L5

Is "int" allowed?

* It is not documented in https://github.com/ElektraInitiative/libelektra/tree/master/doc/METADATA.ini
* It is used in a few places, e.g.:

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/doc/METADATA.ini#L356-L357

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/doc/METADATA.ini#L77-L80

https://github.com/ElektraInitiative/libelektra/blob/90fb5bef6bf2c899d8b90af90d08b99140ae6666/doc/METADATA.ini#L1191-L1195

**Comment by qwepoizt** [comment]
@markus2330: Another check is also failing, namely the "Check" check:

```
doc/news/2018-11-18_0.8.25.md:343:0 http://coveralls.io
doc/news/2019-08-06_0.9.0.md:786:0 https://coveralls.io/github/ElektraInitiative/libelektra
doc/news/2020-05-26_0.9.2.md:274:0 https://coveralls.io/github/ElektraInitiative/libelektra
doc/news/2015-04-03_0.8.11.md:288:0 https://www.libelektra.org/ftp/elektra/pancheri2015gui.pdf
doc/news/2016-12-17_website_release.md:48:0 https://www.libelektra.org/ftp/elektra/mall2016rest.pdf
doc/news/2016-04-29_0.8.16.md:326:0 https://www.libelektra.org/ftp/elektra/berlakovich2016universal.pdf
```

* Have you maybe changed something on https://www.libelektra.org/ftp/elektra/ ?
* I also hope that `coveralls.io` will be back to service soon. It is in maintenance mode, responding with status 503 since Sep 17th. So far none of my PRs were blocked by this. 
* Is there an alternative to removing the coverall links from the old release notes?

**Comment by qwepoizt** [comment]
Thanks for your comment!

I've fixed the usage that made the test fail and created a new issue for a more detailed inspection of this. I've also marked it as "floss2021W", seems like a good issue to start!

I'll wait for the results of the checks.

**Comment by qwepoizt** [comment]
@markus2330: This is now ready to merge.

The 4 unsuccessful checks are caused by:

* 3 broken links, which will soon be updated (https://github.com/ElektraInitiative/libelektra/pull/4058#issuecomment-924129108)
* An unrelated problem introduced in upstream glib (https://github.com/ElektraInitiative/libelektra/pull/4055#issuecomment-923896311)

**Comment by markus2330** [comment]
Thank you very much! :sparkling_heart:

**Pull request merged**
