### PR TITLE
3246 fix kdb exec path

### LINKED ISSUE #3246: KDB_EXEC_PATH should not be set in installed test scripts
> No, KDB_EXEC_PATH is not set for an installed kdb (unless the user sets it)

I just took the master version of Elektra and installed it. The file `/usr/local/lib/elektra/tool_exec/check_meta` contains the line:

```sh
export KDB_EXEC_PATH="/home/klemens/libelektra/build/bin:$KDB_EXEC_PATH"
```

Of course this doesn't affect `testmod_*` tests, but it is wrong nonetheless. I will create a new issue.

_Originally posted by @kodebach in https://github.com/ElektraInitiative/libelektra/issues/2856#issuecomment-554971666_

---

Setting `KDB_EXEC_PATH` in installed test scripts not necessarily wrong, but it should **not** contain the build directory. It wouldn't matter, if the build directory no longer exists. But tests could break, if the build directory contains different versions of the test scripts.

We should use a solution similar to the one that is used for the `$KDB` variable. It is only set to `${CMAKE_BINARY_DIR}/bin/kdb` in the `testscr_*` variants of the tests, which are not installed.

### PR DESCRIPTION
**Pull request by petermax2**
resolves #3246 .

## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by mpranj** [comment]
Thank you for contributing so many fixes! 😊

**Comment by petermax2** [comment]
How come that the suppression:

    {
       <insert_a_suppression_name_here>
       Memcheck:Leak
       match-leak-kinds: all
       ...
       obj:*/bin/kill*
       ...
    }

does not suppress the following leak:

			<Log>==17296== Memcheck, a memory error detector
			==17296== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
			==17296== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
			==17296== Command: /bin/kill 9287 9288
			==17296== Parent PID: 17283
			==17296== 
			==17296==17283== 
			==17283== HEAP SUMMARY:
			==17283==   ==17279== 
			==17279== HEAP SUMMARY:
			==17279==     in use at exit: 2,112 bytes in 60 blocks
			==17279==   total heap usage: 62 allocs, 2 frees, 2,248 bytes allocated
			==17279== 
			==17279== LEAK SUMMARY:
			==17279==    definitely lost: 0 bytes in 0 blocks
			==17279==    indirectly lost: 0 bytes in 0 blocks
			==17279==      possibly lost: 0 bytes in 0 blocks
			==17279==    still reachable: 2,112 bytes in 60 blocks
			==17279==         suppressed: 0 bytes in 0 blocks
			==17279== Reachable blocks (those to which a pointer was found) are not shown.
			==17279== To see them, rerun with: --leak-check=full --show-leak-kinds=all

Do you have any ideas?

**Comment by petermax2** [comment]
Killing the `gpg-agent` on Debian unstable still triggers memory leak detection.

**Comment by petermax2** [comment]
Since the error from #2341 popped up again, I moved the gpg-agent shutdown code into a KDB tool, so I can write a proper valgrind suppression for it. Also re-enabled the memory checks for gpgme and fcrypt. Please keep an eye on the build server and reopen #2341 if the gpg-agent shutdown fails again.

**Comment by petermax2** [comment]
I forgot to push my last changes. :blush:  gimme a second xD

**Comment by markus2330** [comment]
Tell me when you are ready :wink: 

Does gpgQuitAgent really need to be part of the plugin? Why it is not possible to write a suppression in other cases?

**Comment by petermax2** [comment]
> Does gpgQuitAgent really need to be part of the plugin? Why it is not possible to write a suppression in other cases?

The error still occurs and I reopened #2341 again. I will fix it but outisde of the scope of this PR. Let's keep this change simple.

**Comment by petermax2** [comment]
`testscr_check_formatting` failed on Alpine.

**Comment by petermax2** [comment]
Alpine found a strange formatting issue I can not explain:

	diff --git a/src/plugins/specload/specload/remove.quickdump b/src/plugins/specload/specload/remove.quickdump
	index ccedf5000..e69de29bb 100644
	Binary files a/src/plugins/specload/specload/remove.quickdump and b/src/plugins/specload/specload/remove.quickdump differ

Other than that, I'm ready for review and merge, @markus2330 . I will continue to work on #2341 in a separate PR.

**Comment by kodebach** [comment]
> Alpine found a strange formatting issue I can not explain: [...]

Did you try rerunning the job? Normally these errors go away with a rerun.

**Comment by petermax2** [comment]
I am following up the gpg-agent issue (#2341 ) in PR #3410 .

**Comment by petermax2** [comment]
@kodebach could you also please verify if the issue #3246 is resolved with this PR?

**Pull request merged**
