### PR TITLE
test: Fix is_not_rw_storage

### PR DESCRIPTION
**Pull request by llukask**
## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

@markus2330 please review my pull request

## Merging

Please add the "ready to merge" label when the build server and you say
that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for working on this! Seems like you already solved follow-up problems that turned up after you fixed the function?

**Comment by llukask** [comment]
@markus2330 Yes to get the tests to run again, I did manually exclude the following plugins from `is_not_rw_storage`:

- `desktop`, `c`, `cpptemplate`, `specload` because they are not really rw-storage plugins
- `mmapstorage`and `mmapstorage_crc` because they can't export to stdout (#2419)
- `tcl`, `mini`, `simpleini` because they can't deal with values at the root of the exported hierarchy (see my comment on #2423)
- `yambi` because it does not seem to export anything at all

**Comment by llukask** [comment]
I added test files for `xerces` and excluded `yamlcpp` because it does not export anything

**Comment by sanssecours** [comment]
> `yambi` because it does not seem to export anything at all

YAMBi (Yan LR, YAwn, and YAy PEG) do not include write support. They all use [YAML Smith](https://www.libelektra.org/plugins/yamlsmith) to write data back to a YAML file.

> …and excluded `yamlcpp` because it does not export anything.

Are you sure about that? I tried the following, which seems to work:

```sh
kdb set user/tests/key value
kdb export user/tests yamlcpp
#> key: value
kdb export user/tests/key yamlcpp
#> value
```

.

**Comment by llukask** [comment]
@sanssecours 

> …and excluded yamlcpp because it does not export anything.
Yes, thats not correct.

The problem I encountered with yamlcpp is that like `yajl` it cannot hold values in directories.

i.e.
```
kdb set user/tests root
kdb set user/tests/key hello
kdb export user/tests yamlcpp
```
gives
```
key: hello
```
but if you omit setting `user/tests/key` exporting gives just `root`

**Comment by sanssecours** [comment]
> The problem I encountered with yamlcpp is that like `yajl` it cannot hold values in directories.

Thank you for the clarification. For this purpose YAML CPP requires the [Directory Value plugin](https://www.libelektra.org/plugins/directoryvalue). Unfortunately [`kdb export` ignores required plugins](https://github.com/ElektraInitiative/libelektra/issues/1178) 😢.

**Comment by markus2330** [comment]
To get this PR ready, I think we need to exclude these plugins now. But please mark that they should be readded (directly next to the list and in doc/todo/TESTING).

>  The problem I encountered with yamlcpp is that like yajl it cannot hold values in directories.

yajl should now be able to do so. The PR was merged recently.

**Comment by markus2330** [comment]
Any progress here?

**Comment by markus2330** [comment]
@kodebach can you take over #2423 and finish this PR?

**Comment by kodebach** [comment]
I'll do it once I've finished with #3102. (no PR yet, the code is still quite chaotic and broken)

**Comment by kodebach** [comment]
@markus2330 I rebased the branch, let's see what the build servers say...

**Comment by kodebach** [comment]
I added the test data for `toml` and `kconfig` and disabled the tests for them. I think this PR should now be done, let's see if the build server agrees...

@bauhaus93 You should probably try to fix the storage tests for the `toml` plugin, if we want to use it as a default storage plugin...

**Comment by markus2330** [comment]
Great job! :sparkling_heart:

**Comment by mpranj** [comment]
Thank you @llukask for fixing this and @kodebach for finishing it up! 🚀  Great job! 🥇

**Pull request merged**
