### PR TITLE
KConfig Get

### PR DESCRIPTION
**Pull request by darddan**
This has the same changes `https://github.com/ElektraInitiative/libelektra/pull/3249`, without the rebase problems.
I also changed the documentation mentions in the comments from the other PR.

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy.
- [x] The PR is rebased with current master.

## Checklist

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [x] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [x] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

### CODE REVIEW

**Comment by darddan** [comment]
@markus2330 There are some other broken links now :(.
Also, about the previous failed rebase, is it possible that there was a force push to master?
I use two remotes in my local branch `origin` which points to Elektra and `darddan` which points to the fork in my acount.
When I did `git pull origin master` and `git push darddan master` it said there were commits in `darddan` that were not in `origin`, which shouldn't have been true because I didn't commit anything there.

**Comment by markus2330** [comment]
> There are some other broken links now :(.

This is caused by server migration/restart. I'll retrigger the check when the problem is fixed.

> Also, about the previous failed rebase, is it possible that there was a force push to master?

Very unlikely, I pushed normally and pulling did not cause any problems.

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you, I am super-happy with this quick fix :sparkling_heart: 

I am looking forward for the next PR with write support and other improvements.

Please set "ready to merge" if a PR is finished from your perspective and build server passes.

**Pull request merged**
