### PR TITLE
[FLOSS H2] Upgrade Jenkins node to Debian bullseye

### PR DESCRIPTION
**Pull request by 0x6178656c**
Since the CMake version is now incompatible with the one from the Debian stretch repository, I upgraded the Dockerfile to use Debian bullseye.

The only change in packages was:

* `openjdk-8-jdk-headless` to `openjdk-11-jdk-headless`

I successfully ran

```sh
run-make-env
```

in the container.

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://master.libelektra.org/doc/contrib/documentation.md))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the PR, great job! Can you please also update scripts/docker/jenkinsnode/README.md

The README.md needs some overhaul, it is not confirming to the [Documentation Guidelines](https://master.libelektra.org/doc/contrib/documentation.md).

@lukashartl can you verify if this is still used or compatible with our Ansible setup of agents?

**Comment by 0x6178656c** [comment]
> Thank you for the PR, great job! Can you please also update scripts/docker/jenkinsnode/README.md
> 
> The README.md needs some overhaul, it is not confirming to the [Documentation Guidelines](https://master.libelektra.org/doc/contrib/documentation.md).
> 
> @lukashartl can you verify if this is still used or compatible with our Ansible setup of agents?

I read the documentation on the build process and it is actually not clear to me if this Docker image is still used at all? 

The documentation states that the Jenkins nodes should have Docker installed, but this is not the case for this image.
https://github.com/ElektraInitiative/libelektra/blob/master/doc/BUILDSERVER.md#adding-a-jenkins-node

I propose the following:
* If this image is still relevant this should be documented accordingly
* If this image is no longer used it should be removed from repository

**Comment by lukashartl** [comment]
@markus2330 

> @lukashartl can you verify if this is still used or compatible with our Ansible setup of agents?

It is not used for our main build agents. Those are already on bullseye and are using jdk 11. (ansible is also enforcing jdk 11)

I honestly don't know if anyone is still using this image?

**Comment by markus2330** [comment]
Thank you for the update&testing!

> I propose the following:

I agree, I created #4637.

**Pull request merged**
