### PR TITLE
Various Small Fixes

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This PR should fix issue #1721 and issue #1757.

# Checklist

- [x] I checked all commit messages twice.
- [x] I extended the Markdown Shell Recorder test of the INI plugin.
- [x] I ran all tests and everything went fine.
- [x] The release notes contain an item for the only noteworthy update in this PR.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by markus2330** [comment]
Thank you, great to see so many fixes!

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Thank you, great job!

**Pull request merged**
