### PR TITLE
Ckdb namespace removal

### PR DESCRIPTION
**Pull request by Piankero**
## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by Piankero** [comment]
@kodebach I opened this PR with the ckdb removals. If something is missing or I should correct something just tell me and I correct it.

PS: I couldn't push to your repo so I opened it from my branch

**Comment by markus2330** [comment]
Thank you for the PR, it looks very nice!

**Comment by kodebach** [comment]
It seems that `using namespace kdb;` no longer works and has to be replaced by `using kdb::Key;` (and  `using kdb::KeySet;` and  `using kdb::KDB;` if needed).

AFAICT this is because `using namespace kdb` just says to the C++ compiler that it should look in the namespace `kdb` in addition to the global namespace, if a symbol has no explicit namespace. The line `using kdb::Key;` meanwhile is a short form of `using Key = kdb::Key;` and says that `Key` now refers to `kdb::Key` and disables the normal namespace lookup.

This seems to be expected in C++ as [this StackOverflow comment](https://stackoverflow.com/questions/2518796/resolving-namespace-conflicts) suggests that when relying on 
`using namespace` you might as well not use namespaces at all.

**Comment by kodebach** [comment]
While we're changing namespaces: We should
 probably use the namespace `elektra::kdb` instead of `kdb` for C++. The namespace `kdb` is not very unique and could cause problems.

**Comment by markus2330** [comment]
> It seems that using namespace kdb; no longer works and has to be replaced by using kdb::Key; (and using kdb::KeySet; and using kdb::KDB; if needed).

Why? Which compile error? The build server only complains about wrong formatting.

> While we're changing namespaces

Why are we suddenly changing namespaces? The idea was only to remove the ckdb namespace. There should be no need to touch anything in the kdb namespaces.

> We should probably use the namespace elektra::kdb instead of kdb for C++. The namespace kdb is not very unique and could cause problems.

Please keep the PRs focused, #3115 has already grown to a monster. E.g. removing the quickdump legacy code could have been done easily in another PR?

**Comment by kodebach** [comment]
> Why? Which compile error? The build server only complains about wrong formatting.

Look at Travis or Cirrus.

> Why are we suddenly changing namespaces?

"Changing" was a poor choice of words. But we are working on namespaces, namely removing `ckdb`. I also didn't want to suggest that this should be done in this PR, just that it might be sensible at some point.

> Please keep the PRs focused, #3115 has already grown to a monster.


#3115 completely changes one of the most fundamental things in all of Elektra. Of course it is going to be a huge PR with many changes. Including some that are only somewhat related like the changes to quickdump.

> removing the quickdump legacy code could have been done easily in another PR?

I could have done that in a separate PR, we merge that and then I rebase #3115 yes. But I fail to see the advantage in that. Especially, since our build server is semi-broken at the moment.

**Comment by markus2330** [comment]
> Look at Travis or Cirrus.

I think this was the reason why I introduced ckdb in the first place. What about keeping ckdb only for KDB, Key and KeySet? This also has well-defined semantics (which cannot be said for the `extern "C"`/namespace mixture).

> "Changing" was a poor choice of words. But we are working on namespaces, namely removing ckdb. I also didn't want to suggest that this should be done in this PR, just that it might be sensible at some point.

I agree, so it was only a misunderstanding in an off-topic discussion :laughing: As always: new proposals can be made with new issues. But I am afraid this will again be a 2.0 topic.

> #3115 [...]

It is okay/necessary how #3115 is. I just do not want a second PR like this at the same time.

**Comment by kodebach** [comment]
> What about keeping ckdb only for KDB, Key and KeySet? This also has well-defined semantics (which cannot be said for the extern "C"/namespace mixture)

You mean putting `namespace ckdb { ... }` just around the 3 typedefs in `kdb.h`? Then we have the following problem:

Lets look at a shortened version of `kdb.h`:
```c
#ifdef __cplusplus
namespace ckdb {
#endif

typedef struct _KDB	KDB;
typedef struct _Key	Key;
typedef struct _KeySet	KeySet;

#ifdef __cplusplus
}

extern "C" {
#endif

KDB * kdbOpen(Key *errorKey);

#ifdef __cplusplus
}
#endif
```

In C obviously everything works, all of the `#ifdef`s are disabled, but in C++ this breaks AFAIK, since the C++ compiler doesn't know what `KDB` or `Key` is, it only knows `ckdb::KDB` and `ckdb::Key`.

**Comment by markus2330** [comment]
Let us make this PR low-priority. It seems to be not so easy.

**Comment by kodebach** [comment]
> Let us make this PR low-priority. It seems to be not so easy.

Agreed.

It might work the other way round, i.e. to require that **all of** Elektra's C API (i.e. anything that is part of header that is installed) is part of the `namespace ckdb`. Then there shouldn't be any need for `using namespace ckdb` in public header files either the header is only used in C++ (then `ckdb::Key` is the correct way), or it is a C header which means everything in it should also be in `namespace ckdb`.

However, I think for now leaving everything as is is probably the easiest solution.

**Comment by markus2330** [comment]
Yes, the other way around might be easier to implement.

> However, I think for now leaving everything as is is probably the easiest solution.

Yes. I also do not think this has high priority.

**Comment by markus2330** [comment]
I close it as it did not work out.

**Pull request closed without merging**
