### PR TITLE
[FLOSS H3] fix hashing collisions in specification token

### PR DESCRIPTION
**Pull request by lawli3t**
## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Review by flo91 — COMMENTED** [review]
Thanks for your PR, that looks like a really great improvement!

If I execute the testsuite `tests/ctest/test_sha-256.c`, which contains the test `test_streaming_aware_of_order` and is already present in current master, in the codebase of the master branch, it executes successfully.

I copied the test from issue #4110 as it is and it also succeeds with the Elektra version from the current master branch.

However, when I tried to execute your newly added test `test_hashesMetadata` in the testsuite `tests/ctest/test_hash.c`, it fails.
When I ran the new test on the codebase of your PR-branch, it succeeded, as already suggested by the passed buildserver checks.

I think to state that the PR close the issues #4110 (comment in line 85 of `src/libs/ease/hash.c`) can be misleading because the test that is mentioned in the description of that issue is already succeeding in the current master.

Maybe it would be better to create a new issue and link to it from the issue #4110 or at least post an update to the existing issue.
I don't know if the inclusion of the `\0` for calculating the hash value breaks any other things, but at least all tests in Docker and on the buildservers ran successfully, so that looks quite good.

Regarding the commit, it would be good to combine ("squash") the three "fix formatting" commits to one commit and add a module-prefix like written in the PR-description.

> Details of what you changed are in commit messages
> (first line should have `module: short statement` syntax)

A rebase with the current master branch is also necessary.

**Comment by lawli3t** [comment]
> I copied the test from issue #4110 as it is and it also succeeds with the Elektra version from the current master branch.

I think this is because there is an error in the test. The test should check for inequality, not equality in the line:

```
succeed_if (strcmp(string1, string2) == 0, "streaming API of sha_256 is not aware of order!");
```

**Comment by lawli3t** [comment]
squashed and rebased

**Comment by markus2330** [comment]
@lawli3t Elegant solution!

@flo91 Excellent review except I wouldn't push users into squashing commits. It is their decision.

**Comment by markus2330** [comment]
LGTM. Please add the label "ready to merge" if it is ready to merge.

**Comment by markus2330** [comment]
Excellent job! :fireworks:

**Pull request merged**
