### PR TITLE
make python2 a stub

### PR DESCRIPTION
**Pull request by manuelm**
And the other two left over commits which reduce the size of the python2 directory.

Please merge *after* the release :smile: 

Btw, generally I'm in favor of using variants, however I fail to see how this can be accomplished. e.g. if the user specifically want's compile python(3) or python2 only. The contents of the `PLUGINS` variable is directly connected with the expected directories. Also there's the problem with the missing exported symbol.

But one thing we really have to look into is to *not* link every plugin with kdb-full/kdb-static. Maybe by adding some sort of flag. But we can discuss both in a meeting or in a separate issue .

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build please

**Comment by manuelm** [comment]
jenkins build please

**Comment by manuelm** [comment]
jenkins build please

**Comment by manuelm** [comment]
jenkins build bindings please

**Comment by manuelm** [comment]
ready :+1:

**Comment by manuelm** [comment]
@markus2330 can you please merge this? I want to start working on adding the sub-interpreters for python.

**Comment by markus2330** [comment]
I thought we should give Kurt a Chance to look at it. But I merged it to not block you.

**Comment by manuelm** [comment]
Can take a look at lua instead. more interesting anyway.

**Comment by markus2330** [comment]
Already merged, you can also do subinterpreters. But do as you like.

**Pull request merged**
