### PR TITLE
Helper for merge tools

### PR DESCRIPTION
**Pull request by Chemin1**
Depends on #3234
Closes [this review](https://github.com/ElektraInitiative/libelektra/pull/3236#discussion_r347145639)

### CODE REVIEW

**Comment by raphi011** [comment]
jenkins build libelektra please

**Comment by Chemin1** [comment]
jenkins build libelektra please

**Comment by Chemin1** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you, I like these super-small PRs :+1:

**Pull request merged**
