### PR TITLE
python: test kdbEnsure

### PR DESCRIPTION
**Pull request by mpranj**
Test kdbEnsure from swig/python bindings.

## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by mpranj** [comment]
@manuelm is it possible that KDB::ensure from the cpp bindings was automatically wrapped correctly or is it highly likely that this fails? Please take a look if you have time to check if this PR makes any sense. I basically just added the relevant exception and a simple testcase.

**Comment by manuelm** [comment]
LGTM

**Comment by markus2330** [comment]
@kodebach do you also want to also have a look or even extend the example to be useful for commandline-options?

**Comment by kodebach** [comment]
I don't think the test case can (easily) be extended in a way that it would demonstrate the use of commandline-options, as this would require starting separate processes. If you want me to, I can add a separate python example, similar to e.g `examples/gopts.c`.

**Comment by markus2330** [comment]
Yes, a separate python example would be perfect! src/bindings/swig/python/examples/ is a good place.

**Comment by kodebach** [comment]
you can merge this, I will add the gopts python example in #3354

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
