### PR TITLE
Documentation: Fix Broken Links

### PR DESCRIPTION
**Pull request by sanssecours**

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you so much for fixing the links!

**Comment by markus2330** [comment]
Is this ready to merge? Any specific reason why you set "work in progress" here?

**Comment by sanssecours** [comment]
> Any specific reason why you set "work in progress" here?

The same reason as always: I usually do not want to receive comments about code changes until all build jobs finish successfully.

**Comment by markus2330** [comment]
Ok, thank you so much for fixing this!

**Pull request merged**
