### PR TITLE
Shell Recorder: Fix Syntax Error

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

Fix a syntax error in the Shell Recorder script

# Checklist

- [x] I checked the commit message. 
- [x] I ran all tests and everything went fine.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating this PR! Why is a syntax error low priority?

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
> Why is a syntax error low priority?

On most machines `/bin/sh` will just be a link to `bin/bash`. In Bash the command `[` handles the operator `==` without any problems. That is why I only noticed the problem after I executed the Shell Recorder on Debian, which uses Dash as default replacement for `sh`.

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build mergerequests-fast please

**Comment by sanssecours** [comment]
jenkins build fast please

**Comment by markus2330** [comment]
Strange, seems like build fast is broken, this also happened in #1730.

**Comment by sanssecours** [comment]
jenkins build fast please

**Comment by sanssecours** [comment]
> Strange, seems like build fast is broken…

Yep, build artifacts from the `typechecker` plugins caused the [error](https://build.libelektra.org/jenkins/job/elektra-mergerequests-fast/1738/console):

```
CMake Error at src/plugins/CMakeLists.txt:38 (include):
  include could not find load file:

    typechecker/CMakeLists.txt
```

.

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
>   Yep, build artifacts from the typechecker plugins caused the error

Is this problem already merged into master or did a previous build influence builds from these PRs?

**Comment by sanssecours** [comment]
> Is this problem already merged into master or did a previous build influence builds from these PRs?

As far as I can tell pull request #1792 caused the problem.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
