### PR TITLE
template: Added error template for out of memory errors

### PR DESCRIPTION
**Pull request by Piankero**
## Basics

These points need to be fulfilled for every PR:

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Why didn't you directly modfiy ELEKTRA_SET_OUT_OF_MEMORY_ERROR? Is there any reason to have this macro?

**Comment by Piankero** [comment]
@markus2330 I added my first error message template here and changed the majority of the existing messages.

Here are though some things I noticed:

- There is also another macro available [here](https://github.com/ElektraInitiative/libelektra/blob/9b48487e0321b8b415722892af5a92ae37eb11e6/src/include/kdbmacros.h#L64) which is only used 3 times. One could also make the error message templates like this.
- I though about completely removing the possibility to add any text in the for that particular error and take a default one instead but some custom messages make sense such as in [filename.c](https://github.com/Piankero/libelektra/blob/79be253491e35d12e3c7daadf23b4d4cec239c06/src/plugins/resolver/filename.c#L512-L513)

**Comment by markus2330** [comment]
> There is also another macro available here which is only used 3 times. One could also make the error message templates like this.

Yes, I found this method to be the best. But actually I forgot about ELEKTRA_MALLOC_ERROR. So it would be important that we do not have  ELEKTRA_SET_OUT_OF_MEMORY_ERROR, so that people will use the correct one (ELEKTRA_MALLOC_ERROR, imho it should be renamed to ELEKTRA_SET_OUT_OF_MEMORY_ERROR for consistency).

Maybe we can find clever grouping of errors, so that for a specific group, only one template (macro) matches, like we achieved with out-of-memory.

> I thought about completely removing the possibility to add any text for that particular error and take a default one instead but some custom messages make sense such as in filename.c

I think it is not a big problem: if it was realloc or malloc does not matter, you immediately see it in the source code. The size is dynamic, so you cannot see it in the source code. So this information can be helpful (for a very large allocation it is obvious that it will fail).

**Comment by Piankero** [comment]
> ELEKTRA_MALLOC_ERROR, imho it should be renamed to ELEKTRA_SET_OUT_OF_MEMORY_ERROR for consistency

I am confused what you actually want. You want the original macro `ELEKTRA_SET_OUT_OF_MEMORY_ERROR` and `ELEKTRA_SET_OUT_OF_MEMORY_ERRORF` to be removed and be substituted by a renamed version of ELEKTRA_MALLOC_ERROR?

> I think it is not a big problem

The text I marked in filename.c does not give more information about malloc or realloc but it gives a concrete message that it takes a different directory which is definitely important for the user. A complete removal of the dynamic text seems too restricting

> Maybe we can find clever grouping of errors, so that for a specific group, only one template (macro) matches, like we achieved with out-of-memory.

I highly doubt that this is possible but I will take a look at each group. OOM errors are the exception because they are nearly identical in every case whereas I could not think of any template to put in all semantic validation errors.

**Comment by markus2330** [comment]
>  I am confused what you actually want. You want the original macro ELEKTRA_SET_OUT_OF_MEMORY_ERROR and ELEKTRA_SET_OUT_OF_MEMORY_ERRORF to be removed and be substituted by a renamed version of ELEKTRA_MALLOC_ERROR?

Yes, exactly.

Open for me is if there is a "size" in all cases.

> The text I marked in filename.c does not give more information about malloc or realloc but it gives a concrete message that it takes a different directory which is definitely important for the user

This is a very exotic case and the code seems to be quite broken. This case does not justify to add a dynamic text.

Furthermore, "defaulting to /" could be in a different warning (resource) as above. (As it is only a warning, we can yield several ones.)

> I highly doubt that this is possible but I will take a look at each group. OOM errors are the exception because they are nearly identical in every case whereas I could not think of any template to put in all semantic validation errors.

Maybe "semantic value validation", i.e. where the value is incorrect according the specification/type.

But let us first overcome the problems related to out-of-memory errors.

**Comment by Piankero** [comment]
> Open for me is if there is a "size" in all cases.

It seems that some sizes are not given: https://github.com/ElektraInitiative/libelektra/blob/8f4da8abb5124d5cf97bc4151d93f32e5e552f70/src/plugins/augeas/augeas.c#L435

**Comment by markus2330** [comment]
In this case it is `sizeof("Unable to initialize augeas: ")+sizeof(aug_error_message (augeasHandle))`

**Comment by markus2330** [comment]
Btw. I do not think that the given size needs to be byte-precise. Actually a rough estimation would be enough. It is only to know if there was a bug in the system (e.g. that it tried to allocate -1 bytes).

**Comment by Piankero** [comment]
Since the other approach is more fitting I will close this PR

**Pull request closed without merging**
