### PR TITLE
error: removed `ingroup` metadata

### PR DESCRIPTION
**Pull request by Piankero**
error: news

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [x] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [x] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [x] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

@markus2330 please review my pull request

## Merging

Please add the "ready to merge" label when the build server and you say
that everything is ready to be merged.

### CODE REVIEW

**Comment by Piankero** [comment]
@sanssecours Do you know why the build server fails for your markdown tests? I executed them on master and they also failed on my system

**Comment by sanssecours** [comment]
> Do you know why the build server fails for your markdown tests?

Since this PR removes a line from error message, the MSR tests that check these messages need to be updated. I pushed a commit that should fix the failing tests.

**Comment by markus2330** [comment]
Thank you very much! Nice cleanup!

If possible, please create pull requests from branches in your own repo to libelektra's master (this repo).

**Comment by sanssecours** [comment]
> If possible, please create pull requests from branches in your own repo to libelektra's master (this repo).

It would also be great, if we could remove all other branches (except for `master` and `debian`) from the main repository too.

**Comment by Piankero** [comment]
I did not create those branches on the main repository. This one here was a missclick in CLion to be honest. Aren't some of the branches used? (eg. Levensthein Distance)

**Comment by markus2330** [comment]
> This one here was a missclick in CLion to be honest. 

This time it was no problem. It is only annoying if a branch lives for longer.

> if we could remove all other branches (except for master and debian) from the main repository too.

Yes, I fully agree but I did not find time to finish the PRs and it is not possible to remove the branches until the PRs are closed.

**Pull request merged**
