### PR TITLE
Style: Reformat & Check Shell Code With `shfmt`

### PR DESCRIPTION
**Pull request by sanssecours**
# Checklist

- [x] I ran all tests locally and everything went fine.
- [x] The documentation regarding the switch from `checkbashism` to [`shfmt`](https://github.com/mvdan/sh) should be up to date.

### CODE REVIEW

**Comment by markus2330** [comment]
Please rebase.

Are we sure that shfmt implements everything checkbashism does?

It sounds a bit heavyweight to require to install shfmt. How can someone format their shell scripts so that our build server accepts it?

**Comment by sanssecours** [comment]
> Are we sure that shfmt implements everything checkbashism does?

I am pretty sure it does not. However `shfmt` also does not print false positives as far as I can tell.

> It sounds a bit heavyweight to require to install shfmt.

The package requires 3.7MB on my machine:

```sh
brew info shfmt
#> shfmt: stable 2.5.1 (bottled), HEAD
#> Autoformat shell script source code
#> https://github.com/mvdan/sh
#> /usr/local/Cellar/shfmt/2.5.1 (5 files, 3.7MB) *
#>   Poured from bottle on 2018-08-24 at 19:11:48
#> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/shfmt.rb
#> ==> Dependencies
#> Build: go ✘
#> ==> Options
#> --HEAD
#> 	Install HEAD version
#> ==> Analytics
#> install: 575 (30d), 1471 (90d), 3413 (365d)
#> install_on_request: 573 (30d), 1468 (90d), 3408 (365d)
#> build_error: 0 (30d)
```

. That is about two thirds of the space `clang-format` requires (6.0MB). I would not consider this “heavyweight”.

> How can someone format their shell scripts so that our build server accepts it?

I think the easiest option is to just install `shfmt` and then call 

```sh
shfmt -s -sr filename
```

. If you want you can also install a [plugin to reformat the code directly inside your editor](https://github.com/mvdan/sh#related-projects). I know there is [no Debian package for `shfmt` yet](https://github.com/mvdan/sh#shfmt):

> Packages are available for Arch, CRUX, Homebrew, NixOS and Void.

. However, I do not think installing a current version of Go (1.9+) and then calling

```sh
go get -u github.com/mvdan/sh/cmd/shfmt
```

is that big of a problem. Maybe you can also install one of the [`shfmt` binaries](https://github.com/mvdan/sh/releases/tag/v2.5.1) directly, then you do not need to install Go at all.

**Comment by markus2330** [comment]
```
go get -u github.com/mvdan/sh/cmd/shfmt
package github.com/mvdan/sh/cmd/shfmt: cannot download, $GOPATH not set. For more details see: go help gopath
```

I would rather discuss in the next meeting if this dependency is acceptable for everyone.

**Comment by sanssecours** [comment]
> ```
> go get -u github.com/mvdan/sh/cmd/shfmt
> package github.com/mvdan/sh/cmd/shfmt: cannot download, $GOPATH not set. For more details see: go help gopath
> ```

You can download `shfmt` binaries for common operating systems [here](https://github.com/mvdan/sh/releases). For example, to install the tool on a 64 Bit x86 computer running Linux just download the binary from [here](
https://github.com/mvdan/sh/releases/download/v2.5.1/shfmt_v2.5.1_linux_amd64) and put it into a directory that is part of your `PATH`. You **do not need to install Go** for the tool to work at all. I successfully tested that this works [in one of the latest commits](https://github.com/ElektraInitiative/libelektra/pull/2230/commits/02cb2e0171352f3d40e7677c8809ef71ee497457).

> I would rather discuss in the next meeting if this dependency is acceptable for everyone.

Works for me, although I do not think it is that big of a problem. Especially since a lot of contributors do not work on Elektra’s Shell code at all.

**Comment by markus2330** [comment]
Ok, the binaries work for me.

And you are right, not many people are modifying shell code.

Nevertheless, it is better to discuss it if new tools are required to develop on Elektra.

Btw. The build servers seem to fail now.

**Comment by markus2330** [comment]
As discussed: please keep the bashism checks.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
