### PR TITLE
Improve CMake Code of (Markdown) Shell Recorder

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This PR adds some features to the CMake code of the Shell Recorder and the Markdown Shell Recorder. Most importantly the update adds the ability to specify required plugins for MSR an SR tests.

# Checklist

- [x] I checked all commit messages. 
- [x] I ran all tests and everything went fine.
- [x] The PR adds code comments for the new CMake code. 
- [x] The release notes contain up to date information about the new features added in the pull request.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Build finished. No test results found.

**Comment by sanssecours** [comment]
jenkins build gcc-configure-debian please

**Comment by sanssecours** [comment]
jenkins build gcc-configure-debian-wheezy please

**Comment by sanssecours** [comment]
jenkins build incremental please

**Comment by markus2330** [comment]
Build finished. No test results found.

**Comment by sanssecours** [comment]
jenkins build gcc-configure-debian-notest please

**Comment by markus2330** [comment]
Thank you, that is a great idea!

It is much more realistic then #1498

**Comment by sanssecours** [comment]
jenkins build clang please

**Comment by sanssecours** [comment]
jenkins build homepage please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc47-cmake-options please

**Comment by markus2330** [comment]
Build finished. No test results found.

**Comment by sanssecours** [comment]
jenkins build homepage please

**Comment by sanssecours** [comment]
jenkins build homepage please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build gcc please

**Comment by sanssecours** [comment]
jenkins build todo please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc47-cmake-options please

**Comment by markus2330** [comment]
Thank you so much for your continuous improvements!

**Pull request merged**
