### PR TITLE
Merge WIP: Fix dependency problems

### PR DESCRIPTION
**Pull request by Chemin1**
The `merge' branch had all checks green until I could not get to the Jenkins build details anymore. Thus I want to leave it as is for the moment.

This PR continues the commits from `merge`, is rebased to master again and (hopefully, let's see what the buildserver thinks of this) resolves the current problems with undefined references.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for recreating this branch! Let us get this merged asap!

**Comment by Chemin1** [comment]
jenkins build libelektra please

**Comment by Chemin1** [comment]
As suggested in LibGit2's GitHub repository, I now opened a [question on StackOverflow](https://stackoverflow.com/questions/58477412/memory-problems-with-libgit2-initialization) concerning memory management with LibGit2. This shed light upon the segmentation faults on FreeBSD and Mac.

**Comment by Chemin1** [comment]
Superseded by #3105.

**Comment by markus2330** [comment]
> As suggested in LibGit2's GitHub repository, I now opened a question on StackOverflow concerning memory management with LibGit2. This shed light upon the segmentation faults on FreeBSD and Mac.

Very good initiative.

**Pull request closed without merging**
