### PR TITLE
elektrad: update

### PR DESCRIPTION
**Pull request by mpranj**
Based on #3588 (huge thanks to @kodebach). Updates go-elektra and some modules and fixes keyDup.
Enable building of `elektrad` again.

### CODE REVIEW

**Comment by kodebach** [comment]
I don't have time to test this right now. But if you say it works for you (and the tests seem to agree), then I would also say we merge this and if there issues arise we fix them later. The state with this PR merged is definitely better than we the current master version.

IIRC the segfaults in my PR rarely occurred during tests. If think I could reproduce them a bit more consistently (although still not all the time), if I started the server and then executed many requests in quick succession. AFAIK `elektrad` uses a pool of `KDB` handles and somewhere in the management of this pool something went wrong.

**Comment by mpranj** [comment]
> IIRC the segfaults in my PR rarely occurred during tests.

Thanks for taking a look and describing how the segfaults were happening. I'll check again and try to stress the server.

**Comment by mpranj** [comment]
The current state is:
* I can not reproduce a segfault, not even with benchmarks.
* Some memory is not being freed and I can not investigate now. (Definitely happens for `Debug` and `RelWithDebInfo` builds.) Requesting the same key via REST-API fills up memory.
* Benchmarks run partially. The `delete/meta` benchmarks fail, not sure why.

The state is definitely better than master, where afaik nothing works due to the core API changes. Therefore I will merge as soon as the CI is green.

**Comment by markus2330** [comment]
Amazing :sparkle:

**Pull request merged**
