### PR TITLE
csvstorage: remove superfluous if-conditions that fail the build on Debian Unstable

### PR DESCRIPTION
**Pull request by atmaxinger**
This is partly based on #4341, but is superiour because we do not remove the whole check. The argument `colNames` might still be `NULL` so we should really keep the fallback.

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [x] reformat the code with `scripts/dev/reformat-all`
  - [x] make all unit tests pass
  - [x] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [x] I added unit tests for my code
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [x] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [x] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [x] Documentation is introductory, concise, good to read and describes everything what the PR does
- [x] Examples are well chosen and understandable
- [x] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [x] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [x] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [x] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [x] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
Amazing work, thank you so much!

**Comment by markus2330** [comment]
@lawli3t So better rebase your PR on top of master after this gets merged.

**Comment by lawli3t** [comment]
Will do!

Markus Raab ***@***.***> schrieb am Fr., 2. Sept. 2022, 16:33:

**Comment by atmaxinger** [comment]
@markus2330 ready to merge, all tests pass

**Comment by markus2330** [comment]
Well done, finally master is green again! :green_heart:

**Pull request merged**
