### PR TITLE
Fast Cache

### LINKED ISSUE #2644: core: disable global plugins for cache hit and no update
As discussed in #2270 we want to disable all plugins (including global positions) when we have a cache hit. The idea is to store the completely processed KeySet, and then only load it. The change makes a significant performance improvement.

I would like to disable the same plugins for the no update scenario too. It makes no sense that a cache hit is faster (which it is) than an already loaded KeySet with no updates to do.

The obvious drawback is that this prevents us from using certain things like logging, tracer, ... in those positions.

It looks like only one test case fails when we implement this change:

```
261/276 Test #275: testkdb_ensure ................................***Failed    0.27 sec
Running main() from /opt/gtest/googletest/src/gtest_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from Ensure
[ RUN      ] Ensure.GlobalUnmount
[       OK ] Ensure.GlobalUnmount (94 ms)
[ RUN      ] Ensure.Unmount
[       OK ] Ensure.Unmount (86 ms)
[ RUN      ] Ensure.GlobalMount
tracer: open(0x55db6b824780, spec/tests/kdb/ensure = ): 0
/home/jenkins/workspace/libelektra/tests/kdb/testkdb_ensure.cpp:129: Failure
Value of: capture.empty ()
  Actual: true
Expected: false
tracer plugin not run
Google Test trace:
/home/jenkins/workspace/libelektra/tests/kdb/testkdb_ensure.cpp:170: first ensure
/home/jenkins/workspace/libelektra/tests/kdb/testkdb_ensure.cpp:129: Failure
Value of: capture.empty ()
  Actual: true
Expected: false
tracer plugin not run
Google Test trace:
/home/jenkins/workspace/libelektra/tests/kdb/testkdb_ensure.cpp:180: second ensure
tracer: close(0x55db6b824780,  = )
[  FAILED  ] Ensure.GlobalMount (88 ms)
[----------] 3 tests from Ensure (268 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (268 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Ensure.GlobalMount

 1 FAILED TEST
```

I think it would make sense to disable the cache only for the test case such that it can run properly.

### PR DESCRIPTION
**Pull request by mpranj**
Closes #2644.

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [x] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [x] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

### CODE REVIEW

**Comment by mpranj** [comment]
@markus2330 please review my PR.

It implements my proposal from #2644.

**Comment by markus2330** [comment]
Thank you for the improvement!

Is debugGlobalPositions here to stay?

**Comment by mpranj** [comment]
Yes, that would be the only way to force execution of the global plugins. Otherwise we bypass them because of the cache.

**Comment by markus2330** [comment]
Ok, maybe another name would better describe the purpose? What about cacheHitBypass?

**Comment by mpranj** [comment]
Sure. On that note: it also changes the behavior of the NO_UPDATE part. I'll update it with a future PR.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
