### PR TITLE
bindings: only link against lib-core and lib-kdb

### PR DESCRIPTION
**Pull request by manuelm**
Last one for today. Please merge *after* libproposal issue has been solved. Otherwise gi-bindings won't work anymore.

Edit: Or reject in case you don't think it's worth it :-)

### CODE REVIEW

**Comment by markus2330** [comment]
libproposal issue should be resolved now. Can you check if it works now?

Is it necessary to specifiy elektra-core if you already link against elektra-kdb?

**Comment by manuelm** [comment]
jenkins build bindings please

**Comment by manuelm** [comment]
jenkins will find out for us.

Ofc the resolver will pull in elektra-core. But I prefer to explicitly link against all required libraries.

**Comment by markus2330** [comment]
It compiles and ldd shows the correct information. The question remains if this is a cmake-feature (then it would be supported on every cmake-platform) or if its a gnu-ld feature.

**Comment by manuelm** [comment]
If what is a gnu-ld feature? Linking against multiple libraries?

**Comment by markus2330** [comment]
I am talking about that maybe [GNU ld from binutils](https://sourceware.org/binutils/docs/ld/) has a feature which magically links all depend libraries, too.

**Comment by manuelm** [comment]
I'm sorry, I don't get it. Bindings depend on elektra-core + elektra-kdb + language interpreter. I'm linking against all of them + std c++ lib. Which other lib are you seeing or referring to?

**Comment by markus2330** [comment]
Ok, we are talking past each other. I was talking if it is *necessary* to specify all libs. I will merge this here, because obviously it won't hurt to specify it.

**Comment by manuelm** [comment]
In fact explicitly specifying is also some kind of documentation :-)

**Comment by markus2330** [comment]
If we all use it the same way, then yes. Would you specify libcore if you only use `kdb*` functions? (indirect usage)

**Comment by manuelm** [comment]
No, because I didn't use any of its symbols.

**Pull request merged**
