### PR TITLE
quickdump v2: relative key names, reused buffer, etc.

### PR DESCRIPTION
**Pull request by kodebach**
A small PR with some changes to quickdump. We now only store relative key names, to enable relocation. We also reuse the buffer on `kdbGet`, for a minor speed-up.

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the fix! It is much better to have relative key names, see also #51.

**Comment by kodebach** [comment]
From https://travis-ci.org/ElektraInitiative/libelektra/jobs/507354465#L1741:
> No plugin that provides sync could be found

@markus2330 How should I fix that? The `sync` plugin is excluded for the Travis GCC ASAN job (I don't  know why), should I re-include it or should I exclude `quickdump`? (locally GCC ASAN works, if the sync plugin is there) Or is there something I can do, so that `sync` isn't required?

**Comment by markus2330** [comment]
Sync is one of the essential plugins which should always be present. In #423 we discussed about how to improve without risking data loss. So at the moment it would be best if the sync plugin is included in every build job.

@sanssecours Do you know why the sync plugin is not included?

**Comment by sanssecours** [comment]
> Do you know why the sync plugin is not included?

Yes. I [excluded sync and all other non-essential plugins to improve the runtime of `🐧 GCC ASAN`](https://github.com/ElektraInitiative/libelektra/commit/1fdb15eb099192e1690639d598276bb230f6ee1c).

**Comment by kodebach** [comment]
> Yes. I [excluded sync and all other non-essential plugins to improve the runtime of `🐧 GCC ASAN`](https://github.com/ElektraInitiative/libelektra/commit/1fdb15eb099192e1690639d598276bb230f6ee1c).

If we want to only include essential plugins in `🐧 GCC ASAN` shouldn't we use:
```
-DPLUGINS='dump;fstab;haskell;jni;journald;list;lua;python;python2;regexdispatcher;resolver;ruby;simpleini;spec;typechecker;xerces'
```
(the list of plugins available at the time of your commit which you didn't exclude)

Instead of starting with `ALL` and excluding a whole bunch of plugins?

**Comment by sanssecours** [comment]
> …Instead of starting with `ALL` and excluding a whole bunch of plugins?

I explicitly excluded the old (and tested) plugins, since I wanted to make sure newly added plugins (that do not depend on any of the excluded plugins) are tested by `🐧 GCC ASAN`.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
