### PR TITLE
travis: increase wait time and update Xcode version

### PR DESCRIPTION
**Pull request by mpranj**
Try to fix the "No output has been received in the last 10m0s" errors.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the fix!

**Comment by mpranj** [comment]
I don't know if it will actually fix the timeout issues, but it is worth a shot.

**Comment by mpranj** [comment]
Unfortunately it's still not fixed. The command `kdb run_all` takes longer than 20 minutes and the output stops here:

```
Running check_external_example
Running check_external_example_codegen_econf
Running check_external_example_codegen_menu
The command "travis_wait 20 kdb run_all" exited with 137.
```

**Comment by markus2330** [comment]
And more then 20 minutes is not possible? So we need to remove some stuff from the travis build+tests. @sanssecours is there anything you already had removed once and we added it again?

**Comment by mpranj** [comment]
> And more then 20 minutes is not possible?

More than 20 minutes is OK, but the whole build is terminated after 50 minutes (for our open source plan).

So yes, I can try increasing, but it sounds inconsistent. When it finishes, it finishes well below 4 minutes. Why would it then take more than 20 minutes _sometimes_?

**Comment by sanssecours** [comment]
> @sanssecours is there anything you already had removed once and we added it again?

Not really

> Unfortunately it's still not fixed. The command `kdb run_all` takes longer than 20 minutes and the output stops here:

To me that sounds like a real problem. The command should finish sooner, even on underpowered hardware.

**Comment by markus2330** [comment]
`kdb run_all` is quite I/O intensive. If they have some where slow (network) storage everything is possible.

**Comment by mpranj** [comment]
We could disable `kdb run_all` on travis-ci, if it continues to cause problems.

We're running them on cirrus-ci anyway, or is there anything unique/special to the travis builds?

**Comment by markus2330** [comment]
> We're running them on cirrus-ci anyway,

And of course also Jenkins.

> or is there anything unique/special to the travis builds?

Yes, they are the only one using Mac OS X.

The Linux builds of Travis, however, are not really needed. But they do not create problems, or do they?

**Comment by mpranj** [comment]
> Yes, they are the only one using Mac OS X.

No, we have macOS also on cirrus-ci. That was my point.

**Comment by markus2330** [comment]
Ahh, I did not know that. :+1:  Then yes, I have no objections to disabling them on Travis!

**Comment by sanssecours** [comment]
> We're running them on cirrus-ci anyway, or is there anything unique/special to the travis builds?

The Travis build job `🍏 GCC` is the only job that compiles Elektra with GCC on macOS.

**Pull request merged**
