### PR TITLE
Kdb mount

### PR DESCRIPTION
**Pull request by markus2330**
Adds mount/dini features as discussed in #1693 and #1306

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [X] commit messages are fine (with references to issues)
- [ ] I added unit tests
- [X] I ran all tests and everything went fine
- [X] affected documentation is fixed (partly, not for strategy)
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

@sanssecours  please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by markus2330** [comment]
> to not cause any problems at all. That might just be my preference though.

Yes, I see it the same way. The problem is that it does not *always* work smoothly (for cases where plugins modify their config and INI is unable to store parent dirs). Thus I would prefer to have it as a separate switch until we get a reliable behavior.

Other issues (like INI crashes) are imho more important for this release.

**Pull request merged**
