### PR TITLE
shared-only-test-fix

### PR DESCRIPTION
**Pull request by e1528532**
# Purpose

the test `check_kdb_internal_check` also tests the SHARED_ONLY plugins with kdb-full or kdb-static which obviously fails, this PR excludes them in those cases.

# Checklist

Check relevant points but please do not remove entries.
For docu fixes, spell checking, and similar nothing
needs to be checked.

- [X] commit messages are fine ("module: short statement" syntax and refer to issues)
- [ ] I added unit tests
- [X] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [X] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [X] release notes are updated (doc/news/_preparation_next_release.md)

@markus2330 noticed the issue in the full build PR #2046

### CODE REVIEW

**Comment by e1528532** [comment]
jenkins build all please

**Comment by e1528532** [comment]
jenkins build libelektra  please

**Comment by e1528532** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
