### PR TITLE
crypto: fix OpenSSL related linker warning

### LINKED ISSUE #1969: EVP_EncryptFinal
As shown in linker warnings in  #1760, are we sure we do not misuse EVP_EncryptFinal?

```
CMakeFiles/elektra-crypto_openssl.dir/openssl_operations.c.o: In function `elektraCryptoOpenSSLEncrypt':
openssl_operations.c:(.text+0x3a5c): warning: warning: EVP_EncryptFinal is often misused, please use EVP_EncryptFinal_ex and EVP_CIPHER_CTX_cleanup
CMakeFiles/elektra-crypto_openssl.dir/openssl_operations.c.o: In function `elektraCryptoOpenSSLDecrypt':
openssl_operations.c:(.text+0x462b): warning: warning: EVP_DecryptFinal is often misused, please use EVP_DecryptFinal_ex and EVP_CIPHER_CTX_cleanup
```

### PR DESCRIPTION
**Pull request by petermax2**
Fixes #1969 .

# Purpose

Fix OpenSSL-related linker warning.

# Checklist

Check relevant points but please do not remove entries.
For docu fixes, spell checking, and similar nothing
needs to be checked.

- [x] commit messages are fine ("module: short statement" syntax and refer to issues)
- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by petermax2** [comment]
jenkins build jenkinsfile please

**Comment by petermax2** [comment]
@markus2330 We seem to have DNS issues on the build server.

    Unable to look up github.com (port 9418) (Temporary failure in name resolution)

**Comment by ingwinlu** [comment]
jenkins build jenkinsfile please

**Comment by sanssecours** [comment]
jenkins build jenkinsfile please

**Comment by petermax2** [comment]
@markus2330 Travis seems to be hanging, but the build jobs, that ran so far, all succeeded.

It should make no difference if we use `EVP_EncryptFinal` or `EVP_EncryptFinal_ex`and we call the cleanup routine anyway. So, let's make the linker happy.

**Comment by petermax2** [comment]
Update: Travis is still alive.

**Comment by markus2330** [comment]
Thanks for the fix!

Does EVP_EncryptFinal vs. EVP_EncryptFinal_ex make a difference in which OpenSSL version is needed?

**Comment by petermax2** [comment]
The declaration of `EVP_EncryptFinal_ex` is unmodified for 3 years. See `git blame` of the [source](https://github.com/openssl/openssl/blame/master/include/openssl/evp.h).

I guess we are safe. Should I investigate further?

**Pull request merged**
