### PR TITLE
Travis: Add ASAN Enabled GCC Build for Linux

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This PR

- adds a Linux build job for an ASAN enabled GCC build, and
- removes some unneeded CMake code for the ASAN build.

# Checklist

- [x] I checked all commit messages.
- [x] I ran all tests and everything went fine.
- [x] Since this pull request contains no noteworthy changes, I did not update the release notes.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build gcc-asan please

**Comment by sanssecours** [comment]
jenkins build docker please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Build finished. No test results found.

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build test-bindings please

**Comment by sanssecours** [comment]
jenkins build bindings please

**Comment by markus2330** [comment]
Thank you, great job!

**Pull request merged**
