### PR TITLE
ci: add cancellation job to github action

### PR DESCRIPTION
**Pull request by tmakar**
This PR introduces a new job in the elektra GitHub actions pipeline. The new cancel job assures that current actions are cancelled if there a newer actions on the same branch.

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy. If not, fix **in this order**:
  - [x] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://master.libelektra.org/doc/contrib/documentation.md))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating this PR!

Please do/check the basics as written in the PR template. In particular the entry in "doc/news/_preparation_next_release.md" is required, so that we don't forget to mention anyone in the release notes.

**Comment by tmakar** [comment]
This link https://restyled.io seems to be broken (can be found in doc/news/2019-11-26_0.9.1.md:408:0).

**Comment by kodebach** [comment]
> This link https://restyled.io seems to be broken (can be found in doc/news/2019-11-26_0.9.1.md:408:0). Seems that their server is down.

It works again. I restarted the link checker CI job.

**Review by markus2330 — COMMENTED** [review]
I cannot review this, I don't know GitHub workflows well. @kodebach is this what you wanted?

**Comment by kodebach** [comment]
This is what I suggested in #4537, yes. But I have now looked into this a bit more and found that GitHub Actions has [native support](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) for this behaviour. So I think we should just use this instead of adding the custom 3rd party action.

```yaml
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

**Comment by markus2330** [comment]
@tmakar you can also decide to not work on this any further, unless you are interested in it. Jenkins is our main build system, see also doc/BUILDSERVER.md

**Comment by tmakar** [comment]
> Sorry, for the confusion.

No problem, I got it, makes more sense to use inbuilt features over 3rd party!

**Review by kodebach — APPROVED** [review]
LGTM

**Comment by markus2330** [comment]
Great job, thanks for your first contribution! :rocket:

**Pull request merged**
