### PR TITLE
Improved topological search

### PR DESCRIPTION
**Pull request by tom-wa**
@markus2330, can you give it a try ? 
Not sure if it's an issue, but dependencies that can be resolved immediately will be resolved, so the KeySet
```
ksNew (
        10, keyNew ("/a", KEY_VALUE, "b", KEY_META, "dep", "#0", KEY_META, "dep/#0", "/b", KEY_META, "order", "#0", KEY_END),
         keyNew ("/b", KEY_VALUE, "d", KEY_META, "dep", "#0", KEY_META, "dep/#0", "/d", KEY_META "order", "#1", KEY_END),
         keyNew ("/c", KEY_VALUE, "-", KEY_META, "order", "#3", KEY_END), 
         keyNew ("/d", KEY_VALUE, "-", KEY_META, "order", "#2", KEY_END), 
        KS_END);
```
will result in 
`c -> d -> b -> a`
instead of
`d -> b -> a -> c`

```
KEY META     TESTS
==================

	 ---- TEST 1 ----
		-------NEW: 183519
		-------OLD: 474165
	 ---- TEST 2 ----
		-------NEW: 277925
		-------OLD: 1374282
	 ---- TEST 3 ----
		-------NEW: 188224
		-------OLD: 1073342
	 ---- TEST 0 ----
		-------NEW: 12550
		-------OLD: 24260
	 ---- TEST C1 ----
		-------NEW: 31328
		-------OLD: 50776
	 ---- TEST C2 ----
		-------NEW: 114003
		-------OLD: 382698
	 ---- TEST C3 ----
		-------NEW: 94491
		-------OLD: 154237
	 ---- TEST C4 ----
		-------NEW: 98213
		-------OLD: 161158
	 ---- TEST O1 ----
		-------NEW: 90475
		-------OLD: 296682
	 ---- TEST O2 ----
		-------NEW: 89716
		-------OLD: 295983
	 ---- TEST O3 ----
		-------NEW: 95392
		-------OLD: 301018
	 ---- TEST CO1 ----
		-------NEW: 45082
		-------OLD: 78941
	 ---- TEST CO2 ----
		-------NEW: 43677
		-------OLD: 70027
	 ---- TEST CO3 ----
		-------NEW: 99938
		-------OLD: 167445


test_meta RESULTS: 187 test(s) done. 0 error(s).
```

### CODE REVIEW

**Comment by markus2330** [comment]
The implementation seems to be incorrect, a testcase that uses topological search fails now: (BackendBuilder) It detects a cycle where there is none.

**Comment by tom-wa** [comment]
it returns -1 because the key "//a" doesn't exist. (0 is for cycles) 
i'm using strcmp for comparing the keynames here, and //a doesn't match /a. 
oh, and i'm currently using the array notation for order because i got used to it and you told me to use it for ini. which one should i use for order here ? 

```
/a
        order:0
/b
        order:1
/c
        dep:#1
        dep/#0://a
        dep/#1://b
        order:2
```

**Comment by tom-wa** [comment]
@markus2330  sorry, just noticed that i forgot to document the -1 return value because i actually wanted to ditch it for a elektraMetaAddDep function like you suggested.

**Comment by markus2330** [comment]
Ok, thank you! I will fix the kdb-mount code then.

Does it matter what "order" contains as long as strcmp does the right thing?

**Comment by markus2330** [comment]
Btw. it is ok to fix client code using your code ;)

0dae21aca322e90ce35ce9a29b05dca500d3349b should fix the dep/#0 issue, but it still reports an cycle.

**Comment by markus2330** [comment]
```/home/markus/Projekte/Elektra/current/src/libs/meta/meta.c: In function ‘elektraSortTopology’:
/home/markus/Projekte/Elektra/current/src/libs/meta/meta.c:1214:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     else if (i == j)
                ^
```

**Pull request merged**
