### PR TITLE
[FLOSS H2] doc: remove "Don't panic" from Git

### PR DESCRIPTION
**Pull request by joni1993**
Remove 'Don't Panic" note from Git
When you have not panicked at "Unix-based OS" or "command line interface" you probably won't when reading Git, as it is pretty standard now.

But we should probably add a note at make/cmake or C ;)

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by markus2330** [comment]
Actually, I like the "Don't panic!". I agree it should be moved to another paragraph, e.g., about cmake :wink: 

Probably you can also rewrite it a bit to clarify that command line is not necessary for everything (as far as this is actually true, at least for you). Did you try the https://cmake.org/cmake/help/latest/manual/cmake-gui.1.html?

**Comment by joni1993** [comment]
Since writing beginner Makefiles a few years back then, i stay away from C and it's build systems in general. I just tried out cmake-gui and found it more confusing/difficult than just copy/pasting from the guide to CLI. 

Files like `scripts/cmake/ElektraCompiling.cmake` make me dizzy - like seeing C-code ;)  (there should be a word for that...`ceing` - which means looking at stuff that makes you dizzy )

**Comment by markus2330** [comment]
So you are perfect to find the right place for "Don't panic!" :rocket:

**Review by 0x6178656c — APPROVED** [review]
[FLOSS H2 REVIEW]

This also jumped out to me whilst reading the page. I think this does indeed improve the page. (Also nowadays Git is probably more common and not nearly as scary as it used to be.)

A further improvement could be harmonizing the capitalization of "Git".

**Pull request merged**
