### PR TITLE
Kdb import export lookup provider through pluginDatabase

### PR DESCRIPTION
**Pull request by MasterToney**
## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

With this PR `kdb import` and `kdb export` lookup providers through the database, before you had to specify the plugin to use directly by name, e.g. `yajl` where as now you can also specify the format e.g. `json`.

It will implement issue #1178.

### CODE REVIEW

**Comment by MasterToney** [comment]
@markus2330 please review my pull request.

**Comment by markus2330** [comment]
Great job, looks very good. Let us see what the build server says.

**Comment by MasterToney** [comment]
Nice to hear, should I look into adding some unit tests that check if import/export work with both plugin name and file format?

**Comment by markus2330** [comment]
> Nice to hear, should I look into adding some unit tests that check if import/export work with both plugin name and file format?

Yes, some shellrecorder tests in the man pages of kdb import/export would be terrific.

**Comment by markus2330** [comment]
Btw. if you plan to push any new commits on a PR, please remove "ready to merge". "ready to merge" indicate that you do not want to change anything anymore and the build server passes.

**Comment by MasterToney** [comment]
@markus2330 I added two tests for both import and export that check if the command works by specifying either the plugin directly or the desired format.
I also installed ronn and rebuilt elektra with it, the build tells me that the man pages are getting generated but the new examples are not included, so my question: are shell recorder examples excluded from the man pages automatically or am I missing something?

**Comment by sanssecours** [comment]
> are shell recorder examples excluded from the man pages automatically or am I missing something?

Nope, these examples are included in the man pages. The problem is [`ElektraManPage`](https://github.com/ElektraInitiative/libelektra/blob/master/scripts/cmake/ElektraManPage.cmake), which tries to get rid of man pages, where only the date of the generated man page changed:

https://github.com/ElektraInitiative/libelektra/blob/cac326cb6292f216ea05b1f8bb8dd0cba6b24bd3/scripts/cmake/ElektraManPage.cmake#L35-L41

. Unfortunately I did not consider, changes which only include additions. As consequence these kind of man pages are generated, but then immediately reverted. Sorry for this bug. I will try to come up with a solution for this problem.

**Comment by MasterToney** [comment]
@sanssecours no problem ^^ I'm glad it's not something on my end :p
please let me know when a fix is available so that I can include the generated manpages

**Comment by sanssecours** [comment]
> please let me know when a fix is available so that I can include the generated manpages

Thank you for your understanding. Pull request #3184 should fix the problem.

**Comment by markus2330** [comment]
I merged #3184, so rebasing to master should fix the problem.

**Comment by MasterToney** [comment]
@sanssecours thank you, unfortunately now all man pages are marked as changed in doc/man/man1 and man7

The difference in those files is as follows:
```
- .TH "ELEKTRA\-RELATED" "" "June 2019" "" ""
+ .TH "ELEKTRA\-RELATED" "" "October 2019" "" ""
```
I guess the script includes them since a deletion and insertion happened?
For me now it's not a big deal, I can reset them manually but might be something worthy to look into again.

**Comment by sanssecours** [comment]
> @sanssecours thank you for the fix, unfortunately now all man pages are marked as changed in `doc/man/man1` and `doc/man/man7`

I only tested my changes with macOS until now. I assume `diff -e` produces different output on your system. Which version of `diff` do you use? I now tried 

- `diff (GNU diffutils) 2.8.1` on macOS, and
- `diff (GNU diffutils) 3.7` on Alpine Linux,

which both seem to work. The `diff` tool of [BusyBox](https://busybox.net) on the other hand does not work at all, since it does not support the [POSIX option `-e`](https://pubs.opengroup.org/onlinepubs/009695399/utilities/diff.html).

> I guess the script includes them since a deletion and insertion happened?

Currently the CMake code just checks, if the diff output for the editor [`ed`](https://www.gnu.org/fun/jokes/ed-msg.html) (`diff -e`) matches the regex `^4c\n\\.TH [^\n]+\n\\.\n$`. If it does, then the code reverts the changes made by `ronn`.

**Comment by MasterToney** [comment]
I'm too running macOS with `diff (GNU diffutils) 2.8.1` but strangely enough I wasn't able to reproduce the behavior after it's first occurrence.

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by MasterToney** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Release notes are missing.

**Comment by MasterToney** [comment]
Are you sure? Jenkins logs say something along the lines that 
```
508 [debian-buster-full] ERROR: Error fetching remote repo 'origin'
509 [debian-buster-full] hudson.plugins.git.GitException: Failed to fetch from https://github.com/ElektraInitiative/libelektra.git
```
which indicates to me that jenkins cannot clone this repo somehow.
Especially since I changed `doc/news/_preparation_next_release.md` with my contribution.

**Comment by markus2330** [comment]
> Are you sure?

I am sure my statement was wrong :wink:, the problem seems to be somewhere else.

If retrying does not help, making a new PR usually helps.

**Comment by MasterToney** [comment]
Ok, I closed this one and created #3191, let's hope for the best ^^

**Pull request closed without merging**
