### PR TITLE
WIP: test jenkins github PR builder

### PR DESCRIPTION
**Pull request by mpranj**
Dont merge me.

### CODE REVIEW

**Comment by mpranj** [comment]
jenkins build mingw64 please

**Comment by mpranj** [comment]
just testing jenkins, sorry.

jenkins build clang please
jenkins build gcc please
jenkins build gcc-configure-debian please
jenkins build gcc-configure-debian-intree please
jenkins build gcc-configure-debian-musl please
jenkins build gcc-configure-debian-notest please
jenkins build gcc-configure-debian-shared please
jenkins build gcc-configure-debian-stretch please
jenkins build gcc-configure-debian-wheezy please
jenkins build mingw64 please
jenkins build gcc-configure-xdg please
jenkins build gcc-i386 please
jenkins build gcc47-all please
jenkins build git-buildpackage-jessie please
jenkins build git-buildpackage-wheezy please
jenkins build icc please
jenkins build ini please
jenkins build local-installation please
jenkins build please
jenkins build fast please
jenkins build stable please
jenkins build unstable please
jenkins build multiconfig-gcc-stable please
jenkins build multiconfig-gcc-unstable please
jenkins build multiconfig-gcc47-cmake-options please
jenkins build source-package-test please
jenkins build bindings please

**Comment by mpranj** [comment]
jenkins build clang please
jenkins build gcc please
jenkins build gcc-configure-debian please
jenkins build gcc-configure-debian-intree please
jenkins build gcc-configure-debian-musl please
jenkins build gcc-configure-debian-notest please
jenkins build gcc-configure-debian-shared please
jenkins build gcc-configure-debian-stretch please
jenkins build gcc-configure-debian-wheezy please
jenkins build mingw64 please
jenkins build gcc-configure-xdg please
jenkins build gcc-i386 please
jenkins build gcc47-all please
jenkins build git-buildpackage-jessie please
jenkins build git-buildpackage-wheezy please
jenkins build icc please
jenkins build ini please
jenkins build local-installation please
jenkins build please
jenkins build fast please
jenkins build stable please
jenkins build unstable please
jenkins build multiconfig-gcc-stable please
jenkins build multiconfig-gcc-unstable please
jenkins build multiconfig-gcc47-cmake-options please
jenkins build source-package-test please
jenkins build bindings please

**Comment by mpranj** [comment]
jenkins build clang please

**Comment by mpranj** [comment]
jenkins build gcc please
jenkins build gcc-configure-debian please
jenkins build gcc-configure-debian-intree please

**Comment by mpranj** [comment]
jenkins build gcc please

**Comment by mpranj** [comment]
jenkins build gcc-configure-debian please

**Comment by mpranj** [comment]
jenkins build gcc-configure-debian-intree please

**Comment by mpranj** [comment]
jenkins build gcc-configure-debian-musl please

**Comment by mpranj** [comment]
jenkins build gcc-configure-debian-notest please

**Comment by mpranj** [comment]
jenkins build gcc-configure-debian-shared please

**Comment by mpranj** [comment]
jenkins build gcc-configure-debian-stretch please

**Comment by mpranj** [comment]
jenkins build gcc-configure-debian-wheezy please

**Comment by mpranj** [comment]
jenkins build mingw64 please

**Comment by mpranj** [comment]
jenkins build gcc-configure-xdg please

**Comment by mpranj** [comment]
jenkins build gcc-i386 please

**Comment by mpranj** [comment]
jenkins build gcc47-all please

**Comment by mpranj** [comment]
jenkins build git-buildpackage-jessie please

**Comment by mpranj** [comment]
jenkins build git-buildpackage-wheezy please

**Comment by mpranj** [comment]
jenkins build icc please

**Comment by mpranj** [comment]
jenkins build ini please

**Comment by mpranj** [comment]
jenkins build local-installation please

**Comment by mpranj** [comment]
jenkins build please

**Comment by mpranj** [comment]
jenkins build stable please

**Comment by mpranj** [comment]
jenkins build unstable please

**Comment by mpranj** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by mpranj** [comment]
jenkins build multiconfig-gcc-unstable please

**Comment by mpranj** [comment]
jenkins build multiconfig-gcc47-cmake-options please

**Comment by mpranj** [comment]
jenkins build source-package-test please

**Comment by mpranj** [comment]
jenkins build bindings please

**Comment by mpranj** [comment]
jenkins build multiconfig-gcc-unstable please

**Comment by mpranj** [comment]
jenkins build gcc-configure-debian-wheezy please

**Comment by mpranj** [comment]
jenkins build gcc47-all please

**Comment by mpranj** [comment]
jenkins build git-buildpackage-jessie please

**Comment by mpranj** [comment]
jenkins build ini please

**Comment by mpranj** [comment]
jekins build multiconfig-gcc47-cmake-options please

**Comment by mpranj** [comment]
jenkins build multiconfig-gcc47-cmake-options please

**Comment by markus2330** [comment]
Don't worry, creating your own PR is the best way to test jenkins.

**Comment by markus2330** [comment]
Please reopen if needed again

**Pull request closed without merging**
