### PR TITLE
doc: implement debian-stable-full-ini

### PR DESCRIPTION
**Pull request by ingwinlu**
# Purpose

port over ini build job

# Checklist

- [ ] commit messages are fine ("module: short statement" syntax and refer to issues)
- [ ] affected documentation is fixed
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

### CODE REVIEW

**Comment by ingwinlu** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you great job!

@ingwinlu Is it possible to add coverage for this job? (ini is much more tested here than in the other jobs)

@sanssecours Any idea why travis fails so often?

**Comment by ingwinlu** [comment]
> Is it possible to add coverage for this job? 

Sure I just need to add the COVERAGE flags

**Comment by sanssecours** [comment]
> Any idea why travis fails so often?

Usually the Travis build fails

- if Homebrew is unable to download a bottle and then tries to build the package from source (timeout),
- if `apt-get` is unable to download a package, or
- if there are any problems with the Haskell build job.

. The usual problem with the Haskell build job is – of course 😊 – that it is also unable to download the source files for a certain package.

**Comment by ingwinlu** [comment]
https://doc.libelektra.org/coverage/PR-2045/

**Comment by markus2330** [comment]
Thank you, great job!

**Pull request merged**
