### PR TITLE
Elektra Web 1.4

### PR DESCRIPTION
**Pull request by omnidan**
changes from #1892 

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
I am afraid I do not have time to look at this till till next week. :cry:  So you have time for further fixes and improvements :+1: 

If it is not too much work, you could consider #1846 (see very bottom the new proposal: so you would have to rename some of the visibility states and remove one of them)

**Comment by markus2330** [comment]
Can you do the most important (and easiest) fixes? I would like to merge this soon for the next release.

Please delay bigger changes (like find #1943  and that the "new key" dialog only has the key name) for a later PR.

Please set "ready to merge" if the most critical fixes were done.

**Comment by markus2330** [comment]
Any progress here? I would like to do the release and this sounds useful for the release.

I can also merge as-is, then you can write that the user study was done with Elektra 0.8.23.

**Comment by omnidan** [comment]
@markus2330 I won't have time to work on this until Thursday, please merge as-is if you need it earlier than that for the release.

**Comment by markus2330** [comment]
Thank you! If there is enough time, we can also merge 1.5...

**Pull request merged**
