### PR TITLE
kdb-find: initial commit

### LINKED ISSUE #1943: kdb find
Implement find (search) functionality for Elektra keys.

Task: iterate over all keys and print the name of those who match. `-0` feature is required.

Synopsis:

`kdb find <string> [<root>]`

@omnidan any other requirements?

### PR DESCRIPTION
**Pull request by markus2330**
# Purpose

Closes #1943

# Checklist

Check relevant points but please do not remove entries.
For docu fixes, spell checking, and similar nothing
needs to be checked.

- [X] commit messages are fine ("module: short statement" syntax and refer to issues)
- [X] I added unit tests
- [X] I ran all tests locally and everything went fine
- [X] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

@omnidan  please review my pull request

### CODE REVIEW

**Comment by sanssecours** [comment]
Seems rather strange that some of the Markdown Shell Recorder tests fail on Linux. I modified the code in commit f271a17b. Now `kdb find` also prints a descriptive error message for regex errors. Strangely enough the updated code also [seems to fix the failing Linux builds on Travis](https://travis-ci.org/sanssecours/elektra/builds/373363517).

@markus2330: Please feel free to overwrite or delete commit f271a17b if you do not like it.

**Comment by markus2330** [comment]
Thank you for the fix!

**Comment by markus2330** [comment]
jenkins build all please

**Comment by markus2330** [comment]
@ingwinlu It would be great if clang jobs could be fixed. Is it fixed by #1866? Using clang 5.0 should already fix the problem.

**Comment by ingwinlu** [comment]
i did try switching to clang 5.0 in #1866 but it reported the same errors as with 3.8 so I reverted it.

**Comment by sanssecours** [comment]
jenkins build gcc-configure-debian-debug please

**Comment by sanssecours** [comment]
jenkins build gcc-configure-debian-log please

**Comment by markus2330** [comment]
@sanssecours Thank you for the update!

@omnidan Does this PR do what you want?

**Comment by sanssecours** [comment]
Seems like the step [“Deploy Homepage” failed](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-1947/7/pipeline/):

> docker: Error response from daemon: Conflict. The container name "/elektra-backend" is already in use by container "e7dc071c4d2d0c64e1759cfdd45636dbdee83c691bb960716452b2a3bb82ec01". You have to remove (or rename) that container to be able to reuse that name.

.

**Comment by ingwinlu** [comment]
might have been a race condition with another build as it should not run
for PR's. It is fixed in the Jenkinsfile misc pr.

**Comment by ingwinlu** [comment]
actually the backend was repeatedly restarting and hence could not be removed by the build server. sadly no indication what triggered it.

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by omnidan** [comment]
@markus2330 could you add a flag to also search for key values containing the string?

**Comment by markus2330** [comment]
The problem is we are running out of flags in kdb suite (flags are shared between all kdb commands). We could always search for values, too. Or do you plan to give the user a choice which parts are considered?

**Comment by omnidan** [comment]
@markus2330 in that case I would always search by values too

**Comment by markus2330** [comment]
Is it okay that we merge it as-is and implement the search-by-value later? Can you extend Web-UI 1.5 then to use it?

I am sure we'll find a good way to encode the search text for keys and values within a single string. One way would be match the regex against a string which has the key and the value concatenated with a null-byte in between. Or we make a query language. The web UI does not need to be concerned about that, you just call `kdb find <string>`.

**Comment by omnidan** [comment]
@markus2330 yes we can do that - for now we could also just apply the same search string to names and values and return a result if either matches (that is how I would implement it in the Web UI)

**Comment by markus2330** [comment]
Thank you! I merged it!

As discussed, we will extend it so that values are considered to later. At the moment it only searches for keys.

**Pull request merged**
