### PR TITLE
crypto_botan: possibly fix ASAN build? See #1558 for further discussion

### PR DESCRIPTION
**Pull request by petermax2**
# Purpose

fix ASAN build

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [X] commit messages are fine (with references to issues)
- [ ] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by petermax2** [comment]
jenkins build elektra-clang-asan please

**Comment by petermax2** [comment]
@e1528532 could you please check if this fix is any good for the ASAN issues?

**Comment by petermax2** [comment]
jenkins build clang-asan please

**Comment by petermax2** [comment]
/usr/include/botan-1.10/botan/auto_rng.h:24:12: runtime error: member call on address 0x6030000644e0 which does not point to an object of type 'Botan::RandomNumberGenerator'
    0x6030000644e0: note: object is of type '*N5Botan12_GLOBAL__N_115Serialized_PRNGE'                           
    0b 00 00 6b  d0 d9 be 8a 57 7f 00 00  d0 4e 00 00 20 60 00 00  20 87 01 00 80 60 00 00  00 00 00 00          
                  ^~~~~~~~~~~~~~~~~~~~~~~                                                                        
                  vptr for '*N5Botan12_GLOBAL__N_115Serialized_PRNGE'                                            
    /usr/include/botan-1.10/botan/secmem.h:195:33: runtime error: member call on address 0x607000004230 which does not point to an object of type 'Botan::Allocator'
    0x607000004230: note: object is of type 'Botan::Locking_Allocator'                                           
     01 00 80 4a  10 e3 be 8a 57 7f 00 00  00 91 01 00 30 61 00 00  80 92 01 00 30 61 00 00  80 92 01 00         
                  ^~~~~~~~~~~~~~~~~~~~~~~                                                                        
                  vptr for 'Botan::Locking_Allocator'                                                            
    /usr/include/botan-1.10/botan/secmem.h:199:32: runtime error: member call on address 0x607000004230 which does not point to an object of type 'Botan::Allocator'
    0x607000004230: note: object is of type 'Botan::Locking_Allocator'                                           
     01 00 80 4a  10 e3 be 8a 57 7f 00 00  00 91 01 00 30 61 00 00  80 92 01 00 30 61 00 00  80 92 01 00         
                  ^~~~~~~~~~~~~~~~~~~~~~~                                                                        
                  vptr for 'Botan::Locking_Allocator'                                                            
    <unknown>: runtime error: member call on address 0x7fff14fb35f0 which does not point to an object of type 'Botan::PBKDF'
    0x7fff14fb35f0: note: object is of type 'Botan::PKCS5_PBKDF2'                                                
     60 60 00 00  90 74 bf 8a 57 7f 00 00  a0 84 01 00 80 60 00 00  a0 36 fb 14 ff 7f 00 00  07 00 00 00         
                  ^~~~~~~~~~~~~~~~~~~~~~~                                                                        
                  vptr for 'Botan::PKCS5_PBKDF2'

It did not work out so well. It seems like the source of the issues are in the Botan library itself. Btw. I could not reproduce these errors locally on openSUSE with libbotan-1.10.10.

**Comment by markus2330** [comment]
Thank you for looking into it! Would not be a good idea to merge this anyway (even if it would make the memchecker happy).

**Pull request closed without merging**
