### PR TITLE
Apply debian folder from debian/sid

### PR DESCRIPTION
**Pull request by reox**
# Purpose

Use the latest debian folder, to have the same structure as the packages in Debian already.

Used this tar.xz: http://http.debian.net/debian/pool/main/e/elektra/elektra_0.8.14-5.1.debian.tar.xz

# Open Problems
How to do with the python packages? There is now libelektra4-python for the python2.7 bindings and python3-elektra for the python3 bindings.
I think, this should be resolved more likely like:
libelektra4-python for the parts that are actually a library for elektra (independend of the python version?) and python{,3}-elektra for the bindings for python.

Please check the changes in debian/rules. The Debian package used to build for ALL plugins and then get the right files into the packages. I saw, that the current rules file would selectively build the plugins.
I tried to stich it together...

The debian one uses DBUILD_STATIC=OFF, while the current uses ON...

I tried to build on a jessie machine:
```
git clone https://github.com/reox/libelektra.git
cd libelektra
git archive --format=tar 0a1c700f946ab8322aef002cf1d812ae88645887 | gzip > ../elektra_0.8.19.orig.tar.gz
dpkg-buildpackage
```

Unfortunately, the testing fails during the build:

```
ake[1]: Entering directory '/home/vagrant/libelektra'
mkdir -p "/home/vagrant/libelektra/teststmp"
cd obj-* && env HOME="/home/vagrant/libelektra/teststmp" TMPDIR="/home/vagrant/libelektra/teststmp" ctest --output-on-failure -E '(testscr|testkdb)_.*'
Test project /home/vagrant/libelektra/obj-x86_64-linux-gnu
        Start   1: testmod_type
  1/101 Test   #1: testmod_type .....................   Passed    0.02 sec
        Start   2: testtool_backend
  2/101 Test   #2: testtool_backend .................   Passed    0.07 sec
        Start   3: testtool_backendparser
  3/101 Test   #3: testtool_backendparser ...........   Passed    0.01 sec
        Start   4: testtool_backendbuilder
  4/101 Test   #4: testtool_backendbuilder ..........   Passed    0.22 sec
        Start   5: testtool_onesidestrategy
  5/101 Test   #5: testtool_onesidestrategy .........   Passed    0.01 sec
        Start   6: testtool_mergeresult
  6/101 Test   #6: testtool_mergeresult .............   Passed    0.01 sec
        Start   7: testtool_specreader
  7/101 Test   #7: testtool_specreader ..............   Passed    0.02 sec
        Start   8: testtool_umount
  8/101 Test   #8: testtool_umount ..................   Passed    0.01 sec
        Start   9: testtool_mergingkdb
  9/101 Test   #9: testtool_mergingkdb ..............***Failed    0.03 sec
Running main() from gtest_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from MergingKDBTest
[ RUN      ] MergingKDBTest.HandlesUnconflictingKeySets
unknown file: Failure
C++ exception with description "3 Warnings were issued:
 Warning number: 26
	Description: could not open configuration file. You might want to try as root (use sudo !!).
	Ingroup: plugin
	Module: resolver
	At: /home/vagrant/libelektra/src/plugins/resolver/resolver.c:598
	Reason: Could not create configuration file "/etc/kdb/elektra.ecf" because No such file or directory
	Mountpoint: system/elektra
	Configfile: /etc/kdb/elektra.ecf.27931:1488721070.895887.tmp
 Warning number: 75
	Description: could not open file for writing
	Ingroup: plugin
	Module: storage
	At: /home/vagrant/libelektra/src/plugins/dump/dump.cpp:242
	Reason: No such file or directory
	Mountpoint: system/elektra
	Configfile: /etc/kdb/elektra.ecf.27931:1488721070.895887.tmp
 Warning number: 36
	Description: could not unlink file
	Ingroup: plugin
	Module: resolver
	At: /home/vagrant/libelektra/src/plugins/resolver/resolver.c:1048
	Reason: the file "/etc/kdb/elektra.ecf.27931:1488721070.895887.tmp" because of "No such file or directory"
	Mountpoint: system/elektra
	Configfile: /etc/kdb/elektra.ecf.27931:1488721070.895887.tmp
Sorry, the error (#74) occurred!
Description: could not create configuration directory
Ingroup: plugin
Module: resolver
At: /home/vagrant/libelektra/src/plugins/resolver/resolver.c:679
Reason: Could not create directory "/etc/kdb", because: "Permission denied" uid: 1000, euid: 1000, gid: 1000, egid: 1000
Mountpoint: system/elektra
Configfile: /etc/kdb/elektra.ecf.27931:1488721070.895887.tmp
" thrown in SetUp().
[  FAILED  ] MergingKDBTest.HandlesUnconflictingKeySets (18 ms)
[ RUN      ] MergingKDBTest.ThrowsIfNoConflictStrategyRegistered
unknown file: Failure
C++ exception with description "3 Warnings were issued:
 Warning number: 26
	Description: could not open configuration file. You might want to try as root (use sudo !!).
	Ingroup: plugin
	Module: resolver
	At: /home/vagrant/libelektra/src/plugins/resolver/resolver.c:598
	Reason: Could not create configuration file "/etc/kdb/elektra.ecf" because No such file or directory
	Mountpoint: system/elektra
	Configfile: /etc/kdb/elektra.ecf.27931:1488721070.899269.tmp
 Warning number: 75
	Description: could not open file for writing
	Ingroup: plugin
	Module: storage
	At: /home/vagrant/libelektra/src/plugins/dump/dump.cpp:242
	Reason: No such file or directory
	Mountpoint: system/elektra
	Configfile: /etc/kdb/elektra.ecf.27931:1488721070.899269.tmp
 Warning number: 36
	Description: could not unlink file
	Ingroup: plugin
	Module: resolver
	At: /home/vagrant/libelektra/src/plugins/resolver/resolver.c:1048
	Reason: the file "/etc/kdb/elektra.ecf.27931:1488721070.899269.tmp" because of "No such file or directory"
	Mountpoint: system/elektra
	Configfile: /etc/kdb/elektra.ecf.27931:1488721070.899269.tmp
Sorry, the error (#74) occurred!
Description: could not create configuration directory
Ingroup: plugin
Module: resolver
At: /home/vagrant/libelektra/src/plugins/resolver/resolver.c:679
Reason: Could not create directory "/etc/kdb", because: "Permission denied" uid: 1000, euid: 1000, gid: 1000, egid: 1000
Mountpoint: system/elektra
Configfile: /etc/kdb/elektra.ecf.27931:1488721070.899269.tmp
" thrown in SetUp().
[  FAILED  ] MergingKDBTest.ThrowsIfNoConflictStrategyRegistered (3 ms)
[ RUN      ] MergingKDBTest.MergesResolvableConflicts
unknown file: Failure
C++ exception with description "3 Warnings were issued:
 Warning number: 26
	Description: could not open configuration file. You might want to try as root (use sudo !!).
	Ingroup: plugin
	Module: resolver
	At: /home/vagrant/libelektra/src/plugins/resolver/resolver.c:598
	Reason: Could not create configuration file "/etc/kdb/elektra.ecf" because No such file or directory
	Mountpoint: system/elektra
	Configfile: /etc/kdb/elektra.ecf.27931:1488721070.902286.tmp
 Warning number: 75
	Description: could not open file for writing
	Ingroup: plugin
	Module: storage
	At: /home/vagrant/libelektra/src/plugins/dump/dump.cpp:242
	Reason: No such file or directory
	Mountpoint: system/elektra
	Configfile: /etc/kdb/elektra.ecf.27931:1488721070.902286.tmp
 Warning number: 36
	Description: could not unlink file
	Ingroup: plugin
	Module: resolver
	At: /home/vagrant/libelektra/src/plugins/resolver/resolver.c:1048
	Reason: the file "/etc/kdb/elektra.ecf.27931:1488721070.902286.tmp" because of "No such file or directory"
	Mountpoint: system/elektra
	Configfile: /etc/kdb/elektra.ecf.27931:1488721070.902286.tmp
Sorry, the error (#74) occurred!
Description: could not create configuration directory
Ingroup: plugin
Module: resolver
At: /home/vagrant/libelektra/src/plugins/resolver/resolver.c:679
Reason: Could not create directory "/etc/kdb", because: "Permission denied" uid: 1000, euid: 1000, gid: 1000, egid: 1000
Mountpoint: system/elektra
Configfile: /etc/kdb/elektra.ecf.27931:1488721070.902286.tmp
" thrown in SetUp().
[  FAILED  ] MergingKDBTest.MergesResolvableConflicts (3 ms)
[----------] 3 tests from MergingKDBTest (24 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (24 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] MergingKDBTest.HandlesUnconflictingKeySets
[  FAILED  ] MergingKDBTest.ThrowsIfNoConflictStrategyRegistered
[  FAILED  ] MergingKDBTest.MergesResolvableConflicts

 3 FAILED TESTS
  YOU HAVE 2 DISABLED TESTS


        Start  10: testtool_newkeystrategy
 10/101 Test  #10: testtool_newkeystrategy ..........   Passed    0.02 sec
        Start  11: testtool_mergecases
 11/101 Test  #11: testtool_mergecases ..............   Passed    0.01 sec
        Start  12: testtool_pluginspec
 12/101 Test  #12: testtool_pluginspec ..............   Passed    0.01 sec
        Start  13: testtool_comparison
 13/101 Test  #13: testtool_comparison ..............   Passed    0.01 sec
        Start  14: testtool_automergestrategy
 14/101 Test  #14: testtool_automergestrategy .......   Passed    0.01 sec
        Start  15: testtool_metamergestrategy
 15/101 Test  #15: testtool_metamergestrategy .......   Passed    0.01 sec
        Start  16: testtool_samemountpoint
 16/101 Test  #16: testtool_samemountpoint ..........   Passed    0.02 sec
        Start  17: testtool_keyhelper
 17/101 Test  #17: testtool_keyhelper ...............   Passed    0.01 sec
        Start  18: testcpp_contextual_thread
 18/101 Test  #18: testcpp_contextual_thread ........   Passed    0.26 sec
        Start  19: testcpp_contextual_basic
 19/101 Test  #19: testcpp_contextual_basic .........   Passed    0.06 sec
        Start  20: testcpp_iter_name
 20/101 Test  #20: testcpp_iter_name ................   Passed    0.01 sec
        Start  21: testcpp_ks
 21/101 Test  #21: testcpp_ks .......................   Passed    0.03 sec
        Start  22: testcpp_kdb
 22/101 Test  #22: testcpp_kdb ......................   Passed    0.02 sec
        Start  23: testcpp_contextual_update
 23/101 Test  #23: testcpp_contextual_update ........   Passed    0.02 sec
        Start  24: testcpp_contextual_policy
 24/101 Test  #24: testcpp_contextual_policy ........   Passed    0.01 sec
        Start  25: testcpp_ksget
 25/101 Test  #25: testcpp_ksget ....................   Passed    0.01 sec
        Start  26: testcpp_contextual_nocontext
 26/101 Test  #26: testcpp_contextual_nocontext .....   Passed    0.01 sec
        Start  27: testcpp_iter
 27/101 Test  #27: testcpp_iter .....................   Passed    0.01 sec
        Start  28: testcpp_meta
 28/101 Test  #28: testcpp_meta .....................   Passed    0.01 sec
        Start  29: testcpp_keyio
 29/101 Test  #29: testcpp_keyio ....................   Passed    0.01 sec
        Start  30: testcpp_key
 30/101 Test  #30: testcpp_key ......................   Passed    0.02 sec
        Start  31: testpy2_key.py
 31/101 Test  #31: testpy2_key.py ...................   Passed    0.29 sec
        Start  32: testpy2_keyset.py
 32/101 Test  #32: testpy2_keyset.py ................   Passed    0.02 sec
        Start  33: testpy2_kdb.py
 33/101 Test  #33: testpy2_kdb.py ...................   Passed    0.03 sec
        Start  34: test_kdb.lua
 34/101 Test  #34: test_kdb.lua .....................   Passed    0.06 sec
        Start  35: test_keyset.lua
 35/101 Test  #35: test_keyset.lua ..................   Passed    0.01 sec
        Start  36: test_key.lua
 36/101 Test  #36: test_key.lua .....................   Passed    0.00 sec
        Start  37: test_context
 37/101 Test  #37: test_context .....................   Passed    0.02 sec
        Start  38: test_getenv
 38/101 Test  #38: test_getenv ......................   Passed    0.02 sec
        Start  39: test_fork
 39/101 Test  #39: test_fork ........................   Passed    0.01 sec
        Start  40: testmod_augeas
 40/101 Test  #40: testmod_augeas ...................   Passed    0.13 sec
        Start  41: testmod_base64
 41/101 Test  #41: testmod_base64 ...................   Passed    0.01 sec
        Start  42: testmod_boolean
 42/101 Test  #42: testmod_boolean ..................   Passed    0.00 sec
        Start  43: testmod_ccode
 43/101 Test  #43: testmod_ccode ....................   Passed    0.00 sec
        Start  44: testmod_conditionals
 44/101 Test  #44: testmod_conditionals .............   Passed    0.01 sec
        Start  45: testmod_csvstorage
 45/101 Test  #45: testmod_csvstorage ...............   Passed    0.02 sec
        Start  46: testmod_dbus
 46/101 Test  #46: testmod_dbus .....................   Passed    0.02 sec
        Start  47: testmod_dpkg
 47/101 Test  #47: testmod_dpkg .....................   Passed    0.00 sec
        Start  48: testmod_dump
 48/101 Test  #48: testmod_dump .....................   Passed    0.00 sec
        Start  49: testmod_enum
 49/101 Test  #49: testmod_enum .....................   Passed    0.01 sec
        Start  50: testmod_fcrypt
 50/101 Test  #50: testmod_fcrypt ...................   Passed    0.15 sec
        Start  51: testmod_filecheck
 51/101 Test  #51: testmod_filecheck ................   Passed    0.02 sec
        Start  52: testmod_fstab
 52/101 Test  #52: testmod_fstab ....................   Passed    0.01 sec
        Start  53: testmod_glob
 53/101 Test  #53: testmod_glob .....................   Passed    0.00 sec
        Start  54: testmod_hexcode
 54/101 Test  #54: testmod_hexcode ..................   Passed    0.00 sec
        Start  55: testmod_hosts
 55/101 Test  #55: testmod_hosts ....................   Passed    0.03 sec
        Start  56: testmod_iconv
 56/101 Test  #56: testmod_iconv ....................   Passed    0.02 sec
        Start  57: testmod_ini
 57/101 Test  #57: testmod_ini ......................   Passed    0.05 sec
        Start  58: testmod_keytometa
 58/101 Test  #58: testmod_keytometa ................   Passed    0.00 sec
        Start  59: testmod_line
 59/101 Test  #59: testmod_line .....................   Passed    0.00 sec
        Start  60: testmod_lineendings
 60/101 Test  #60: testmod_lineendings ..............   Passed    0.00 sec
        Start  61: testmod_list
 61/101 Test  #61: testmod_list .....................   Passed    0.02 sec
        Start  62: testmod_mathcheck
 62/101 Test  #62: testmod_mathcheck ................   Passed    0.01 sec
        Start  63: testmod_mozprefs
 63/101 Test  #63: testmod_mozprefs .................   Passed    0.01 sec
        Start  64: testmod_network
 64/101 Test  #64: testmod_network ..................   Passed    0.00 sec
        Start  65: testmod_ni
 65/101 Test  #65: testmod_ni .......................   Passed    0.00 sec
        Start  66: testmod_profile
 66/101 Test  #66: testmod_profile ..................   Passed    0.00 sec
        Start  67: testmod_rename
 67/101 Test  #67: testmod_rename ...................   Passed    0.00 sec
        Start  68: testmod_resolver
 68/101 Test  #68: testmod_resolver .................   Passed    0.00 sec
        Start  69: testmod_shell
 69/101 Test  #69: testmod_shell ....................   Passed    0.00 sec
        Start  70: testmod_spec
 70/101 Test  #70: testmod_spec .....................   Passed    0.00 sec
        Start  71: testmod_uname
 71/101 Test  #71: testmod_uname ....................   Passed    0.00 sec
        Start  72: testmod_validation
 72/101 Test  #72: testmod_validation ...............   Passed    0.01 sec
        Start  73: testmod_xmltool
 73/101 Test  #73: testmod_xmltool ..................   Passed    0.04 sec
        Start  74: testmod_yajl
 74/101 Test  #74: testmod_yajl .....................   Passed    0.04 sec
        Start  75: testabi_rel
 75/101 Test  #75: testabi_rel ......................   Passed    0.00 sec
        Start  76: testabi_key
 76/101 Test  #76: testabi_key ......................   Passed    0.00 sec
        Start  77: testabi_ks
 77/101 Test  #77: testabi_ks .......................   Passed    0.02 sec
        Start  78: testabi_meta
 78/101 Test  #78: testabi_meta .....................   Passed    0.00 sec
        Start  79: test_spec
 79/101 Test  #79: test_spec ........................   Passed    0.00 sec
        Start  80: test_backend
 80/101 Test  #80: test_backend .....................   Passed    0.00 sec
        Start  81: test_plugin
 81/101 Test  #81: test_plugin ......................   Passed    0.00 sec
        Start  82: test_args
 82/101 Test  #82: test_args ........................   Passed    0.00 sec
        Start  83: test_opmphm_vheap
 83/101 Test  #83: test_opmphm_vheap ................   Passed    0.00 sec
        Start  84: test_mountsplit
 84/101 Test  #84: test_mountsplit ..................   Passed    0.00 sec
        Start  85: test_internal
 85/101 Test  #85: test_internal ....................   Passed    0.00 sec
        Start  86: test_splitset
 86/101 Test  #86: test_splitset ....................   Passed    0.00 sec
        Start  87: test_ks
 87/101 Test  #87: test_ks ..........................   Passed    0.00 sec
        Start  88: test_split
 88/101 Test  #88: test_split .......................   Passed    0.00 sec
        Start  89: test_keyname
 89/101 Test  #89: test_keyname .....................   Passed    0.00 sec
        Start  90: test_mount
 90/101 Test  #90: test_mount .......................   Passed    0.00 sec
        Start  91: test_splitget
 91/101 Test  #91: test_splitget ....................   Passed    0.00 sec
        Start  92: test_proposal
 92/101 Test  #92: test_proposal ....................   Passed    0.00 sec
        Start  93: test_size
 93/101 Test  #93: test_size ........................   Passed    0.00 sec
        Start  94: test_key
 94/101 Test  #94: test_key .........................   Passed    0.03 sec
        Start  95: test_meta
 95/101 Test  #95: test_meta ........................   Passed    0.00 sec
        Start  96: test_namespace
 96/101 Test  #96: test_namespace ...................   Passed    0.00 sec
        Start  97: test_trie
 97/101 Test  #97: test_trie ........................   Passed    0.00 sec
        Start  98: test_operation
 98/101 Test  #98: test_operation ...................   Passed    0.00 sec
        Start  99: test_opmphm_vstack
 99/101 Test  #99: test_opmphm_vstack ...............   Passed    0.00 sec
        Start 100: test_order
100/101 Test #100: test_order .......................   Passed    0.00 sec
        Start 101: test_array
101/101 Test #101: test_array .......................   Passed    0.00 sec

99% tests passed, 1 tests failed out of 101

Label Time Summary:
bindings    =   0.42 sec
kdbtests    =   0.15 sec
memleak     =   0.48 sec

Total Test time (real) =   2.45 sec

The following tests FAILED:
	  9 - testtool_mergingkdb (Failed)
Errors while running CTest
debian/rules:63: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 8
make[1]: Leaving directory '/home/vagrant/libelektra'
debian/rules:56: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```
I'm not sure if this is a problem of the build process or the tests beeing too old?
It seems to me the testsuite tries to write to /etc which does obviously not work because I'm not running the build process as root.

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build git-buildpackage-jessie please

**Comment by markus2330** [comment]
Thank you for this PR! It is great to come closer to the excellent package as in Debian by @pinotree.

> How to do with the python packages? There is now libelektra4-python for the python2.7 bindings and python3-elektra for the python3 bindings. I think, this should be resolved more likely like: libelektra4-python for the parts that are actually a library for elektra (independend of the python version?) and python{,3}-elektra for the bindings for python.

From my side it only important that all bindings and plugins for both python2 and python3 are present. I would it rather split dependency-wise: binding and plugin to the same package, but separated for python2/3. But I am no expert in Debian packaging. @pinotree Can you give us some input here?

> Please check the changes in debian/rules. The Debian package used to build for ALL plugins and then get the right files into the packages. I saw, that the current rules file would selectively build the plugins.

Yes, if you can build ALL, its perfect. The selection was because some plugins did not build at some Debian versions.

Some bindings seems to be missing though, e.g. `swig_python;swig_ruby`.

> testtool_mergingkdb failed

The regex in `override_dh_auto_test` does not work anymore. Use `ctest --output-on-failure -LE kdbtests` instead, then it is our problem to exclude tests that need file system access ;)

Did you test the qt-gui and `kdb run_all` after installing?

@pinotree Is it okay for you that we use the `debian/*` files also with BSD license? It is in a different branch, but it would be easier if everything is roughly the same license.

**Comment by markus2330** [comment]
add to whitelist

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build git-buildpackage-jessie please

**Comment by reox** [comment]
I think we should add in our packaging the dependecies on the old packages, e.g.
in libelektra4:
Replaces: libelektra-core4
Breaks: libelektra-core4

i think this should give a clean way to change from the old package names to the new ones?

**Comment by markus2330** [comment]
> i think this should give a clean way to change from the old package names to the new ones?

Yes, that is a good idea!

Could you also fix all lintian issues?

I am really looking forward to these changes!

**Comment by reox** [comment]
for much of the linitan stuff, I think it has to be changed in the buildprocess and not in the debian files?
```
W: elektra source: binaries-have-file-conflict elektra-bin elektra-qt-gui usr/share/man/man1/kdb-qt-gui.1.gz
W: elektra source: changelog-should-mention-nmu
W: elektra source: source-nmu-has-incorrect-version-number 0.8.19-1
W: libelektra4: breaks-without-version libelektra-core4
W: libelektra4: extra-license-file usr/share/doc/elektra/LICENSE.md
W: libelektra4: non-dev-pkg-with-shlib-symlink usr/lib/x86_64-linux-gnu/libelektra-proposal.so.0.8.19 usr/lib/x86_64-linux-gnu/libelektra-proposal.so
W: libelektra4: non-dev-pkg-with-shlib-symlink usr/lib/x86_64-linux-gnu/libelektra-meta.so.0.8.19 usr/lib/x86_64-linux-gnu/libelektra-meta.so
W: libelektra4: non-dev-pkg-with-shlib-symlink usr/lib/x86_64-linux-gnu/libelektra-kdb.so.0.8.19 usr/lib/x86_64-linux-gnu/libelektra-kdb.so
W: libelektra4: non-dev-pkg-with-shlib-symlink ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: libelektra4: dev-pkg-without-shlib-symlink usr/lib/x86_64-linux-gnu/libelektraintercept-fs.so usr/lib/x86_64-linux-gnu/libelektraintercept-fs.so
W: libelektra4: shlib-without-versioned-soname usr/lib/x86_64-linux-gnu/libelektraintercept-fs.so libelektraintercept-fs.so
W: libelektra4-python: breaks-without-version libelektra-python4
W: elektra-bin: package-name-doesnt-match-sonames libelektratools2
W: elektra-bin: manpage-has-bad-whatis-entry usr/share/man/man1/kdb-qt-gui.1.gz
W: elektra-bin: binary-without-manpage usr/bin/kdb-full
E: elektra-bin: python-script-but-no-python-dep usr/lib/x86_64-linux-gnu/elektra/tool_exec/find-tools
E: elektra-bin: python-script-but-no-python-dep usr/lib/x86_64-linux-gnu/elektra/tool_exec/gen
W: elektra-bin: executable-not-elf-or-script usr/lib/x86_64-linux-gnu/elektra/tool_exec/ffconfig/setupProxy
W: elektra-bin: executable-not-elf-or-script usr/lib/x86_64-linux-gnu/elektra/tool_exec/ffconfig/setupHomepage
W: elektra-bin: executable-not-elf-or-script usr/lib/x86_64-linux-gnu/elektra/tool_exec/ffconfig/writeConfigFiles
W: elektra-bin: executable-not-elf-or-script ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: elektra-bin: non-dev-pkg-with-shlib-symlink usr/lib/x86_64-linux-gnu/libelektratools.so.0.8.19 usr/lib/x86_64-linux-gnu/libelektratools.so
E: elektra-bin: shlib-in-multi-arch-foreign-package usr/lib/x86_64-linux-gnu/libelektratools.so.0.8.19
W: elektra-doc: embedded-javascript-library usr/share/doc/elektra-doc/libelektra-doc/html/jquery.js please use libjs-jquery
W: elektra-doc: manpage-has-bad-whatis-entry usr/share/man/man3/automergeconfiguration.cpp.3elektra.gz
W: elektra-doc: manpage-has-bad-whatis-entry usr/share/man/man3/backends.cpp.3elektra.gz
W: elektra-doc: manpage-has-bad-whatis-entry usr/share/man/man3/deprecated.3elektra.gz
W: elektra-doc: manpage-has-bad-whatis-entry ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: elektra-doc: manpage-has-errors-from-man usr/share/man/man3/doc_CODING_md.3elektra.gz 179: warning [p 3, 8.3i]: can't break line
W: elektra-doc: manpage-has-errors-from-man usr/share/man/man3/doc_NEWS_md.3elektra.gz 595: warning [p 10, 10.2i]: can't break line
W: elektra-doc: manpage-has-errors-from-man usr/share/man/man3/doc_decisions_bool_md.3elektra.gz 67: warning: macro `false',' not defined
W: elektra-doc: manpage-has-errors-from-man ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: elektra-doc: manpage-not-compressed usr/share/man/man3/examples_backend.cpp.3elektra
E: elektra-doc: doc-base-file-references-missing-file elektra-doc:7 /usr/share/doc/elektra-doc/html/index.html
E: elektra-doc: doc-base-file-references-missing-file elektra-doc:8 /usr/share/doc/elektra-doc/html/*.html
E: elektra-qt-gui: binary-or-shlib-defines-rpath usr/bin/elektra-qt-editor /home/vmmanage/libelektra/obj-x86_64-linux-gnu/lib
W: elektra-qt-gui: manpage-has-bad-whatis-entry usr/share/man/man1/kdb-qt-gui.1.gz
W: elektra-qt-gui: binary-without-manpage usr/bin/elektra-qt-editor
W: elektra-qt-gui: desktop-entry-invalid-category Elektra usr/share/applications/org.libelektra.elektra-qt-editor.desktop
W: elektra-qt-gui: desktop-entry-invalid-category Configuration usr/share/applications/org.libelektra.elektra-qt-editor.desktop
N: 30 tags overridden (6 warnings, 24 info)
```

for example all those manpage errors

**Comment by markus2330** [comment]
Yes, some of the lintian warnings seem to be doxygen issues (manpage-has-bad-whatis-entry, manpage-has-errors-from-man), but all the `E` (errors) seem to be packaging related.

**Comment by markus2330** [comment]
jenkins build git-buildpackage-jessie please

**Comment by markus2330** [comment]
Btw. can you also try to build master? E.g. binary-or-shlib-defines-rpath of qt-editor should be fixed there. ("jenkins build git-buildpackage-jessie please" builds master)

**Comment by reox** [comment]
Do you have an idea how this can be easily done? Do you merge master into the debian branch and use `git archive` to create a tar?

**Comment by markus2330** [comment]
You can see it in the build log of the aforementioned git-buildpackage-jessie job. For your convenience:

```
# already on master with tag
git checkout -b master origin/master
git tag -f $VERSION

git checkout -b debian origin/debian
git merge --no-ff -m "merge $VERSION" master

dch -l ".$BUILD_NUMBER" "auto build"

git commit -am "auto build $VERSION"
#dpkg-source -b .. --commit

git buildpackage -sa
```

Obviously this repo needs to be discarded afterwards.

**Comment by reox** [comment]
I get this warning in the build process:
```
dpkg-gencontrol: Warnung: Feld Depends von Paket libelektra-dev: unbekannte Substitutionsvariable ${shlibs:Depends}
dpkg-gencontrol: Warnung: Paket python3-elektra: unbenutzte Substitutionsvariable ${python3:Provides}
dpkg-gencontrol: Warnung: Paket python3-elektra: unbenutzte Substitutionsvariable ${python3:Versions}
dpkg-gencontrol: Warnung: Paket python-elektra: unbenutzte Substitutionsvariable ${python:Provides}
dpkg-gencontrol: Warnung: Paket python-elektra: unbenutzte Substitutionsvariable ${python:Versions}
dpkg-gencontrol: Warnung: Feld Depends von Paket elektra-bin: unbekannte Substitutionsvariable ${python:Depends}
```

No idea why this is a problem... Who has packaged python packages and know what to do? because i think its correct... what's with the elektra-bin package I dont know either :/

**Comment by markus2330** [comment]
jenkins build git-buildpackage-jessie please

**Comment by markus2330** [comment]
jenkins build git-buildpackage-jessie please

**Comment by markus2330** [comment]
Thank you, great job!

**Pull request merged**
