### PR TITLE
Elektra Web 1.5 (fixed)

### PR DESCRIPTION
**Pull request by omnidan**
@markus2330 I created a new PR to work around the commit problem.

old PR: #2029

### CODE REVIEW

**Comment by markus2330** [comment]
Now you squashed all commits (commit history is lost). Please keep your commits.

**Comment by omnidan** [comment]
@markus2330 I do not know how to do this now without manually cherry picking commits from the other branch...

**Comment by markus2330** [comment]
cherry picking is also easy with this little number of commits.

**Comment by omnidan** [comment]
#2100

**Comment by omnidan** [comment]
#2101

**Pull request closed without merging**
