### PR TITLE
Improve error messages (crypto, fcrypt, gpgme)

### LINKED ISSUE #3022: error messages in crypto plugins&tests
I think in general it would be good if the crypto plugins and the crypto test cases give better error messages. Should I open a new issue for this? 

```
 95/267 Test  #93: testmod_gpgme .................................***Failed    0.18 sec
OK closing connection
GPGME        TESTS
==================

/home/markus/Projekte/Elektra/current/src/plugins/gpgme/testmod_gpgme.c:227: error in test_encryption_decryption: kdb get failed
/home/markus/Projekte/Elektra/current/src/plugins/gpgme/testmod_gpgme.c:243: error in test_encryption_decryption: key type not restored to string during decryption
/home/markus/Projekte/Elektra/current/src/plugins/gpgme/testmod_gpgme.c:244: error in test_encryption_decryption: key content not restored during decryption
/home/markus/Projekte/Elektra/current/src/plugins/gpgme/testmod_gpgme.c:254: error in test_encryption_decryption: key content not restored during decryption

gpgme Results: 45 Tests done — 4 errors
```

### PR DESCRIPTION
**Pull request by petermax2**
Closes #3022 .

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy.
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by petermax2** [comment]
`testmod_dbusrecv` failed on Travis. Is this a known issue?

	DBUSRECV TESTS
	==============
	testing prerequisites
	detecting available bus types - please ignore single error messages prefixed with "connect:"
	connect: Failed to open connection to system message bus: Failed to connect to socket /usr/local/var/run/dbus/system_bus_socket: No such file or directory
	test commit
	../src/plugins/dbusrecv/testmod_dbusrecv.c:180: error in test_commit: string "system/tests/testmod_dbusrecv/changed" is not equal to "user/tests/foo/bar"
		compared: expectedKeyName and keyName (test_callbackKey)
	test adding keys
	../src/plugins/dbusrecv/testmod_dbusrecv.c:228: error in test_keyAdded: string "system/tests/testmod_dbusrecv/added" is not equal to "user/tests/foo"
		compared: expectedKeyName and keyName (test_callbackKey)
	test adding keys
	../src/plugins/dbusrecv/testmod_dbusrecv.c:276: error in test_keyChanged: string "system/tests/testmod_dbusrecv/changed" is not equal to "user/tests/foo/bar"
		compared: expectedKeyName and keyName (test_callbackKey)
	testmod_dbusrecv Results: 34 Tests done — 3 errors.

**Comment by sanssecours** [comment]
> `testmod_dbusrecv` failed on Travis. Is this a known issue?

[Yes](https://github.com/ElektraInitiative/libelektra/issues/2439), the test sometimes fails in situation with high load. The test does not fail on Jenkins, because we do not execute it at all:

https://github.com/ElektraInitiative/libelektra/blob/dc24c7fc23a247127b29ff7023c933b336123e17/scripts/jenkins/Jenkinsfile#L1301-L1317

.

**Comment by petermax2** [comment]
After restarting the job on Travis the test succeeded.

**Comment by markus2330** [comment]
Thank you very much for this PR!

@petermax2 is this still work in progress?

**Comment by petermax2** [comment]
It is ready to merge, I was just waiting for the build servers to finish.

**Comment by markus2330** [comment]
Thank you, great work! You fixed a lot of @Piankero's TODOs.

**Comment by Piankero** [comment]
Sorry for the late reply but the PR is good!
Thank you very much for the help concerning those error messages. It was very hard for me to understand how and what errors can actually occur! :)

**Pull request merged**
