### PR TITLE
Scripts: find-tools makes now pep and pyflakes happy

### PR DESCRIPTION
**Pull request by KurtMi**

### CODE REVIEW

**Comment by markus2330** [comment]
We can discuss again if we want to change style of python scripts, but this would make the tab usage inconsistent to other python scripts, so I will delay this after release.

**Comment by KurtMi** [comment]
I thought I fix all pep warnings, but I will change it back to tabs, so it is done!

**Comment by markus2330** [comment]
Actually pep8 does not make much sense here, its a completely different style than we are using.

I think we should either fully use pep8 or make it similar to our existing guidelines. I would favour our own guidelines, it makes editor settings easier.

We should also consider the python code we already have.

**Comment by KurtMi** [comment]
Ok then, leave this PR open I will push the file search also here, asap!

**Comment by KurtMi** [comment]
@markus2330 should be fine now and fix #782 and #799. Sorry for the delay, it planned to do it before 8.17.

**Comment by KurtMi** [comment]
jenkins build please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
