### PR TITLE
INI: Add Crash Test

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This PR adds a crash test for the INI plugin. The test uses various problematic input files we determined using [AFL](https://github.com/ElektraInitiative/libelektra/issues/185#issuecomment-352291498).

The pull request also contains bug fixes for the INI plugin and various other minor enhancements.

# Checklist

- [x] I checked all commit messages.
- [x] I added a Markdown Shell Recorder test.
- [x] I ran all tests and everything went fine.
- [x] The PR adds logging statements to the code of the INI plugin.
- [x] I also added information about the changes to the INI plugin to the release notes.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Does every of these crash tests need a different fix? I would favor if we do not have to include so much data into the main repository. It is enough to have a regression test for every fix that was added.

To see if everything is fixed, we need to rerun AFL anyway.

**Comment by sanssecours** [comment]
> Does every of these crash tests need a different fix? 

Nope.

> I would favor if we do not have to include so much data into the main repository. It is enough to have a regression test for every fix that was added.

I feared that you would say something like that. I will have a look and try to only include minimal examples for the crash test.

> To see if everything is fixed, we need to rerun AFL anyway.

Yeah, I think we should do that after Thomas (@tom-wa) has time to work on the INI plugin again 😊.

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by markus2330** [comment]
Do you know what the problems of elektra-multiconfig-gcc-stable and elektra-multiconfig-gcc47-cmake-options are?

**Comment by sanssecours** [comment]
> Do you know what the problems of elektra-multiconfig-gcc-stable and elektra-multiconfig-gcc47-cmake-options are?

The build job `elektra-multiconfig-gcc-stable` fails about half of the time, usually because of problems with the `semlock` plugin (see issue #1260).

Running `elektra-multiconfig-gcc47-cmake-options` fails, if you change anything on `master` in the meantime. This situation is quite common, since running `elektra-multiconfig-gcc47-cmake-options` takes about half a day.

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by markus2330** [comment]
Thank you for your investigation. Any idea why changes in master lead to failures? If we cannot work around this, I propose to disable this job (or even the other multi-config, too?). With little changes to other jobs, it might be redundant anyway.

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc47-cmake-options please

**Comment by sanssecours** [comment]
jenkins build multiconfig-gcc-stable please

**Comment by sanssecours** [comment]
> Any idea why changes in master lead to failures?

Looks like this might be an [Jenkins issue](https://github.com/janinko/ghprb/issues/116), but I am not really sure about that.

**Comment by markus2330** [comment]
The issue might be related but we might have hit another corner case (because of the multi-config jobs). Can you report our case?

**Comment by sanssecours** [comment]
> Can you report our case?

Seems like using `${ghprbActualCommit}` instead of `${sha1}` might solve our issue. At least the build of `elektra-multiconfig-gcc47-cmake-options` in this PR has not failed yet.

**Comment by markus2330** [comment]
Thank you, great work!

**Pull request merged**
