### PR TITLE
 Add fix to arguments for create methods in HelloElektra.java

### PR DESCRIPTION
**Pull request by dmoisej**
## Basics

Do not describe the purpose here but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [x] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating this PR! It seems like there is a syntactical error in the release notes.

Some additional comments in the HelloElektra.java is very much appreciated.

**Comment by dmoisej** [comment]
Hi, I see that. Firstly I believe I see the problem with release notes and also I will add additional comments but could you help me with release notes?

As I changed the code in the example for Java binding, in what section do I need to put the release notes in the doc/news/_preparation_next_release.md? Should it be Bindings section?

**Comment by markus2330** [comment]
> Hi, I see that. Firstly I believe I see the problem with release notes and also I will add additional comments but could you help me with release notes?

You only need to surround your name with `_`, i.e. change `(Dmytro Moiseiuk)` to `_(Dmytro Moiseiuk)_`. See also what the build server says: https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2542/1/

> As I changed the code in the example for Java binding, in what section do I need to put the release notes in the doc/news/_preparation_next_release.md? Should it be Bindings section?

Yes, Bindings is fine!

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by dmoisej** [comment]
Fixed the release notes. The pull request is updated.

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
