### PR TITLE
Sanitizer: Ignore Issues in Old Versions of `libstdc++`

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This PR simplifies the build process by using a blacklist to ignore sanitizer problems in `libstdc++`. Before this update we would explicitly disable tests, that reported problems in `libstdc++`.

# Checklist

- [x] I checked the only commit message twice.
- [x] I ran all tests and everything went fine.
- [x] I added a code comment in the sanitizer blacklist.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
Does anybody know why the sanitizer reports the following [errors](https://build.libelektra.org/jenkins/job/elektra-clang-asan/330/console):

```
src/libs/tools/src/plugin.cpp:(105:2|394:9|404:9): 
  runtime error: call to function (unknown) through pointer to incorrect function type 
  
  'int (*)(ckdb::_Plugin *, ckdb::_KeySet *, ckdb::_Key *)'

(build/lib/libelektra-storage.so+0xe080): note: (unknown) defined here
SUMMARY: AddressSanitizer: undefined-behavior
```

in

- `testshell_selftest`
- `testshell_markdown_tutorial_validation`
- `testshell_markdown_base64`
- `testshell_markdown_mini`
- `testshell_markdown_tcl`

? The errors in `testshell_markdown_mini` seem especially strange, since `testshell_markdown_camel` works without any problems, and I do not see any difference in the plugin interface between the mINI and Camel plugin.

**Comment by markus2330** [comment]
> Does anybody know why the sanitizer reports the following errors:

Can you try if the error also happens with STATIC/FULL build. If there is a difference, the problem might be in the dlopen interface. Differences between the plugins might be explained because you have mounted one of the plugins but not the others?

**Comment by sanssecours** [comment]
I now executed the tests inside a Virtual Machine running Debian Stretch. Interestingly the sanitizer prints the same error messages, but in another test (`testshell_markdown_kdb-complete`).

**Comment by sanssecours** [comment]
> Can you try if the error also happens with STATIC/FULL build?

The table below shows the results.

| Type           |                     Compilation                       |            Failed Tests           |
|:--------------:|:-----------------------------------------------------:|:---------------------------------:|
| `FULL`         | `undefined reference to `__ubsan_vptr_type_cache'`   |                 ❌                |
| `SHARED`       |                          ✅                         | `testshell_markdown_kdb-complete`  |
| `STATIC`       |                          ✅                         | `testshell_db_changes`, …          |

**Log:** [Static Build - Failed Tests.txt](https://github.com/ElektraInitiative/libelektra/files/1558749/Static.Build.log.txt)

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
@markus2330 Since you reacted with a “confused emoji” to the [table above](https://github.com/ElektraInitiative/libelektra/pull/1728#issuecomment-351669233):

- Translating Elektra with `BUILD_FULL=ON` (`BUILD_SHARED=OFF`, `BUILD_STATIC=OFF`, `ENABLE_ASAN=ON`) does not work
- Translating Elektra with `BUILD_STATIC=ON` (`BUILD_SHARED=OFF`, `BUILD_FULL=OFF`, `ENABLE_ASAN=ON`) produces even more test failures

**Comment by markus2330** [comment]
Thank you for the extra info. Seems like dlopen does not cause (all) the problem(s), otherwise full/static should have no errors. With full/static calls to plugins are ordinary function calls. I am confused about what the actual problem is.

> undefined reference to __ubsan_vptr_type_cache

Seems like `-lubsan` is missing somewhere or not correctly placed within the command-line options of gcc?

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
Looks like the error messages about the call through a function pointer of incorrect type do indeed show a problem. At least ignoring the messages does not fix the failing tests.

**Comment by sanssecours** [comment]
I opened an issue about the failing test `testshell_markdown_kdb-complete` [here](https://github.com/ElektraInitiative/libelektra/issues/1747).

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build clang-asan please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Thank you for the PR! Travis seems to have problems, hopefully it builds on the master now.

**Pull request merged**
