### PR TITLE
mathcheck: fix #653 + many other things

### LINKED ISSUE #653: OpenBSD: testmod_mathcheck fails
19/104 Test  #19: testmod_mathcheck ..................***Failed    0.01 sec
	elektraFtoA: val: 1.5, ret: 1.5
	elektraEFtoF: string: 1.5, ret: 1.5
	MATHCHECK	   TESTS
	==================

	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:73: error in main: error
	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:77: error in main: error
	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:81: error in main: error
	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:84: error in main: error
	/root/Projekte/libelektra/src/plugins/mathcheck/testmod_mathcheck.c:87: error in main: error

	testmod_mathcheck RESULTS: 60 test(s) done. 5 error(s).

### PR DESCRIPTION
**Pull request by tom-wa**
# Purpose

fixed #653 + some other issues and a broken unittest

# Checklist

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
@KurtMi @petermax2 Can you check if known mathcheck problems are fixed now?

@tom-wa please add unit tests to avoid future regressions.

**Comment by petermax2** [comment]
Confirmed OpenBSD 6.0 build and test run for 52c357d8354b11fb93d5ad016c2a1669042e9e84 :

    # ./bin/testmod_mathcheck                                                                                                                   
    MATHCHECK          TESTS
    ==================


    testmod_mathcheck RESULTS: 60 test(s) done. 0 error(s).
    elektraFtoA: val: 1.5, ret: 1.5
    elektraEFtoF: string: 1.5, ret: 1.5

Confirmed Fedora 24 build and test run for 52c357d8354b11fb93d5ad016c2a1669042e9e84 . Same results here.

The problem seems to be fixed.

**Comment by petermax2** [comment]
Also works on OS X.

**Comment by markus2330** [comment]
@petermax2 thank you for checking!

@tom-wa please add unit tests to avoid future regressions.

**Comment by petermax2** [comment]
@tom-wa could you please have a look at the memory leak in #942 ?

**Comment by tom-wa** [comment]
@petermax2 also fixed with this PR.

**Comment by petermax2** [comment]
Thank you!

**Comment by KurtMi** [comment]
This PR does not fix #721 with test cases in #870

**Comment by tom-wa** [comment]
@KurtMi thats an issue with #870, i've added a comment there.

**Comment by markus2330** [comment]
Ok, thank you! Let us continue discussion at #870.

**Pull request merged**
