### PR TITLE
Cirrus: Use Bourne Shell Compatible Syntax

### PR DESCRIPTION
**Pull request by sanssecours**

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the quick fix!

**Comment by markus2330** [comment]
Is this ready to merge?

**Comment by sanssecours** [comment]
> Is this ready to merge?

Since you merged pull request #2847 before this PR, nope.

**Comment by markus2330** [comment]
Ok, sorry. Should I also change == to =?

**Comment by sanssecours** [comment]
> Should I also change == to =?

Since the comparison operator `==` seems to work too, I think it is not a problem to leave it as it is now. Strictly speaking [`==` is a Bash specific extension](https://unix.stackexchange.com/questions/168284/unix-test-when-to-use-eq-vs-vs-in-test-commands) though, as far as I know.

**Pull request closed without merging**
