### PR TITLE
crypto: Display available GPG keys if config option is missing.

### LINKED ISSUE #895: crypto plugin: list available keys in case of missing config
# Situation / Problem

If no gpg key is specified at `/gpg/key` at mount time, the following error message is displayed:

```
Error (#130) occurred!
Description: The configuration is invalid or incomplete.
Ingroup: plugin
Module: crypto
At: /root/libelektra/src/plugins/crypto/gpg.c:219
Reason: Missing GPG key (specified as /gpg/key) in plugin configuration.
Mountpoint: 
Configfile:
```
# Expected Behaviour (Proposal)

Additionally a list of available gpg keys should be presented to the user.

### PR DESCRIPTION
**Pull request by petermax2**
# Purpose

If /gpg/key is not provided in the plugin configuration a list of available GPG key IDs is shown in the error description.

Fixes #895 .

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [ ] I added unit tests
- [x] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Good to see activity from you again!

**Comment by markus2330** [comment]
Thank you, can you add some documentation of the new feature? (See also other requests about docu)

@sanssecours do you have some time to give this a try?

**Comment by markus2330** [comment]
jenkins build please

**Comment by sanssecours** [comment]
> @sanssecours do you have some time to give this a try?

I tried it and everything worked as described. I just saved my very first secret key 🙌. The change should improve usability of the `crypto` plugin for novice users like me quite considerably.

I noticed a **small bug** while I read the well-written and comprehensive `ReadMe` of the crypto plugin. It looks like the [HTML version of the documentation](https://www.libelektra.org/plugins/crypto) still contains `#ifdef` directives.

**Comment by markus2330** [comment]
> small bug

Its done correctly by @petermax2 (even though some more newlines around the `#ifdefs` would make the Markdown a bit more pretty). If you use `kdb info` the ifdefs should be gone.

Fixing it for the homepage is not so trivial, as it would need to understand the compilation variants. I added it to #1228.

**Comment by sanssecours** [comment]
> Fixing it for the homepage is not so trivial, as it would need to understand the compilation variants.

I just used the homepage as an example. I think this is a problem of the Doxygen documentation, rather than a problem of the website. Both, the HTML version of the documentation, and the PDF manual, contain `#ifdef` directives. 

> If you use `kdb info` the ifdefs should be gone.

That is correct. Thanks you for this useful information. For now I use the command

```sh
kdb info crypto_gcrypt > /tmp/help.md | open -a Marked /tmp/help.md
```

to read the documentation of the `crypto` plugin.

**Comment by markus2330** [comment]
> this is a problem of the Doxygen documentation, rather than a problem of the website. Both, the HTML version of the documentation, and the PDF manual, contain #ifdef directives.

Doxygen would be relatively easy to fix, we could run the preprocessor as filter. Nevertheless, I think its a minor issue thus we do not have many plugins that use compilation variants.

GitHub itself obviously always will show the `ifdefs`.

**Pull request merged**
