### PR TITLE
highlevel: fix linker flags

### LINKED ISSUE #2363: Linker flags for highlevel API
pkg-config and also `examples/highlevel/README.md` recommend to link against `elektra` but this library is deprecated. (It contains core+kdb for legacy applications that existed before our library split.)

Furthermore, the order of the linker flags seem to be incorrect, they currently are `-lelektra-kdb -lelektra-ease -lelektra-highlevel` but highlevel should be first, and then the libs to provide the symbols for highlevel.

So it is something like `highlevel kdb ease core`?

The "cmake" example does not have these problems.

### PR DESCRIPTION
**Pull request by kodebach**
Closes #2363 

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
It seems like that also LIBRARIES in ./src/libs/highlevel/CMakeLists.txt has the same problem. So #2364 is not fixed by this PR.

**Comment by kodebach** [comment]
The Travis build `🍏 FULL` timed out while building the caches, but run all tests successfully, so I'm marking this as "ready to merge".

PS. I think we should investigate speeding up macOS builds, they are a real bottleneck.

**Comment by kodebach** [comment]
> It seems like that also LIBRARIES in ./src/libs/highlevel/CMakeLists.txt has the same problem.

Not sure what you mean... I changed `LIBRARIES` in this PR so that it uses the correct order of libraries. Although afaik the order should only matter for static libraries.

**Comment by markus2330** [comment]
You are right, #2364 is fixed here.

I was confused by a different problem, which also exists also in the main elektra.pc file, see #2367

**Comment by kodebach** [comment]
> It would be really nice, if someone could look into this and fix the [timeout problems](https://github.com/ElektraInitiative/libelektra/issues/2310) properly.

I just took a quick look and found a few things:
- we are installing packages using `before_install` (why not `install`?), maybe the `apt` and `homebrew` [addons](https://docs.travis-ci.com/user/installing-dependencies/#installing-dependencies-on-multiple-operating-systems) are quicker in some way
- We should definitely cache `/home/travis/.rvm` (or the macOS equivalent if that is different). According to [Travis](https://docs.travis-ci.com/user/caching/) using `rvm install` might take a few minutes.
- Caching the Homebrew directory doesn't seem to speed up `brew install` because our jobs still take 10min+ for installing.
- Using `ninja -j2` or similar might be a good idea  (for build, not necessarily for testing), but I don't know what the best value for the Travis setup would be.
- If all that doesn't help, `ccache` might be worth a try.

**Comment by sanssecours** [comment]
> - we are installing packages using `before_install` (why not `install`?)

I assume we use `before_install`, since the [Travis documentation](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-standard-infrastructure) states that you should install dependencies in this step.

> maybe the `apt` and `homebrew` [addons](https://docs.travis-ci.com/user/installing-dependencies/#installing-dependencies-on-multiple-operating-systems) are quicker in some way

According to the Travis documentation using the Homebrew addon is the preferred way to install macOS dependencies. It might make sense to switch to the new system.

> - We should definitely cache `/home/travis/.rvm` (or the macOS equivalent if that is different). According to [Travis](https://docs.travis-ci.com/user/caching/) using `rvm install` might take a few minutes.

Sounds like a good idea.

> - Caching the Homebrew directory doesn't seem to speed up `brew install` because our jobs still take 10min+ for installing.

Caching the Homebrew installation cache is mainly a workaround against Homebrew starting to build packages from source, if it was unable to download a bottle (binary package) for a formula. I am not sure, if removing this cache would decrease the build time, but it might be worth a try.

> - Using `ninja -j2` or similar might be a good idea  (for build, not necessarily for testing), but I don't know what the best value for the Travis setup would be.

Ninja should (at least in theory) already utilize a multi-core system properly:

```sh
ninja -h
#> ...
#> -j N     run N jobs in parallel [default=10, derived from CPUs available]
#> ...
```

.

> EDIT: I thought you meant the macOS timeout problems on Travis...

Nope 😊, I meant the timeout problems of the notification bindings and plugins. Sorry for not pointing that out clearly. These timeouts happen on all of our build systems (Travis, Jenkins, Cirrus), which makes them especially annoying. Thanks for your input about speeding up the Travis build though 💖.

**Comment by markus2330** [comment]
Thank you for the interesting discussions. If possible, please move discussions to the corresponding issues, or at least link to it. If broad issues like #160 do not fit, please create new issues.

**Comment by markus2330** [comment]
> I'm marking this as "ready to merge".

I assume this should be ready to merge. Now also all builds were successful. Thank you!

**Pull request merged**
