### PR TITLE
Elektra api

### PR DESCRIPTION
**Pull request by domhof**
# Purpose

Elektra highlevel API

- Added support for enums and arrays
- Improved formatting of generated code
- Fixed key-normalization (trailing / and /# get removed as well)
- Fixed code generation for string default values
- Eliminated some public helper methods (fewer auto completion suggestions in IDEs makes it easier for developers to find the right elektra method)
- Removed error enums from error specification file (instead we use the raw error code)

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [ ] commit messages are fine (with references to issues)
- [ ] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
@tom-wa can you take a look?

**Comment by markus2330** [comment]
@domhof Please add some changelog what you changed since the last review of this PR.

**Comment by domhof** [comment]
@markus2330 I've added a log to the PR description.

**Comment by markus2330** [comment]
The PR seems to still contain wrong source code reformatting, did you use the correct clang? And a TODO next to the changelog would be good, too. Did you do everything as discussed? (For example is required+default logic implemented, full tutorial written, ...)

**Comment by domhof** [comment]
I'll close this PR for now and provide another PR with some updates. Regarding the format, is there anything else besides running the reformat-source script? I'm using clang-format version 3.8.0.

**Comment by markus2330** [comment]
> I'll close this PR for now and provide another PR with some updates.

Thank you! Please make sure that it is clear what the PR contains, what is missing, and what we should review.

> Regarding the format, is there anything else besides running the reformat-source script?

No, but you are you sure that your clang-format 3.8.0 is used? Maybe you have installed more than one version of llvm and clang-format of the another llvm is used?

I use `clang-format version 3.8.1-12~bpo8+1 (tags/RELEASE_381/final)`.

**Pull request closed without merging**
