### PR TITLE
[FLOSS P2] fish auto completion wrapper

### PR DESCRIPTION
**Pull request by muskater**
This is a prototype for the fish shell completion wrapper using the script from #3228 
The corresponding issue is #4051 

## How-To reproduce and test this RP

The easiest way is the following:
- Clone my [fork](https://github.com/muskater/libelektra/tree/p2_fish) and check-out the `p2_fish` branch
- Clone the [repository](https://github.com/ulrikeschaefer/libelektra) from @ulrikeschaefer
- Copy the whole content of `src/tools/autocompletion` in my repository
- Go through [this](https://www.libelektra.org/tutorials/run-all-tests-with-docker) tutorial for building the container
- Execute `fish`
- Mount the `kdb spec` files with 
`kdb mount /home/jenkins/workspace/src/tools/autocompletion/kdb-spec system:/spec/autocomplete/kdb -f ni`
- Create a symbolic link for the shell completion 
`ln -s ~/workspace/src/tools/autocompletion/kdb.fish  ~/.config/fish/completions/kdb.fish`
- Now the `kdb` shell completion should work!

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by muskater** [comment]
The changes in the Dockerfile will of course be reverted once this PR finalises. This is only so it is easier for someone else to test my changes.

**Comment by markus2330** [comment]
Did you already have a look at scripts/completion/kdb.fish? Probably it is best to keep on maintaining it for a bit and write a separate fish completion wrapper for other applications that have a specification.

**Comment by muskater** [comment]
Yes I did, the current fish completion wrapper is quite complicated, but feature complete.
Are there any particular applications that you were thinking about that would need a completion wrapper?

**Comment by markus2330** [comment]
> Yes I did, the current fish completion wrapper is quite complicated, but feature complete.

I am quite sure there are some tools introduced after the wrapper was updated the last time. E.g. `kdb basename` was quite recently introduced, does completion work there?

> Are there any particular applications that you were thinking about that would need a completion wrapper?

It probably makes sense to start testing with the `rm` command as written in the doc/tutorials/command-line-options.md

The next applications we should support (write specifications for) are the tools of Elektra, e.g. `kdb fuse`. @dev2718 can you maybe help writing that specification? In long term we want a specification for the whole `kdb` tool suite.

**Pull request closed without merging**
