### PR TITLE
fix #4432: opts docs: use arg/help instead of arg/name

### LINKED ISSUE #4432: elektraGetOptsHelpMessage docs/examples use 'opt/arg/name' instead of  'opt/arg/help'
## Steps to Reproduce the Problem

```c
...
(ks, keyNew (baseKeyName "spec:/test/path", KEY_META, "description", "Some description",  \
                                            KEY_META, "opt", "p", \
                                            KEY_META, "opt/arg/name", "path", \
                                            KEY_META, "opt/long", "path", \
                                            KEY_META, "opt/arg", "required", KEY_END));  \
...
... elektraGetOpts (ks, argc, (const char **) argv, (const char **) environ, errorKey);
...
char * help = elektraGetOptsHelpMessage (errorKey, NULL, NULL);
```

The `--help` output ignores the specified `opt/arg/name` and always uses `ARG` instead.

## Expected Result

```
OPTIONS
...
  -p path, --profile=path     Some description.
...

```

## Actual Result

```
OPTIONS
...
  -p ARG, --profile=ARG       Some description.
...

```

### PR DESCRIPTION
**Pull request by hannes99**
Replaces `arg/name` with `arg/help` in the opts examples and the docs where used.

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [x] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [x] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by hannes99** [comment]
Does anyone have an idea about how the failing test could be caused by the suggested changes?

**Comment by kodebach** [comment]
jenkins build libelektra please

**Comment by kodebach** [comment]
Not sure, the error was a timeout, so I restarted the build, maybe it was just a weird server load issue.

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
@hannes99 I only saw network problems in the build output (`Cannot contact l1: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel`) which is probably simply some instance of the network problem as reported in #160.

If there are any weird temporary problems, please restart the job using the phrase (see master.libelektra.org/doc/BUILDSERVER.md) and report the problem in #160.

If it is not that, please copy&paste the output of the failing test case I didn't see here as comment :wink:

**Comment by markus2330** [comment]
@hannes99 Thank you for the fix! :1st_place_medal: 

@lukashartl Thank you for restarting the job! :heart:

**Pull request merged**
