### PR TITLE
core: fix: kdb_long_double_t use when not available

### PR DESCRIPTION
**Pull request by DasRoteSkelett**
On two occasions, for kdb_long_double_t was checked even if this
type is not applicable on target platform.

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [ ] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [X ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [X ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

@markus2330 please review my pull request

## Merging

Please add the "ready to merge" label when the build server and you say
that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you very much for this bug report and the fix at the same time! :+1:

Can you please, as suggested by the buildserver, add your name in the release notes so that you get the proper credits? https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2729/1/pipeline says:

```The release notes were not extended correctly (with  lines changed).

Please make sure you add at least one line describing your contribution followed
by the text _(your name)_.

For example, if Sandra Power fixed a typo, she adds to doc/news/_preparation_next_release.md:

- typo fixed _(Sandra Power)_

Similar contributions might be summarized shortly before the release.


```

Furthermore there is a trivial formatting problem, please add a space after the comment. (We use an automatic formatting tool as described in https://master.libelektra.org/doc/CODING.md

**Comment by DasRoteSkelett** [comment]
Hi @markus2330 !

Thanks for the feedback. I hope, I addressed your concerns. 

Regards,

   Matthias

**Comment by markus2330** [comment]
Thank you! Let us see what the build server says.

May I ask how you use Elektra on mips?

**Comment by DasRoteSkelett** [comment]
Hi Markus,

I do not know why the build fail, I have run reformat-source on the files I touched. 

We are developing IoT Devices. We came across the need to store different data (From serial numbers to User defined commissioning data (WPA2 password for example)). Right now, I am evaluating elektra to be used in new and existing projects. Cross compiling was a bit of a struggle to be honest, and there is still a local patch I am not sure about if I should upstream it (basically, only add_subdirectory(benchmarks) if BUILD_TESTS is set. Do not need benchmarks, if cross compiling). Also, I find the specifications / metadata very interesting, but I am having problems finding out about the available options. We would need for example something like "readonly" or protection with md5 sums or other hashes of values. Also I would love to use the code generator for C++, but also it seems difficult for me to find useful information on this...

Regards,
   
   Matthias

**Comment by markus2330** [comment]
> I do not know why the build fail, I have run reformat-source on the files I touched.

The one with the failing links might have been a problem on the master, a rebase might help here. (@sanssecours do you maybe know about https://github.com/ElektraInitiative/libelektra/pull/2729/checks?check_run_id=137894241)

The one here https://github.com/ElektraInitiative/libelektra/pull/2729/checks?check_run_id=137884082 is about Markdown formatting (it is a different formatting tool). Here it should be enough to `quote` the `kdb_long_double_t`:

```
- Fixed minor problem when `kdb_long_double_t` is not available (e.g. mips32). _(Matthias Schoepfer)_
```

> We are developing IoT Devices. We came across the need to store different data (From serial numbers to User defined commissioning data (WPA2 password for example)). 

Nice. Elektra was already used for this. Would be great to see this working.

> Right now, I am evaluating elektra to be used in new and existing projects. Cross compiling was a bit of a struggle to be honest,

Yes, unfortunately there is no good tutorial on how to do it. The package of OpenWRT is currently the cleanest solution for cross-compilation, see https://github.com/openwrt/packages/blob/master/libs/elektra/Makefile

Please always feel free to ask questions here in the issue tracker.

> and there is still a local patch I am not sure about if I should upstream it (basically, only add_subdirectory(benchmarks) if BUILD_TESTS is set.

Yes, makes sense, I will accept that.

> Do not need benchmarks, if cross compiling). Also, I find the specifications / metadata very interesting, but I am having problems finding out about the available options.

https://master.libelektra.org/doc/METADATA.ini is a full description of all available specifications. The specifications are implemented by the [plugins](https://www.libelektra.org/plugins/readme). Regex, Basic Types and Ranges work very good (and are used a lot) For plugins marked as experimental it is better to ask before you spend too much time on it.

> We would need for example something like "readonly" or protection with md5 sums or other hashes of values.

restrict/write is already implemented in the Web-UI and it will be implemented soon by @kodebach  as plugin https://github.com/ElektraInitiative/libelektra/issues/2706

Simply set the permissions of the specifications in a way, that offending users/applications cannot change the specification, then it should be more safe than with md5 sums.

If you really want signatures, there is the [fcrypt](https://www.libelektra.org/plugins/fcrypt) plugin which can sign the whole file. @petermax2 (the author) would be very happy if you use it. But I am afraid it was not really used much before, so please expect bugs. @petermax2 is still active, so eventual bugs might be fixed by us, though.

> Also I would love to use the code generator for C++, but also it seems difficult for me to find useful information on this...

We now work on the high-level API, which also uses code generation (and is type safe and should provide guarantees that values are always returned). It is C and has less features than the previous [pythongen](https://master.libelektra.org/src/tools/pythongen/) but is will be also more reliable (we use it for a bigger project, LCDproc). The pythongen was mostly used for writing papers. It worked well for medium-sized prototypes and benchmarks. For questions, please open issues.

**Comment by petermax2** [comment]
> @petermax2 is still active, so eventual bugs might be fixed by us, though.

Active yes! But pretty stressed out, so please be patient if you assign tasks to me. :smile:

**Comment by sanssecours** [comment]
> do you maybe know about https://github.com/ElektraInitiative/libelektra/pull/2729/checks?check_run_id=137894241

The broken links were fixed in commit af053dcb. Please rebase the PR on the `master` branch to fix the build job output.

**Comment by markus2330** [comment]
A big thanks for the PR! Please open an issue for any questions.

**Pull request merged**
