### PR TITLE
Crypto-Plugin: ref counting for library initialization (WIP)

### PR DESCRIPTION
**Pull request by petermax2**
I prepared the library initialization using a simple ref counter (protected by a mutex) as preparation for the planned OpenSSL support.

- [x] investigate crypto API based ref counting
- [ ] check if gcrypt has been initialized (possibly by an application)

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you!

I think the abstraction can be improved: the ref counting schema is needed for openssl, but for others there might be a better solution (atomic refcounting already as part of a crypto-API).

So why not put the refcounting to the gcrypt and openssl provider of `elektraCryptoInit`? (No library has such ref counting is a valid answer: then the choice of abstraction is correct.)

**Comment by markus2330** [comment]
Btw. a way to avoid init/cleanup might be needed to. (e.g. If application already configured openssl)

**Comment by petermax2** [comment]
gcrypt does not seem to have any ref counting built into its public API. They might be using it internally  (I read some old discussions about it in developer forums). Libssl uses ref counting internally but they don't seem to make it public either. Libcrypto does not use any ref counting at all but provides a lock mechanism through its API. [1, 2] However this is the part of the API that we try to initialize here. ;)

[[1] The Libgcrypt Reference Manual](https://gnupg.org/documentation/manuals/gcrypt/index.html#Top)
[2] Viega, Messier and Chandra. Network Security With OpenSSL. O'Reilly. 2002.

**Comment by markus2330** [comment]
Ok, then thank you for the PR! Some plugin options and maybe also as metadata in kdbOpen()/kdbClose() to enable/disable tearup/down should be added later, too. (and the check if gcrypt has been initialized)

I merged it, because it was a nicely coupled unit, please create a new PR then.

**Comment by petermax2** [comment]
Thank you! 

OK, I noted the metadata check. Checking if gcrypt has already been set up is not supported by the API. In general the manual suggests to leave all of the initialization stuff to the application developer. So OpenSSL will make some things easier for us.

**Comment by markus2330** [comment]
An additional remark to the internal ref counting in gcrypt/libssl: If they do it correctly, it should not matter if you reopen/reclose it as long as the number of open and close matches?

What happens if the crypto libs have multiple init/teardown? Did you test it?
The default behaviour has to be chosen carefully based on that.

For plugin configuration we should,however, agree to a naming convention in #418 first.

**Comment by petermax2** [comment]
For now it does not matter if the setup routines have been called multiple. I tested it for both Gcrypt and libcrypto. That may change in the future. The gcrypt folks are planning on dropping the initialization alltogether in the future but they didn't make it clear when that will be.

**Comment by markus2330** [comment]
That sounds good! Did you also test the case with complete shutdown and restart? That caused problems in python.

So the ref counting introduced in this PR is actually not needed?

**Comment by petermax2** [comment]
gcrypt does not have to shutdown, I'm not sure about OpenSSL yet. The one thing I did not test yet is how these libraries behave when multiple threads are running and the library gets re-initialized in between operations. OpenSSL shouldn't have any problems as they internally just update a function pointer.

The thing with ref counting is: I want to comply to the guidelines and manuals of the crypto APIs as much as possible. And they all suggest to initializing the libraries as early as possible and call these routines only once. So maybe in a future update something breaks if we call the setup routines multiple times. Also if libgcrypt starts in FIPS-enabled mode the library does additional setup, that is supposed to run only once in the lifetime of the application. The same is true for libcrypto. I think the self tests in FIPS-mode may throw errors if executed multiple times. It all depends on versions and compile/startup options and we can not be careful enough.

**Comment by markus2330** [comment]
Ok, thank you! So better we have the ref-counting in place!

**Pull request merged**
