### PR TITLE
Markdown Shell Recorder: Support Empty `#>` directive

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request adds

- support for empty `#>` checks to the Markdown Shell Recorder and
- a basic MSR test for the `ni` plugin.

.

# Checklist

- [x] I checked all commit messages.
- [x] I ran all tests locally and everything went fine.
- [x] The PR contains an updated version of the release notes.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the great maintenance work. I'll start the build server tomorrow morning.

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Thank you, great job! You did not mention "a basic MSR test for the ni plugin." in the release notes.

**Comment by sanssecours** [comment]
> You did not mention "a basic MSR test for the ni plugin." in the release notes.

I added the [text about the test](https://github.com/ElektraInitiative/libelektra/pull/2038/files#diff-47ed151a0df6c926f5b1320d140a5b34R125) to an already existing item in the release notes.

**Comment by markus2330** [comment]
Thank you for being so careful!

**Pull request merged**
