### PR TITLE
Globbing flag fix

### PR DESCRIPTION
**Pull request by fberlakovich**
# Purpose

Fixes the issues described in #709. 

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you, well done! But it seems there is a memory leak.

**Comment by fberlakovich** [comment]
> Thank you, well done! But it seems there is a memory leak.

Ah damn it, I can already guess where. I will have a look.

**Comment by markus2330** [comment]
And it seems like that I created some merge conflicts in the README.md. Can you rebase please?

**Comment by markus2330** [comment]
@fberlakovich Thank you, great work! I hope to read from you again soon! Maybe an augeas tutorial ;)

@krit0n Can you also add this new feature in the tutorial?

```
$ kdb mount --with-recommends hosts /hosts hosts
$ kdb set user/hosts/blah rejected
... The hosts keyset contains unknown keys. Only keys below ipv4 and ipv6 are allowed.
```

**Comment by krit0n** [comment]
I've added it in the mount tutorial

**Pull request merged**
