### PR TITLE
#2717: Improve qt-gui error message popup

### PR DESCRIPTION
**Pull request by 0003088**
## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [ ] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [ ] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see [Coding Guidelines](/doc/CODING.md))
- [ ] meta data is updated (e.g. README.md of plugins and [METADATA.ini](/doc/METADATA.md))

## Review

Reviewers will usually check the following:

- [ ] Code is conforming to [our Coding Guidelines](/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](/doc/DESGIN.md)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Documentation is concise and good to read
- [ ] Examples are well chosen and understandable

## Labels

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the build server is happy** and also you
  say that everything is ready to be merged.

I'ts been a while since my last merge request, so I'm not exactly sure what to do and what items to check, so please advise.

I think the error popup now behaves as desired, however, I have a strange problem, see screenshot. I'm not sure if it's related to the fact, that I use i3 as window manager or if it's an issue with the Qt version on my machine. Could anybody check if this problem is present on their installations?

Screenshot_20190605_210317

### CODE REVIEW

**Comment by markus2330** [comment]
@0003088 thank you very much for this improvement! You need to

1. write a line of release notes, followed  by `_(your name)_.`, so that your contribution is not forgotten in the release notes
2. maybe reformat the code with clang-format (the build server gives you the patch and how to apply it if it is difficult for you to install clang-format)

@Piankero can you try this PR and see if the error message looks fine?

**Comment by Piankero** [comment]
qt-error-new
Looks good to me :) well done

**Comment by markus2330** [comment]
@Piankero can you maybe help with that?

**Comment by Piankero** [comment]
I can reformat it and add a message to the news. But I need to know the name of @0003088

**Comment by markus2330** [comment]
Thank you!

doc/AUTHORS.md tells you that his name is "Raffael Pancheri"

**Comment by Piankero** [comment]
@markus2330 feel free to merge, the failed linux build is just because fish has an invalid cert for their website atm

**Comment by markus2330** [comment]
Thank you very much!

> invalid cert for their website atm

Yes, the URL is already fixed in master, so a rebase would also avoid the problem.

**Pull request merged**
