### PR TITLE
[FLOSS H3] Removing elektraCopyCallbackMeta-Function

### LINKED ISSUE #4221: remove elektraCopyCallbackMeta
https://github.com/ElektraInitiative/libelektra/blob/0d9ba69aedca7ec8ad706255672867f1aa174e52/src/libs/elektra/keyset.c#L1881-L1905

The key name checks are wrong, they don't take the `meta:/` namespace into account. It also seems this functionality isn't tested anywhere, otherwise we should have noticed it by now.

### PR DESCRIPTION
**Pull request by Dynamichost96**
Fixes #4221

## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by Janldeboer** [comment]
The changes seem useful and well implemented.
You can fix the the formatting reported by the `restyled` check by running the following command on the base folder of your branch:
`curl https://restyled.io/gh/ElektraInitiative/repos/libelektra/jobs/2637695/patch`

You might also have to change the names of the commits in start with the module names like `doc:` or `src:`
You can do so by interactively rebasing using `git rebase -i HEAD~9` where `9` is the number of commits you want to change.

The errors in `continuous-integration/jenkins/pr-merge` and `🔗 Check` seem unrelated to your changes and might disappear once the checks run again.

**Review by Janldeboer — APPROVED** [review]

**Comment by Dynamichost96** [comment]
> The changes seem useful and well implemented. You can fix the the formatting reported by the `restyled` check by running the following command on the base folder of your branch: `curl https://restyled.io/gh/ElektraInitiative/repos/libelektra/jobs/2637695/patch`
> 
> You might also have to change the names of the commits in start with the module names like `doc:` or `src:` You can do so by interactively rebasing using `git rebase -i HEAD~9` where `9` is the number of commits you want to change.
> 
> The errors in `continuous-integration/jenkins/pr-merge` and `🔗 Check` seem unrelated to your changes and might disappear once the checks run again.

Thank you! I will try these Changes and might also look if its more suitable to remove the whole code or leave it commented while waiting for a fix.

**Comment by markus2330** [comment]
Yes, please remove the whole code. Also the code using callback/ in src/tools/kdb/get.cpp needs to be removed. Also the code around line 2439 in keyset.c and setCallback in include/elektra/key.hpp is not needed anymore.

**Comment by flo91** [comment]
Nice cleanup work!
As reported by the CI, some additional code has to be removed.
The warnings should also occur if you build Elektra locally.
With `cmake -DCOMMON_FLAGS="-Werror"` the build fails if warnings are present (warnings are treated as errors).
Such a build should finish successfully before committing your changes.

Please also make sure that all tests pass.

**Pull request closed without merging**
