### PR TITLE
crypto-plugin: fix static link issues

### PR DESCRIPTION
**Pull request by petermax2**
# Purpose

Make exported function names unique by using the `CRYPTO_PLUGIN_FUNCTION` macro.

See #951 for full discussion.

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build local-installation please

**Comment by markus2330** [comment]
Looks great, thanks for the fast response! Let us see what the build server says!

**Comment by markus2330** [comment]
Build server is happy, too!

**Comment by petermax2** [comment]
OS X build still works :)

**Pull request merged**
