### PR TITLE
Add no kdb

### PR DESCRIPTION
**Pull request by ingwinlu**
# Purpose

Port over nokdb test.

# Checklist

- [x] commit messages are fine ("module: short statement" syntax and refer to issues)
- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [x] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)
- [x] release notes are updated (doc/news/_preparation_next_release.md)

### CODE REVIEW

**Comment by markus2330** [comment]
Please do not forget to copy the build descriptions into the Jenkinsfile. In this case: "Builds Elektra with Debian unstable default compiler. Calls script configure-debian but without kdbtests: make run_nokdbtests Namespaces system+user are not writeable."

**Comment by markus2330** [comment]
Improvements (and updates) of the descriptions are of course *very welcomed*. But reducing the already minimal docu should be avoided.

**Comment by ingwinlu** [comment]
This was the first time I actually added [a comment](https://github.com/ElektraInitiative/libelektra/pull/2049/files#diff-a57090b1ae67f034f93b0d6f3efcce90R337) because I thought it was worthwhile information...

**Comment by markus2330** [comment]
Please rebase.

**Comment by markus2330** [comment]
Thank you!

Please improve the release notes (saying what they do vs. the names) in the other PRs.

**Pull request merged**
