### PR TITLE
Add doc icheck update

### LINKED ISSUE #2009: doc: changes to icheck script
Forgot to add section to doc/news/_preparation_next_release.md mentioning that the icheck script now no longer leaves the base directory.

### PR DESCRIPTION
**Pull request by ingwinlu**
# Purpose

Document changes to run_icheck script.

closes #2009

### CODE REVIEW

**Comment by markus2330** [comment]
Why not adding your name?

**Comment by ingwinlu** [comment]
no names are mentioned in any of the other points

**Comment by markus2330** [comment]
Yes, they all ignored what is said in the beginning of the file :cry: 

Seems like there is no way around #1966

**Comment by sanssecours** [comment]
> Yes, they all ignored what is said in the beginning of the file 😢

That is technically not true. I do not ignore that stuff, but I just do not want add something like “thanks to René Schwaiger”. Thanking oneself is usually something that is quite frowned upon. Also, you do not add your name in that way to the release notes either. I could live with the compromise of just adding the authors name in parentheses. That’s for example also how [TextMate](https://github.com/textmate/textmate) handles this:

bundles

.

**Comment by markus2330** [comment]
I am perfectly happy with the name in parentheses and italics. Thanks for this excellent feedback! Then let us do it this way.

Btw. what does the `[+]` mean?

**Comment by sanssecours** [comment]
> Btw. what does the [+] mean?

The `[+]` just acts as a ”button” to show detailed information about an update:

bundles

.

**Comment by markus2330** [comment]
@ingwinlu Could you please also add `*(Lukas Winkler)*` to your entries and also document #2012 please? Also a rebase is required.

**Comment by ingwinlu** [comment]
@markus2330 done

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
