### PR TITLE
Elektra: Plugins: Semlock: Test: add /dev/shm mounted as tempfs check

### PR DESCRIPTION
**Pull request by KurtMi**
# Checklist

- [x] commit messages are fine (with references to issues)

### CODE REVIEW

**Comment by markus2330** [comment]
Seems like the test does not work on travis.

**Comment by KurtMi** [comment]
This RP will be rejected, reasons in #1260.

**Comment by markus2330** [comment]
It is not necessary to remove branches which are in your own repo.

**Comment by KurtMi** [comment]
I know but I like my own repo clean :) The issue and the Files changed tab of this PR will be enough to recode this PR, although I think the `system (...)` invocation will not on osx.

**Pull request closed without merging**
