### PR TITLE
Shell Recorder: Fix Issues

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

This pull request should address some of the problems of the (Markdown) Shell Recorder. There are still [some issues left](https://github.com/ElektraInitiative/libelektra/issues/944), but for now I want to work on something else again 😊.

# Checklist

- [x] I checked all commit messages. The issue references should be correct, as far as I can tell.
- [x] I ran all tests and everything went fine.
- [x] I added MSR tests.
- [x] The pull request also contains updated documentation for the Markdown Shell Recorder.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build please

**Comment by sanssecours** [comment]
jenkins build please

**Comment by sanssecours** [comment]
jenkins build ini please

**Comment by sanssecours** [comment]
jenkins build ini please

**Comment by markus2330** [comment]
Thank you, excellent work!

**Pull request merged**
