### PR TITLE
rest-frontend: fix $http.get calls

### PR DESCRIPTION
**Pull request by BernhardDenner**
fix homepage due to angular version upgrade.
The fixed version is already online ;)

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by BernhardDenner** [comment]
However, 'login' has still issues. Due to the lack of a proper development env I wasn't able to find this issue. Hmmm, maybe @Namoshek can have a look.

**Comment by BernhardDenner** [comment]
fixes #1676

**Comment by markus2330** [comment]
Thank you, that is great! (Especially that the new site is already online!)

Does `jenkins build homepage please` work? (I'll try to issue it)

Does this PR break the website for older versions of angular JS?

@Namoshek Do you have time for a quick review?

**Comment by markus2330** [comment]
jenkins build homepage please

**Comment by Namoshek** [comment]
I also had a look at the login issue. The login does work, the token is stored and the user is authenticated (which is also visible after refreshing the page). But for some reason, both the `.then(function(response) { ... })` and the `.catch(function(response) { ... })` functions are called in the [AuthLoginController.js](../blob/master/src/tools/rest-frontend/resources/assets/js/controllers/main/auth/AuthLoginController.js). The login method on the authentication service is called as described in [their API](https://github.com/sahat/satellizer#authloginuser-options) though. And there have been no changes to the satellizer project since mid 2016, which was before we had a working build. So I'm pretty much clueless.

**Comment by markus2330** [comment]
The snippet converter works again! Unfortunately without xerces or yamlcpp.

So I'll merge this, if you have any idea about how to make the login work again, please create a PR!

**Comment by markus2330** [comment]
I created #1679 for discussion about login, and  #1680 about new plugins.

**Pull request merged**
