### PR TITLE
Yet Another Memory Leak ( #840 )

### LINKED ISSUE #840: Memleak in crypto_openssl
From http://community.markus-raab.org:8080/job/elektra-clang/
```
&lt;b&gt;MPK&lt;/b&gt; ==3558== 16,384 bytes in 1 blocks are still reachable in loss record 572 of 572
==3558==    at 0x4C2AF2E: realloc (vg_replace_malloc.c:692)
==3558==    by 0x572742F: CRYPTO_realloc (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==3558==    by 0x57B178B: lh_insert (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==3558==    by 0x57B3E69: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==3558==    by 0x57B383A: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==3558==    by 0x6460589: ???
==3558==    by 0x64615A1: ???
==3558==    by 0x504E110: elektraPluginOpen (plugin.c:295)
==3558==    by 0x402138: test_init (test_internals.h:136)
==3558==    by 0x402138: main (testmod_crypto_openssl.c:21)
==3558== 
CYPTO        TESTS
==================


crypto_openssl
```

### PR DESCRIPTION
**Pull request by petermax2**
Fixes #840 .

### CODE REVIEW

**Comment by petermax2** [comment]
jenkins build clang please

**Comment by petermax2** [comment]
jenkins build clang please

**Comment by petermax2** [comment]
@markus2330 I think a review for the suppressions would not be interesting. Ready for merge.

**Comment by markus2330** [comment]
Thank you for the fix!

**Pull request merged**
