### PR TITLE
JNI: Write Tutorial for Java Plugin Development

### PR DESCRIPTION
**Pull request by mirunix**
## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [ ] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [x] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [x] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

## Review

Remove the line below and add the "work in progress" label if you do
not want the PR to be reviewed:

@markus2330 please review my pull request

## Merging

Please add the "ready to merge" label when the build server and you say
that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Very nice that you started it! Commit messages, links, release notes, ... all seems to be perfect. The tutorial itself, however, is quite short at the moment.

How to get started? (How to mount it ...)

**Comment by mirunix** [comment]
Thank you for the feedback. I will continue writing on it.

**Comment by mirunix** [comment]
Hello @markus2330 , I have a question regarding the info, mount etc. of Java plugins:

According to https://www.libelektra.org/plugins/jni , I should be able to call kdb info on the plugin using classname and classpath, but I am not sure what they actually should be. Could you please make it more clear to me?

Thank you!

**Comment by markus2330** [comment]
> classname and classpath, but I am not sure what they actually should be

There are some examples how it could be but the exact classpath depends on your System. Ideally (if jna and Elektra's jna binding is installed properly) the classpath should only point to your jar you want to use.

The classname is the classname of the plugin you implemented.

@Piankero did you also use the jni plugin in Windows? Which classpath did you need?

**Comment by Piankero** [comment]
Unfortunately I cannot help since I do not use Windows for coding.
Furthermore I used the JNA and not JNI. I'm sorry

**Comment by markus2330** [comment]
@mirunix basically you cannot easily overspecify the "classpath". Simply add everything until all classes are found. If you found out what is needed, please update the docu, so that we also have an example for Windows.

**Comment by markus2330** [comment]
Already merged via #2800

**Pull request closed without merging**
