### PR TITLE
Travis: Enable All Bindings

### PR DESCRIPTION
**Pull request by sanssecours**
# Purpose

Looks like we somehow removed the code enabling “all” bindings on Travis. After this update Travis uses `ALL` as default value for `BINDINGS` again. This pull request also deals with the consequence of this update, mainly by disabling certain warnings produced by code generated by SWIG.

# Checklist

- [x] I checked all commit messages.
- [x] I ran all tests locally and everything went fine.
- [x] I added code comments for the disabled warning. 
- [x] This PR contains an updated version of the release notes.

### CODE REVIEW

**Comment by sanssecours** [comment]
jenkins build all please

**Comment by markus2330** [comment]
Could you please remove the cmake reformatting from other PRs (other than #1959)? It makes the PRs unreadable.

**Comment by sanssecours** [comment]
> Could you please remove the cmake reformatting from other PRs (other than #1959)? 

I can rebase the pull request after you merge PR #1959. Is there any reason why you have not done that yet?

**Comment by sanssecours** [comment]
jenkins build jenkinsfile please

**Comment by markus2330** [comment]
Thank you for taking care of travis!

Having 0.8.23 milestone and "low priority" logically conflicts :smile:  Should this be part of the next release or is it irrelevant? If it is relevant, could you please rebase and make the PR minimal?

**Comment by sanssecours** [comment]
> Should this be part of the next release or is it irrelevant?

While I think the update fixes an unfortunate regression, I do not care if it is part of the release or not, especially since it only improves the test coverage of the Travis build jobs.

>  If it is relevant, could you please rebase and make the PR minimal?

I rebased the PR on `master`. The update is still based on the formatted CMake code of PR #1959, since I see now value in fixing the merge conflicts I would have to handle (twice) otherwise.

**Comment by markus2330** [comment]
Ok, then I'll merge it after the release.

Thanks for fixing the regression, though.

**Comment by sanssecours** [comment]
jenkins build jenkinsfile please

**Comment by sanssecours** [comment]
jenkins build jenkinsfile[debian-unstable-full] please

**Comment by sanssecours** [comment]
jenkins build jenkinsfile please

**Comment by markus2330** [comment]
Why is this PR repeatedly notifying me?

**Comment by markus2330** [comment]
Ok, no problem. You only remove the build server commands so quickly that I never saw what you did :wink:

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
