### PR TITLE
Shell Recorder: Add Plugins syntax for test cases.

### PR DESCRIPTION
**Pull request by KurtMi**

### CODE REVIEW

**Comment by KurtMi** [comment]
Draft for #944 
shell recorder should have a way to specify (plugin) dependencies needed to run the test case

**Comment by markus2330** [comment]
Thanks! What is missing in the PR? (It says Draft) Or do you mean that only one subpoint is implemented?

Some further useful features in this context:
- What about if storage already implies Plugins?
- Or even more comfortable, what if we get the plugins from import/export/mount statements, too?

I can move this to #944 if you see them out of scope for this PR.

**Comment by KurtMi** [comment]
I mentioned draft because I was not sure if you are happy with such a solution and the used plugins in the other test cases are missing.

> What about if storage already implies Plugins?
> Or even more comfortable, what if we get the plugins from import/export/mount statements, too?

In my opinion the usage of the storage is not appropriate because it is only a variable which is used later in the test case and it is used to define the storage plugins and we have a bunch of others too.
I think it is possible to parse the import/export/mount statements but very hard to do with cmake syntax.

Do I need to specify the resolver also?

**Comment by markus2330** [comment]
You can assume a "resolver" and "storage" to be present (should checked by cmake at compile time).

Why do you need cmake syntax to parse it? Why not parse within shell recorder?

**Comment by KurtMi** [comment]
As discussed, this problem will be solved in a other way, so i close this PR.

**Pull request closed without merging**
