### PR TITLE
Add jenkinsfile homepage

### PR DESCRIPTION
**Pull request by ingwinlu**
# Purpose

Add homepage build to Jenkinsfile

# Checklist

- [ ] commit messages are fine ("module: short statement" syntax and refer to issues)
- [ ] affected documentation is fixed
- [ ] release notes are updated (doc/news/_preparation_next_release.md)

# Expanded Checklist
- [ ] Disable old Homepage build job
- [ ] point dns to new location

### CODE REVIEW

**Comment by ingwinlu** [comment]
jenkins build all please

**Comment by ingwinlu** [comment]
While I suggest to not point the dns to a7 till it gets its replacement cpu i think we can merge that in now.

**Comment by markus2330** [comment]
Thank you, great work!

Great that you even added apiary. I am looking forward to have something similar for #1901 :wink:  There we could immediately go live for internal purposes (even on broken a7).

**Comment by ingwinlu** [comment]
This has some problems that will need to be addressed. For one it deploy even when not in master (forgot to remove a debug line) and more severe the tagging does not work as PR's obviously share build ID's.

**Pull request merged**
