### PR TITLE
Create packages for Debian Bullseye

### LINKED ISSUE #3854: Debian "Bullseye" packages
As Debian "Bullseye" https://www.debian.org/releases/testing/ will hopefully release soon, we should also create Debian packages for it. Can we maybe already start doing so in the upcoming 0.9.6 release?

### PR DESCRIPTION
**Pull request by robaerd**
Closes #3854

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by mpranj** [comment]
Thank you so much for working on this!

**Comment by robaerd** [comment]
There is a problem with the tests `testkdb_allplugins` and `test_tools_plugindatabase.py` on Debian Bullseye.
`test_tools_plugindatabase.py` failed on the [first](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-3855/1/pipeline) build server run. 
However, on the [second](https://build.libelektra.org/blue/organizations/jenkins/libelektra/detail/PR-3855/2/pipeline/) run `test_tools_plugindatabase.py` did not fail, but now the memcheck test for `testkdb_allplugins` is failing.
I was only able to reproduce the memcheck error of `testkdb_allplugins` locally.

```
0% tests passed, 1 tests failed out of 1

Label Time Summary:
kdbtests    =  23.39 sec*proc (1 test)

Total Test time (real) =  23.42 sec

The following tests FAILED:
	264 - testkdb_allplugins (Failed)
-- Processing memory checking output:
1/1 MemCheck: #264: testkdb_allplugins ...............   Defects: 3
MemCheck log files can be found here: (<#> corresponds to test number)
```
[MemoryChecker.264.log](https://github.com/ElektraInitiative/libelektra/files/6490023/MemoryChecker.264.log)

**Comment by markus2330** [comment]
testkdb_allplugins is always a cause of troubles, as it is usually only telling us that some external library leaks and it is quite difficult to debug. Probably it is best if we mark it as "memleak".

```
60/264 Test  #42: test_tools_plugindatabase.py ..................***Exception: SegFault  0.80 sec
```

could be anything. The last python segfault we had was a problem with a specific python version #3539 #248 #25
I would say let us hope Debian has already fixed it. (If you cannot reproduce it again.)

**Comment by robaerd** [comment]
Should now be fixed.
The travis jobs are shown as failing because they somehow still reference the restyled/pull-3855 branch. For the correct build results see [here](https://travis-ci.org/github/ElektraInitiative/libelektra/builds/771430540).
The "🔗 Check" job however is failing because the Elektra package got somehow removed from http://packages.gentoo.org. 
```
Broken Links:
—————————————
doc/INSTALL.md:16:0 http://packages.gentoo.org/package/app-admin/elektra
doc/news/2014-07-28_0.8.7.md:104:0 http://packages.gentoo.org/package/app-admin/elektra
doc/news/2017-03-18_lcdproc.md:203:0 http://packages.gentoo.org/package/app-admin/elektra
```

**Comment by markus2330** [comment]
Thank you! :rocket: 

> The travis jobs are shown as failing because they somehow still reference the restyled/pull-3855 branch. For the correct build results see here.

Simply set "ready to merge" if it is okay.

> The "link Check" job however is failing because the Elektra package got somehow removed from http://packages.gentoo.org.

Can you remove the links please? (Can also be in a different PR.)

**Pull request merged**
