### PR TITLE
fixes #645

### LINKED ISSUE #645: INI Plugin: Tests Fail on OS X
Since pull request #599 was merged `testscr_check_get_set` and `testmod_ini` fail on my machine. Here is the output of `testmod_ini`:

```
INI	   TESTS
==================

Compare <[section1]
>, with <section1/key1 = value1
>
in file /usr/local/share/elektra/test_data/ini/plainini, line 2.
tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
src/plugins/ini/testmod_ini.c:78: error in test_plainIniWrite: files do not match as expected
Compare <[section1]
>, with <section1/key1 = value1
>
in file /usr/local/share/elektra/test_data/ini/emptyval, line 2.
tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
src/plugins/ini/testmod_ini.c:106: error in test_plainIniEmptyWrite: files do not match as expected
Compare <key1 = value1
>, with <[section1]
>
in file /usr/local/share/elektra/test_data/ini/sectionini, line 5.
tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
src/plugins/ini/testmod_ini.c:347: error in test_sectionWrite: files do not match as expected
Compare <[section1]
>, with <section1/key1 = val1
>
in file /usr/local/share/elektra/test_data/ini/sectionmerge.output, line 1.
tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
src/plugins/ini/testmod_ini.c:386: error in test_sectionMerge: files do not match as expected
Compare <[Section1]
>, with <Section1/testkey0 = testval0
>
in file /usr/local/share/elektra/test_data/ini/insertTest.output.ini, line 1.
tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
src/plugins/ini/testmod_ini.c:444: error in test_insertOrder: files do not match as expected
Compare <array = 0
>, with <array = 2
>
in file /usr/local/share/elektra/test_data/ini/arrayInsertOut.ini, line 4.
tests/cframework/tests.c:174: error in compare_line_files: comparing lines failed
src/plugins/ini/testmod_ini.c:492: error in test_arrayInsert: files do not match as expected

test_ini RESULTS: 191 test(s) done. 12 error(s).
```

The command `ctest -V -R testscr_check_get_set` prints the following output:

```
UpdateCTestConfiguration  from :build/DartConfiguration.tcl
Parse Config file:build/DartConfiguration.tcl
UpdateCTestConfiguration  from :build/DartConfiguration.tcl
Parse Config file:build/DartConfiguration.tcl
Test project build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 77
    Start 77: testscr_check_get_set

77: Test command: /Users/rene/Dropbox/Studium/Master\ Thesis/Configuration\ Parsing/Source/Elektra/build/tests/shell/testscr_check_get_set.sh
77: Test timeout computed to be: 1500
77:
77: ELEKTRA BASIC COMMAND SCRIPTS TESTS
77:
77: Check if script tests the correct version
77: augeas not a read-write storage
77: ccode not a read-write storage
77: conditionals not a read-write storage
77: constants not a read-write storage
77: counter not a read-write storage
77: crypto_gcrypt not a read-write storage
77: csvstorage not a read-write storage
77: curlget not a read-write storage
77: doc not a read-write storage
77: dpkg not a read-write storage
77:
77: -- Testing dump
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: enum not a read-write storage
77: error not a read-write storage
77: filecheck not a read-write storage
77: glob not a read-write storage
77: hexcode not a read-write storage
77: hidden not a read-write storage
77: hosts not a read-write storage
77: iconv not a read-write storage
77:
77: -- Testing ini
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: Did not find keyerror: user/tests/script/hello/a/array/#3 is not 3
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58334 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key user/tests/script/hello/a/array/#0
77: Did not find keyerror: user/tests/script/hello/a/array/#4 is not 4
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58337 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key user/tests/script/hello/a/array/#0
77: Did not find keyerror: user/tests/script/hello/a/array/#5 is not 5
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58339 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key user/tests/script/hello/a/array/#0
77: Did not find keyerror: user/tests/script/hello/a/array/#6 is not 6
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58341 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key user/tests/script/hello/a/array/#0
77: Did not find keyerror: user/tests/script/hello/a/array/#7 is not 7
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58343 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key user/tests/script/hello/a/array/#0
77: Did not find keyerror: user/tests/script/hello/a/array/#8 is not 8
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58348 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key user/tests/script/hello/a/array/#0
77: Did not find keyerror: user/tests/script/hello/a/array/#9 is not 9
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: Did not find keyerror: system/tests/script/hello/a/array/#3 is not 3
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58388 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key system/tests/script/hello/a/array/#0
77: Did not find keyerror: system/tests/script/hello/a/array/#4 is not 4
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58390 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key system/tests/script/hello/a/array/#0
77: Did not find keyerror: system/tests/script/hello/a/array/#5 is not 5
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58392 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key system/tests/script/hello/a/array/#0
77: Did not find keyerror: system/tests/script/hello/a/array/#6 is not 6
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58394 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key system/tests/script/hello/a/array/#0
77: Did not find keyerror: system/tests/script/hello/a/array/#7 is not 7
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58399 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key system/tests/script/hello/a/array/#0
77: Did not find keyerror: system/tests/script/hello/a/array/#8 is not 8
77: build/tests/shell/testscr_check_get_set.sh: line 1134: 58401 Segmentation fault: 11  "$KDB" set "$KEY" "$VALUE" > /dev/null
77: error: could not set key system/tests/script/hello/a/array/#0
77: Did not find keyerror: system/tests/script/hello/a/array/#9 is not 9
77: error: found remaining files /Users/rene/.config/test.ini.58334:1461763871.4295607571.tmp /Users/rene/.config/test.ini.58337:1461763872.4295090567.tmp /Users/rene/.config/test.ini.58339:1461763872.4295528148.tmp /Users/rene/.config/test.ini.58341:1461763873.4294996850.tmp /Users/rene/.config/test.ini.58343:1461763873.4295381935.tmp /Users/rene/.config/test.ini.58348:1461763873.4295812303.tmp in /Users/rene/.config
77: error: found remaining files /etc/kdb/test.ini.58388:1461763874.140733194299509.tmp /etc/kdb/test.ini.58390:1461763875.140733193704383.tmp /etc/kdb/test.ini.58392:1461763875.140733194182024.tmp /etc/kdb/test.ini.58394:1461763876.140733193547216.tmp /etc/kdb/test.ini.58399:1461763876.140733193990036.tmp /etc/kdb/test.ini.58401:1461763877.140733193397306.tmp in /etc/kdb
77: iterate not a read-write storage
77: jni not a read-write storage
77: keytometa not a read-write storage
77: line not a read-write storage
77: lineendings not a read-write storage
77: list not a read-write storage
77: logchange not a read-write storage
77: lua not a read-write storage
77: mathcheck not a read-write storage
77: network not a read-write storage
77:
77: -- Testing ni
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: noresolver not a read-write storage
77: null not a read-write storage
77: path not a read-write storage
77: profile not a read-write storage
77: python2 not a read-write storage
77: regexstore not a read-write storage
77: rename not a read-write storage
77: resolver_fm_hpu_b not a read-write storage
77: resolver_fm_b_b not a read-write storage
77: resolver_fm_pb_b not a read-write storage
77: resolver_fm_hb_b not a read-write storage
77: resolver_fm_hp_b not a read-write storage
77: resolver_fm_ub_x not a read-write storage
77: resolver_fm_xb_x not a read-write storage
77: resolver_fm_xp_x not a read-write storage
77: resolver_fm_xhp_x not a read-write storage
77: resolver_fm_uhb_xb not a read-write storage
77: semlock not a read-write storage
77: shell not a read-write storage
77: spec not a read-write storage
77: struct not a read-write storage
77: sync not a read-write storage
77: syslog not a read-write storage
77:
77: -- Testing tcl
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: template not a read-write storage
77: timeofday not a read-write storage
77: tracer not a read-write storage
77: type not a read-write storage
77: uname not a read-write storage
77: validation not a read-write storage
77: wresolver not a read-write storage
77:
77: -- Testing xmltool
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77:
77: -- Testing yajl
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: testing ls command
77: testing rm command
77: Did not find keyDid not find keytesting array
77: -n Master
77: Configuration
77: testscr_check_get_set.sh RESULTS: 538 test(s) done
77:  28 error(s).
1/1 Test #77: testscr_check_get_set ............***Failed   17.89 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
kdbtests    =  17.89 sec (1 test)
memleak     =  17.89 sec (1 test)

Total Test time (real) =  17.90 sec

The following tests FAILED:
	 77 - testscr_check_get_set (Failed)
Errors while running CTest
```

If you need any additional information, then please just comment below.

### PR DESCRIPTION
**Pull request by mpranj**
fixes #645 for me after countless debugging hours on:
- Mac OS X (10.11.4)
- FreeBSD (10.3-RELEASE-p2)

The only change is in `iniWriteKeySet `: using `mergesort` instead of `qsort`. The implementations appear to differ vastly and I'm still not sure why qsort is causing problems here. I hope that mergesort is acceptable here, but I don't suppose it will have much impact on runtime.

### CODE REVIEW

**Comment by markus2330** [comment]
Thanks! Are you also interested in the ini plugin to investigate in it so deeply?

Seems like iniCmpOrder is buggy. @tom-wa Can you take it from here?

**Comment by mpranj** [comment]
will fix compile issues, didn't see that mergesort is BSD libc only

**Comment by markus2330** [comment]
@mpranj I think you should rather not put more effort in it at the moment. Its quite sure that iniCmpOrder does not work, I do not think we need a specific property of mergesort here. (the `-lbsd` dependency should not be added because of a broken comparision function)

**Comment by mpranj** [comment]
I suppose we can close this then

**Comment by markus2330** [comment]
Yes, but neverless thanks, you pointed to the problem.

**Pull request closed without merging**
