### PR TITLE
Enhance search

### PR DESCRIPTION
**Pull request by hesirui**
I added docsearch as instructed above, but I still an error that it cant find the selector. Despite it is correctly set (relates https://github.com/slimphp/Slim-Website/issues/290). Is this probably an issue with docsearch? 

work in progress

### CODE REVIEW

**Comment by kodebach** [comment]
Please add a line to the release notes [like the server instructs you to](https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2581/2/pipeline#step-290-log-3). You should always add this line before opening a PR. Changing it later on, if the content of the PR changes is not a problem.

**Comment by hesirui** [comment]
It's a work in progress Pull Request to get feedback for my approach,
that's why I didn't add the release notes yet. But I will do so from now
on. 

Am 2019-04-04 11:45, schrieb kodebach:

> Please add a line to the release notes like the server instructs you to [1]. You should always add this line before opening a PR. Changing it later on, if the content of the PR changes is not a problem. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

  

Links:
------
[1]
https://build.libelektra.org/jenkins/blue/organizations/jenkins/libelektra/detail/PR-2581/2/pipeline#step-290-log-3
[2]
https://github.com/ElektraInitiative/libelektra/pull/2581#issuecomment-479828395
[3]

**Comment by markus2330** [comment]
@s-pace finally we started to work on #1815! Thanks again for your help there!

Can you maybe help us with the problem @hesirui mentioned above (cant find the selector)?

**Comment by markus2330** [comment]
jenkins build homepage please

**Comment by s-pace** [comment]
👋 @markus2330 Great news,

@hesirui do you make sure that the `<input/>`element already exists with the proper id set when the `docsearch()` function is call? The issue raised from slimphp/Slim-Website#290 is that they were trying to append the dropdown to an element which does not exist.

I couldn't have a look from a preview. Let me know if you have more details.

**Comment by hesirui** [comment]
Thank you that was the right hint, docsearch was called before the page was fully initialized. The search is now integrated on the main page, results appear as soon as you type. The old search will still be invoked when pressing the search button.

**Comment by markus2330** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
This are great news! Can you please also update the text "Search for configuration snippet..."?

**Comment by sanssecours** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
It seems like that this change lets the validation fail:

```
Value of: cf.isValidated ()
  Actual: true
Expected: false
```

https://build.libelektra.org/jenkins/job/elektra-homepage/661/console

**Comment by hesirui** [comment]
If two service access the same control, that validation breaks. Without dramatic changes I doubt it is possible to integrate that search box into the same html input as the normal search. I would simply add another input, if that is okay with you?

**Comment by markus2330** [comment]
Actually, we do not need the search for the snippets anymore (At least not so visible, the newest snippet is from 2017). So you can replace the functionality.

The snippet search will still be available via https://www.libelektra.org/entries/search
Please also change the text "the search bar at the top of the page" accordingly.

As nice-to-have you could preserve the snippet search for logged-in users. (As login has no other purpose than working with snippets).

**Comment by markus2330** [comment]
@hesirui any progress here? It would be great to have this fixed.

**Comment by hesirui** [comment]
yes, I am on it

**Comment by hesirui** [comment]
jenkins build homepage please

**Comment by hesirui** [comment]
jenkins build homepage please

**Comment by sanssecours** [comment]
Looks like there are conflicts in the [main ReadMe file](https://github.com/ElektraInitiative/libelektra/blob/master/README.md). Please rebase your changes on the `master` branch.

**Comment by hesirui** [comment]
I rebased it

**Comment by markus2330** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
build allow

**Comment by hesirui** [comment]
I think this fixed the problem. From my side it is ready to merge.

**Comment by sanssecours** [comment]
> I rebased it

As far as I can tell, you work is still not based on the current state of the `master` branch. Since I think it is a little bit hard to read the updates shown by GitHub (32 updated files), I decided to rebase your PR on `master` and create a [new pull request](https://github.com/ElektraInitiative/libelektra/pull/2796).

**Comment by markus2330** [comment]
Do you have some problems with the Gruntfile? You can ask Namoshek for help.

**Comment by hesirui** [comment]
No it works, I just commited the wrong one intially, I works now.

**Comment by markus2330** [comment]
Now we only need a clean PR which contains nothing but the changes.

**Comment by markus2330** [comment]
Already merged via #2796

**Pull request closed without merging**
