### PR TITLE
Various Minor Fixes

### PR DESCRIPTION
**Pull request by sanssecours**

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for working on this! Can you push the commit which fixes the URLs directly on master?

This PR seems to contain several unrelated things.

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by sanssecours** [comment]
jenkins build libelektra please

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
