### PR TITLE
Remove kdbprivate.h from kdb get & mount

### LINKED ISSUE #3162: get rid of kdbprivate.h in bindings/tools
- [ ] src/tools/kdb/get.cpp:#include <kdbprivate.h>
- [ ] src/tools/kdb/mount.cpp:#include <kdbprivate.h>
- [x] src/bindings/glib/gelektra-keyset.c:#include <kdbprivate.h>
- [x] src/bindings/glib/gelektra-key.c:#include <kdbprivate.h>
- [ ] src/bindings/intercept/fs/intercept.c:#include <kdbprivate.h>

@manuelm can fix the glib bindings and @PhilippGackstatter the others?

### PR DESCRIPTION
**Pull request by PhilippGackstatter**
fixes #3162
(except for intercept bindings)

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [ ] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you very much!

**Comment by markus2330** [comment]
reformat-c was not executed here, and I did not notice as jenkins triggering was broken.

**Comment by sanssecours** [comment]
> reformat-c was not executed here

The script was executed [here](https://travis-ci.org/ElektraInitiative/libelektra/jobs/616352807#L1881) and `testscr_check_formatting` failed as expected. However, since we now use `ctest $ARGS --rerun-failed`:

https://github.com/ElektraInitiative/libelektra/blob/8d9dba123e662a011a69d04ce8535831d39f0543/scripts/dev/run_all.in#L17

the test `testscr_check_formatting` was executed again. This time the test did not fail, since the source was modified:

https://github.com/ElektraInitiative/libelektra/blob/8d9dba123e662a011a69d04ce8535831d39f0543/tests/shell/check_formatting.sh#L14-L17

. One option to solve this problem would be to `stash` the current changes at the end of the `check_formatting.sh`. I do not know if doing that has other unintended consequences though.

**Comment by markus2330** [comment]
@sanssecours Thank you for finding out! :sparkle:  Can you create a new issue with this text above?

**Comment by PhilippGackstatter** [comment]
> reformat-c was not executed here, and I did not notice as jenkins triggering was broken.

Sorry about that. The changes were so minor I didn't think of it.

**Comment by markus2330** [comment]
No problem, it was easy to fix and revealed an important bug in the buildserver.

**Pull request merged**
