### PR TITLE
Kdb import export provider

### PR DESCRIPTION
**Pull request by MasterToney**
## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildservers are happy.
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [x] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

With this PR `kdb import` and `kdb export` lookup providers through the database, before you had to specify the plugin to use directly by name, e.g. `yajl` where as now you can also specify the format e.g. `json`.

It will implement issue #1178.

### CODE REVIEW

**Comment by MasterToney** [comment]
The tests now fail because of the spell checking which wants `json` to be capitalized.
E.g.
-To change the configuration in KDB below `user` in json format, you would use:<br>
-`kdb editor user json`

should be

-To change the configuration in KDB below `user` in JSON format, you would use:<br>
-`kdb editor user JSON`

The problem now is that the lookup for suiting plugins is case-sensitive and as such `kdb editor user JSON` would not find yajl.

@markus2330 as I see it there are two options:
1. change the behavior of `lookupProvides` in `pluginDatabase.hpp` so that it searches case insensitive which would allow us to capitalize the file format in the commands
2. always call `lookupProvides` with lower case string within `kdb-import` `kdb-export` and `kdb-editor` which has the drawback of creating an oversight in the future.

I also briefly looked into adopting `/scripts/sed` to ignore json inside '' or ''' ''' blocks but do not think that this is feasible, wanted or even possible. What do you think?

**Comment by markus2330** [comment]
I do not think we should make any workarounds just for spellchecking. So simply remove the file from being checked (scripts/dev/fix-spelling) or remove offending JSON line in scripts/sed as needed.

> change the behavior of lookupProvides in pluginDatabase.hpp so that it searches case insensitive which would allow us to capitalize the file format in the commands

Yes, it makes sense to lower-case everything in there as it is not allowed anyway that json and JSON are different plugins (or providers).

**Comment by MasterToney** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build libelektra please

**Comment by MasterToney** [comment]
Is there a way to rerun travis-ci like with jenkins?
Since form my side I don't have much more to add to this PR.
I decided to switch the examples to xml and therefore avoid the hassle with spellchecking.

**Comment by mpranj** [comment]
I restarted it for you. If you want to restart the builds you have to log in to travis-ci using your github account.

**Comment by markus2330** [comment]
Thank you very much for this improvement!

**Pull request merged**
