### PR TITLE
Scripts: Remove YAML Benchmark Script

### PR DESCRIPTION
**Pull request by sanssecours**

### CODE REVIEW

**Comment by markus2330** [comment]
This will conflict with  #2938, can you maybe push your change on top of  #2938? Any help in  #2938 is very much appreciated.

**Comment by sanssecours** [comment]
> This will conflict with #2938, can you maybe push your change on top of #2938? Any help in #2938 is very much appreciated.

This PR just removes a single file (`scripts/benchmark-yaml.in`) and a single line in `scripts/CMakeLists.txt`. I do not think that will be much of a problem.

**Comment by sanssecours** [comment]
> Any help in #2938 is very much appreciated.

I created a partial clone of the `scripts` branch and [opened a pull request](https://github.com/ElektraInitiative/libelektra/pull/2941) to debug the build problems.

**Comment by markus2330** [comment]
Thank you very much for looking into the scripts branch!

Please feel free to remove scripts which are not needed anymore.

**Comment by markus2330** [comment]
Do you want this to be merged or can you add this to the scripts branch?

**Comment by sanssecours** [comment]
> Do you want this to be merged or can you add this to the scripts branch?

I already rebased PR #2941 on this pull request in my local copy of the repository. There were only minor merge conflicts concerning the release notes. Everything else was fine, hence merging this PR as it is should not be problematic at all.

**Pull request merged**
