### PR TITLE
Replace openwrt image

### LINKED ISSUE #4958: Unable to build docker images
The jenkins CI is currently broken. The problem seems to be that the "Build docker images" stage is unable to pull the `openwrtorg/sdk` image which indeed does not exist (any longer?) on dockerhub.

### PR DESCRIPTION
**Pull request by Eiskasten**
This PR tries to fix #4958 by replacing the `openwrtorg/sdk` with the `openwrt/sdk` docker image.

## Basics

- [ ] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add them to the release notes.**
- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - add a line in `doc/news/_preparation_next_release.md`
  - reformat the code with `scripts/dev/reformat-all`
  - make all unit tests pass
  - fix all memleaks
  - fix the CI itself (or rebase if already fixed)
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if everything is done** and no further pushes are planned by you.

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
If this works, it would be perfect! :rocket:

**Comment by Eiskasten** [comment]
jenkins build libelektra please

**Comment by Eiskasten** [comment]
jenkins build libelektra please

**Comment by Eiskasten** [comment]
The jenkins pipeline ran through now, it is currently quite unstable and often fails due to java related tasks. However, the cirrus tasks which involve the `scripts/docker/cirrus/arch/Dockerfile` always fail. Cirrus reports: Container errored with 'ImagePullBackOff: Back-off pulling image "gcr.io/cirrus-ci-community/elektrainitiative/libelektra/scripts/docker/cirrus/arch/dockerfile:192f328646916150a6104131ce20859c"'. The base image of the dockerfile, `archlinux:base-devel` is available to my local docker instance.

**Pull request merged**
