### PR TITLE
fcrypt: improve unit test

### LINKED ISSUE #1593: Fcrypt: KDB Get Succeeded on Faulty Non-Verifiable File
# Description

Seems like part of `testmod_fcrypt` failed in one of the [latest Travis builds](https://travis-ci.org/sanssecours/libelektra/jobs/269210137#L2747):

```
FCRYPT       TESTS
==================
/Users/travis/build/sanssecours/libelektra/src/plugins/fcrypt/testmod_fcrypt.c:228: error in test_file_signature_operations: kdb get succeeded on faulty non-verifiable file
fcrypt RESULTS: 39 test(s) done. 1 error(s).
```

. I do not think that this is an OS or compiler-specific bug, since I saw the same issue using both 

- GCC on macOS and 
- Clang on Linux

.

# System Information

- Elektra Version: `master`

### PR DESCRIPTION
**Pull request by petermax2**
# Purpose

The unit test that should detect faulty signatures caused non-reproducible errors on the build servers (see #1593 ).
This re-designed test should be more robust. Instead of writing a file and corrupting it afterwards, a modified clear-signed text file is written in a separate unit test.

This should hopefully fix #1593 .

# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [x] I added unit tests
- [ ] affected documentation is fixed
- [ ] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

@markus2330 please review my pull request

### CODE REVIEW

**Comment by petermax2** [comment]
@markus2330 just a minor improvement. But it is ready for review and merge.

**Comment by sanssecours** [comment]
The behavior of the new test looks good to me. I just ran the test a thousand times without a single failure. Thank you for the update.

**Comment by petermax2** [comment]
@sanssecours thank you for the tests!

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
