### PR TITLE
typechecker-finalizations

### PR DESCRIPTION
**Pull request by e1528532**
## Basics

Some small improvements to get into the release

## Checklist

For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [ ] I ran all tests locally and everything went fine
- [X] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins)

## Review

trying to create a haskell build on xenial and documenting the dependency script

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you! Please keep the changes as small as possible, otherwise I am afraid I cannot do the release in time.

**Comment by e1528532** [comment]
Ok, so i suggest doing the xenial build in a different PR, as usual when i touch docker on my local machine after some months it doesn't work anymore :D
Is there anything else you really want to be in the current release that is documentation-related?

**Comment by e1528532** [comment]
So as these are only documentation related issues please review and then merge, i doubt that they have an impact on any test

**Comment by markus2330** [comment]
Thank you for the last-minute changes.

**Pull request merged**
