### PR TITLE
enum: simplify

### PR DESCRIPTION
**Pull request by tom-wa**
# Purpose

removed useless "features", added postgetstorage placement, kicked posix regex, refactored

# Checklist

- [x] commit messages are fine (with references to issues)
- [x] I ran all tests and everything went fine
- [ ] I added unit tests
- [x] affected documentation is fixed
- [x] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

### CODE REVIEW

**Comment by tom-wa** [comment]
jenkins build please

**Comment by markus2330** [comment]
@domhof Can you take a look if you like the enum syntax? (and if it is like we discussed)

**Comment by domhof** [comment]
@tom-wa Does the code allow multi-enums? Because last time we said that we won't support those.

**Comment by markus2330** [comment]
The code supported multienums already before. But afaik we wont need it for lcdproc.

**Comment by markus2330** [comment]
Thanks @tom-wa!

If further changes are needed in the enum plugin, its better to have them in separate PRs.

**Pull request merged**
