### PR TITLE
Fix xerces plugin locale

### PR DESCRIPTION
**Pull request by e1528532**
# Purpose
Use UTF-8 instead of the system locale for the xerces plugin to avoid problems if the locale is set to POSIX or something similar when trying to parse xml files with special characters.

# Checklist

- [X] commit messages are fine (with references to issues)
- [X] I ran all tests and everything went fine
- [ ] I added unit tests
- [ ] affected documentation is fixed
- [X] I added code comments, logging, and assertions
- [ ] meta data is updated (e.g. README.md of plugins)

WIP to see if it works

### CODE REVIEW

**Comment by e1528532** [comment]
jenkins build homepage please

**Comment by e1528532** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
add to whitelist

**Comment by markus2330** [comment]
jenkins build homepage please

**Comment by markus2330** [comment]
Thank you for the PR!

The build jobs run now.

**Comment by e1528532** [comment]
looks like the homepage built successfully now. We should still check if the plugin works regarding to special characters when used within the homepage. But if something is wrong there, i guess this can be a separate PR so we can merge this.

**Comment by markus2330** [comment]
Thank you for the PR!

The build jobs are finished. The new website has been immediately live:

https://www.libelektra.org/conversion

Seems like there are some issues regarding umlauts and it also fails at output format for quite some KeySets.

**Pull request merged**
