### PR TITLE
Remove kdbproposal

### LINKED ISSUE #2993: remove kdbproposal.h
- [x] keySetStringF move to internal?
- [x] elektraKsToMemArray completely remove?
- [x] ksRenameKeys completely remove?
- [x] keyLock and elektraLockOptions: move to internal?
- [x] elektraLookupOptions
- [x] elektraKeySetName: use instead of keySetName or always allow meta names?
- [x] elektraKeyGetMetaKeySet see #2983 
- [x] ksPrev and ksPopAtCursor: needs discussion
- [x] keyRel2 better than keyRel, but maybe remove both?
- [x] keyAsCascading remove?
- [x] keyGetLevelsBelow?

./src/libs/elektra/proposal.c and ./src/libs/proposal/proposal.c

- [x] keySetStringF: can be moved to hosts, as nobody else uses it yet
- [x] elektraKeyGetMetaKeySet: to be removed (obsolete by keyMeta)
- [x] elektraKeyLock: to be renamed and moved see #3179
- [ ] elektraKsPopAtCursor: to be renamed and moved see #3189

### PR DESCRIPTION
**Pull request by PhilippGackstatter**
fixes #2993 

Removes `kdbproposal.h` and `libproposal` as they are no longer needed.

Left to do
- `elektraKeySetName` may be taken care of by #3115 

## Basics

These points need to be fulfilled for every PR:

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy.
- [x] The PR is rebased with current master.

If you have any troubles fulfilling these criteria, please write
about the trouble as comment in the PR. We will help you.
But we cannot accept PRs that do not fulfill the basics.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://master.libelektra.org/doc/CODING.md))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned every code not directly written by me in [THIRD-PARTY-LICENSES](doc/THIRD-PARTY-LICENSES)

## Review

Reviewers will usually check the following:

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

If you are already Elektra developer:

- Add the "work in progress" label if you do not want the PR to be reviewed yet.
- Add the "ready to merge" label **if the basics are fulfilled** and you also
  say that everything is ready to be merged.

### CODE REVIEW

**Comment by PhilippGackstatter** [comment]
I removed `libproposal` as part of this PR because it was empty after removing all functions. 

Now `dh_install` is still looking for the library at install time, but I can't find where it is referenced. Can someone point me to the file I need to modify? Thanks!

**Comment by sanssecours** [comment]
> Now `dh_install` is still looking for the library at install time, but I can't find where it is referenced. Can someone point me to the file I need to modify? Thanks!

I think you need to remove this line:

https://github.com/ElektraInitiative/libelektra/blob/69b9483dae605dd7d325a25c0ef8d555f115e4a8/debian/libelektra4.install#L48

in the `debian` branch.

**Comment by markus2330** [comment]
Thank you for helping out!

**Comment by mpranj** [comment]
Hi 👋, is there a reason why we did not merge this yet?

Does it depend on the Keyname overhaul or can it be merged independently?

**Comment by PhilippGackstatter** [comment]
> Does it depend on the Keyname overhaul or can it be merged independently?

I believe it can be merged independently, but I've forgotten the details. I can look into this if this is still relevant. I'm not sure how much of #2993 was actually taken care of here.

**Comment by mpranj** [comment]
> I can look into this if this is still relevant.

It's not high priority, but seems like some work already went into it and it looks almost finished. I have not checked though if everything from #2993 has been implemented.

**Comment by PhilippGackstatter** [comment]
I've rebased and looked at what's missing.
It's actually just `elektraKeySetName` that's still in `kdbproposal.h` but it would be removed by #3555. After that, `kdbproposal.h` is empty and can be removed.
And then there is `elektraKsPopAtCursor` which is declared in `kdbprivate.h` and implemented in `src/libs/elektra/proposal.c` and would be moved as part of #3189. This wasn't part of `libproposal` anyway and I think the PR that implements that can move the function and delete this `proposal.c` file, and then that would be the last proposal-thing.

So I think this can be merged as is, as the rest is better handled in other PRs.

**Comment by markus2330** [comment]
Thank you for looking into it! I fixed now the Debian branch to not include the proposal library and header file.

**Comment by PhilippGackstatter** [comment]
jenkins build libelektra please

No idea what's wrong with the `ruby` plugin. It fails on all darwin builds. Nothing from this PR should affect the plugin in any way, so my guess would be its an external issue. It seems there have been some issues in the past with SWIG and ruby. Do you have any ideas by chance @mpranj @markus2330?

**Comment by markus2330** [comment]
Yes, `../src/plugins/ruby/ruby.cpp:39:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]` also seems to me quite unrelated. Somehow Qnil or VALUE get wrongly defined? I created  #3559.

@mpranj  If the same error also occurs on master, we can probably merge this.

**Comment by mpranj** [comment]
Thank you so much @PhilippGackstatter, great to finally have this cleaned up!

I confirmed the ruby problem exists on master too (unfortunately).

**Pull request merged**
