### PR TITLE
multifile+cache fix

### LINKED ISSUE #2702: cache: kdb cp -rf with multifile resolver results in erroneous cache hit / corrupt data
Using the multifile resolver with the cache plugin seems to be broken. When doing a `kdb cp -rf ` the data from the source is lost when working inside the same multifile backend.

## Steps to Reproduce the Problem
 
```sh
kdb mount -R multifile -c storage="csvstorage",pattern="*.csv",resolver="resolver" multitest user/tests/multifile

kdb ls user/tests/multifile/first.csv
#> user/tests/multifile/first.csv/#0
#> user/tests/multifile/first.csv/#0/#0
#> user/tests/multifile/first.csv/#1
#> user/tests/multifile/first.csv/#1/#0
#> user/tests/multifile/first.csv/#2
#> user/tests/multifile/first.csv/#2/#0

kdb ls user/tests/multifile/empty.csv
#> user/tests/multifile/empty.csv/#0
#> user/tests/multifile/empty.csv/#0/#0

kdb cp -rf user/tests/multifile/first.csv user/tests/multifile/empty.csv

kdb ls user/tests/multifile/first.csv
```

If your key database (KDB) might influence the outcome, please use `kdb stash`
to temporarily have an empty KDB. (Restore instructions are printed.)

## Expected Result

```sh
kdb ls user/tests/multifile/first.csv
#> user/tests/multifile/first.csv/#0
#> user/tests/multifile/first.csv/#0/#0
#> user/tests/multifile/first.csv/#1
#> user/tests/multifile/first.csv/#1/#0
#> user/tests/multifile/first.csv/#2
#> user/tests/multifile/first.csv/#2/#0
```
## Actual Result

```sh
kdb ls user/tests/multifile/first.csv
#> 
```

## System Information

- Elektra Version: master
- debian stretch docker container

### PR DESCRIPTION
**Pull request by mpranj**
Closes #2702, #2694, #2740 & enables `cache` again.

## Basics

Check relevant points but **please do not remove entries**.
Do not describe the purpose of this PR in the PR description but:

- [x] Short descriptions should be in the release notes (added as entry in
      `doc/news/_preparation_next_release.md` which contains `_(my name)_`)
      **Please always add something to the the release notes.**
- [x] Longer descriptions should be in documentation or in design decisions.
- [x] Describe details of how you changed the code in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, should be in the commit messages.

## Checklist

Check relevant points but **please do not remove entries**.
For docu fixes, spell checking, and similar none of these points below
need to be checked.

- [ ] I added unit tests
- [x] I ran all tests locally and everything went fine
- [x] affected documentation is fixed
- [ ] I added code comments, logging, and assertions (see doc/CODING.md)
- [ ] meta data is updated (e.g. README.md of plugins and doc/METADATA.md)

### CODE REVIEW

**Comment by mpranj** [comment]
@markus2330 this is ready to review & merge. It enables cache as default again. It fixes a bug I introduced (#2702) but does **not** fix the (somewhat cache-unrelated) multifile/resolver segfaults.

**Comment by markus2330** [comment]
Thank you for creating this PR!

Btw. you can also create more than one PR and give me instructions in which order I should merge them. In any case there should be no need to push to a PR that is already "ready to merge".

**Comment by mpranj** [comment]
@markus2330 done.

**Comment by markus2330** [comment]
Thank you very much!

**Pull request merged**
