### PR TITLE
Spec plugin check placements warning

### PR DESCRIPTION
**Pull request by tmakar**
## Basics

- [x] Short descriptions of your changes are in the release notes
      (added as entry in `doc/news/_preparation_next_release.md` which
      contains `_(my name)_`)
      **Please always add something to the release notes.**
- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildservers are happy. If not, fix **in this order**:
  - [ ] add a line in `doc/news/_preparation_next_release.md`
  - [ ] reformat the code with `scripts/dev/reformat-all`
  - [ ] make all unit tests pass
  - [ ] fix all memleaks
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation (see [Documentation Guidelines](https://www.libelektra.org/devgettingstarted/documentation))
- [ ] I fixed all affected decisions (see [Decision Process](https://www.libelektra.org/decisions/decision-process))
- [ ] I added code comments, logging, and assertions as appropriate (see [Coding Guidelines](https://www.libelektra.org/devgettingstarted/coding))
- [ ] I updated all meta data (e.g. README.md of plugins and [METADATA.ini](https://master.libelektra.org/doc/METADATA.ini))
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is introductory, concise, good to read and describes everything what the PR does
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to [our Coding Guidelines](https://master.libelektra.org/doc/CODING.md)
- [ ] APIs are conforming to [our Design Guidelines](https://master.libelektra.org/doc/DESIGN.md)
- [ ] Code is consistent to [our Design Decisions](https://master.libelektra.org/doc/decisions)

## Labels

- [ ] Add the "work in progress" label if you do not want the PR to be reviewed yet.
- [ ] Add the "ready to merge" label **if the basics are fulfilled** and no further pushes are planned by you.

### CODE REVIEW

**Comment by tmakar** [comment]
fixes #4859

**Comment by atmaxinger** [comment]
Looks good! Could you maybe also add this placement information into the doc for hooks and/or plugins?

**Review by kodebach — APPROVED** [review]
LGTM, thanks for the quick PR

**Comment by atmaxinger** [comment]
Please also remove the whitelisting from `check_kdb_internal_check.sh`

**Review by atmaxinger — CHANGES_REQUESTED** [review]
LGTM, but please also remove the whitelisting from check_kdb_internal_check.sh

**Comment by atmaxinger** [comment]
I'm thinking we maybe should do the same treatment to the `gopts` plugins as well in this PR? It's just adding the `hooks` placement into the README and removing the whitelisting from check_kdb_internal_check.sh

**Comment by tmakar** [comment]
> I'm thinking we maybe should do the same treatment to the `gopts` plugins as well in this PR? It's just adding the `hooks` placement into the README and removing the whitelisting from check_kdb_internal_check.sh

Yes, probably makes sense to clean this up here as well.

**Review by atmaxinger — APPROVED** [review]
LGTM, nice work. Thanks!

**Comment by atmaxinger** [comment]
Please rebase to current master and resolve the merge conflict.

**Comment by tmakar** [comment]
@atmaxinger rebased!

**Comment by atmaxinger** [comment]
Thank you for the outstanding work!

**Pull request merged**
