### PR TITLE
Added Spanish Translation of qt-gui #682

### PR DESCRIPTION
**Pull request by pixelead0**
# Purpose

Describe the purpose of the pull request.
Added Spanish Translation of qt-gui #682 
# Checklist

Please only check relevant points.
For docu fixes, spell checking and similar nothing
needs to be checked.
- [ x ] i18n spanish

@markus2330 please review my pull request

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for creating the translation! That is a very nice contribution!

Did you try to run qt-gui with the translation enabled? I think we also need to add the qm file and add it to i18n.qrc. @0003088 is this correct?

@0003088 Is there any specific reason why the german translation is called "de_DE" and not simply "de"? I think @pixelead0 is right here and we should use the most general locale name as long as we do not distinguish.

**Comment by 0003088** [comment]
@markus2330 As far as I can remember you are correct. I do not think that I chose 'de_DE' "for fun" so to speak, but that I followed a convention by doing so. @pixelead0 I really can recomment qt's Translator tool, it doesn't get any easier than that.

**Comment by mpranj** [comment]
As for the locale, the 2-letter code is sufficient. The .qm file definitely needs to be produced with lrelease and then added to the .qrc resource file.

In fact, I [think](http://doc.qt.io/qt-5/qtranslator.html#load) the de_DE locale would not be loaded for environments with locale de_AT.

**Comment by markus2330** [comment]
Yes, I think @mpranj is right here. For me (de_AT locale) the (de_DE) also was not found. It seems like that QTranslator::load as we do it is not recommended anymore. In the long run we also should generate the qm files and not have them checked in.

@pixelead0 is there anything we can help you with? Are there any issues with creating the qm file and add it to i18n.qrc? Or do you have troubles starting up the gui?

**Comment by markus2330** [comment]
@pixelead0 Hi, any news here? You are getting late for the Hacktoberfest!

**Comment by markus2330** [comment]
@pixelead0 Can I merge it for the upcoming release?

**Comment by markus2330** [comment]
@pixelead0 Would be great if I can add it to 0.8.20 release.

**Comment by markus2330** [comment]
Thank you!

**Pull request merged**
